/**
 * A1 · L01 — Greetings and introductions.
 *
 * The words you need to open and close a conversation: greetings for every time
 * of day, the verb heißen, and the politeness words danke / bitte.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  {
    id: 'v.a1.l01.hallo',
    de: 'Hallo',
    en: 'hello, hi',
    pos: 'phrase',
    example: 'Hallo, ich bin Anna!',
    exampleEn: 'Hello, I am Anna!',
    level: 'A1',
    topic: 'greetings',
    difficulty: 1,
    note: 'Informal but very common — fine with colleagues you already know.',
  },
  {
    id: 'v.a1.l01.guten-morgen',
    de: 'Guten Morgen',
    en: 'good morning',
    pos: 'phrase',
    example: 'Guten Morgen, Frau Weber! Wie geht es Ihnen?',
    exampleEn: 'Good morning, Ms Weber! How are you?',
    level: 'A1',
    topic: 'greetings',
    difficulty: 1,
    note: 'Used until about eleven o’clock.',
  },
  {
    id: 'v.a1.l01.guten-tag',
    de: 'Guten Tag',
    en: 'hello, good day',
    pos: 'phrase',
    example: 'Guten Tag, mein Name ist Bergmann.',
    exampleEn: 'Hello, my name is Bergmann.',
    level: 'A1',
    topic: 'greetings',
    difficulty: 1,
    note: 'The safe, polite greeting for the whole day — shops, offices, strangers.',
  },
  {
    id: 'v.a1.l01.guten-abend',
    de: 'Guten Abend',
    en: 'good evening',
    pos: 'phrase',
    example: 'Guten Abend! Ist Herr Klein noch im Büro?',
    exampleEn: 'Good evening! Is Mr Klein still in the office?',
    level: 'A1',
    topic: 'greetings',
    difficulty: 1,
    note: 'From about six in the evening. Gute Nacht is only for going to bed.',
  },
  {
    id: 'v.a1.l01.tschuess',
    de: 'Tschüss',
    en: 'bye',
    pos: 'phrase',
    example: 'Tschüss, bis morgen!',
    exampleEn: 'Bye, see you tomorrow!',
    level: 'A1',
    topic: 'greetings',
    difficulty: 1,
    note: 'The informal goodbye — the partner of Hallo.',
  },
  {
    id: 'v.a1.l01.auf-wiedersehen',
    de: 'Auf Wiedersehen',
    en: 'goodbye',
    pos: 'phrase',
    example: 'Auf Wiedersehen, Herr Doktor!',
    exampleEn: 'Goodbye, doctor!',
    level: 'A1',
    topic: 'greetings',
    difficulty: 2,
    note: 'The formal goodbye — the partner of Guten Tag. On the phone: Auf Wiederhören.',
  },
  {
    id: 'v.a1.l01.heissen',
    de: 'heißen',
    en: 'to be called',
    pos: 'verb',
    example: 'Wie heißen Sie? — Ich heiße Anna.',
    exampleEn: 'What is your name? — My name is Anna.',
    level: 'A1',
    topic: 'greetings',
    difficulty: 1,
    forms: {
      ich: 'heiße',
      du: 'heißt',
      er: 'heißt',
      wir: 'heißen',
      ihr: 'heißt',
      sie: 'heißen',
    },
    note: 'The stem ends in ß, so du and er look the same: du heißt, er heißt.',
  },
  {
    id: 'v.a1.l01.wie-geht-es-dir',
    de: 'Wie geht es dir?',
    en: 'How are you? (informal)',
    pos: 'phrase',
    example: 'Hallo Tom! Wie geht es dir?',
    exampleEn: 'Hello Tom! How are you?',
    level: 'A1',
    topic: 'greetings',
    difficulty: 2,
    note: 'Polite version: Wie geht es Ihnen? Spoken short form: Wie geht’s?',
  },
  {
    id: 'v.a1.l01.danke',
    de: 'danke',
    en: 'thank you',
    pos: 'phrase',
    example: 'Danke schön! — Bitte schön!',
    exampleEn: 'Thank you very much! — You are welcome!',
    level: 'A1',
    topic: 'greetings',
    difficulty: 1,
  },
  {
    id: 'v.a1.l01.bitte',
    de: 'bitte',
    en: 'please; you are welcome',
    pos: 'phrase',
    example: 'Wie heißen Sie, bitte?',
    exampleEn: 'What is your name, please?',
    level: 'A1',
    topic: 'greetings',
    difficulty: 2,
    note: 'One word, two jobs: it asks politely, and it answers danke.',
  },
  {
    id: 'v.a1.l01.freut-mich',
    de: 'Freut mich',
    en: 'nice to meet you',
    pos: 'phrase',
    example: 'Ich bin Lena. — Freut mich!',
    exampleEn: 'I am Lena. — Nice to meet you!',
    level: 'A1',
    topic: 'greetings',
    difficulty: 2,
    note: 'Works with du and with Sie. The other person often answers: Freut mich auch!',
  },
  {
    id: 'v.a1.l01.willkommen',
    de: 'Willkommen',
    en: 'welcome',
    pos: 'phrase',
    example: 'Herzlich willkommen in Berlin!',
    exampleEn: 'A warm welcome to Berlin!',
    level: 'A1',
    topic: 'greetings',
    difficulty: 2,
  },
  {
    id: 'v.a1.l01.name',
    de: 'Name',
    en: 'name',
    pos: 'noun',
    article: 'der',
    plural: 'die Namen',
    example: 'Mein Name ist Anna Bergmann.',
    exampleEn: 'My name is Anna Bergmann.',
    level: 'A1',
    topic: 'personal',
    difficulty: 2,
  },
  {
    id: 'v.a1.l01.herr',
    de: 'Herr',
    en: 'Mr, gentleman',
    pos: 'noun',
    article: 'der',
    plural: 'die Herren',
    example: 'Guten Tag, Herr Weber!',
    exampleEn: 'Hello, Mr Weber!',
    level: 'A1',
    topic: 'greetings',
    difficulty: 2,
    note: 'Herr or Frau plus a surname is the signal that you must use Sie.',
  },
  {
    id: 'v.a1.l01.frau',
    de: 'Frau',
    en: 'Ms, Mrs; woman',
    pos: 'noun',
    article: 'die',
    plural: 'die Frauen',
    example: 'Das ist Frau Klein. Sie ist sehr nett.',
    exampleEn: 'This is Ms Klein. She is very nice.',
    level: 'A1',
    topic: 'greetings',
    difficulty: 2,
    note: 'German has no Fräulein any more — every woman is Frau.',
  },
  {
    id: 'v.a1.l01.gut',
    de: 'gut',
    en: 'good, well',
    pos: 'adj',
    example: 'Danke, gut! Und dir?',
    exampleEn: 'Fine, thanks! And you?',
    level: 'A1',
    topic: 'greetings',
    difficulty: 1,
    note: 'The standard answer to Wie geht es dir? Stronger: sehr gut.',
  },
]

export default vocab
