/**
 * A1 · L04 — Family and people (Familie und Leute)
 *
 * Every family member the learner needs to describe a photo of their family,
 * plus the two words for marital status and the everyday adjective "nett".
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  {
    id: 'v.a1.l04.familie',
    de: 'Familie',
    en: 'family',
    pos: 'noun',
    article: 'die',
    plural: 'die Familien',
    example: 'Meine Familie wohnt in Bremen.',
    exampleEn: 'My family lives in Bremen.',
    level: 'A1',
    topic: 'family',
    difficulty: 1,
    note: 'Almost all nouns ending in -ie are feminine: die Familie, die Linie, die Industrie.',
  },
  {
    id: 'v.a1.l04.vater',
    de: 'Vater',
    en: 'father',
    pos: 'noun',
    article: 'der',
    plural: 'die Väter',
    example: 'Mein Vater heißt Peter.',
    exampleEn: 'My father is called Peter.',
    level: 'A1',
    topic: 'family',
    difficulty: 1,
    note: 'Informally: der Papa, der Vati.',
  },
  {
    id: 'v.a1.l04.mutter',
    de: 'Mutter',
    en: 'mother',
    pos: 'noun',
    article: 'die',
    plural: 'die Mütter',
    example: 'Meine Mutter arbeitet im Krankenhaus.',
    exampleEn: 'My mother works in the hospital.',
    level: 'A1',
    topic: 'family',
    difficulty: 1,
    note: 'Informally: die Mama, die Mutti.',
  },
  {
    id: 'v.a1.l04.eltern',
    de: 'Eltern',
    en: 'parents',
    pos: 'noun',
    article: 'die',
    plural: 'die Eltern',
    example: 'Meine Eltern wohnen in Köln.',
    exampleEn: 'My parents live in Cologne.',
    level: 'A1',
    topic: 'family',
    difficulty: 1,
    note: 'Plural only — there is no singular. The verb is always plural: Meine Eltern sind nett.',
  },
  {
    id: 'v.a1.l04.bruder',
    de: 'Bruder',
    en: 'brother',
    pos: 'noun',
    article: 'der',
    plural: 'die Brüder',
    example: 'Ich habe einen Bruder.',
    exampleEn: 'I have one brother.',
    level: 'A1',
    topic: 'family',
    difficulty: 1,
    note: 'After haben the masculine article changes: ein Bruder → einen Bruder.',
  },
  {
    id: 'v.a1.l04.schwester',
    de: 'Schwester',
    en: 'sister',
    pos: 'noun',
    article: 'die',
    plural: 'die Schwestern',
    example: 'Meine Schwester ist Ärztin.',
    exampleEn: 'My sister is a doctor.',
    level: 'A1',
    topic: 'family',
    difficulty: 1,
  },
  {
    id: 'v.a1.l04.geschwister',
    de: 'Geschwister',
    en: 'brothers and sisters, siblings',
    pos: 'noun',
    article: 'die',
    plural: 'die Geschwister',
    example: 'Hast du Geschwister?',
    exampleEn: 'Do you have any brothers or sisters?',
    level: 'A1',
    topic: 'family',
    difficulty: 2,
    note: 'Plural only, and the standard way to ask: Hast du Geschwister?',
  },
  {
    id: 'v.a1.l04.sohn',
    de: 'Sohn',
    en: 'son',
    pos: 'noun',
    article: 'der',
    plural: 'die Söhne',
    example: 'Mein Sohn ist vier Jahre alt.',
    exampleEn: 'My son is four years old.',
    level: 'A1',
    topic: 'family',
    difficulty: 2,
  },
  {
    id: 'v.a1.l04.tochter',
    de: 'Tochter',
    en: 'daughter',
    pos: 'noun',
    article: 'die',
    plural: 'die Töchter',
    example: 'Ihre Tochter studiert in Leipzig.',
    exampleEn: 'Her daughter studies in Leipzig.',
    level: 'A1',
    topic: 'family',
    difficulty: 2,
  },
  {
    id: 'v.a1.l04.kind',
    de: 'Kind',
    en: 'child',
    pos: 'noun',
    article: 'das',
    plural: 'die Kinder',
    example: 'Das Kind spielt im Garten.',
    exampleEn: 'The child is playing in the garden.',
    level: 'A1',
    topic: 'family',
    difficulty: 1,
    note: 'Neuter, whether the child is a boy or a girl. The plural die Kinder is extremely common.',
  },
  {
    id: 'v.a1.l04.grosseltern',
    de: 'Großeltern',
    en: 'grandparents',
    pos: 'noun',
    article: 'die',
    plural: 'die Großeltern',
    example: 'Meine Großeltern sind schon alt.',
    exampleEn: 'My grandparents are quite old already.',
    level: 'A1',
    topic: 'family',
    difficulty: 2,
    note: 'Plural only, like Eltern. Singular: der Großvater (Opa), die Großmutter (Oma).',
  },
  {
    id: 'v.a1.l04.mann',
    de: 'Mann',
    en: 'man; husband',
    pos: 'noun',
    article: 'der',
    plural: 'die Männer',
    example: 'Ihr Mann heißt Jonas.',
    exampleEn: 'Her husband is called Jonas.',
    level: 'A1',
    topic: 'family',
    difficulty: 1,
    note: 'With a possessive it means husband: mein Mann = my husband, ihr Mann = her husband.',
  },
  {
    id: 'v.a1.l04.verheiratet',
    de: 'verheiratet',
    en: 'married',
    pos: 'adj',
    example: 'Meine Schwester ist verheiratet.',
    exampleEn: 'My sister is married.',
    level: 'A1',
    topic: 'family',
    difficulty: 2,
    note: 'Always with sein: Ich bin verheiratet. Never with haben.',
  },
  {
    id: 'v.a1.l04.ledig',
    de: 'ledig',
    en: 'single, unmarried',
    pos: 'adj',
    example: 'Mein Bruder ist noch ledig.',
    exampleEn: 'My brother is still single.',
    level: 'A1',
    topic: 'family',
    difficulty: 3,
    note: 'The word on official forms. In conversation people say: Ich bin Single.',
  },
  {
    id: 'v.a1.l04.nett',
    de: 'nett',
    en: 'nice, kind',
    pos: 'adj',
    example: 'Meine Großeltern sind sehr nett.',
    exampleEn: 'My grandparents are very nice.',
    level: 'A1',
    topic: 'family',
    difficulty: 1,
    note: 'The everyday word for a pleasant person. For things use schön or gut.',
  },
]

export default vocab
