/**
 * A1 · L05 — Daily routine / Der Tagesablauf
 *
 * The verbs of an ordinary day (most of them separable), plus the time words
 * that hold a day together: morgens, mittags, abends, jeden Tag, oft, nie.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── Separable verbs ──────────────────────────────────────────────────── */
  {
    id: 'v.a1.l05.aufstehen',
    de: 'aufstehen',
    en: 'to get up',
    pos: 'verb',
    example: 'Ich möchte am Sonntag nicht früh aufstehen.',
    exampleEn: 'I do not want to get up early on Sunday.',
    level: 'A1',
    topic: 'routine',
    difficulty: 1,
    separable: true,
    note: 'In a normal sentence the prefix splits off: Ich stehe um sechs Uhr auf.',
    forms: {
      ich: 'stehe auf',
      du: 'stehst auf',
      er: 'steht auf',
      wir: 'stehen auf',
      ihr: 'steht auf',
      sie: 'stehen auf',
    },
  },
  {
    id: 'v.a1.l05.anfangen',
    de: 'anfangen',
    en: 'to start, to begin',
    pos: 'verb',
    example: 'Ich möchte morgen um acht Uhr anfangen.',
    exampleEn: 'I would like to start at eight tomorrow.',
    level: 'A1',
    topic: 'routine',
    difficulty: 2,
    separable: true,
    note: 'Separable and stem-changing: Die Arbeit fängt um acht Uhr an. (a → ä)',
    forms: {
      ich: 'fange an',
      du: 'fängst an',
      er: 'fängt an',
      wir: 'fangen an',
      ihr: 'fangt an',
      sie: 'fangen an',
    },
  },
  {
    id: 'v.a1.l05.einkaufen',
    de: 'einkaufen',
    en: 'to do the shopping',
    pos: 'verb',
    example: 'Am Samstag gehe ich einkaufen.',
    exampleEn: 'On Saturday I go shopping.',
    level: 'A1',
    topic: 'routine',
    difficulty: 2,
    separable: true,
    note: 'Split in a normal sentence: Ich kaufe am Samstag ein.',
    forms: {
      ich: 'kaufe ein',
      du: 'kaufst ein',
      er: 'kauft ein',
      wir: 'kaufen ein',
      ihr: 'kauft ein',
      sie: 'kaufen ein',
    },
  },
  {
    id: 'v.a1.l05.fernsehen',
    de: 'fernsehen',
    en: 'to watch TV',
    pos: 'verb',
    example: 'Abends sehe ich eine Stunde fern.',
    exampleEn: 'In the evening I watch TV for an hour.',
    level: 'A1',
    topic: 'routine',
    difficulty: 2,
    separable: true,
    note: 'Separable and stem-changing: du siehst fern, er sieht fern. (e → ie)',
    forms: {
      ich: 'sehe fern',
      du: 'siehst fern',
      er: 'sieht fern',
      wir: 'sehen fern',
      ihr: 'seht fern',
      sie: 'sehen fern',
    },
  },
  {
    id: 'v.a1.l05.ankommen',
    de: 'ankommen',
    en: 'to arrive',
    pos: 'verb',
    example: 'Ich möchte pünktlich im Büro ankommen.',
    exampleEn: 'I want to arrive at the office on time.',
    level: 'A1',
    topic: 'routine',
    difficulty: 3,
    separable: true,
    note: 'Split in a normal sentence: Der Zug kommt um acht Uhr an.',
    forms: {
      ich: 'komme an',
      du: 'kommst an',
      er: 'kommt an',
      wir: 'kommen an',
      ihr: 'kommt an',
      sie: 'kommen an',
    },
  },
  {
    id: 'v.a1.l05.mitkommen',
    de: 'mitkommen',
    en: 'to come along',
    pos: 'verb',
    example: 'Möchtest du am Samstag mitkommen?',
    exampleEn: 'Would you like to come along on Saturday?',
    level: 'A1',
    topic: 'routine',
    difficulty: 2,
    separable: true,
    note: 'Split in a normal question: Kommst du mit?',
    forms: {
      ich: 'komme mit',
      du: 'kommst mit',
      er: 'kommt mit',
      wir: 'kommen mit',
      ihr: 'kommt mit',
      sie: 'kommen mit',
    },
  },

  /* ── Simple and stem-changing verbs ───────────────────────────────────── */
  {
    id: 'v.a1.l05.duschen',
    de: 'duschen',
    en: 'to have a shower',
    pos: 'verb',
    example: 'Ich dusche jeden Morgen kalt.',
    exampleEn: 'I have a cold shower every morning.',
    level: 'A1',
    topic: 'routine',
    difficulty: 1,
    forms: {
      ich: 'dusche',
      du: 'duschst',
      er: 'duscht',
      wir: 'duschen',
      ihr: 'duscht',
      sie: 'duschen',
    },
  },
  {
    id: 'v.a1.l05.fruehstuecken',
    de: 'frühstücken',
    en: 'to have breakfast',
    pos: 'verb',
    example: 'Wir frühstücken um halb acht in der Küche.',
    exampleEn: 'We have breakfast at half past seven in the kitchen.',
    level: 'A1',
    topic: 'routine',
    difficulty: 2,
    note: 'Completely regular, even though it looks long.',
    forms: {
      ich: 'frühstücke',
      du: 'frühstückst',
      er: 'frühstückt',
      wir: 'frühstücken',
      ihr: 'frühstückt',
      sie: 'frühstücken',
    },
  },
  {
    id: 'v.a1.l05.schlafen',
    de: 'schlafen',
    en: 'to sleep',
    pos: 'verb',
    example: 'Ich schlafe jede Nacht sieben Stunden.',
    exampleEn: 'I sleep seven hours every night.',
    level: 'A1',
    topic: 'routine',
    difficulty: 2,
    note: 'Stem change a → ä: du schläfst, er schläft.',
    forms: {
      ich: 'schlafe',
      du: 'schläfst',
      er: 'schläft',
      wir: 'schlafen',
      ihr: 'schlaft',
      sie: 'schlafen',
    },
  },

  /* ── One noun ─────────────────────────────────────────────────────────── */
  {
    id: 'v.a1.l05.wecker',
    de: 'Wecker',
    en: 'alarm clock',
    pos: 'noun',
    article: 'der',
    plural: 'die Wecker',
    example: 'Mein Wecker klingelt um sechs Uhr.',
    exampleEn: 'My alarm clock rings at six o’clock.',
    level: 'A1',
    topic: 'routine',
    difficulty: 1,
    note: 'Words for machines ending in -er are masculine and keep the same form in the plural.',
  },

  /* ── Time and frequency ───────────────────────────────────────────────── */
  {
    id: 'v.a1.l05.morgens',
    de: 'morgens',
    en: 'in the morning(s)',
    pos: 'adv',
    example: 'Morgens trinke ich einen Kaffee.',
    exampleEn: 'In the morning I drink a coffee.',
    level: 'A1',
    topic: 'time',
    difficulty: 1,
    note: 'The -s ending means "every morning", not one single morning.',
  },
  {
    id: 'v.a1.l05.mittags',
    de: 'mittags',
    en: 'at midday, at lunchtime',
    pos: 'adv',
    example: 'Mittags esse ich in der Kantine.',
    exampleEn: 'At lunchtime I eat in the canteen.',
    level: 'A1',
    topic: 'time',
    difficulty: 2,
  },
  {
    id: 'v.a1.l05.abends',
    de: 'abends',
    en: 'in the evening(s)',
    pos: 'adv',
    example: 'Abends lese ich ein Buch.',
    exampleEn: 'In the evening I read a book.',
    level: 'A1',
    topic: 'time',
    difficulty: 1,
  },
  {
    id: 'v.a1.l05.jeden-tag',
    de: 'jeden Tag',
    en: 'every day',
    pos: 'phrase',
    example: 'Jeden Tag fahre ich mit dem Bus zur Arbeit.',
    exampleEn: 'Every day I go to work by bus.',
    level: 'A1',
    topic: 'time',
    difficulty: 1,
    note: 'A fixed time chunk — always jeden Tag, never "jeder Tag".',
  },
  {
    id: 'v.a1.l05.oft',
    de: 'oft',
    en: 'often',
    pos: 'adv',
    example: 'Ich sehe abends oft fern.',
    exampleEn: 'I often watch TV in the evening.',
    level: 'A1',
    topic: 'time',
    difficulty: 1,
  },
  {
    id: 'v.a1.l05.nie',
    de: 'nie',
    en: 'never',
    pos: 'adv',
    example: 'Ich frühstücke nie im Büro.',
    exampleEn: 'I never have breakfast in the office.',
    level: 'A1',
    topic: 'time',
    difficulty: 2,
    note: 'nie is already negative — you do not add nicht or kein.',
  },
]

export default vocab
