/**
 * A1 · L07 — Shopping and money / Einkaufen und Geld
 *
 * The words you need between the shop door and the till: the three places
 * Germans actually shop (Supermarkt, Bäckerei, Kasse), the four verbs of a
 * purchase (kaufen, kosten, brauchen, bezahlen), the two adjectives every
 * price gets judged with (teuer, billig), and the quantity words that let you
 * ask for an amount instead of pointing: Kilo, Flasche, Packung, Tüte.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── Places ───────────────────────────────────────────────────────────── */
  {
    id: 'v.a1.l07.supermarkt',
    de: 'Supermarkt',
    en: 'supermarket',
    pos: 'noun',
    article: 'der',
    plural: 'die Supermärkte',
    example: 'Der Supermarkt ist heute bis acht Uhr offen.',
    exampleEn: 'The supermarket is open until eight today.',
    level: 'A1',
    topic: 'shopping',
    difficulty: 1,
    note: 'Where you are shopping: im Supermarkt. Where you are going: in den Supermarkt.',
  },
  {
    id: 'v.a1.l07.baeckerei',
    de: 'Bäckerei',
    en: 'bakery',
    pos: 'noun',
    article: 'die',
    plural: 'die Bäckereien',
    example: 'Ich kaufe das Brot immer in der Bäckerei.',
    exampleEn: 'I always buy the bread at the bakery.',
    level: 'A1',
    topic: 'shopping',
    difficulty: 1,
    note: 'Every noun ending in -ei is feminine: die Bäckerei, die Metzgerei, die Konditorei.',
  },
  {
    id: 'v.a1.l07.kasse',
    de: 'Kasse',
    en: 'till, checkout',
    pos: 'noun',
    article: 'die',
    plural: 'die Kassen',
    example: 'Die Kasse ist vorne rechts.',
    exampleEn: 'The checkout is at the front on the right.',
    level: 'A1',
    topic: 'shopping',
    difficulty: 2,
  },

  /* ── Money ────────────────────────────────────────────────────────────── */
  {
    id: 'v.a1.l07.geld',
    de: 'Geld',
    en: 'money',
    pos: 'noun',
    article: 'das',
    plural: null,
    example: 'Ich habe heute kein Geld dabei.',
    exampleEn: 'I have no money with me today.',
    level: 'A1',
    topic: 'money',
    difficulty: 1,
    note: 'No everyday plural. Coins are das Kleingeld, cash is das Bargeld.',
  },
  {
    id: 'v.a1.l07.preis',
    de: 'Preis',
    en: 'price',
    pos: 'noun',
    article: 'der',
    plural: 'die Preise',
    example: 'Der Preis ist gut — nur zwei Euro.',
    exampleEn: 'The price is good — only two euros.',
    level: 'A1',
    topic: 'money',
    difficulty: 1,
  },
  {
    id: 'v.a1.l07.euro',
    de: 'Euro',
    en: 'euro',
    pos: 'noun',
    article: 'der',
    plural: 'die Euro',
    example: 'Eine Flasche Wasser kostet einen Euro.',
    exampleEn: 'A bottle of water costs one euro.',
    level: 'A1',
    topic: 'money',
    difficulty: 1,
    note: 'After a number Euro stays singular: zwei Euro, zehn Euro — never "zwei Euros".',
  },

  /* ── The four verbs of a purchase ─────────────────────────────────────── */
  {
    id: 'v.a1.l07.kaufen',
    de: 'kaufen',
    en: 'to buy',
    pos: 'verb',
    example: 'Ich kaufe eine Packung Kaffee.',
    exampleEn: 'I am buying a packet of coffee.',
    level: 'A1',
    topic: 'shopping',
    difficulty: 1,
    forms: {
      ich: 'kaufe',
      du: 'kaufst',
      er: 'kauft',
      wir: 'kaufen',
      ihr: 'kauft',
      sie: 'kaufen',
    },
  },
  {
    id: 'v.a1.l07.kosten',
    de: 'kosten',
    en: 'to cost',
    pos: 'verb',
    example: 'Wie viel kostet ein Kilo Tomaten?',
    exampleEn: 'How much does a kilo of tomatoes cost?',
    level: 'A1',
    topic: 'money',
    difficulty: 1,
    note: 'In a shop you almost only need two forms: kostet for one thing, kosten for several.',
    forms: {
      ich: 'koste',
      du: 'kostest',
      er: 'kostet',
      wir: 'kosten',
      ihr: 'kostet',
      sie: 'kosten',
    },
  },
  {
    id: 'v.a1.l07.brauchen',
    de: 'brauchen',
    en: 'to need',
    pos: 'verb',
    example: 'Ich brauche keine Tüte, danke.',
    exampleEn: 'I do not need a bag, thank you.',
    level: 'A1',
    topic: 'shopping',
    difficulty: 1,
    forms: {
      ich: 'brauche',
      du: 'brauchst',
      er: 'braucht',
      wir: 'brauchen',
      ihr: 'braucht',
      sie: 'brauchen',
    },
  },
  {
    id: 'v.a1.l07.bezahlen',
    de: 'bezahlen',
    en: 'to pay',
    pos: 'verb',
    example: 'Bezahlen Sie bar oder mit Karte?',
    exampleEn: 'Are you paying in cash or by card?',
    level: 'A1',
    topic: 'money',
    difficulty: 2,
    note: 'The prefix be- never splits off. zahlen alone works too: Ich zahle bar.',
    forms: {
      ich: 'bezahle',
      du: 'bezahlst',
      er: 'bezahlt',
      wir: 'bezahlen',
      ihr: 'bezahlt',
      sie: 'bezahlen',
    },
  },

  /* ── Judging a price ──────────────────────────────────────────────────── */
  {
    id: 'v.a1.l07.teuer',
    de: 'teuer',
    en: 'expensive',
    pos: 'adj',
    example: 'Das ist zu teuer — ich nehme es nicht.',
    exampleEn: 'That is too expensive — I am not taking it.',
    level: 'A1',
    topic: 'money',
    difficulty: 1,
  },
  {
    id: 'v.a1.l07.billig',
    de: 'billig',
    en: 'cheap',
    pos: 'adj',
    example: 'Das Wasser hier ist sehr billig.',
    exampleEn: 'The water here is very cheap.',
    level: 'A1',
    topic: 'money',
    difficulty: 2,
    note: 'billig can hint at poor quality. For "good value" Germans say günstig.',
  },

  /* ── How much of it ───────────────────────────────────────────────────── */
  {
    id: 'v.a1.l07.kilo',
    de: 'Kilo',
    en: 'kilo',
    pos: 'noun',
    article: 'das',
    plural: 'die Kilo',
    example: 'Ein Kilo Äpfel kostet zwei Euro.',
    exampleEn: 'A kilo of apples costs two euros.',
    level: 'A1',
    topic: 'shopping',
    difficulty: 2,
    note: 'Half a kilo is ein Pfund — still a normal word at the market.',
  },
  {
    id: 'v.a1.l07.flasche',
    de: 'Flasche',
    en: 'bottle',
    pos: 'noun',
    article: 'die',
    plural: 'die Flaschen',
    example: 'Eine Flasche Wasser, bitte.',
    exampleEn: 'A bottle of water, please.',
    level: 'A1',
    topic: 'shopping',
    difficulty: 1,
  },
  {
    id: 'v.a1.l07.packung',
    de: 'Packung',
    en: 'packet, pack',
    pos: 'noun',
    article: 'die',
    plural: 'die Packungen',
    example: 'Ich nehme eine Packung Kaffee.',
    exampleEn: 'I will take a packet of coffee.',
    level: 'A1',
    topic: 'shopping',
    difficulty: 2,
    note: 'Nouns ending in -ung are always feminine: die Packung, die Rechnung, die Wohnung.',
  },
  {
    id: 'v.a1.l07.tuete',
    de: 'Tüte',
    en: 'bag, carrier bag',
    pos: 'noun',
    article: 'die',
    plural: 'die Tüten',
    example: 'Brauchen Sie eine Tüte?',
    exampleEn: 'Do you need a bag?',
    level: 'A1',
    topic: 'shopping',
    difficulty: 2,
    note: 'At every German till you will hear this question — and bags cost extra.',
  },
]

export default vocab
