/**
 * A1 · L02 — Personal information / Persönliche Angaben
 *
 * Countries and nationalities, languages, jobs, where you live and work,
 * spelling your name, phone number and e-mail address.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── Countries, nationalities, languages ──────────────────────────────── */
  {
    id: 'v.a1.l02.land',
    de: 'Land',
    en: 'country',
    pos: 'noun',
    article: 'das',
    plural: 'die Länder',
    example: 'Österreich ist ein Land in Europa.',
    exampleEn: 'Austria is a country in Europe.',
    level: 'A1',
    topic: 'countries',
    difficulty: 1,
    note: 'The plural adds an umlaut: das Land → die Länder.',
  },
  {
    id: 'v.a1.l02.kommen',
    de: 'kommen',
    en: 'to come, to be from',
    pos: 'verb',
    example: 'Ich komme aus Indien.',
    exampleEn: 'I come from India.',
    level: 'A1',
    topic: 'countries',
    difficulty: 1,
    forms: {
      ich: 'komme',
      du: 'kommst',
      er: 'kommt',
      wir: 'kommen',
      ihr: 'kommt',
      sie: 'kommen',
    },
    note: 'Origin is always kommen + aus: aus Indien, aus Österreich, aus Berlin.',
  },
  {
    id: 'v.a1.l02.inder',
    de: 'Inder',
    en: 'Indian (man)',
    pos: 'noun',
    article: 'der',
    plural: 'die Inder',
    example: 'Herr Kumar ist Inder und kommt aus Delhi.',
    exampleEn: 'Mr Kumar is Indian and comes from Delhi.',
    level: 'A1',
    topic: 'countries',
    difficulty: 2,
    note: 'Female form: die Inderin. After sein a nationality takes no article — Er ist Inder.',
  },
  {
    id: 'v.a1.l02.deutsch',
    de: 'deutsch',
    en: 'German (adjective)',
    pos: 'adj',
    example: 'Anna ist deutsch und kommt aus Hamburg.',
    exampleEn: 'Anna is German and comes from Hamburg.',
    level: 'A1',
    topic: 'countries',
    difficulty: 2,
    note: 'Small letter for the adjective (sie ist deutsch), capital for the language (sie spricht Deutsch).',
  },
  {
    id: 'v.a1.l02.sprache',
    de: 'Sprache',
    en: 'language',
    pos: 'noun',
    article: 'die',
    plural: 'die Sprachen',
    example: 'Welche Sprache sprechen Sie zu Hause?',
    exampleEn: 'Which language do you speak at home?',
    level: 'A1',
    topic: 'countries',
    difficulty: 2,
  },
  {
    id: 'v.a1.l02.sprechen',
    de: 'sprechen',
    en: 'to speak',
    pos: 'verb',
    example: 'Ich spreche Englisch, Hindi und ein bisschen Deutsch.',
    exampleEn: 'I speak English, Hindi and a little German.',
    level: 'A1',
    topic: 'countries',
    difficulty: 2,
    forms: {
      ich: 'spreche',
      du: 'sprichst',
      er: 'spricht',
      wir: 'sprechen',
      ihr: 'sprecht',
      sie: 'sprechen',
    },
    note: 'Stem change e → i in the du and er forms only: du sprichst, er spricht.',
  },

  /* ── Where you live and work ──────────────────────────────────────────── */
  {
    id: 'v.a1.l02.wohnen',
    de: 'wohnen',
    en: 'to live, to reside',
    pos: 'verb',
    example: 'Ich wohne jetzt in Hamburg.',
    exampleEn: 'I live in Hamburg now.',
    level: 'A1',
    topic: 'personal',
    difficulty: 1,
    forms: {
      ich: 'wohne',
      du: 'wohnst',
      er: 'wohnt',
      wir: 'wohnen',
      ihr: 'wohnt',
      sie: 'wohnen',
    },
    note: 'wohnen + in + town: in Berlin, in Wien. Where you come from needs aus.',
  },
  {
    id: 'v.a1.l02.arbeiten',
    de: 'arbeiten',
    en: 'to work',
    pos: 'verb',
    example: 'Ich arbeite als Ingenieurin in München.',
    exampleEn: 'I work as an engineer in Munich.',
    level: 'A1',
    topic: 'jobs',
    difficulty: 1,
    forms: {
      ich: 'arbeite',
      du: 'arbeitest',
      er: 'arbeitet',
      wir: 'arbeiten',
      ihr: 'arbeitet',
      sie: 'arbeiten',
    },
    note: 'The stem ends in -t, so du and er/ihr add an extra -e-: du arbeitest, er arbeitet.',
  },

  /* ── Jobs ─────────────────────────────────────────────────────────────── */
  {
    id: 'v.a1.l02.beruf',
    de: 'Beruf',
    en: 'job, profession',
    pos: 'noun',
    article: 'der',
    plural: 'die Berufe',
    example: 'Was sind Sie von Beruf?',
    exampleEn: 'What is your job?',
    level: 'A1',
    topic: 'jobs',
    difficulty: 1,
    note: 'The standard question is "Was sind Sie von Beruf?" — von Beruf has no article.',
  },
  {
    id: 'v.a1.l02.ingenieur',
    de: 'Ingenieur',
    en: 'engineer (man)',
    pos: 'noun',
    article: 'der',
    plural: 'die Ingenieure',
    example: 'Herr Kumar arbeitet als Ingenieur in Stuttgart.',
    exampleEn: 'Mr Kumar works as an engineer in Stuttgart.',
    level: 'A1',
    topic: 'jobs',
    difficulty: 2,
    note: 'Female form: die Ingenieurin. Spoken roughly "in-zhe-NIÖR".',
  },
  {
    id: 'v.a1.l02.lehrerin',
    de: 'Lehrerin',
    en: 'teacher (woman)',
    pos: 'noun',
    article: 'die',
    plural: 'die Lehrerinnen',
    example: 'Frau Schmidt ist Lehrerin und arbeitet in Bonn.',
    exampleEn: 'Ms Schmidt is a teacher and works in Bonn.',
    level: 'A1',
    topic: 'jobs',
    difficulty: 2,
    note: 'Male form: der Lehrer. The ending -in is always feminine, and its plural doubles the n: -innen.',
  },
  {
    id: 'v.a1.l02.student',
    de: 'Student',
    en: 'student (man)',
    pos: 'noun',
    article: 'der',
    plural: 'die Studenten',
    example: 'Ich bin Student und wohne in Wien.',
    exampleEn: 'I am a student and live in Vienna.',
    level: 'A1',
    topic: 'jobs',
    difficulty: 2,
    note: 'Female form: die Studentin. Only for university — a school pupil is der Schüler.',
  },
  {
    id: 'v.a1.l02.aerztin',
    de: 'Ärztin',
    en: 'doctor (woman)',
    pos: 'noun',
    article: 'die',
    plural: 'die Ärztinnen',
    example: 'Anna ist Ärztin und arbeitet in Köln.',
    exampleEn: 'Anna is a doctor and works in Cologne.',
    level: 'A1',
    topic: 'jobs',
    difficulty: 2,
    note: 'Male form: der Arzt. Careful with the umlaut — Arzt but Ärztin.',
  },

  /* ── Contact details ──────────────────────────────────────────────────── */
  {
    id: 'v.a1.l02.buchstabieren',
    de: 'buchstabieren',
    en: 'to spell',
    pos: 'verb',
    example: 'Bitte buchstabieren Sie Ihren Namen.',
    exampleEn: 'Please spell your name.',
    level: 'A1',
    topic: 'personal',
    difficulty: 2,
    forms: {
      ich: 'buchstabiere',
      du: 'buchstabierst',
      er: 'buchstabiert',
      wir: 'buchstabieren',
      ihr: 'buchstabiert',
      sie: 'buchstabieren',
    },
    note: 'Verbs in -ieren are perfectly regular. The stress falls on the -ie-: buchsta-BIE-ren.',
  },
  {
    id: 'v.a1.l02.telefonnummer',
    de: 'Telefonnummer',
    en: 'phone number',
    pos: 'noun',
    article: 'die',
    plural: 'die Telefonnummern',
    example: 'Wie ist Ihre Telefonnummer?',
    exampleEn: 'What is your phone number?',
    level: 'A1',
    topic: 'personal',
    difficulty: 1,
    note: 'German asks for a number with wie, not was: Wie ist Ihre Telefonnummer?',
  },
  {
    id: 'v.a1.l02.email-adresse',
    de: 'E-Mail-Adresse',
    en: 'e-mail address',
    pos: 'noun',
    article: 'die',
    plural: 'die E-Mail-Adressen',
    example: 'Meine E-Mail-Adresse ist priya.sharma@mail.de.',
    exampleEn: 'My e-mail address is priya.sharma@mail.de.',
    level: 'A1',
    topic: 'personal',
    difficulty: 2,
    note: 'The @ is read as "at" and the dot as "Punkt": priya Punkt sharma at mail Punkt de.',
  },
]

export default vocab
