/**
 * A1 · L03 — Numbers, time and dates.
 *
 * The words you need to say how many, what time it is and which day something
 * happens. Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  {
    id: 'v.a1.l03.uhr',
    de: 'Uhr',
    en: 'clock, watch; o’clock',
    pos: 'noun',
    article: 'die',
    plural: 'die Uhren',
    example: 'Meine Uhr ist kaputt. Wie spät ist es?',
    exampleEn: 'My watch is broken. What time is it?',
    level: 'A1',
    topic: 'time',
    difficulty: 1,
    note: 'Uhr is also the word for "o’clock": um acht Uhr = at eight o’clock.',
  },
  {
    id: 'v.a1.l03.stunde',
    de: 'Stunde',
    en: 'hour',
    pos: 'noun',
    article: 'die',
    plural: 'die Stunden',
    example: 'Der Deutschkurs dauert zwei Stunden.',
    exampleEn: 'The German course lasts two hours.',
    level: 'A1',
    topic: 'time',
    difficulty: 1,
    note: 'Do not mix up die Stunde (a length of time) with die Uhr (the clock).',
  },
  {
    id: 'v.a1.l03.minute',
    de: 'Minute',
    en: 'minute',
    pos: 'noun',
    article: 'die',
    plural: 'die Minuten',
    example: 'Der Bus kommt in fünf Minuten.',
    exampleEn: 'The bus is coming in five minutes.',
    level: 'A1',
    topic: 'time',
    difficulty: 2,
  },
  {
    id: 'v.a1.l03.termin',
    de: 'Termin',
    en: 'appointment',
    pos: 'noun',
    article: 'der',
    plural: 'die Termine',
    example: 'Ich habe am Dienstag einen Termin.',
    exampleEn: 'I have an appointment on Tuesday.',
    level: 'A1',
    topic: 'time',
    difficulty: 2,
    note: 'einen Termin haben / machen — to have / to make an appointment.',
  },
  {
    id: 'v.a1.l03.woche',
    de: 'Woche',
    en: 'week',
    pos: 'noun',
    article: 'die',
    plural: 'die Wochen',
    example: 'Die Woche hat sieben Tage.',
    exampleEn: 'The week has seven days.',
    level: 'A1',
    topic: 'time',
    difficulty: 1,
  },
  {
    id: 'v.a1.l03.montag',
    de: 'Montag',
    en: 'Monday',
    pos: 'noun',
    article: 'der',
    plural: 'die Montage',
    example: 'Am Montag beginnt der neue Kurs.',
    exampleEn: 'The new course starts on Monday.',
    level: 'A1',
    topic: 'time',
    difficulty: 1,
    note: 'All seven days are masculine: der Montag, der Dienstag, der Mittwoch … With a day you say am: am Montag.',
  },
  {
    id: 'v.a1.l03.januar',
    de: 'Januar',
    en: 'January',
    pos: 'noun',
    article: 'der',
    plural: null,
    example: 'Im Januar ist es in Berlin sehr kalt.',
    exampleEn: 'In January it is very cold in Berlin.',
    level: 'A1',
    topic: 'time',
    difficulty: 2,
    note: 'All twelve months are masculine, and with a month you say im: im Januar, im Mai.',
  },
  {
    id: 'v.a1.l03.datum',
    de: 'Datum',
    en: 'date',
    pos: 'noun',
    article: 'das',
    plural: 'die Daten',
    example: 'Welches Datum haben wir heute?',
    exampleEn: 'What is the date today?',
    level: 'A1',
    topic: 'time',
    difficulty: 3,
    note: 'Irregular plural: das Datum → die Daten.',
  },
  {
    id: 'v.a1.l03.viertel',
    de: 'Viertel',
    en: 'quarter',
    pos: 'noun',
    article: 'das',
    plural: 'die Viertel',
    example: 'Es ist Viertel nach sieben.',
    exampleEn: 'It is a quarter past seven.',
    level: 'A1',
    topic: 'time',
    difficulty: 2,
    note: 'Viertel nach = quarter past, Viertel vor = quarter to. No article in the time phrase.',
  },
  {
    id: 'v.a1.l03.halb',
    de: 'halb',
    en: 'half',
    pos: 'adj',
    example: 'Es ist halb neun.',
    exampleEn: 'It is half past eight.',
    level: 'A1',
    topic: 'time',
    difficulty: 2,
    note: 'halb points to the NEXT full hour: halb neun = 8:30, not 9:30.',
  },
  {
    id: 'v.a1.l03.heute',
    de: 'heute',
    en: 'today',
    pos: 'adv',
    example: 'Heute habe ich viel Zeit.',
    exampleEn: 'Today I have a lot of time.',
    level: 'A1',
    topic: 'time',
    difficulty: 1,
  },
  {
    id: 'v.a1.l03.morgen',
    de: 'morgen',
    en: 'tomorrow',
    pos: 'adv',
    example: 'Morgen beginnt mein Kurs um neun Uhr.',
    exampleEn: 'Tomorrow my course starts at nine o’clock.',
    level: 'A1',
    topic: 'time',
    difficulty: 1,
    note: 'Small letter morgen = tomorrow; capital der Morgen = the morning. „morgen früh" = tomorrow morning.',
  },
  {
    id: 'v.a1.l03.gestern',
    de: 'gestern',
    en: 'yesterday',
    pos: 'adv',
    example: 'Die Zeitung ist von gestern.',
    exampleEn: 'The newspaper is from yesterday.',
    level: 'A1',
    topic: 'time',
    difficulty: 2,
    note: 'Learn the set together: gestern – heute – morgen.',
  },
  {
    id: 'v.a1.l03.hundert',
    de: 'hundert',
    en: 'hundred',
    pos: 'num',
    example: 'Das Hotel hat hundert Zimmer.',
    exampleEn: 'The hotel has a hundred rooms.',
    level: 'A1',
    topic: 'numbers',
    difficulty: 2,
    note: 'German says plain hundert where English says "a hundred".',
  },
  {
    id: 'v.a1.l03.tausend',
    de: 'tausend',
    en: 'thousand',
    pos: 'num',
    example: 'Ein Kilometer hat tausend Meter.',
    exampleEn: 'A kilometre has a thousand metres.',
    level: 'A1',
    topic: 'numbers',
    difficulty: 3,
  },
  {
    id: 'v.a1.l03.beginnen',
    de: 'beginnen',
    en: 'to begin, to start',
    pos: 'verb',
    forms: {
      ich: 'beginne',
      du: 'beginnst',
      er: 'beginnt',
      wir: 'beginnen',
      ihr: 'beginnt',
      sie: 'beginnen',
    },
    example: 'Der Film beginnt um halb acht.',
    exampleEn: 'The film starts at half past seven.',
    level: 'A1',
    topic: 'time',
    difficulty: 2,
    note: 'Completely regular. Things begin um + a clock time and am + a day.',
  },
]

export default vocab
