/**
 * A1 · L09 — Hobbies and the weather / Hobbys und Wetter
 *
 * Two halves of one conversation: what you do in your free time (Hobby,
 * Freizeit, Sport, schwimmen, wandern, kochen, tanzen, fotografieren, gern,
 * lieber) and what the sky is doing (Wetter, Sonne, Regen, Schnee, regnen,
 * Grad). Together they let a learner make a weekend plan.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── Free time: the nouns ─────────────────────────────────────────────── */
  {
    id: 'v.a1.l09.hobby',
    de: 'Hobby',
    en: 'hobby',
    pos: 'noun',
    article: 'das',
    plural: 'die Hobbys',
    example: 'Mein Hobby ist Fußball.',
    exampleEn: 'My hobby is football.',
    level: 'A1',
    topic: 'hobbies',
    difficulty: 1,
    note: 'Borrowed from English, so the plural takes -s: die Hobbys.',
  },
  {
    id: 'v.a1.l09.freizeit',
    de: 'Freizeit',
    en: 'free time, leisure time',
    pos: 'noun',
    article: 'die',
    plural: null,
    example: 'In der Freizeit koche ich gern.',
    exampleEn: 'In my free time I like cooking.',
    level: 'A1',
    topic: 'hobbies',
    difficulty: 2,
    note: 'No plural. The fixed phrase is in der Freizeit — German does not say "meine Freizeit" here.',
  },
  {
    id: 'v.a1.l09.sport',
    de: 'Sport',
    en: 'sport, exercise',
    pos: 'noun',
    article: 'der',
    plural: null,
    example: 'Am Abend mache ich Sport.',
    exampleEn: 'In the evening I do sport.',
    level: 'A1',
    topic: 'hobbies',
    difficulty: 1,
    note: 'You "make" sport in German: Sport machen. There is no article in that phrase.',
  },

  /* ── Free time: the verbs ─────────────────────────────────────────────── */
  {
    id: 'v.a1.l09.schwimmen',
    de: 'schwimmen',
    en: 'to swim',
    pos: 'verb',
    example: 'Im Sommer schwimme ich sehr gern.',
    exampleEn: 'In summer I really like swimming.',
    level: 'A1',
    topic: 'hobbies',
    difficulty: 1,
    forms: {
      ich: 'schwimme',
      du: 'schwimmst',
      er: 'schwimmt',
      wir: 'schwimmen',
      ihr: 'schwimmt',
      sie: 'schwimmen',
    },
  },
  {
    id: 'v.a1.l09.wandern',
    de: 'wandern',
    en: 'to hike, to go walking',
    pos: 'verb',
    example: 'Meine Eltern wandern jedes Wochenende.',
    exampleEn: 'My parents go hiking every weekend.',
    level: 'A1',
    topic: 'hobbies',
    difficulty: 2,
    note: 'The stem ends in -er, so the ich form drops a letter in speech: ich wandere, often ich wandre.',
    forms: {
      ich: 'wandere',
      du: 'wanderst',
      er: 'wandert',
      wir: 'wandern',
      ihr: 'wandert',
      sie: 'wandern',
    },
  },
  {
    id: 'v.a1.l09.kochen',
    de: 'kochen',
    en: 'to cook',
    pos: 'verb',
    example: 'Heute Abend koche ich Nudeln.',
    exampleEn: 'This evening I am cooking pasta.',
    level: 'A1',
    topic: 'hobbies',
    difficulty: 1,
    forms: {
      ich: 'koche',
      du: 'kochst',
      er: 'kocht',
      wir: 'kochen',
      ihr: 'kocht',
      sie: 'kochen',
    },
  },
  {
    id: 'v.a1.l09.tanzen',
    de: 'tanzen',
    en: 'to dance',
    pos: 'verb',
    example: 'Meine Schwester tanzt sehr gut.',
    exampleEn: 'My sister dances very well.',
    level: 'A1',
    topic: 'hobbies',
    difficulty: 2,
    note: 'The stem ends in -z, so the -s of the du ending disappears: du tanzt — the same word as er tanzt.',
    forms: {
      ich: 'tanze',
      du: 'tanzt',
      er: 'tanzt',
      wir: 'tanzen',
      ihr: 'tanzt',
      sie: 'tanzen',
    },
  },
  {
    id: 'v.a1.l09.fotografieren',
    de: 'fotografieren',
    en: 'to take photos, to photograph',
    pos: 'verb',
    example: 'Im Park fotografiere ich gern Blumen.',
    exampleEn: 'In the park I like taking photos of flowers.',
    level: 'A1',
    topic: 'hobbies',
    difficulty: 3,
    note: 'Verbs in -ieren are completely regular and never change their vowel.',
    forms: {
      ich: 'fotografiere',
      du: 'fotografierst',
      er: 'fotografiert',
      wir: 'fotografieren',
      ihr: 'fotografiert',
      sie: 'fotografieren',
    },
  },

  /* ── How much you like it ─────────────────────────────────────────────── */
  {
    id: 'v.a1.l09.gern',
    de: 'gern',
    en: 'gladly, with pleasure (marks what you like doing)',
    pos: 'adv',
    example: 'Ich höre gern Musik.',
    exampleEn: 'I like listening to music.',
    level: 'A1',
    topic: 'hobbies',
    difficulty: 1,
    note: 'German has no verb "to like doing". You add gern to the normal verb: Ich koche gern.',
  },
  {
    id: 'v.a1.l09.lieber',
    de: 'lieber',
    en: 'rather, preferably',
    pos: 'adv',
    example: 'Heute möchte ich lieber zu Hause bleiben.',
    exampleEn: 'Today I would rather stay at home.',
    level: 'A1',
    topic: 'hobbies',
    difficulty: 2,
    note: 'The three steps are gern → lieber → am liebsten (most of all).',
  },

  /* ── The weather ──────────────────────────────────────────────────────── */
  {
    id: 'v.a1.l09.wetter',
    de: 'Wetter',
    en: 'weather',
    pos: 'noun',
    article: 'das',
    plural: null,
    example: 'Wie ist das Wetter in Berlin?',
    exampleEn: 'What is the weather like in Berlin?',
    level: 'A1',
    topic: 'weather',
    difficulty: 1,
    note: 'The question is always Wie ist das Wetter? — with wie (how), not with was.',
  },
  {
    id: 'v.a1.l09.sonne',
    de: 'Sonne',
    en: 'sun',
    pos: 'noun',
    article: 'die',
    plural: null,
    example: 'Die Sonne scheint den ganzen Tag.',
    exampleEn: 'The sun shines all day long.',
    level: 'A1',
    topic: 'weather',
    difficulty: 1,
    note: 'The sun does its own verb: die Sonne scheint.',
  },
  {
    id: 'v.a1.l09.regen',
    de: 'Regen',
    en: 'rain',
    pos: 'noun',
    article: 'der',
    plural: null,
    example: 'Bei Regen bleibe ich zu Hause.',
    exampleEn: 'When it rains I stay at home.',
    level: 'A1',
    topic: 'weather',
    difficulty: 1,
    note: 'bei Regen / bei Schnee is the fixed way to say "when it rains / snows".',
  },
  {
    id: 'v.a1.l09.schnee',
    de: 'Schnee',
    en: 'snow',
    pos: 'noun',
    article: 'der',
    plural: null,
    example: 'Im Januar haben wir oft Schnee.',
    exampleEn: 'In January we often have snow.',
    level: 'A1',
    topic: 'weather',
    difficulty: 2,
    note: 'The matching verb is schneien: Es schneit.',
  },
  {
    id: 'v.a1.l09.regnen',
    de: 'regnen',
    en: 'to rain',
    pos: 'verb',
    example: 'Es regnet heute den ganzen Tag.',
    exampleEn: 'It is raining all day today.',
    level: 'A1',
    topic: 'weather',
    difficulty: 2,
    note: 'Weather verbs only exist in the es form: Es regnet. There is no ich regne.',
  },
  {
    id: 'v.a1.l09.grad',
    de: 'Grad',
    en: 'degree (temperature)',
    pos: 'noun',
    article: 'der',
    plural: 'die Grad',
    example: 'Heute haben wir zweiundzwanzig Grad.',
    exampleEn: 'Today it is twenty-two degrees.',
    level: 'A1',
    topic: 'weather',
    difficulty: 2,
    note: 'After a number Grad never changes: zwanzig Grad, dreißig Grad. German says wir haben … Grad where English says "it is".',
  },
]

export default vocab
