/**
 * A1 · L10 — Transport and directions / Verkehr und Wegbeschreibung
 *
 * The words you need to get across a German city: the vehicles (Bus, Bahn, Zug,
 * Fahrrad), the places they stop at (Haltestelle, Bahnhof), the ticket, the
 * three separable steigen-verbs (einsteigen, aussteigen, umsteigen) and the
 * four direction words that answer every "Wie komme ich zu …?".
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── Vehicles ─────────────────────────────────────────────────────────── */
  {
    id: 'v.a1.l10.bus',
    de: 'Bus',
    en: 'bus',
    pos: 'noun',
    article: 'der',
    plural: 'die Busse',
    example: 'Der Bus kommt in fünf Minuten.',
    exampleEn: 'The bus is coming in five minutes.',
    level: 'A1',
    topic: 'transport',
    difficulty: 1,
    note: 'Travelling by bus is mit dem Bus — never "bei Bus" or "in Bus".',
  },
  {
    id: 'v.a1.l10.bahn',
    de: 'Bahn',
    en: 'train, tram (the rail network)',
    pos: 'noun',
    article: 'die',
    plural: 'die Bahnen',
    example: 'Die Bahn nach Köln fährt um acht Uhr.',
    exampleEn: 'The train to Cologne leaves at eight.',
    level: 'A1',
    topic: 'transport',
    difficulty: 2,
    note: 'die Bahn is the system or the tram; der Zug is the single train you sit in.',
  },
  {
    id: 'v.a1.l10.zug',
    de: 'Zug',
    en: 'train',
    pos: 'noun',
    article: 'der',
    plural: 'die Züge',
    example: 'Der Zug nach Berlin fährt um zehn Uhr.',
    exampleEn: 'The train to Berlin leaves at ten.',
    level: 'A1',
    topic: 'transport',
    difficulty: 1,
    note: 'Plural with umlaut: der Zug → die Züge.',
  },
  {
    id: 'v.a1.l10.fahrrad',
    de: 'Fahrrad',
    en: 'bicycle',
    pos: 'noun',
    article: 'das',
    plural: 'die Fahrräder',
    example: 'Ich fahre jeden Tag mit dem Fahrrad ins Büro.',
    exampleEn: 'Every day I cycle to the office.',
    level: 'A1',
    topic: 'transport',
    difficulty: 2,
    note: 'Short form: das Rad. Both are neuter, both take mit dem.',
  },

  /* ── Places ───────────────────────────────────────────────────────────── */
  {
    id: 'v.a1.l10.haltestelle',
    de: 'Haltestelle',
    en: 'stop (bus or tram stop)',
    pos: 'noun',
    article: 'die',
    plural: 'die Haltestellen',
    example: 'Die Haltestelle ist gleich rechts.',
    exampleEn: 'The stop is right there on the right.',
    level: 'A1',
    topic: 'transport',
    difficulty: 2,
    note: 'From halten (to stop). Nouns ending in -e are nearly always feminine.',
  },
  {
    id: 'v.a1.l10.bahnhof',
    de: 'Bahnhof',
    en: 'station',
    pos: 'noun',
    article: 'der',
    plural: 'die Bahnhöfe',
    example: 'Der Bahnhof ist nicht weit von hier.',
    exampleEn: 'The station is not far from here.',
    level: 'A1',
    topic: 'transport',
    difficulty: 1,
    note: 'The main station of a city is der Hauptbahnhof, often written Hbf.',
  },
  {
    id: 'v.a1.l10.strasse',
    de: 'Straße',
    en: 'street, road',
    pos: 'noun',
    article: 'die',
    plural: 'die Straßen',
    example: 'Nehmen Sie die zweite Straße links.',
    exampleEn: 'Take the second street on the left.',
    level: 'A1',
    topic: 'directions',
    difficulty: 1,
    note: 'In addresses it joins the name: die Gartenstraße, die Hauptstraße.',
  },

  /* ── The ticket ───────────────────────────────────────────────────────── */
  {
    id: 'v.a1.l10.fahrkarte',
    de: 'Fahrkarte',
    en: 'ticket',
    pos: 'noun',
    article: 'die',
    plural: 'die Fahrkarten',
    example: 'Eine Fahrkarte nach Köln, bitte.',
    exampleEn: 'One ticket to Cologne, please.',
    level: 'A1',
    topic: 'transport',
    difficulty: 1,
    note: 'Also das Ticket. At the counter you simply say: Eine Fahrkarte nach …, bitte.',
  },

  /* ── The three steigen-verbs ──────────────────────────────────────────── */
  {
    id: 'v.a1.l10.einsteigen',
    de: 'einsteigen',
    en: 'to get on, to board',
    pos: 'verb',
    example: 'Ich möchte vorne einsteigen.',
    exampleEn: 'I would like to get on at the front.',
    level: 'A1',
    topic: 'transport',
    difficulty: 2,
    separable: true,
    note: 'In a normal sentence the prefix splits off: Ich steige vorne ein.',
    forms: {
      ich: 'steige ein',
      du: 'steigst ein',
      er: 'steigt ein',
      wir: 'steigen ein',
      ihr: 'steigt ein',
      sie: 'steigen ein',
    },
  },
  {
    id: 'v.a1.l10.aussteigen',
    de: 'aussteigen',
    en: 'to get off',
    pos: 'verb',
    example: 'Wo möchten Sie aussteigen?',
    exampleEn: 'Where would you like to get off?',
    level: 'A1',
    topic: 'transport',
    difficulty: 2,
    separable: true,
    note: 'Split in a normal sentence: Ich steige am Bahnhof aus.',
    forms: {
      ich: 'steige aus',
      du: 'steigst aus',
      er: 'steigt aus',
      wir: 'steigen aus',
      ihr: 'steigt aus',
      sie: 'steigen aus',
    },
  },
  {
    id: 'v.a1.l10.umsteigen',
    de: 'umsteigen',
    en: 'to change (buses, trains)',
    pos: 'verb',
    example: 'Wir möchten am Bahnhof umsteigen.',
    exampleEn: 'We would like to change at the station.',
    level: 'A1',
    topic: 'transport',
    difficulty: 3,
    separable: true,
    note: 'ein — aus — um: you get on, you get off, and in between you change.',
    forms: {
      ich: 'steige um',
      du: 'steigst um',
      er: 'steigt um',
      wir: 'steigen um',
      ihr: 'steigt um',
      sie: 'steigen um',
    },
  },

  /* ── Directions ───────────────────────────────────────────────────────── */
  {
    id: 'v.a1.l10.links',
    de: 'links',
    en: 'left, on the left',
    pos: 'adv',
    example: 'Die Apotheke ist links.',
    exampleEn: 'The pharmacy is on the left.',
    level: 'A1',
    topic: 'directions',
    difficulty: 1,
    note: 'links never changes its form. "Turn left" is Gehen Sie links.',
  },
  {
    id: 'v.a1.l10.rechts',
    de: 'rechts',
    en: 'right, on the right',
    pos: 'adv',
    example: 'Gehen Sie an der Ecke rechts.',
    exampleEn: 'Turn right at the corner.',
    level: 'A1',
    topic: 'directions',
    difficulty: 1,
    note: 'die Ecke = the corner; an der Ecke is the fixed phrase for "at the corner".',
  },
  {
    id: 'v.a1.l10.geradeaus',
    de: 'geradeaus',
    en: 'straight on, straight ahead',
    pos: 'adv',
    example: 'Gehen Sie bitte geradeaus.',
    exampleEn: 'Please go straight on.',
    level: 'A1',
    topic: 'directions',
    difficulty: 2,
    note: 'One word, stress on the last syllable: gerade-AUS.',
  },
  {
    id: 'v.a1.l10.zu-fuss',
    de: 'zu Fuß',
    en: 'on foot, walking',
    pos: 'phrase',
    example: 'Ich gehe zu Fuß zur Arbeit.',
    exampleEn: 'I walk to work.',
    level: 'A1',
    topic: 'transport',
    difficulty: 2,
    note: 'The one way of travelling with no mit: mit dem Bus, mit der Bahn — but zu Fuß.',
  },
  {
    id: 'v.a1.l10.entschuldigung',
    de: 'Entschuldigung',
    en: 'excuse me, sorry',
    pos: 'phrase',
    example: 'Entschuldigung, wo ist die Haltestelle?',
    exampleEn: 'Excuse me, where is the stop?',
    level: 'A1',
    topic: 'directions',
    difficulty: 1,
    note: 'The word that opens every question to a stranger. Also used to say sorry.',
  },
]

export default vocab
