/**
 * A1 · L06 — Food, drinks and the restaurant / Essen, Trinken und im Restaurant
 *
 * Sixteen words for a real German lunch: what is on the plate, what is in the
 * glass, and the four words that run the whole visit — die Speisekarte,
 * bestellen, die Rechnung, der Kellner.
 *
 * Every noun here is chosen so the learner meets all three genders while
 * practising the accusative, where only the masculine der → den changes.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── On the plate ─────────────────────────────────────────────────────── */
  {
    id: 'v.a1.l06.brot',
    de: 'Brot',
    en: 'bread',
    pos: 'noun',
    article: 'das',
    plural: 'die Brote',
    example: 'Das Brot ist noch warm.',
    exampleEn: 'The bread is still warm.',
    level: 'A1',
    topic: 'food',
    difficulty: 1,
    note: 'Neuter, so it never changes in the accusative: Ich esse das Brot.',
  },
  {
    id: 'v.a1.l06.broetchen',
    de: 'Brötchen',
    en: 'bread roll',
    pos: 'noun',
    article: 'das',
    plural: 'die Brötchen',
    example: 'Zum Frühstück esse ich ein Brötchen mit Butter.',
    exampleEn: 'For breakfast I eat a bread roll with butter.',
    level: 'A1',
    topic: 'food',
    difficulty: 2,
    note: 'The ending -chen always makes a noun das, and it never changes in the plural.',
  },
  {
    id: 'v.a1.l06.apfel',
    de: 'Apfel',
    en: 'apple',
    pos: 'noun',
    article: 'der',
    plural: 'die Äpfel',
    example: 'Ich esse jeden Tag einen Apfel.',
    exampleEn: 'I eat an apple every day.',
    level: 'A1',
    topic: 'food',
    difficulty: 2,
    note: 'Masculine, so it becomes den Apfel / einen Apfel as an object. Plural: a → ä.',
  },
  {
    id: 'v.a1.l06.suppe',
    de: 'Suppe',
    en: 'soup',
    pos: 'noun',
    article: 'die',
    plural: 'die Suppen',
    example: 'Die Suppe schmeckt heute sehr gut.',
    exampleEn: 'The soup tastes very good today.',
    level: 'A1',
    topic: 'food',
    difficulty: 1,
    note: 'Nouns ending in -e are usually feminine and add -n in the plural.',
  },
  {
    id: 'v.a1.l06.salat',
    de: 'Salat',
    en: 'salad; lettuce',
    pos: 'noun',
    article: 'der',
    plural: 'die Salate',
    example: 'Ich nehme den Salat mit Käse.',
    exampleEn: 'I will take the salad with cheese.',
    level: 'A1',
    topic: 'food',
    difficulty: 1,
    note: 'Masculine — one of the words where you really hear the accusative: den Salat.',
  },
  {
    id: 'v.a1.l06.mittagessen',
    de: 'Mittagessen',
    en: 'lunch',
    pos: 'noun',
    article: 'das',
    plural: 'die Mittagessen',
    example: 'Das Mittagessen kostet neun Euro.',
    exampleEn: 'Lunch costs nine euros.',
    level: 'A1',
    topic: 'food',
    difficulty: 2,
    note: 'Also das Frühstück (breakfast) and das Abendessen (dinner) — all three meals are das.',
  },

  /* ── In the glass ─────────────────────────────────────────────────────── */
  {
    id: 'v.a1.l06.kaffee',
    de: 'Kaffee',
    en: 'coffee',
    pos: 'noun',
    article: 'der',
    plural: 'die Kaffees',
    example: 'Der Kaffee ist heiß.',
    exampleEn: 'The coffee is hot.',
    level: 'A1',
    topic: 'food',
    difficulty: 1,
    note: 'The plural die Kaffees means cups of coffee: Zwei Kaffees, bitte.',
  },
  {
    id: 'v.a1.l06.wasser',
    de: 'Wasser',
    en: 'water',
    pos: 'noun',
    article: 'das',
    plural: null,
    example: 'Ein Wasser, bitte.',
    exampleEn: 'A water, please.',
    level: 'A1',
    topic: 'food',
    difficulty: 1,
    note: 'Uncountable, so there is no everyday plural. In a café you still order ein Wasser.',
  },
  {
    id: 'v.a1.l06.saft',
    de: 'Saft',
    en: 'juice',
    pos: 'noun',
    article: 'der',
    plural: 'die Säfte',
    example: 'Der Saft ist kalt.',
    exampleEn: 'The juice is cold.',
    level: 'A1',
    topic: 'food',
    difficulty: 2,
    note: 'Compounds keep the gender: der Apfelsaft, der Orangensaft. Plural: a → ä.',
  },

  /* ── The restaurant itself ────────────────────────────────────────────── */
  {
    id: 'v.a1.l06.speisekarte',
    de: 'Speisekarte',
    en: 'menu',
    pos: 'noun',
    article: 'die',
    plural: 'die Speisekarten',
    example: 'Der Kellner bringt die Speisekarte.',
    exampleEn: 'The waiter brings the menu.',
    level: 'A1',
    topic: 'restaurant',
    difficulty: 2,
    note: 'A compound takes the gender of its last part: die Karte → die Speisekarte.',
  },
  {
    id: 'v.a1.l06.rechnung',
    de: 'Rechnung',
    en: 'bill, invoice',
    pos: 'noun',
    article: 'die',
    plural: 'die Rechnungen',
    example: 'Die Rechnung ist leider sehr hoch.',
    exampleEn: 'Unfortunately the bill is very high.',
    level: 'A1',
    topic: 'restaurant',
    difficulty: 2,
    note: 'Every noun ending in -ung is feminine. To pay you simply say: Die Rechnung, bitte.',
  },
  {
    id: 'v.a1.l06.kellner',
    de: 'Kellner',
    en: 'waiter',
    pos: 'noun',
    article: 'der',
    plural: 'die Kellner',
    example: 'Der Kellner bringt das Essen.',
    exampleEn: 'The waiter brings the food.',
    level: 'A1',
    topic: 'restaurant',
    difficulty: 2,
    note: 'Female form: die Kellnerin. Nouns in -er do not change in the plural.',
  },

  /* ── Doing things ─────────────────────────────────────────────────────── */
  {
    id: 'v.a1.l06.bestellen',
    de: 'bestellen',
    en: 'to order',
    pos: 'verb',
    example: 'Wir bestellen eine Suppe und einen Salat.',
    exampleEn: 'We are ordering a soup and a salad.',
    level: 'A1',
    topic: 'restaurant',
    difficulty: 1,
    note: 'Completely regular, and what you order stands in the accusative.',
    forms: {
      ich: 'bestelle',
      du: 'bestellst',
      er: 'bestellt',
      wir: 'bestellen',
      ihr: 'bestellt',
      sie: 'bestellen',
    },
  },
  {
    id: 'v.a1.l06.moechten',
    de: 'möchten',
    en: 'would like',
    pos: 'verb',
    example: 'Ich möchte einen Kaffee, bitte.',
    exampleEn: 'I would like a coffee, please.',
    level: 'A1',
    topic: 'restaurant',
    difficulty: 2,
    note: 'ich and er share one form (möchte) with no -t. The polite way to order anything.',
    forms: {
      ich: 'möchte',
      du: 'möchtest',
      er: 'möchte',
      wir: 'möchten',
      ihr: 'möchtet',
      sie: 'möchten',
    },
  },
  {
    id: 'v.a1.l06.schmecken',
    de: 'schmecken',
    en: 'to taste (good)',
    pos: 'verb',
    example: 'Das Brot schmeckt sehr lecker.',
    exampleEn: 'The bread tastes delicious.',
    level: 'A1',
    topic: 'food',
    difficulty: 3,
    note: 'The food is the subject, not the person: Die Suppe schmeckt gut, not "Ich schmecke die Suppe".',
    forms: {
      ich: 'schmecke',
      du: 'schmeckst',
      er: 'schmeckt',
      wir: 'schmecken',
      ihr: 'schmeckt',
      sie: 'schmecken',
    },
  },
  {
    id: 'v.a1.l06.lecker',
    de: 'lecker',
    en: 'delicious, tasty',
    pos: 'adj',
    example: 'Der Salat ist wirklich lecker.',
    exampleEn: 'The salad is really tasty.',
    level: 'A1',
    topic: 'food',
    difficulty: 1,
    note: 'Used after ist or schmeckt, so it takes no ending: Das schmeckt lecker.',
  },
]

export default vocab
