/**
 * A1 · L08 — Home and furniture / Wohnen und Möbel
 *
 * The rooms of a flat, the furniture inside them, the rent on the door — and
 * three adjectives to describe it all. Every noun is stored with its article
 * AND its plural, because this lesson teaches the plural.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── The flat and its rooms ───────────────────────────────────────────── */
  {
    id: 'v.a1.l08.wohnung',
    de: 'Wohnung',
    en: 'flat, apartment',
    pos: 'noun',
    article: 'die',
    plural: 'die Wohnungen',
    example: 'Meine Wohnung hat drei Zimmer.',
    exampleEn: 'My flat has three rooms.',
    level: 'A1',
    topic: 'housing',
    difficulty: 1,
    note: 'Every noun ending in -ung is feminine and takes -en in the plural: die Wohnung → die Wohnungen.',
  },
  {
    id: 'v.a1.l08.zimmer',
    de: 'Zimmer',
    en: 'room',
    pos: 'noun',
    article: 'das',
    plural: 'die Zimmer',
    example: 'Das Zimmer ist klein, aber hell.',
    exampleEn: 'The room is small but bright.',
    level: 'A1',
    topic: 'home',
    difficulty: 1,
    note: 'Singular and plural look identical — only the article changes: das Zimmer → die Zimmer.',
  },
  {
    id: 'v.a1.l08.schlafzimmer',
    de: 'Schlafzimmer',
    en: 'bedroom',
    pos: 'noun',
    article: 'das',
    plural: 'die Schlafzimmer',
    example: 'Mein Schlafzimmer ist sehr ruhig.',
    exampleEn: 'My bedroom is very quiet.',
    level: 'A1',
    topic: 'home',
    difficulty: 2,
    note: 'schlafen + Zimmer. A compound noun takes the gender of its LAST part, so it is das Schlafzimmer.',
  },
  {
    id: 'v.a1.l08.wohnzimmer',
    de: 'Wohnzimmer',
    en: 'living room',
    pos: 'noun',
    article: 'das',
    plural: 'die Wohnzimmer',
    example: 'Im Wohnzimmer stehen ein Sofa und zwei Stühle.',
    exampleEn: 'In the living room there are a sofa and two chairs.',
    level: 'A1',
    topic: 'home',
    difficulty: 2,
    note: 'Germans say stehen (stand) for furniture, not "there is": Im Wohnzimmer steht ein Tisch.',
  },
  {
    id: 'v.a1.l08.kueche',
    de: 'Küche',
    en: 'kitchen',
    pos: 'noun',
    article: 'die',
    plural: 'die Küchen',
    example: 'Die Küche ist neu und sehr praktisch.',
    exampleEn: 'The kitchen is new and very practical.',
    level: 'A1',
    topic: 'home',
    difficulty: 1,
    note: 'Nouns ending in -e are usually feminine and add -n in the plural: die Küche → die Küchen.',
  },
  {
    id: 'v.a1.l08.bad',
    de: 'Bad',
    en: 'bathroom',
    pos: 'noun',
    article: 'das',
    plural: 'die Bäder',
    example: 'Das Bad ist klein und dunkel.',
    exampleEn: 'The bathroom is small and dark.',
    level: 'A1',
    topic: 'home',
    difficulty: 2,
    note: 'Plural with -er and an Umlaut: das Bad → die Bäder, like das Haus → die Häuser.',
  },

  /* ── Furniture ────────────────────────────────────────────────────────── */
  {
    id: 'v.a1.l08.tisch',
    de: 'Tisch',
    en: 'table',
    pos: 'noun',
    article: 'der',
    plural: 'die Tische',
    example: 'Der Tisch ist zu groß für die Küche.',
    exampleEn: 'The table is too big for the kitchen.',
    level: 'A1',
    topic: 'home',
    difficulty: 1,
    note: 'Also: der Schreibtisch = desk. Masculine, plural with -e: die Tische.',
  },
  {
    id: 'v.a1.l08.stuhl',
    de: 'Stuhl',
    en: 'chair',
    pos: 'noun',
    article: 'der',
    plural: 'die Stühle',
    example: 'Der Stuhl ist alt, aber sehr bequem.',
    exampleEn: 'The chair is old but very comfortable.',
    level: 'A1',
    topic: 'home',
    difficulty: 1,
    note: 'Plural adds -e and an Umlaut: der Stuhl → die Stühle.',
  },
  {
    id: 'v.a1.l08.bett',
    de: 'Bett',
    en: 'bed',
    pos: 'noun',
    article: 'das',
    plural: 'die Betten',
    example: 'Das Bett ist neu und sehr groß.',
    exampleEn: 'The bed is new and very big.',
    level: 'A1',
    topic: 'home',
    difficulty: 1,
    note: 'The t doubles in the plural: das Bett → die Betten.',
  },
  {
    id: 'v.a1.l08.schrank',
    de: 'Schrank',
    en: 'wardrobe, cupboard',
    pos: 'noun',
    article: 'der',
    plural: 'die Schränke',
    example: 'Der Schrank ist braun und sehr alt.',
    exampleEn: 'The wardrobe is brown and very old.',
    level: 'A1',
    topic: 'home',
    difficulty: 2,
    note: 'Also: der Kühlschrank = fridge. Plural with -e and Umlaut: die Schränke.',
  },
  {
    id: 'v.a1.l08.sofa',
    de: 'Sofa',
    en: 'sofa, couch',
    pos: 'noun',
    article: 'das',
    plural: 'die Sofas',
    example: 'Das Sofa ist alt, aber gemütlich.',
    exampleEn: 'The sofa is old but cosy.',
    level: 'A1',
    topic: 'home',
    difficulty: 1,
    note: 'A loan word, so the plural takes -s: die Sofas — like die Autos and die Handys.',
  },
  {
    id: 'v.a1.l08.lampe',
    de: 'Lampe',
    en: 'lamp, light',
    pos: 'noun',
    article: 'die',
    plural: 'die Lampen',
    example: 'Die Lampe ist modern und sehr hell.',
    exampleEn: 'The lamp is modern and very bright.',
    level: 'A1',
    topic: 'home',
    difficulty: 1,
    note: 'Feminine, plural with -n: die Lampe → die Lampen.',
  },
  {
    id: 'v.a1.l08.fenster',
    de: 'Fenster',
    en: 'window',
    pos: 'noun',
    article: 'das',
    plural: 'die Fenster',
    example: 'Das Zimmer hat zwei Fenster.',
    exampleEn: 'The room has two windows.',
    level: 'A1',
    topic: 'home',
    difficulty: 2,
    note: 'Nouns in -er, -el and -en usually add nothing in the plural: das Fenster → die Fenster.',
  },
  {
    id: 'v.a1.l08.miete',
    de: 'Miete',
    en: 'rent',
    pos: 'noun',
    article: 'die',
    plural: 'die Mieten',
    example: 'Die Miete kostet 750 Euro im Monat.',
    exampleEn: 'The rent is 750 euros a month.',
    level: 'A1',
    topic: 'housing',
    difficulty: 3,
    note: 'Germans ask: Wie hoch ist die Miete? — literally "how high is the rent?"',
  },

  /* ── Describing a home ────────────────────────────────────────────────── */
  {
    id: 'v.a1.l08.hell',
    de: 'hell',
    en: 'bright, light',
    pos: 'adj',
    example: 'Das Wohnzimmer ist groß und hell.',
    exampleEn: 'The living room is big and bright.',
    level: 'A1',
    topic: 'home',
    difficulty: 1,
    note: 'The opposite is dunkel (dark): Das Bad ist dunkel. Both are the first words in every flat advert.',
  },
  {
    id: 'v.a1.l08.gemuetlich',
    de: 'gemütlich',
    en: 'cosy, comfortable',
    pos: 'adj',
    example: 'Meine Wohnung ist klein, aber sehr gemütlich.',
    exampleEn: 'My flat is small but very cosy.',
    level: 'A1',
    topic: 'home',
    difficulty: 2,
    note: 'A very German compliment — it works for a room, a café or a whole evening.',
  },
]

export default vocab
