/**
 * A2 · L18 — Plans, problems and solutions / Pläne, Probleme und Lösungen
 *
 * The words for the day something does not work: making a plan (der Plan,
 * vorhaben, sich vorbereiten), naming the trouble (das Problem, kaputt,
 * funktionieren, schiefgehen), and fixing it in a shop or an office
 * (sich beschweren, umtauschen, zurückgeben, die Quittung, die Garantie,
 * sich entschuldigen, vorschlagen, versprechen, absagen, klappen).
 *
 * The list is deliberately half separable (vorhaben, umtauschen,
 * zurückgeben, vorschlagen, absagen, schiefgehen, sich vorbereiten) and half
 * inseparable (sich beschweren, sich entschuldigen, versprechen) so the
 * grammar step has real material on both sides.
 *
 * erledigen, verschieben, Termin, Rechnung and Schaden are already taught
 * earlier — they are reused here, not redefined.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── Making a plan ────────────────────────────────────────────────────── */
  {
    id: 'v.a2.l18.plan',
    de: 'Plan',
    en: 'plan',
    pos: 'noun',
    article: 'der',
    plural: 'die Pläne',
    example: 'Der Plan für das Wochenende steht schon.',
    exampleEn: 'The plan for the weekend is already settled.',
    level: 'A2',
    topic: 'social',
    difficulty: 1,
    note: 'Fixed phrases: Pläne machen (to make plans), Was sind deine Pläne? The plural takes an Umlaut: die Pläne.',
  },
  {
    id: 'v.a2.l18.vorhaben',
    de: 'vorhaben',
    en: 'to plan, to intend',
    pos: 'verb',
    example: 'Ich möchte wissen, was du am Wochenende vorhast.',
    exampleEn: 'I would like to know what you are planning for the weekend.',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    separable: true,
    note: 'Built on haben, so it is irregular: ich habe vor, du hast vor. The everyday way to ask about plans: Was hast du am Samstag vor?',
    forms: {
      ich: 'habe vor',
      du: 'hast vor',
      er: 'hat vor',
      wir: 'haben vor',
      ihr: 'habt vor',
      sie: 'haben vor',
    },
    perfect: 'hat vorgehabt',
  },
  {
    id: 'v.a2.l18.vorbereiten',
    de: 'sich vorbereiten',
    en: 'to prepare (yourself)',
    pos: 'verb',
    example: 'Meine Kollegin bereitet sich auf das Gespräch vor.',
    exampleEn: 'My colleague is preparing for the meeting.',
    level: 'A2',
    topic: 'work',
    difficulty: 2,
    separable: true,
    note: 'Reflexive and separable at the same time: Ich bereite mich vor. What you prepare for takes auf + accusative: auf die Prüfung.',
    forms: {
      ich: 'bereite mich vor',
      du: 'bereitest dich vor',
      er: 'bereitet sich vor',
      wir: 'bereiten uns vor',
      ihr: 'bereitet euch vor',
      sie: 'bereiten sich vor',
    },
    perfect: 'hat sich vorbereitet',
  },
  {
    id: 'v.a2.l18.vorschlagen',
    de: 'vorschlagen',
    en: 'to suggest, to propose',
    pos: 'verb',
    example: 'Darf ich einen Termin am Freitag vorschlagen?',
    exampleEn: 'May I suggest an appointment on Friday?',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    separable: true,
    note: 'Stem-changing as well: du schlägst vor, er schlägt vor. The noun is der Vorschlag = the suggestion.',
    forms: {
      ich: 'schlage vor',
      du: 'schlägst vor',
      er: 'schlägt vor',
      wir: 'schlagen vor',
      ihr: 'schlagt vor',
      sie: 'schlagen vor',
    },
    perfect: 'hat vorgeschlagen',
  },
  {
    id: 'v.a2.l18.absagen',
    de: 'absagen',
    en: 'to cancel, to call off',
    pos: 'verb',
    example: 'Wir müssen das Treffen am Dienstag leider absagen.',
    exampleEn: 'Unfortunately we have to cancel the meeting on Tuesday.',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    separable: true,
    note: 'absagen kills the appointment; verschieben only moves it. The opposite is zusagen = to accept an invitation.',
    forms: {
      ich: 'sage ab',
      du: 'sagst ab',
      er: 'sagt ab',
      wir: 'sagen ab',
      ihr: 'sagt ab',
      sie: 'sagen ab',
    },
    perfect: 'hat abgesagt',
  },
  {
    id: 'v.a2.l18.versprechen',
    de: 'versprechen',
    en: 'to promise',
    pos: 'verb',
    example: 'Ich verspreche dir, ich rufe morgen früh an.',
    exampleEn: 'I promise you, I will call tomorrow morning.',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    note: 'ver- is inseparable, so nothing moves and the participle has no ge-: versprochen. The person you promise something to stands in the dative: Ich verspreche dir …',
    forms: {
      ich: 'verspreche',
      du: 'versprichst',
      er: 'verspricht',
      wir: 'versprechen',
      ihr: 'versprecht',
      sie: 'versprechen',
    },
    perfect: 'hat versprochen',
  },

  /* ── When it goes wrong ───────────────────────────────────────────────── */
  {
    id: 'v.a2.l18.problem',
    de: 'Problem',
    en: 'problem',
    pos: 'noun',
    article: 'das',
    plural: 'die Probleme',
    example: 'Wir haben ein Problem mit der Lieferung.',
    exampleEn: 'We have a problem with the delivery.',
    level: 'A2',
    topic: 'services',
    difficulty: 1,
    note: 'Kein Problem! is the standard friendly answer to a request. The thing that is wrong follows with mit + dative.',
  },
  {
    id: 'v.a2.l18.loesung',
    de: 'Lösung',
    en: 'solution',
    pos: 'noun',
    article: 'die',
    plural: 'die Lösungen',
    example: 'Der Chef sucht eine schnelle Lösung.',
    exampleEn: 'The boss is looking for a quick solution.',
    level: 'A2',
    topic: 'services',
    difficulty: 1,
    note: 'From the verb lösen = to solve. Every noun ending in -ung is feminine and makes its plural with -en.',
  },
  {
    id: 'v.a2.l18.kaputt',
    de: 'kaputt',
    en: 'broken, not working',
    pos: 'adj',
    example: 'Der Drucker im Büro ist schon wieder kaputt.',
    exampleEn: 'The printer in the office is broken again.',
    level: 'A2',
    topic: 'technology',
    difficulty: 1,
    note: 'Used with sein, never with haben: Das Handy ist kaputt. kaputtmachen = to break something.',
  },
  {
    id: 'v.a2.l18.funktionieren',
    de: 'funktionieren',
    en: 'to work, to function',
    pos: 'verb',
    example: 'Mein neues Handy funktioniert seit gestern nicht mehr.',
    exampleEn: 'My new phone has not been working since yesterday.',
    level: 'A2',
    topic: 'technology',
    difficulty: 2,
    note: 'Only machines funktionieren. For a plan or an idea Germans say klappen. Verbs in -ieren take no ge-: hat funktioniert.',
    forms: {
      ich: 'funktioniere',
      du: 'funktionierst',
      er: 'funktioniert',
      wir: 'funktionieren',
      ihr: 'funktioniert',
      sie: 'funktionieren',
    },
    perfect: 'hat funktioniert',
  },
  {
    id: 'v.a2.l18.klappen',
    de: 'klappen',
    en: 'to work out, to go well',
    pos: 'verb',
    example: 'Hoffentlich klappt alles am Montag.',
    exampleEn: 'Hopefully everything will work out on Monday.',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    note: 'Almost always third person: Das klappt. / Es hat geklappt. Answering Klappt das bei dir? means "Does that work for you?"',
    forms: {
      ich: 'klappe',
      du: 'klappst',
      er: 'klappt',
      wir: 'klappen',
      ihr: 'klappt',
      sie: 'klappen',
    },
    perfect: 'hat geklappt',
  },
  {
    id: 'v.a2.l18.schiefgehen',
    de: 'schiefgehen',
    en: 'to go wrong',
    pos: 'verb',
    example: 'Bei der Lieferung ist leider etwas schiefgegangen.',
    exampleEn: 'Unfortunately something went wrong with the delivery.',
    level: 'A2',
    topic: 'services',
    difficulty: 3,
    separable: true,
    note: 'The exact opposite of klappen. It is a movement-style verb, so the Perfekt takes sein: Es ist schiefgegangen.',
    forms: {
      ich: 'gehe schief',
      du: 'gehst schief',
      er: 'geht schief',
      wir: 'gehen schief',
      ihr: 'geht schief',
      sie: 'gehen schief',
    },
    perfect: 'ist schiefgegangen',
  },

  /* ── Sorting it out in the shop ───────────────────────────────────────── */
  {
    id: 'v.a2.l18.quittung',
    de: 'Quittung',
    en: 'receipt',
    pos: 'noun',
    article: 'die',
    plural: 'die Quittungen',
    example: 'Ohne Quittung kann ich leider nichts umtauschen.',
    exampleEn: 'Without a receipt I unfortunately cannot exchange anything.',
    level: 'A2',
    topic: 'shopping',
    difficulty: 1,
    note: 'In a shop you also hear der Kassenbon or der Bon. Keep it: no Quittung, no Umtausch.',
  },
  {
    id: 'v.a2.l18.garantie',
    de: 'Garantie',
    en: 'guarantee, warranty',
    pos: 'noun',
    article: 'die',
    plural: 'die Garantien',
    example: 'Das Gerät hat noch ein Jahr Garantie.',
    exampleEn: 'The device still has a year of warranty.',
    level: 'A2',
    topic: 'shopping',
    difficulty: 2,
    note: 'Said without an article in the useful phrase: Ich habe noch Garantie. In Germany two years are the legal minimum.',
  },
  {
    id: 'v.a2.l18.umtauschen',
    de: 'umtauschen',
    en: 'to exchange (an item)',
    pos: 'verb',
    example: 'Kann ich die Hose noch umtauschen?',
    exampleEn: 'Can I still exchange the trousers?',
    level: 'A2',
    topic: 'shopping',
    difficulty: 2,
    separable: true,
    note: 'umtauschen = swap it for another item; zurückgeben = hand it back for your money. The noun is der Umtausch.',
    forms: {
      ich: 'tausche um',
      du: 'tauschst um',
      er: 'tauscht um',
      wir: 'tauschen um',
      ihr: 'tauscht um',
      sie: 'tauschen um',
    },
    perfect: 'hat umgetauscht',
  },
  {
    id: 'v.a2.l18.zurueckgeben',
    de: 'zurückgeben',
    en: 'to give back, to return',
    pos: 'verb',
    example: 'Ich möchte das Handy zurückgeben und mein Geld bekommen.',
    exampleEn: 'I would like to return the phone and get my money.',
    level: 'A2',
    topic: 'shopping',
    difficulty: 2,
    separable: true,
    note: 'zurück- is separable and stressed: Ich gebe es morgen zurück. The verb also changes its stem: du gibst zurück, er gibt zurück.',
    forms: {
      ich: 'gebe zurück',
      du: 'gibst zurück',
      er: 'gibt zurück',
      wir: 'geben zurück',
      ihr: 'gebt zurück',
      sie: 'geben zurück',
    },
    perfect: 'hat zurückgegeben',
  },
  {
    id: 'v.a2.l18.beschweren',
    de: 'sich beschweren',
    en: 'to complain',
    pos: 'verb',
    example: 'Der Kunde beschwert sich über den Service.',
    exampleEn: 'The customer is complaining about the service.',
    level: 'A2',
    topic: 'services',
    difficulty: 3,
    note: 'be- is inseparable, so the participle has no ge-: hat sich beschwert. What you complain about takes über + accusative.',
    forms: {
      ich: 'beschwere mich',
      du: 'beschwerst dich',
      er: 'beschwert sich',
      wir: 'beschweren uns',
      ihr: 'beschwert euch',
      sie: 'beschweren sich',
    },
    perfect: 'hat sich beschwert',
  },
  {
    id: 'v.a2.l18.entschuldigen',
    de: 'sich entschuldigen',
    en: 'to apologise',
    pos: 'verb',
    example: 'Der Verkäufer entschuldigt sich für den Fehler.',
    exampleEn: 'The shop assistant apologises for the mistake.',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    note: 'ent- is inseparable: hat sich entschuldigt, never "geentschuldigt". The reason follows with für + accusative.',
    forms: {
      ich: 'entschuldige mich',
      du: 'entschuldigst dich',
      er: 'entschuldigt sich',
      wir: 'entschuldigen uns',
      ihr: 'entschuldigt euch',
      sie: 'entschuldigen sich',
    },
    perfect: 'hat sich entschuldigt',
  },
]

export default vocab
