/**
 * A2 · L16 — Invitations and social life / Einladungen und Freizeit
 *
 * Sixteen words for the evening that has to be organised before it can happen:
 * the invitation itself (Einladung, einladen, Feier, Geburtstag, Geschenk,
 * zusagen, sich verabreden), the negotiating (Lust haben, Vorschlag) and the
 * places you end up in (Kneipe, Lokal, Runde) — plus the four words this
 * lesson's grammar lives on: langweilig, spannend, am liebsten, am besten.
 *
 * absagen, vorschlagen, treffen, lieber, teuer and gemütlich are already taught
 * in earlier lessons — they are reused here, not redefined.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── The invitation ───────────────────────────────────────────────────── */
  {
    id: 'v.a2.l16.einladung',
    de: 'Einladung',
    en: 'invitation',
    pos: 'noun',
    article: 'die',
    plural: 'die Einladungen',
    example: 'Vielen Dank für die Einladung zu deiner Feier!',
    exampleEn: 'Many thanks for the invitation to your party!',
    level: 'A2',
    topic: 'social',
    difficulty: 1,
    note: 'Fixed combinations: eine Einladung bekommen, eine Einladung annehmen, eine Einladung absagen.',
  },
  {
    id: 'v.a2.l16.einladen',
    de: 'einladen',
    en: 'to invite; to treat someone',
    pos: 'verb',
    example: 'Wir wollen auch die neuen Kollegen einladen.',
    exampleEn: 'We want to invite the new colleagues too.',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    separable: true,
    note: 'jemanden zu etwas einladen: Ich lade dich zum Essen ein. On its own, Ich lade dich ein also means "it is on me".',
    forms: {
      ich: 'lade ein',
      du: 'lädst ein',
      er: 'lädt ein',
      wir: 'laden ein',
      ihr: 'ladet ein',
      sie: 'laden ein',
    },
    perfect: 'hat eingeladen',
  },
  {
    id: 'v.a2.l16.feier',
    de: 'Feier',
    en: 'party, celebration',
    pos: 'noun',
    article: 'die',
    plural: 'die Feiern',
    example: 'Die Feier beginnt am Samstag um acht Uhr.',
    exampleEn: 'The party starts on Saturday at eight.',
    level: 'A2',
    topic: 'social',
    difficulty: 1,
    note: 'A Feier has a reason (Geburtstag, Hochzeit, Abschied); die Party is younger and more informal.',
  },
  {
    id: 'v.a2.l16.geburtstag',
    de: 'Geburtstag',
    en: 'birthday',
    pos: 'noun',
    article: 'der',
    plural: 'die Geburtstage',
    example: 'Meine Schwester hat am Freitag Geburtstag.',
    exampleEn: 'My sister has her birthday on Friday.',
    level: 'A2',
    topic: 'social',
    difficulty: 1,
    note: 'German uses haben, not sein: Ich habe am Montag Geburtstag. The greeting is Herzlichen Glückwunsch zum Geburtstag!',
  },
  {
    id: 'v.a2.l16.geschenk',
    de: 'Geschenk',
    en: 'present, gift',
    pos: 'noun',
    article: 'das',
    plural: 'die Geschenke',
    example: 'Wir suchen noch ein Geschenk für unseren Chef.',
    exampleEn: 'We are still looking for a present for our boss.',
    level: 'A2',
    topic: 'social',
    difficulty: 1,
    note: 'From schenken (to give as a present). Nouns that start with Ge- and name a thing are usually das.',
  },
  {
    id: 'v.a2.l16.zusagen',
    de: 'zusagen',
    en: 'to accept (an invitation), to say yes',
    pos: 'verb',
    example: 'Ich möchte gern zusagen, aber ich muss noch meine Frau fragen.',
    exampleEn: 'I would like to accept, but I still have to ask my wife.',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    separable: true,
    note: 'The opposite is absagen. Both are separable: Ich sage zu. / Ich sage leider ab.',
    forms: {
      ich: 'sage zu',
      du: 'sagst zu',
      er: 'sagt zu',
      wir: 'sagen zu',
      ihr: 'sagt zu',
      sie: 'sagen zu',
    },
    perfect: 'hat zugesagt',
  },
  {
    id: 'v.a2.l16.sich-verabreden',
    de: 'sich verabreden',
    en: 'to arrange to meet',
    pos: 'verb',
    example: 'Meine Kollegen verabreden sich jeden Freitag zum Mittagessen.',
    exampleEn: 'My colleagues arrange to meet for lunch every Friday.',
    level: 'A2',
    topic: 'social',
    difficulty: 3,
    note: 'sich mit jemandem verabreden — the other person comes with mit + Dativ: Ich verabrede mich mit Sara.',
    forms: {
      ich: 'verabrede mich',
      du: 'verabredest dich',
      er: 'verabredet sich',
      wir: 'verabreden uns',
      ihr: 'verabredet euch',
      sie: 'verabreden sich',
    },
    perfect: 'hat sich verabredet',
  },

  /* ── Negotiating the plan ─────────────────────────────────────────────── */
  {
    id: 'v.a2.l16.lust-haben',
    de: 'Lust haben',
    en: 'to feel like (doing something)',
    pos: 'phrase',
    example: 'Hast du heute Abend Lust auf ein Bier?',
    exampleEn: 'Do you feel like a beer this evening?',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    note: 'Lust auf + Akkusativ for a thing: Lust auf einen Film. Keine Lust haben is the normal way to say you cannot be bothered.',
  },
  {
    id: 'v.a2.l16.vorschlag',
    de: 'Vorschlag',
    en: 'suggestion, proposal',
    pos: 'noun',
    article: 'der',
    plural: 'die Vorschläge',
    example: 'Dein Vorschlag ist besser als meiner.',
    exampleEn: 'Your suggestion is better than mine.',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    note: 'einen Vorschlag machen = to make a suggestion. The verb behind it is vorschlagen.',
  },
  {
    id: 'v.a2.l16.am-besten',
    de: 'am besten',
    en: 'best; best of all',
    pos: 'adv',
    example: 'Am besten treffen wir uns direkt vor dem Kino.',
    exampleEn: 'It is best if we meet right in front of the cinema.',
    level: 'A2',
    topic: 'opinion',
    difficulty: 2,
    note: 'gut – besser – am besten. At the start of a sentence, am besten is a friendly, low-pressure way to suggest something.',
  },
  {
    id: 'v.a2.l16.am-liebsten',
    de: 'am liebsten',
    en: 'most of all, best of all (preference)',
    pos: 'adv',
    example: 'Am liebsten treffe ich meine Freunde in einer Kneipe.',
    exampleEn: 'Most of all I like meeting my friends in a pub.',
    level: 'A2',
    topic: 'opinion',
    difficulty: 2,
    note: 'gern – lieber – am liebsten. It says what you like doing best, not what is objectively best (that is am besten).',
  },

  /* ── Where you end up ─────────────────────────────────────────────────── */
  {
    id: 'v.a2.l16.kneipe',
    de: 'Kneipe',
    en: 'pub, bar',
    pos: 'noun',
    article: 'die',
    plural: 'die Kneipen',
    example: 'In der Kneipe an der Ecke ist es sehr gemütlich.',
    exampleEn: 'The pub on the corner is very cosy.',
    level: 'A2',
    topic: 'restaurant',
    difficulty: 2,
    note: 'A Kneipe is for drinking and talking. For a proper meal Germans say Restaurant or Lokal.',
  },
  {
    id: 'v.a2.l16.lokal',
    de: 'Lokal',
    en: 'restaurant, eating place',
    pos: 'noun',
    article: 'das',
    plural: 'die Lokale',
    example: 'Wir kennen ein gutes Lokal in der Nähe vom Bahnhof.',
    exampleEn: 'We know a good place to eat near the station.',
    level: 'A2',
    topic: 'restaurant',
    difficulty: 2,
    note: 'das Lokal is a small, usually simple restaurant — a place, never the English adjective "local".',
  },
  {
    id: 'v.a2.l16.runde',
    de: 'Runde',
    en: 'round (of drinks)',
    pos: 'noun',
    article: 'die',
    plural: 'die Runden',
    example: 'Diese Runde bezahle ich!',
    exampleEn: 'This round is on me!',
    level: 'A2',
    topic: 'restaurant',
    difficulty: 3,
    note: 'eine Runde ausgeben = to buy a round for everyone. noch eine Runde also simply means "one more".',
  },

  /* ── Saying what you thought of it ────────────────────────────────────── */
  {
    id: 'v.a2.l16.langweilig',
    de: 'langweilig',
    en: 'boring',
    pos: 'adj',
    example: 'Der Abend war leider ziemlich langweilig.',
    exampleEn: 'Unfortunately the evening was rather boring.',
    level: 'A2',
    topic: 'opinion',
    difficulty: 1,
    note: 'langweilig – langweiliger – am langweiligsten. Mir ist langweilig means "I am bored" — the person goes in the dative.',
  },
  {
    id: 'v.a2.l16.spannend',
    de: 'spannend',
    en: 'exciting, gripping',
    pos: 'adj',
    example: 'Das Konzert war spannender als der Film.',
    exampleEn: 'The concert was more exciting than the film.',
    level: 'A2',
    topic: 'opinion',
    difficulty: 2,
    note: 'spannend for films, books and stories. For an evening that made you nervous Germans say aufregend.',
  },
]

export default vocab
