/**
 * A2 · L17 — Telling stories about the past / Von früher erzählen
 *
 * The words a story needs: the four verbs that carry it (erzählen, passieren,
 * erleben, sich erinnern), the four things that go wrong or right (verlieren,
 * vergessen, treffen, umziehen, kennenlernen), the three nouns you hang it on
 * (das Erlebnis, die Erinnerung, die Geschichte) and the six little adverbs
 * that put the events in order (damals, früher, plötzlich, zuerst, danach,
 * schließlich).
 *
 * gestern, morgen and heute are already taught at A1 — reused here, not
 * redefined.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── Telling and remembering ──────────────────────────────────────────── */
  {
    id: 'v.a2.l17.erzaehlen',
    de: 'erzählen',
    en: 'to tell, to recount',
    pos: 'verb',
    example: 'Meine Oma erzählt gern Geschichten von früher.',
    exampleEn: 'My grandma likes telling stories from the old days.',
    level: 'A2',
    topic: 'social',
    difficulty: 1,
    forms: {
      ich: 'erzähle',
      du: 'erzählst',
      er: 'erzählt',
      wir: 'erzählen',
      ihr: 'erzählt',
      sie: 'erzählen',
    },
    perfect: 'hat erzählt',
    note: 'The listener goes in the dative: Ich erzähle dir alles. Inseparable er- means no ge- in the participle.',
  },
  {
    id: 'v.a2.l17.passieren',
    de: 'passieren',
    en: 'to happen',
    pos: 'verb',
    example: 'Gestern ist auf der Autobahn ein Unfall passiert.',
    exampleEn: 'There was an accident on the motorway yesterday.',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    forms: {
      ich: 'passiere',
      du: 'passierst',
      er: 'passiert',
      wir: 'passieren',
      ihr: 'passiert',
      sie: 'passieren',
    },
    perfect: 'ist passiert',
    note: 'Verbs in -ieren never take ge-, and passieren takes sein: Was ist passiert?',
  },
  {
    id: 'v.a2.l17.erleben',
    de: 'erleben',
    en: 'to experience, to go through',
    pos: 'verb',
    example: 'In Berlin haben wir ein schönes Wochenende erlebt.',
    exampleEn: 'We had a lovely weekend in Berlin.',
    level: 'A2',
    topic: 'travel',
    difficulty: 2,
    forms: {
      ich: 'erlebe',
      du: 'erlebst',
      er: 'erlebt',
      wir: 'erleben',
      ihr: 'erlebt',
      sie: 'erleben',
    },
    perfect: 'hat erlebt',
    note: 'leben = to live, erleben = to live through something. The prefix er- takes the ge- away.',
  },
  {
    id: 'v.a2.l17.sich-erinnern',
    de: 'sich erinnern',
    en: 'to remember',
    pos: 'verb',
    example: 'Mein Vater erinnert sich gern an seine Schulzeit.',
    exampleEn: 'My father likes remembering his school days.',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    forms: {
      ich: 'erinnere mich',
      du: 'erinnerst dich',
      er: 'erinnert sich',
      wir: 'erinnern uns',
      ihr: 'erinnert euch',
      sie: 'erinnern sich',
    },
    perfect: 'hat sich erinnert',
    note: 'Always with an + accusative: Ich erinnere mich an den Tag.',
  },

  /* ── What goes wrong, and what goes right ─────────────────────────────── */
  {
    id: 'v.a2.l17.verlieren',
    de: 'verlieren',
    en: 'to lose',
    pos: 'verb',
    example: 'Ich habe meinen Schlüssel im Zug verloren.',
    exampleEn: 'I lost my key on the train.',
    level: 'A2',
    topic: 'travel',
    difficulty: 1,
    forms: {
      ich: 'verliere',
      du: 'verlierst',
      er: 'verliert',
      wir: 'verlieren',
      ihr: 'verliert',
      sie: 'verlieren',
    },
    perfect: 'hat verloren',
    note: 'Strong verb with a new vowel, and ver- means no ge-: verloren.',
  },
  {
    id: 'v.a2.l17.vergessen',
    de: 'vergessen',
    en: 'to forget',
    pos: 'verb',
    example: 'Ich habe den Termin beim Zahnarzt leider vergessen.',
    exampleEn: 'Unfortunately I forgot the appointment at the dentist.',
    level: 'A2',
    topic: 'routine',
    difficulty: 2,
    forms: {
      ich: 'vergesse',
      du: 'vergisst',
      er: 'vergisst',
      wir: 'vergessen',
      ihr: 'vergesst',
      sie: 'vergessen',
    },
    perfect: 'hat vergessen',
    note: 'e → i in du and er/sie/es. The participle looks exactly like the infinitive: vergessen.',
  },
  {
    id: 'v.a2.l17.treffen',
    de: 'treffen',
    en: 'to meet, to run into',
    pos: 'verb',
    example: 'Wir treffen uns am Samstag im Café.',
    exampleEn: 'We are meeting at the café on Saturday.',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    forms: {
      ich: 'treffe',
      du: 'triffst',
      er: 'trifft',
      wir: 'treffen',
      ihr: 'trefft',
      sie: 'treffen',
    },
    perfect: 'hat getroffen',
    note: 'sich treffen = to meet up by arrangement; jemanden treffen = to bump into someone.',
  },
  {
    id: 'v.a2.l17.umziehen',
    de: 'umziehen',
    en: 'to move house',
    pos: 'verb',
    example: 'Nächsten Monat müssen wir nach Köln umziehen.',
    exampleEn: 'Next month we have to move to Cologne.',
    level: 'A2',
    topic: 'housing',
    difficulty: 2,
    forms: {
      ich: 'ziehe um',
      du: 'ziehst um',
      er: 'zieht um',
      wir: 'ziehen um',
      ihr: 'zieht um',
      sie: 'ziehen um',
    },
    perfect: 'ist umgezogen',
    separable: true,
    note: 'The ge- sits between prefix and stem: umgezogen. You change place, so the auxiliary is sein.',
  },
  {
    id: 'v.a2.l17.kennenlernen',
    de: 'kennenlernen',
    en: 'to get to know, to meet for the first time',
    pos: 'verb',
    example: 'Wo habt ihr euch eigentlich kennengelernt?',
    exampleEn: 'Where did you two actually meet?',
    level: 'A2',
    topic: 'relationships',
    difficulty: 2,
    forms: {
      ich: 'lerne kennen',
      du: 'lernst kennen',
      er: 'lernt kennen',
      wir: 'lernen kennen',
      ihr: 'lernt kennen',
      sie: 'lernen kennen',
    },
    perfect: 'hat kennengelernt',
    separable: true,
    note: 'One word in the infinitive and the participle, two words in the present: Ich lerne viele Leute kennen.',
  },

  /* ── The nouns of a story ─────────────────────────────────────────────── */
  {
    id: 'v.a2.l17.erlebnis',
    de: 'Erlebnis',
    en: 'experience, something you lived through',
    pos: 'noun',
    article: 'das',
    plural: 'die Erlebnisse',
    example: 'Die Reise nach Island war ein tolles Erlebnis.',
    exampleEn: 'The trip to Iceland was a great experience.',
    level: 'A2',
    topic: 'travel',
    difficulty: 2,
    note: 'Nouns in -nis are almost always das, and the plural doubles the s: die Erlebnisse.',
  },
  {
    id: 'v.a2.l17.erinnerung',
    de: 'Erinnerung',
    en: 'memory',
    pos: 'noun',
    article: 'die',
    plural: 'die Erinnerungen',
    example: 'An meine Schulzeit habe ich nur gute Erinnerungen.',
    exampleEn: 'I only have good memories of my school days.',
    level: 'A2',
    topic: 'social',
    difficulty: 2,
    note: 'Every noun in -ung is feminine and takes -en in the plural.',
  },
  {
    id: 'v.a2.l17.geschichte',
    de: 'Geschichte',
    en: 'story',
    pos: 'noun',
    article: 'die',
    plural: 'die Geschichten',
    example: 'Meine Kollegin hat mir eine lustige Geschichte erzählt.',
    exampleEn: 'My colleague told me a funny story.',
    level: 'A2',
    topic: 'social',
    difficulty: 1,
    note: 'die Geschichte means both "story" and "history" — the context decides.',
  },

  /* ── Putting the events in order ──────────────────────────────────────── */
  {
    id: 'v.a2.l17.damals',
    de: 'damals',
    en: 'back then, at that time',
    pos: 'adv',
    example: 'Damals hatte ich noch kein Auto.',
    exampleEn: 'Back then I did not have a car yet.',
    level: 'A2',
    topic: 'time',
    difficulty: 2,
    note: 'damals points far back into the past; dann points forward to the next step of the story.',
  },
  {
    id: 'v.a2.l17.frueher',
    de: 'früher',
    en: 'in the past, used to',
    pos: 'adv',
    example: 'Früher habe ich in Delhi gewohnt.',
    exampleEn: 'I used to live in Delhi.',
    level: 'A2',
    topic: 'time',
    difficulty: 1,
    note: 'German has no "used to" — früher plus the Perfekt does the whole job.',
  },
  {
    id: 'v.a2.l17.ploetzlich',
    de: 'plötzlich',
    en: 'suddenly',
    pos: 'adv',
    example: 'Plötzlich ist das Licht ausgegangen.',
    exampleEn: 'Suddenly the light went out.',
    level: 'A2',
    topic: 'time',
    difficulty: 2,
    note: 'The word that tells your listener the story is about to turn.',
  },
  {
    id: 'v.a2.l17.zuerst',
    de: 'zuerst',
    en: 'first, at first',
    pos: 'adv',
    example: 'Zuerst haben wir das Hotel gesucht.',
    exampleEn: 'First we looked for the hotel.',
    level: 'A2',
    topic: 'time',
    difficulty: 1,
    note: 'The story chain: zuerst – dann – danach – schließlich.',
  },
  {
    id: 'v.a2.l17.danach',
    de: 'danach',
    en: 'after that, afterwards',
    pos: 'adv',
    example: 'Wir haben gegessen und danach einen Film gesehen.',
    exampleEn: 'We ate and after that we watched a film.',
    level: 'A2',
    topic: 'time',
    difficulty: 1,
    note: 'danach = nach + that. It needs no noun after it, unlike nach dem Essen.',
  },
  {
    id: 'v.a2.l17.schliesslich',
    de: 'schließlich',
    en: 'finally, in the end',
    pos: 'adv',
    example: 'Schließlich haben wir den Schlüssel im Auto gefunden.',
    exampleEn: 'In the end we found the key in the car.',
    level: 'A2',
    topic: 'time',
    difficulty: 3,
    note: 'schließlich closes a story. endlich is different — it carries relief after a long wait.',
  },
]

export default vocab
