/**
 * A2 · L11 — Travel and booking / Reisen und buchen
 *
 * The words you need to book a room, read a confirmation and tell someone
 * about a trip you have already made. Every verb carries its Perfekt, because
 * this lesson talks about the journey in the past.
 *
 * Words already taught earlier (Bahnhof, Zug, Zimmer, ankommen, umsteigen,
 * Fahrkarte) are reused, not redefined.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── The trip ─────────────────────────────────────────────────────────── */
  {
    id: 'v.a2.l11.reise',
    de: 'Reise',
    en: 'journey, trip',
    pos: 'noun',
    article: 'die',
    plural: 'die Reisen',
    example: 'Die Reise nach Wien hat nur vier Stunden gedauert.',
    exampleEn: 'The journey to Vienna only took four hours.',
    level: 'A2',
    topic: 'travel',
    difficulty: 1,
    note: 'Gute Reise! is what you say to someone who is leaving.',
  },
  {
    id: 'v.a2.l11.urlaub',
    de: 'Urlaub',
    en: 'holiday, vacation (time off work)',
    pos: 'noun',
    article: 'der',
    plural: 'die Urlaube',
    example: 'Im Sommer machen wir drei Wochen Urlaub in Italien.',
    exampleEn: 'In summer we take three weeks of holiday in Italy.',
    level: 'A2',
    topic: 'travel',
    difficulty: 1,
    note: 'Urlaub machen = to go on holiday. The plural is rare — Germans say Urlaub for the whole period.',
  },
  {
    id: 'v.a2.l11.hotel',
    de: 'Hotel',
    en: 'hotel',
    pos: 'noun',
    article: 'das',
    plural: 'die Hotels',
    example: 'Das Hotel liegt direkt am Bahnhof.',
    exampleEn: 'The hotel is right next to the station.',
    level: 'A2',
    topic: 'travel',
    difficulty: 1,
  },
  {
    id: 'v.a2.l11.unterkunft',
    de: 'Unterkunft',
    en: 'accommodation, place to stay',
    pos: 'noun',
    article: 'die',
    plural: 'die Unterkünfte',
    example: 'Wir suchen eine günstige Unterkunft in der Stadt.',
    exampleEn: 'We are looking for cheap accommodation in the city.',
    level: 'A2',
    topic: 'travel',
    difficulty: 2,
    note: 'The umbrella word: a hotel, a guest house or a flat are all Unterkünfte.',
  },
  {
    id: 'v.a2.l11.aufenthalt',
    de: 'Aufenthalt',
    en: 'stay',
    pos: 'noun',
    article: 'der',
    plural: 'die Aufenthalte',
    example: 'Der Aufenthalt in Hamburg hat uns sehr gefallen.',
    exampleEn: 'We really enjoyed the stay in Hamburg.',
    level: 'A2',
    topic: 'travel',
    difficulty: 2,
    note: 'On a timetable Aufenthalt also means the waiting time between two trains.',
  },

  /* ── Booking ──────────────────────────────────────────────────────────── */
  {
    id: 'v.a2.l11.buchen',
    de: 'buchen',
    en: 'to book',
    pos: 'verb',
    example: 'Ich habe den Flug schon online gebucht.',
    exampleEn: 'I have already booked the flight online.',
    level: 'A2',
    topic: 'travel',
    difficulty: 1,
    perfect: 'hat gebucht',
    forms: {
      ich: 'buche',
      du: 'buchst',
      er: 'bucht',
      wir: 'buchen',
      ihr: 'bucht',
      sie: 'buchen',
    },
  },
  {
    id: 'v.a2.l11.reservieren',
    de: 'reservieren',
    en: 'to reserve',
    pos: 'verb',
    example: 'Ich möchte ein Doppelzimmer für zwei Nächte reservieren.',
    exampleEn: 'I would like to reserve a double room for two nights.',
    level: 'A2',
    topic: 'travel',
    difficulty: 2,
    perfect: 'hat reserviert',
    note: 'Verbs in -ieren take no ge- in the Perfekt: reserviert, not gereserviert.',
    forms: {
      ich: 'reserviere',
      du: 'reservierst',
      er: 'reserviert',
      wir: 'reservieren',
      ihr: 'reserviert',
      sie: 'reservieren',
    },
  },
  {
    id: 'v.a2.l11.buchung',
    de: 'Buchung',
    en: 'booking, reservation',
    pos: 'noun',
    article: 'die',
    plural: 'die Buchungen',
    example: 'Ich habe die Buchung per E-Mail bekommen.',
    exampleEn: 'I received the booking by email.',
    level: 'A2',
    topic: 'travel',
    difficulty: 2,
    note: 'Every noun ending in -ung is feminine: die Buchung, die Übernachtung, die Rechnung.',
  },
  {
    id: 'v.a2.l11.einzelzimmer',
    de: 'Einzelzimmer',
    en: 'single room',
    pos: 'noun',
    article: 'das',
    plural: 'die Einzelzimmer',
    example: 'Ein Einzelzimmer kostet 79 Euro pro Nacht.',
    exampleEn: 'A single room costs 79 euros per night.',
    level: 'A2',
    topic: 'travel',
    difficulty: 1,
    note: 'A compound takes the gender of its last part: das Zimmer → das Einzelzimmer.',
  },
  {
    id: 'v.a2.l11.doppelzimmer',
    de: 'Doppelzimmer',
    en: 'double room',
    pos: 'noun',
    article: 'das',
    plural: 'die Doppelzimmer',
    example: 'Wir haben ein Doppelzimmer mit Balkon bekommen.',
    exampleEn: 'We got a double room with a balcony.',
    level: 'A2',
    topic: 'travel',
    difficulty: 1,
  },
  {
    id: 'v.a2.l11.uebernachtung',
    de: 'Übernachtung',
    en: 'overnight stay, night (in a hotel)',
    pos: 'noun',
    article: 'die',
    plural: 'die Übernachtungen',
    example: 'Die Übernachtung mit Frühstück kostet 95 Euro.',
    exampleEn: 'The overnight stay including breakfast costs 95 euros.',
    level: 'A2',
    topic: 'travel',
    difficulty: 2,
    note: 'Hotels count in Übernachtungen; the verb is übernachten (hat übernachtet).',
  },

  /* ── Getting there and back ───────────────────────────────────────────── */
  {
    id: 'v.a2.l11.flug',
    de: 'Flug',
    en: 'flight',
    pos: 'noun',
    article: 'der',
    plural: 'die Flüge',
    example: 'Der Flug nach Berlin dauert eine Stunde.',
    exampleEn: 'The flight to Berlin takes one hour.',
    level: 'A2',
    topic: 'travel',
    difficulty: 1,
  },
  {
    id: 'v.a2.l11.rueckfahrt',
    de: 'Rückfahrt',
    en: 'return journey (by road or rail)',
    pos: 'noun',
    article: 'die',
    plural: 'die Rückfahrten',
    example: 'Die Rückfahrt ist am Sonntagabend.',
    exampleEn: 'The return journey is on Sunday evening.',
    level: 'A2',
    topic: 'travel',
    difficulty: 2,
    note: 'By plane it is der Rückflug; Hin- und Rückfahrt = return ticket.',
  },
  {
    id: 'v.a2.l11.abfahren',
    de: 'abfahren',
    en: 'to depart, to set off',
    pos: 'verb',
    example: 'Wir müssen morgen früh abfahren.',
    exampleEn: 'We have to set off early tomorrow.',
    level: 'A2',
    topic: 'travel',
    difficulty: 2,
    separable: true,
    perfect: 'ist abgefahren',
    note: 'Separable, so the ge- slips inside in the Perfekt: abgefahren. On timetables ab = departure.',
    forms: {
      ich: 'fahre ab',
      du: 'fährst ab',
      er: 'fährt ab',
      wir: 'fahren ab',
      ihr: 'fahrt ab',
      sie: 'fahren ab',
    },
  },
  {
    id: 'v.a2.l11.koffer',
    de: 'Koffer',
    en: 'suitcase',
    pos: 'noun',
    article: 'der',
    plural: 'die Koffer',
    example: 'Mein Koffer ist leider sehr schwer.',
    exampleEn: 'Unfortunately my suitcase is very heavy.',
    level: 'A2',
    topic: 'travel',
    difficulty: 1,
    note: 'The -er ending already is the plural: der Koffer → die Koffer.',
  },
  {
    id: 'v.a2.l11.packen',
    de: 'packen',
    en: 'to pack',
    pos: 'verb',
    example: 'Am Abend vor der Reise packe ich meinen Koffer.',
    exampleEn: 'The evening before the trip I pack my suitcase.',
    level: 'A2',
    topic: 'travel',
    difficulty: 1,
    perfect: 'hat gepackt',
    forms: {
      ich: 'packe',
      du: 'packst',
      er: 'packt',
      wir: 'packen',
      ihr: 'packt',
      sie: 'packen',
    },
  },
  {
    id: 'v.a2.l11.sich-freuen-auf',
    de: 'sich freuen auf',
    en: 'to look forward to',
    pos: 'verb',
    example: 'Meine Kinder freuen sich schon auf die Reise.',
    exampleEn: 'My children are already looking forward to the trip.',
    level: 'A2',
    topic: 'travel',
    difficulty: 3,
    perfect: 'hat sich gefreut',
    note: 'auf + Akkusativ, and the reflexive pronoun changes with the person: ich freue mich, du freust dich.',
    forms: {
      ich: 'freue mich',
      du: 'freust dich',
      er: 'freut sich',
      wir: 'freuen uns',
      ihr: 'freut euch',
      sie: 'freuen sich',
    },
  },
]

export default vocab
