/**
 * A2 · L12 — Appointments and the doctor / Termine und beim Arzt
 *
 * Everything you need at a German Hausarztpraxis: the words on the door
 * (Sprechstunde, Praxis), the words at the desk (Versichertenkarte,
 * Beschwerden), the words in the room (untersuchen, wehtun, sich fühlen) and
 * the two pieces of paper you leave with (das Rezept, die Krankmeldung).
 *
 * "Termin" is already taught in A1 L03 (v.a1.l03.termin) and is reused here,
 * not redefined.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── At the practice ──────────────────────────────────────────────────── */
  {
    id: 'v.a2.l12.praxis',
    de: 'Praxis',
    en: 'medical practice, surgery',
    pos: 'noun',
    article: 'die',
    plural: 'die Praxen',
    example: 'Die Praxis ist am Mittwochnachmittag geschlossen.',
    exampleEn: 'The practice is closed on Wednesday afternoon.',
    level: 'A2',
    topic: 'health',
    difficulty: 2,
    note: 'Irregular plural: die Praxis → die Praxen. A family doctor works in einer Hausarztpraxis.',
  },
  {
    id: 'v.a2.l12.sprechstunde',
    de: 'Sprechstunde',
    en: 'consultation hours, surgery hours',
    pos: 'noun',
    article: 'die',
    plural: 'die Sprechstunden',
    example: 'Die Sprechstunde ist heute nur von acht bis zwölf Uhr.',
    exampleEn: 'Consultation hours today are only from eight to twelve.',
    level: 'A2',
    topic: 'health',
    difficulty: 2,
    note: 'Literally "speaking hour" — the times you may come without a long wait. The sign says: Sprechstunde nach Vereinbarung.',
  },
  {
    id: 'v.a2.l12.versichertenkarte',
    de: 'Versichertenkarte',
    en: 'health insurance card',
    pos: 'noun',
    article: 'die',
    plural: 'die Versichertenkarten',
    example: 'Bitte geben Sie mir Ihre Versichertenkarte.',
    exampleEn: 'Please give me your health insurance card.',
    level: 'A2',
    topic: 'services',
    difficulty: 3,
    note: 'Take it to every appointment — without it the practice normally asks you to pay yourself.',
  },
  {
    id: 'v.a2.l12.beschwerde',
    de: 'Beschwerde',
    en: 'complaint, symptom',
    pos: 'noun',
    article: 'die',
    plural: 'die Beschwerden',
    example: 'Welche Beschwerden haben Sie denn?',
    exampleEn: 'What symptoms do you have, then?',
    level: 'A2',
    topic: 'health',
    difficulty: 3,
    note: 'At the doctor it is almost always plural: die Beschwerden. In an office, eine Beschwerde is a complaint.',
  },
  {
    id: 'v.a2.l12.schmerz',
    de: 'Schmerz',
    en: 'pain',
    pos: 'noun',
    article: 'der',
    plural: 'die Schmerzen',
    example: 'Ich habe seit gestern starke Schmerzen im Rücken.',
    exampleEn: 'I have had bad back pain since yesterday.',
    level: 'A2',
    topic: 'health',
    difficulty: 2,
    note: 'Used in the plural in real life: Ich habe Schmerzen. Glue it onto a body part: Halsschmerzen, Kopfschmerzen, Bauchschmerzen.',
  },
  {
    id: 'v.a2.l12.husten',
    de: 'Husten',
    en: 'cough',
    pos: 'noun',
    article: 'der',
    plural: null,
    example: 'Ich habe seit einer Woche Husten.',
    exampleEn: 'I have had a cough for a week.',
    level: 'A2',
    topic: 'health',
    difficulty: 1,
    note: 'No plural and no article in the sentence: Ich habe Husten, not "einen Husten".',
  },
  {
    id: 'v.a2.l12.fieber',
    de: 'Fieber',
    en: 'fever, temperature',
    pos: 'noun',
    article: 'das',
    plural: null,
    example: 'Mein Sohn hat Fieber und muss im Bett bleiben.',
    exampleEn: 'My son has a fever and has to stay in bed.',
    level: 'A2',
    topic: 'health',
    difficulty: 1,
    note: 'Germans give it in degrees: Ich habe achtunddreißig Grad Fieber.',
  },
  {
    id: 'v.a2.l12.erkaeltung',
    de: 'Erkältung',
    en: 'cold (illness)',
    pos: 'noun',
    article: 'die',
    plural: 'die Erkältungen',
    example: 'Das ist nur eine leichte Erkältung.',
    exampleEn: 'That is only a slight cold.',
    level: 'A2',
    topic: 'health',
    difficulty: 2,
    note: 'The verb is reflexive: Ich habe mich erkältet — I have caught a cold.',
  },
  {
    id: 'v.a2.l12.rezept',
    de: 'Rezept',
    en: 'prescription',
    pos: 'noun',
    article: 'das',
    plural: 'die Rezepte',
    example: 'Der Arzt schreibt mir ein Rezept für die Apotheke.',
    exampleEn: 'The doctor is writing me a prescription for the pharmacy.',
    level: 'A2',
    topic: 'health',
    difficulty: 2,
    note: 'The same word also means a cooking recipe — the context decides.',
  },
  {
    id: 'v.a2.l12.apotheke',
    de: 'Apotheke',
    en: 'pharmacy, chemist',
    pos: 'noun',
    article: 'die',
    plural: 'die Apotheken',
    example: 'Die Apotheke am Bahnhof hat bis acht Uhr geöffnet.',
    exampleEn: 'The pharmacy at the station is open until eight.',
    level: 'A2',
    topic: 'services',
    difficulty: 1,
    note: 'Not a drugstore: a Drogerie sells shampoo, an Apotheke sells medicine.',
  },
  {
    id: 'v.a2.l12.tablette',
    de: 'Tablette',
    en: 'tablet, pill',
    pos: 'noun',
    article: 'die',
    plural: 'die Tabletten',
    example: 'Nehmen Sie bitte dreimal am Tag eine Tablette.',
    exampleEn: 'Please take one tablet three times a day.',
    level: 'A2',
    topic: 'health',
    difficulty: 1,
    note: 'The verb is nehmen, not essen or trinken: Tabletten nehmen.',
  },
  {
    id: 'v.a2.l12.krankmeldung',
    de: 'Krankmeldung',
    en: 'sick note, doctor’s certificate',
    pos: 'noun',
    article: 'die',
    plural: 'die Krankmeldungen',
    example: 'Ich muss die Krankmeldung noch an meinen Chef schicken.',
    exampleEn: 'I still have to send the sick note to my boss.',
    level: 'A2',
    topic: 'work',
    difficulty: 3,
    note: 'The paper you get from the practice. Many employers want it from day three of an illness.',
  },

  /* ── Verbs ────────────────────────────────────────────────────────────── */
  {
    id: 'v.a2.l12.sich-fuehlen',
    de: 'sich fühlen',
    en: 'to feel (a way)',
    pos: 'verb',
    example: 'Meine Tochter fühlt sich seit gestern nicht wohl.',
    exampleEn: 'My daughter has not been feeling well since yesterday.',
    level: 'A2',
    topic: 'health',
    difficulty: 2,
    note: 'Always with the pronoun: Wie fühlen Sie sich? — the first question every doctor asks.',
    forms: {
      ich: 'fühle mich',
      du: 'fühlst dich',
      er: 'fühlt sich',
      wir: 'fühlen uns',
      ihr: 'fühlt euch',
      sie: 'fühlen sich',
    },
    perfect: 'hat sich gefühlt',
  },
  {
    id: 'v.a2.l12.wehtun',
    de: 'wehtun',
    en: 'to hurt',
    pos: 'verb',
    example: 'Wenn mir der Hals wehtut, trinke ich warmen Tee.',
    exampleEn: 'When my throat hurts, I drink warm tea.',
    level: 'A2',
    topic: 'health',
    difficulty: 3,
    separable: true,
    note: 'The person goes in the dative: Mir tut der Kopf weh. The body part is the subject.',
    forms: {
      ich: 'tue weh',
      du: 'tust weh',
      er: 'tut weh',
      wir: 'tun weh',
      ihr: 'tut weh',
      sie: 'tun weh',
    },
    perfect: 'hat wehgetan',
  },
  {
    id: 'v.a2.l12.untersuchen',
    de: 'untersuchen',
    en: 'to examine',
    pos: 'verb',
    example: 'Der Arzt untersucht mich gleich.',
    exampleEn: 'The doctor is going to examine me in a moment.',
    level: 'A2',
    topic: 'health',
    difficulty: 2,
    note: 'unter- here is inseparable, so it never splits and the participle takes no ge-: untersucht.',
    forms: {
      ich: 'untersuche',
      du: 'untersuchst',
      er: 'untersucht',
      wir: 'untersuchen',
      ihr: 'untersucht',
      sie: 'untersuchen',
    },
    perfect: 'hat untersucht',
  },
  {
    id: 'v.a2.l12.krankschreiben',
    de: 'krankschreiben',
    en: 'to sign someone off sick',
    pos: 'verb',
    example: 'Der Arzt hat mich für drei Tage krankgeschrieben.',
    exampleEn: 'The doctor signed me off sick for three days.',
    level: 'A2',
    topic: 'work',
    difficulty: 3,
    separable: true,
    note: 'Separable: Der Arzt schreibt mich krank. The paper itself is die Krankmeldung.',
    forms: {
      ich: 'schreibe krank',
      du: 'schreibst krank',
      er: 'schreibt krank',
      wir: 'schreiben krank',
      ihr: 'schreibt krank',
      sie: 'schreiben krank',
    },
    perfect: 'hat krankgeschrieben',
  },
  {
    id: 'v.a2.l12.verschieben',
    de: 'verschieben',
    en: 'to postpone, to move (a date)',
    pos: 'verb',
    example: 'Können wir den Termin auf Donnerstag verschieben?',
    exampleEn: 'Can we move the appointment to Thursday?',
    level: 'A2',
    topic: 'time',
    difficulty: 2,
    note: 'verschieben auf + accusative: auf Freitag, auf nächste Woche. ver- is inseparable.',
    forms: {
      ich: 'verschiebe',
      du: 'verschiebst',
      er: 'verschiebt',
      wir: 'verschieben',
      ihr: 'verschiebt',
      sie: 'verschieben',
    },
    perfect: 'hat verschoben',
  },

  /* ── Adjective ────────────────────────────────────────────────────────── */
  {
    id: 'v.a2.l12.dringend',
    de: 'dringend',
    en: 'urgent, urgently',
    pos: 'adj',
    example: 'Ich brauche dringend einen Termin.',
    exampleEn: 'I urgently need an appointment.',
    level: 'A2',
    topic: 'health',
    difficulty: 2,
    note: 'Works as an adjective and as an adverb: ein dringender Fall, but also Ich muss dringend zum Arzt.',
  },
]

export default vocab
