/**
 * A2 · L15 — Banking, offices and phone calls / Bank, Amt und Telefon
 *
 * Three rooms full of German bureaucracy in eighteen words: the bank counter
 * (Konto, Überweisung, EC-Karte, Kontoauszug, abheben, überweisen), the
 * Bürgeramt (Formular, Antrag, Ausweis, Anmeldung, Wartenummer, ausfüllen,
 * unterschreiben) and the telephone (Kundenservice, in der Leitung,
 * weiterverbinden, zurückrufen).
 *
 * Geld, Rechnung, Termin, Vertrag and sich melden are already taught earlier —
 * they are reused here, not redefined.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── At the bank ──────────────────────────────────────────────────────── */
  {
    id: 'v.a2.l15.konto',
    de: 'Konto',
    en: 'bank account',
    pos: 'noun',
    article: 'das',
    plural: 'die Konten',
    example: 'Das Geld ist seit Montag auf meinem Konto.',
    exampleEn: 'The money has been in my account since Monday.',
    level: 'A2',
    topic: 'money',
    difficulty: 1,
    note: 'The plural is die Konten, not "die Kontos". A current account is das Girokonto.',
  },
  {
    id: 'v.a2.l15.ueberweisung',
    de: 'Überweisung',
    en: 'bank transfer',
    pos: 'noun',
    article: 'die',
    plural: 'die Überweisungen',
    example: 'Die Überweisung dauert meistens einen Werktag.',
    exampleEn: 'The transfer usually takes one working day.',
    level: 'A2',
    topic: 'money',
    difficulty: 2,
    note: 'Every noun ending in -ung is feminine — die Überweisung, die Anmeldung, die Rechnung.',
  },
  {
    id: 'v.a2.l15.ec-karte',
    de: 'EC-Karte',
    en: 'debit card',
    pos: 'noun',
    article: 'die',
    plural: 'die EC-Karten',
    example: 'Kann ich hier mit der EC-Karte bezahlen?',
    exampleEn: 'Can I pay by debit card here?',
    level: 'A2',
    topic: 'money',
    difficulty: 1,
    note: 'The everyday German card. Officially it is now die Girocard, but everybody still says EC-Karte.',
  },
  {
    id: 'v.a2.l15.kontoauszug',
    de: 'Kontoauszug',
    en: 'bank statement',
    pos: 'noun',
    article: 'der',
    plural: 'die Kontoauszüge',
    example: 'Meine Kontoauszüge hole ich am Automaten in der Filiale.',
    exampleEn: 'I get my bank statements from the machine in the branch.',
    level: 'A2',
    topic: 'money',
    difficulty: 2,
    note: 'From das Konto + der Auszug. A compound noun always takes the gender of its last part.',
  },
  {
    id: 'v.a2.l15.abheben',
    de: 'abheben',
    en: 'to withdraw (cash)',
    pos: 'verb',
    example: 'Am Automaten kann man rund um die Uhr Geld abheben.',
    exampleEn: 'You can withdraw cash at the machine around the clock.',
    level: 'A2',
    topic: 'money',
    difficulty: 2,
    separable: true,
    perfect: 'hat abgehoben',
    note: 'Separable: Ich hebe hundert Euro ab. The opposite is einzahlen — to pay cash in.',
    forms: {
      ich: 'hebe ab',
      du: 'hebst ab',
      er: 'hebt ab',
      wir: 'heben ab',
      ihr: 'hebt ab',
      sie: 'heben ab',
    },
  },
  {
    id: 'v.a2.l15.ueberweisen',
    de: 'überweisen',
    en: 'to transfer (money)',
    pos: 'verb',
    example: 'Ich überweise die Miete immer am Ersten.',
    exampleEn: 'I always transfer the rent on the first of the month.',
    level: 'A2',
    topic: 'money',
    difficulty: 2,
    perfect: 'hat überwiesen',
    note: 'NOT separable: the prefix über- stays on the verb, and the Perfekt has no ge-: überwiesen.',
    forms: {
      ich: 'überweise',
      du: 'überweist',
      er: 'überweist',
      wir: 'überweisen',
      ihr: 'überweist',
      sie: 'überweisen',
    },
  },

  /* ── At the Bürgeramt ─────────────────────────────────────────────────── */
  {
    id: 'v.a2.l15.formular',
    de: 'Formular',
    en: 'form',
    pos: 'noun',
    article: 'das',
    plural: 'die Formulare',
    example: 'Das Formular finden Sie auch im Internet.',
    exampleEn: 'You can also find the form on the internet.',
    level: 'A2',
    topic: 'services',
    difficulty: 1,
    note: 'Nouns ending in -ar from Latin are usually neuter: das Formular, das Exemplar.',
  },
  {
    id: 'v.a2.l15.antrag',
    de: 'Antrag',
    en: 'application (to an office)',
    pos: 'noun',
    article: 'der',
    plural: 'die Anträge',
    example: 'Ich stelle den Antrag noch diese Woche.',
    exampleEn: 'I will put in the application this week.',
    level: 'A2',
    topic: 'services',
    difficulty: 2,
    note: 'The fixed phrase is einen Antrag stellen — you "put" an application, you do not "make" it.',
  },
  {
    id: 'v.a2.l15.ausweis',
    de: 'Ausweis',
    en: 'ID card',
    pos: 'noun',
    article: 'der',
    plural: 'die Ausweise',
    example: 'Bitte zeigen Sie mir Ihren Ausweis.',
    exampleEn: 'Please show me your ID card.',
    level: 'A2',
    topic: 'services',
    difficulty: 1,
    note: 'In full: der Personalausweis. A passport is der Reisepass.',
  },
  {
    id: 'v.a2.l15.anmeldung',
    de: 'Anmeldung',
    en: 'registration',
    pos: 'noun',
    article: 'die',
    plural: 'die Anmeldungen',
    example: 'Die Anmeldung dauert nur zehn Minuten.',
    exampleEn: 'The registration only takes ten minutes.',
    level: 'A2',
    topic: 'services',
    difficulty: 2,
    note: 'In Germany you must register your address within two weeks of moving in.',
  },
  {
    id: 'v.a2.l15.buergeramt',
    de: 'Bürgeramt',
    en: 'citizens’ registration office',
    pos: 'noun',
    article: 'das',
    plural: 'die Bürgerämter',
    example: 'Das Bürgeramt hat mittwochs bis achtzehn Uhr geöffnet.',
    exampleEn: 'The registration office is open until six p.m. on Wednesdays.',
    level: 'A2',
    topic: 'services',
    difficulty: 2,
    note: 'Every noun in -amt is neuter and takes an umlaut in the plural: das Amt, die Ämter.',
  },
  {
    id: 'v.a2.l15.wartenummer',
    de: 'Wartenummer',
    en: 'queue number, ticket number',
    pos: 'noun',
    article: 'die',
    plural: 'die Wartenummern',
    example: 'Ziehen Sie am Eingang bitte eine Wartenummer.',
    exampleEn: 'Please take a queue number at the entrance.',
    level: 'A2',
    topic: 'services',
    difficulty: 2,
    note: 'You hear eine Nummer ziehen everywhere in German offices — the machine prints it for you.',
  },
  {
    id: 'v.a2.l15.ausfuellen',
    de: 'ausfüllen',
    en: 'to fill in, to complete (a form)',
    pos: 'verb',
    example: 'Sie müssen das Formular vorher zu Hause ausfüllen.',
    exampleEn: 'You have to fill in the form at home beforehand.',
    level: 'A2',
    topic: 'services',
    difficulty: 1,
    separable: true,
    perfect: 'hat ausgefüllt',
    note: 'Separable: Ich fülle das Formular aus. Only paper gets ausgefüllt — a glass gets gefüllt.',
    forms: {
      ich: 'fülle aus',
      du: 'füllst aus',
      er: 'füllt aus',
      wir: 'füllen aus',
      ihr: 'füllt aus',
      sie: 'füllen aus',
    },
  },
  {
    id: 'v.a2.l15.unterschreiben',
    de: 'unterschreiben',
    en: 'to sign',
    pos: 'verb',
    example: 'Bitte unterschreiben Sie hier unten rechts.',
    exampleEn: 'Please sign here at the bottom right.',
    level: 'A2',
    topic: 'services',
    difficulty: 2,
    perfect: 'hat unterschrieben',
    note: 'NOT separable, so no ge- in the Perfekt: Ich habe den Vertrag unterschrieben. The noun is die Unterschrift.',
    forms: {
      ich: 'unterschreibe',
      du: 'unterschreibst',
      er: 'unterschreibt',
      wir: 'unterschreiben',
      ihr: 'unterschreibt',
      sie: 'unterschreiben',
    },
  },

  /* ── On the phone ─────────────────────────────────────────────────────── */
  {
    id: 'v.a2.l15.kundenservice',
    de: 'Kundenservice',
    en: 'customer service',
    pos: 'noun',
    article: 'der',
    plural: null,
    example: 'Der Kundenservice ist von acht bis achtzehn Uhr da.',
    exampleEn: 'Customer service is there from eight until six.',
    level: 'A2',
    topic: 'services',
    difficulty: 2,
    note: 'Used only in the singular. The people are die Mitarbeiter im Kundenservice.',
  },
  {
    id: 'v.a2.l15.in-der-leitung',
    de: 'in der Leitung',
    en: 'on the line (telephone)',
    pos: 'phrase',
    example: 'Bleiben Sie bitte kurz in der Leitung.',
    exampleEn: 'Please stay on the line for a moment.',
    level: 'A2',
    topic: 'services',
    difficulty: 2,
    note: 'die Leitung is the phone line. Germans never say "in der Linie".',
  },
  {
    id: 'v.a2.l15.weiterverbinden',
    de: 'weiterverbinden',
    en: 'to put through, to transfer (a call)',
    pos: 'verb',
    example: 'Einen Moment, ich verbinde Sie weiter.',
    exampleEn: 'One moment, I will put you through.',
    level: 'A2',
    topic: 'services',
    difficulty: 3,
    separable: true,
    perfect: 'hat weiterverbunden',
    note: 'Separable: Ich verbinde Sie weiter. On its own, verbinden mit means to connect someone with somebody.',
    forms: {
      ich: 'verbinde weiter',
      du: 'verbindest weiter',
      er: 'verbindet weiter',
      wir: 'verbinden weiter',
      ihr: 'verbindet weiter',
      sie: 'verbinden weiter',
    },
  },
  {
    id: 'v.a2.l15.zurueckrufen',
    de: 'zurückrufen',
    en: 'to call back',
    pos: 'verb',
    example: 'Rufen Sie mich bitte morgen Vormittag zurück.',
    exampleEn: 'Please call me back tomorrow morning.',
    level: 'A2',
    topic: 'services',
    difficulty: 2,
    separable: true,
    perfect: 'hat zurückgerufen',
    note: 'Separable, and the ge- goes in the middle: zurückgerufen. The noun is der Rückruf.',
    forms: {
      ich: 'rufe zurück',
      du: 'rufst zurück',
      er: 'ruft zurück',
      wir: 'rufen zurück',
      ihr: 'ruft zurück',
      sie: 'rufen zurück',
    },
  },
]

export default vocab
