/**
 * A2 · L14 — Housing and renting / Wohnen und mieten
 *
 * The words you actually need to read a German flat advert and survive a
 * viewing: the people (Vermieter, Mieter, Hausmeister), the paperwork
 * (Mietvertrag, Kaution, Nebenkosten, Warmmiete), the building (Stock,
 * Aufzug, Heizung) and the four verbs of a tenancy (einziehen, ausziehen,
 * kündigen, reparieren).
 *
 * Wohnung, Miete, Zimmer, Küche, Bad and Schrank are already taught at A1 —
 * they are reused here, not redefined.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── The people ───────────────────────────────────────────────────────── */
  {
    id: 'v.a2.l14.vermieter',
    de: 'Vermieter',
    en: 'landlord',
    pos: 'noun',
    article: 'der',
    plural: 'die Vermieter',
    example: 'Der Vermieter wohnt selbst im Haus.',
    exampleEn: 'The landlord lives in the building himself.',
    level: 'A2',
    topic: 'housing',
    difficulty: 1,
    note: 'Female: die Vermieterin. From vermieten = to let out.',
  },
  {
    id: 'v.a2.l14.mieter',
    de: 'Mieter',
    en: 'tenant',
    pos: 'noun',
    article: 'der',
    plural: 'die Mieter',
    example: 'Der Mieter zahlt die Miete immer pünktlich.',
    exampleEn: 'The tenant always pays the rent on time.',
    level: 'A2',
    topic: 'housing',
    difficulty: 1,
    note: 'Female: die Mieterin. Nouns in -er for people never change in the plural.',
  },
  {
    id: 'v.a2.l14.hausmeister',
    de: 'Hausmeister',
    en: 'caretaker, building manager',
    pos: 'noun',
    article: 'der',
    plural: 'die Hausmeister',
    example: 'Der Hausmeister hat einen Schlüssel für den Keller.',
    exampleEn: 'The caretaker has a key for the cellar.',
    level: 'A2',
    topic: 'housing',
    difficulty: 2,
    note: 'The person you call first when something in the building breaks.',
  },

  /* ── The paperwork and the money ──────────────────────────────────────── */
  {
    id: 'v.a2.l14.mietvertrag',
    de: 'Mietvertrag',
    en: 'rental contract, lease',
    pos: 'noun',
    article: 'der',
    plural: 'die Mietverträge',
    example: 'Ich habe den Mietvertrag gestern unterschrieben.',
    exampleEn: 'I signed the rental contract yesterday.',
    level: 'A2',
    topic: 'housing',
    difficulty: 2,
    note: 'A compound takes the gender of its last part: der Vertrag → der Mietvertrag.',
  },
  {
    id: 'v.a2.l14.kaution',
    de: 'Kaution',
    en: 'deposit',
    pos: 'noun',
    article: 'die',
    plural: 'die Kautionen',
    example: 'Ich muss eine Kaution von 1380 Euro zahlen.',
    exampleEn: 'I have to pay a deposit of 1380 euros.',
    level: 'A2',
    topic: 'housing',
    difficulty: 2,
    note: 'You get it back when you move out — if there is no damage.',
  },
  {
    id: 'v.a2.l14.nebenkosten',
    de: 'Nebenkosten',
    en: 'extra costs, service charges',
    pos: 'noun',
    article: 'die',
    plural: 'die Nebenkosten',
    example: 'Die Nebenkosten betragen 180 Euro im Monat.',
    exampleEn: 'The service charges come to 180 euros a month.',
    level: 'A2',
    topic: 'housing',
    difficulty: 2,
    note: 'Plural only — there is no "die Nebenkost". Usually heating, water, rubbish and the caretaker.',
  },
  {
    id: 'v.a2.l14.warmmiete',
    de: 'Warmmiete',
    en: 'rent including bills',
    pos: 'noun',
    article: 'die',
    plural: 'die Warmmieten',
    example: 'Die Warmmiete liegt bei 870 Euro.',
    exampleEn: 'The rent including bills is around 870 euros.',
    level: 'A2',
    topic: 'housing',
    difficulty: 3,
    note: 'Warmmiete = Kaltmiete + Nebenkosten. Adverts often show only the Kaltmiete.',
  },

  /* ── The flat and the building ────────────────────────────────────────── */
  {
    id: 'v.a2.l14.quadratmeter',
    de: 'Quadratmeter',
    en: 'square metre',
    pos: 'noun',
    article: 'der',
    plural: 'die Quadratmeter',
    example: 'Die Wohnung hat 78 Quadratmeter.',
    exampleEn: 'The flat has 78 square metres.',
    level: 'A2',
    topic: 'housing',
    difficulty: 2,
    note: 'Written m² in adverts. After a number it stays singular: 78 Quadratmeter.',
  },
  {
    id: 'v.a2.l14.stock',
    de: 'Stock',
    en: 'floor, storey',
    pos: 'noun',
    article: 'der',
    plural: 'die Stockwerke',
    example: 'Wir wohnen im dritten Stock.',
    exampleEn: 'We live on the third floor.',
    level: 'A2',
    topic: 'housing',
    difficulty: 2,
    note: 'Irregular plural: die Stockwerke. Ground floor is das Erdgeschoss, so the first Stock is one up.',
  },
  {
    id: 'v.a2.l14.aufzug',
    de: 'Aufzug',
    en: 'lift, elevator',
    pos: 'noun',
    article: 'der',
    plural: 'die Aufzüge',
    example: 'Im Haus gibt es zum Glück einen Aufzug.',
    exampleEn: 'Luckily there is a lift in the building.',
    level: 'A2',
    topic: 'housing',
    difficulty: 1,
    note: 'Also der Fahrstuhl — the two words are interchangeable.',
  },
  {
    id: 'v.a2.l14.heizung',
    de: 'Heizung',
    en: 'heating, radiator',
    pos: 'noun',
    article: 'die',
    plural: 'die Heizungen',
    example: 'Die Heizung im Wohnzimmer ist seit gestern kalt.',
    exampleEn: 'The heating in the living room has been cold since yesterday.',
    level: 'A2',
    topic: 'housing',
    difficulty: 1,
    note: 'Nouns ending in -ung are always feminine.',
  },
  {
    id: 'v.a2.l14.besichtigung',
    de: 'Besichtigung',
    en: 'viewing',
    pos: 'noun',
    article: 'die',
    plural: 'die Besichtigungen',
    example: 'Die Besichtigung ist am Donnerstag um 17 Uhr.',
    exampleEn: 'The viewing is on Thursday at 5 p.m.',
    level: 'A2',
    topic: 'housing',
    difficulty: 2,
    note: 'From besichtigen = to view. Again -ung, so again feminine.',
  },
  {
    id: 'v.a2.l14.schaden',
    de: 'Schaden',
    en: 'damage, fault',
    pos: 'noun',
    article: 'der',
    plural: 'die Schäden',
    example: 'Bitte melden Sie den Schaden sofort dem Hausmeister.',
    exampleEn: 'Please report the damage to the caretaker immediately.',
    level: 'A2',
    topic: 'housing',
    difficulty: 2,
    note: 'Plural adds an Umlaut: der Schaden → die Schäden.',
  },
  {
    id: 'v.a2.l14.moebliert',
    de: 'möbliert',
    en: 'furnished',
    pos: 'adj',
    example: 'Die Wohnung ist nicht möbliert.',
    exampleEn: 'The flat is not furnished.',
    level: 'A2',
    topic: 'housing',
    difficulty: 2,
    note: 'From die Möbel = furniture. Adverts write möbl. or teilmöbliert (partly furnished).',
  },

  /* ── The verbs of a tenancy ───────────────────────────────────────────── */
  {
    id: 'v.a2.l14.einziehen',
    de: 'einziehen',
    en: 'to move in',
    pos: 'verb',
    example: 'Wir möchten schon im Mai in die Wohnung einziehen.',
    exampleEn: 'We would like to move into the flat as early as May.',
    level: 'A2',
    topic: 'housing',
    difficulty: 2,
    separable: true,
    perfect: 'ist eingezogen',
    note: 'Movement, so the preposition takes the accusative: Ich ziehe in die Wohnung ein.',
    forms: {
      ich: 'ziehe ein',
      du: 'ziehst ein',
      er: 'zieht ein',
      wir: 'ziehen ein',
      ihr: 'zieht ein',
      sie: 'ziehen ein',
    },
  },
  {
    id: 'v.a2.l14.ausziehen',
    de: 'ausziehen',
    en: 'to move out',
    pos: 'verb',
    example: 'Die Familie muss Ende Juni aus der Wohnung ausziehen.',
    exampleEn: 'The family has to move out of the flat at the end of June.',
    level: 'A2',
    topic: 'housing',
    difficulty: 2,
    separable: true,
    perfect: 'ist ausgezogen',
    note: 'With a person it means to undress: Ich ziehe die Jacke aus. Context tells you which.',
    forms: {
      ich: 'ziehe aus',
      du: 'ziehst aus',
      er: 'zieht aus',
      wir: 'ziehen aus',
      ihr: 'zieht aus',
      sie: 'ziehen aus',
    },
  },
  {
    id: 'v.a2.l14.kuendigen',
    de: 'kündigen',
    en: 'to give notice, to terminate',
    pos: 'verb',
    example: 'Ich muss den Mietvertrag drei Monate vorher kündigen.',
    exampleEn: 'I have to give three months notice on the rental contract.',
    level: 'A2',
    topic: 'housing',
    difficulty: 3,
    perfect: 'hat gekündigt',
    note: 'Used for flats and for jobs: Ich habe meine Stelle gekündigt.',
    forms: {
      ich: 'kündige',
      du: 'kündigst',
      er: 'kündigt',
      wir: 'kündigen',
      ihr: 'kündigt',
      sie: 'kündigen',
    },
  },
  {
    id: 'v.a2.l14.reparieren',
    de: 'reparieren',
    en: 'to repair, to fix',
    pos: 'verb',
    example: 'Der Hausmeister kann die Heizung morgen reparieren.',
    exampleEn: 'The caretaker can repair the heating tomorrow.',
    level: 'A2',
    topic: 'housing',
    difficulty: 1,
    perfect: 'hat repariert',
    note: 'Verbs in -ieren build the Perfekt without ge-: repariert, not gerepariert.',
    forms: {
      ich: 'repariere',
      du: 'reparierst',
      er: 'repariert',
      wir: 'reparieren',
      ihr: 'repariert',
      sie: 'reparieren',
    },
  },
]

export default vocab
