/**
 * A2 · L13 — Work and the office / Arbeit und Büro
 *
 * The words you need to survive a German working day: who sits in which
 * department, what a Besprechung and a Frist are, and the four verbs that carry
 * almost every office message — sich melden, Bescheid sagen, erledigen,
 * sich kümmern um.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── People and places ────────────────────────────────────────────────── */
  {
    id: 'v.a2.l13.kollege',
    de: 'Kollege',
    en: 'colleague (male)',
    pos: 'noun',
    article: 'der',
    plural: 'die Kollegen',
    example: 'Mein Kollege kümmert sich heute um die Kunden.',
    exampleEn: 'My colleague is taking care of the customers today.',
    level: 'A2',
    topic: 'work',
    difficulty: 1,
    note: 'A weak noun: in every case except the nominative singular it becomes Kollegen — mit dem Kollegen, für den Kollegen.',
  },
  {
    id: 'v.a2.l13.kollegin',
    de: 'Kollegin',
    en: 'colleague (female)',
    pos: 'noun',
    article: 'die',
    plural: 'die Kolleginnen',
    example: 'Meine neue Kollegin arbeitet in der Abteilung Einkauf.',
    exampleEn: 'My new colleague works in the purchasing department.',
    level: 'A2',
    topic: 'work',
    difficulty: 1,
    note: 'The ending -in makes the female form, and every -in noun doubles the n in the plural: Kolleginnen.',
  },
  {
    id: 'v.a2.l13.abteilung',
    de: 'Abteilung',
    en: 'department',
    pos: 'noun',
    article: 'die',
    plural: 'die Abteilungen',
    example: 'In unserer Abteilung arbeiten zwölf Leute.',
    exampleEn: 'Twelve people work in our department.',
    level: 'A2',
    topic: 'work',
    difficulty: 2,
    note: 'Nouns ending in -ung are always feminine and always take -en in the plural.',
  },
  {
    id: 'v.a2.l13.besprechung',
    de: 'Besprechung',
    en: 'meeting',
    pos: 'noun',
    article: 'die',
    plural: 'die Besprechungen',
    example: 'Die Besprechung dauert heute nur eine halbe Stunde.',
    exampleEn: 'The meeting only lasts half an hour today.',
    level: 'A2',
    topic: 'work',
    difficulty: 2,
    note: 'Also common: das Meeting. Besprechung is the word you will see in German calendars.',
  },
  {
    id: 'v.a2.l13.homeoffice',
    de: 'Homeoffice',
    en: 'working from home',
    pos: 'noun',
    article: 'das',
    plural: null,
    example: 'Am Montag arbeite ich im Homeoffice.',
    exampleEn: 'On Monday I work from home.',
    level: 'A2',
    topic: 'work',
    difficulty: 1,
    note: 'Used almost only in the fixed phrase im Homeoffice — a plural is not normally used.',
  },

  /* ── Work, tasks and time ─────────────────────────────────────────────── */
  {
    id: 'v.a2.l13.aufgabe',
    de: 'Aufgabe',
    en: 'task',
    pos: 'noun',
    article: 'die',
    plural: 'die Aufgaben',
    example: 'Diese Aufgabe muss ich bis Freitag erledigen.',
    exampleEn: 'I have to finish this task by Friday.',
    level: 'A2',
    topic: 'work',
    difficulty: 1,
  },
  {
    id: 'v.a2.l13.auftrag',
    de: 'Auftrag',
    en: 'order, job (from a customer)',
    pos: 'noun',
    article: 'der',
    plural: 'die Aufträge',
    example: 'Wir haben heute einen großen Auftrag bekommen.',
    exampleEn: 'We received a big order today.',
    level: 'A2',
    topic: 'work',
    difficulty: 2,
    note: 'An Auftrag comes from a customer; an Aufgabe is any piece of work you have to do.',
  },
  {
    id: 'v.a2.l13.frist',
    de: 'Frist',
    en: 'deadline',
    pos: 'noun',
    article: 'die',
    plural: 'die Fristen',
    example: 'Die Frist für den Bericht ist am Freitag.',
    exampleEn: 'The deadline for the report is on Friday.',
    level: 'A2',
    topic: 'work',
    difficulty: 2,
    note: 'eine Frist einhalten = to meet a deadline; eine Frist verschieben = to move it.',
  },
  {
    id: 'v.a2.l13.feierabend',
    de: 'Feierabend',
    en: 'end of the working day',
    pos: 'noun',
    article: 'der',
    plural: 'die Feierabende',
    example: 'Um fünf Uhr habe ich endlich Feierabend.',
    exampleEn: 'At five I finally finish work.',
    level: 'A2',
    topic: 'work',
    difficulty: 2,
    note: 'Germans say Feierabend haben / machen — there is no article in that phrase.',
  },
  {
    id: 'v.a2.l13.ueberstunden',
    de: 'Überstunden',
    en: 'overtime',
    pos: 'noun',
    article: 'die',
    plural: 'die Überstunden',
    example: 'Diese Woche habe ich schon zehn Überstunden gemacht.',
    exampleEn: 'This week I have already done ten hours of overtime.',
    level: 'A2',
    topic: 'work',
    difficulty: 3,
    note: 'Plural only — you count them: zwei Überstunden, zehn Überstunden.',
  },

  /* ── Paperwork ────────────────────────────────────────────────────────── */
  {
    id: 'v.a2.l13.vertrag',
    de: 'Vertrag',
    en: 'contract',
    pos: 'noun',
    article: 'der',
    plural: 'die Verträge',
    example: 'Mein Vertrag läuft noch zwei Jahre.',
    exampleEn: 'My contract still runs for two years.',
    level: 'A2',
    topic: 'work',
    difficulty: 2,
  },
  {
    id: 'v.a2.l13.gehalt',
    de: 'Gehalt',
    en: 'salary',
    pos: 'noun',
    article: 'das',
    plural: 'die Gehälter',
    example: 'Das Gehalt kommt bei uns immer am Monatsende.',
    exampleEn: 'Our salary always arrives at the end of the month.',
    level: 'A2',
    topic: 'money',
    difficulty: 2,
    note: 'das Gehalt is monthly office pay; der Lohn is usually paid by the hour.',
  },
  {
    id: 'v.a2.l13.urlaubsantrag',
    de: 'Urlaubsantrag',
    en: 'holiday request (form)',
    pos: 'noun',
    article: 'der',
    plural: 'die Urlaubsanträge',
    example: 'Ich gebe den Urlaubsantrag morgen bei meiner Chefin ab.',
    exampleEn: 'I will hand in the holiday request to my boss tomorrow.',
    level: 'A2',
    topic: 'work',
    difficulty: 3,
    note: 'A compound takes the gender of its last part: der Antrag → der Urlaubsantrag.',
  },

  /* ── The four office verbs ────────────────────────────────────────────── */
  {
    id: 'v.a2.l13.sich-melden',
    de: 'sich melden',
    en: 'to get in touch',
    pos: 'verb',
    example: 'Bitte melden Sie sich, wenn Sie Fragen haben.',
    exampleEn: 'Please get in touch if you have any questions.',
    level: 'A2',
    topic: 'work',
    difficulty: 2,
    note: 'sich melden bei + Dative: Ich melde mich bei der Kundin.',
    forms: {
      ich: 'melde mich',
      du: 'meldest dich',
      er: 'meldet sich',
      wir: 'melden uns',
      ihr: 'meldet euch',
      sie: 'melden sich',
    },
    perfect: 'hat sich gemeldet',
  },
  {
    id: 'v.a2.l13.erledigen',
    de: 'erledigen',
    en: 'to get done, to deal with',
    pos: 'verb',
    example: 'Ich erledige die Aufgabe noch vor dem Feierabend.',
    exampleEn: 'I will get the task done before the end of the day.',
    level: 'A2',
    topic: 'work',
    difficulty: 2,
    note: 'Verbs starting with er- never take ge- in the Perfekt: hat erledigt.',
    forms: {
      ich: 'erledige',
      du: 'erledigst',
      er: 'erledigt',
      wir: 'erledigen',
      ihr: 'erledigt',
      sie: 'erledigen',
    },
    perfect: 'hat erledigt',
  },
  {
    id: 'v.a2.l13.sich-kuemmern',
    de: 'sich kümmern um',
    en: 'to take care of',
    pos: 'verb',
    example: 'Meine Kollegin kümmert sich um die neuen Aufträge.',
    exampleEn: 'My colleague is taking care of the new orders.',
    level: 'A2',
    topic: 'work',
    difficulty: 3,
    note: 'Always reflexive and always with um + Accusative: Ich kümmere mich um den Vertrag.',
    forms: {
      ich: 'kümmere mich',
      du: 'kümmerst dich',
      er: 'kümmert sich',
      wir: 'kümmern uns',
      ihr: 'kümmert euch',
      sie: 'kümmern sich',
    },
    perfect: 'hat sich gekümmert',
  },
  {
    id: 'v.a2.l13.bescheid-sagen',
    de: 'Bescheid sagen',
    en: 'to let someone know',
    pos: 'phrase',
    example: 'Sag mir bitte Bescheid, wenn du die Zahlen hast.',
    exampleEn: 'Please let me know when you have the figures.',
    level: 'A2',
    topic: 'work',
    difficulty: 2,
    note: 'The person you tell stands in the Dative: Ich sage dir Bescheid. Bescheid is always capitalised.',
  },
  {
    id: 'v.a2.l13.zustaendig',
    de: 'zuständig',
    en: 'responsible, in charge',
    pos: 'adj',
    example: 'Für die Rechnungen ist meine Kollegin zuständig.',
    exampleEn: 'My colleague is responsible for the invoices.',
    level: 'A2',
    topic: 'work',
    difficulty: 3,
    note: 'Fixed pattern: zuständig sein für + Accusative. Wer ist dafür zuständig?',
  },
]

export default vocab
