/**
 * B1 · L21 — Opinions and discussion / Meinungen und Diskussionen
 *
 * The words of an argument: what you hold (die Meinung, der Grund, das
 * Argument), how you weigh it (der Vorteil, der Nachteil, der Kompromiss),
 * what you do with other people's views (zustimmen, widersprechen,
 * überzeugen, behaupten) and the small words that make an opinion sound
 * measured instead of blunt (eigentlich, allerdings, außerdem,
 * wahrscheinlich).
 *
 * finden, glauben, denken and der Vorschlag are earlier words and are reused
 * here, not redefined.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── What you hold ────────────────────────────────────────────────────── */
  {
    id: 'v.b1.l21.meinung',
    de: 'Meinung',
    en: 'opinion',
    pos: 'noun',
    article: 'die',
    plural: 'die Meinungen',
    example: 'Meiner Meinung nach ist das eine gute Idee.',
    exampleEn: 'In my opinion that is a good idea.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 1,
    note: 'Two fixed frames: Meiner Meinung nach … (verb comes next!) and Ich bin der Meinung, dass … Disagreeing: Ich bin anderer Meinung.',
  },
  {
    id: 'v.b1.l21.grund',
    de: 'Grund',
    en: 'reason; ground',
    pos: 'noun',
    article: 'der',
    plural: 'die Gründe',
    example: 'Aus diesem Grund haben wir uns anders entschieden.',
    exampleEn: 'For this reason we decided differently.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 1,
    note: 'aus diesem Grund = for this reason. The plural takes an Umlaut: die Gründe. A reason FOR something: der Grund für …',
  },
  {
    id: 'v.b1.l21.argument',
    de: 'Argument',
    en: 'argument (a point in favour or against)',
    pos: 'noun',
    article: 'das',
    plural: 'die Argumente',
    example: 'Das ist ein gutes Argument, aber ich sehe das anders.',
    exampleEn: 'That is a good argument, but I see it differently.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 1,
    note: 'An argument as a POINT. A quarrel between people is der Streit, never das Argument.',
  },
  {
    id: 'v.b1.l21.vorteil',
    de: 'Vorteil',
    en: 'advantage',
    pos: 'noun',
    article: 'der',
    plural: 'die Vorteile',
    example: 'Ein großer Vorteil ist, dass man flexibel arbeiten kann.',
    exampleEn: 'A big advantage is that you can work flexibly.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 1,
    note: 'Vor + Teil, and der Teil is masculine. Vor- und Nachteile = pros and cons.',
  },
  {
    id: 'v.b1.l21.nachteil',
    de: 'Nachteil',
    en: 'disadvantage',
    pos: 'noun',
    article: 'der',
    plural: 'die Nachteile',
    example: 'Der Nachteil ist, dass die Wohnungen dort sehr teuer sind.',
    exampleEn: 'The disadvantage is that the flats there are very expensive.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 1,
    note: 'Der Vorteil / Nachteil ist, dass … is the easiest way to start weighing an idea.',
  },
  {
    id: 'v.b1.l21.kompromiss',
    de: 'Kompromiss',
    en: 'compromise',
    pos: 'noun',
    article: 'der',
    plural: 'die Kompromisse',
    example: 'Nach einer langen Diskussion haben wir einen Kompromiss gefunden.',
    exampleEn: 'After a long discussion we found a compromise.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 1,
    note: 'einen Kompromiss finden / schließen. Germans pride themselves on it — der Kompromiss is a word with a good reputation.',
  },
  {
    id: 'v.b1.l21.diskussion',
    de: 'Diskussion',
    en: 'discussion',
    pos: 'noun',
    article: 'die',
    plural: 'die Diskussionen',
    example: 'Die Diskussion über das Thema war sehr spannend.',
    exampleEn: 'The discussion about the topic was very exciting.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 1,
    note: 'Every noun in -ion is feminine: die Diskussion, die Information, die Situation. The verb is diskutieren über + accusative.',
  },

  /* ── What you do with other views ─────────────────────────────────────── */
  {
    id: 'v.b1.l21.meinen',
    de: 'meinen',
    en: 'to think, to be of the opinion; to mean',
    pos: 'verb',
    example: 'Was meinen Sie dazu?',
    exampleEn: 'What do you think about it?',
    level: 'B1',
    topic: 'opinion',
    difficulty: 1,
    note: 'Two jobs: an opinion (Ich meine, dass …) and a meaning (Wie meinen Sie das? — What do you mean by that?).',
    forms: {
      ich: 'meine',
      du: 'meinst',
      er: 'meint',
      wir: 'meinen',
      ihr: 'meint',
      sie: 'meinen',
    },
    perfect: 'hat gemeint',
    praeteritum: 'meinte',
  },
  {
    id: 'v.b1.l21.zustimmen',
    de: 'zustimmen',
    en: 'to agree (with someone)',
    pos: 'verb',
    example: 'Da kann ich dir nur zustimmen.',
    exampleEn: 'I can only agree with you there.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 2,
    separable: true,
    note: 'Takes the dative: Ich stimme dir / Ihnen zu. Separable, so zu goes to the end of the sentence.',
    forms: {
      ich: 'stimme zu',
      du: 'stimmst zu',
      er: 'stimmt zu',
      wir: 'stimmen zu',
      ihr: 'stimmt zu',
      sie: 'stimmen zu',
    },
    perfect: 'hat zugestimmt',
    praeteritum: 'stimmte zu',
  },
  {
    id: 'v.b1.l21.widersprechen',
    de: 'widersprechen',
    en: 'to contradict, to disagree with',
    pos: 'verb',
    example: 'Ich muss dir leider widersprechen.',
    exampleEn: 'I am afraid I have to disagree with you.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 2,
    note: 'Dative, like zustimmen. wider- is inseparable here, and sprechen changes e to i: du widersprichst, er widerspricht.',
    forms: {
      ich: 'widerspreche',
      du: 'widersprichst',
      er: 'widerspricht',
      wir: 'widersprechen',
      ihr: 'widersprecht',
      sie: 'widersprechen',
    },
    perfect: 'hat widersprochen',
    praeteritum: 'widersprach',
  },
  {
    id: 'v.b1.l21.ueberzeugen',
    de: 'überzeugen',
    en: 'to convince',
    pos: 'verb',
    example: 'Das Argument hat mich überzeugt.',
    exampleEn: 'The argument convinced me.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 2,
    note: 'über- is inseparable here — no ge-: hat überzeugt. Ich bin davon überzeugt, dass … = I am convinced that …',
    forms: {
      ich: 'überzeuge',
      du: 'überzeugst',
      er: 'überzeugt',
      wir: 'überzeugen',
      ihr: 'überzeugt',
      sie: 'überzeugen',
    },
    perfect: 'hat überzeugt',
    praeteritum: 'überzeugte',
  },
  {
    id: 'v.b1.l21.behaupten',
    de: 'behaupten',
    en: 'to claim, to maintain',
    pos: 'verb',
    example: 'Er behauptet, dass er nichts davon wusste.',
    exampleEn: 'He claims that he knew nothing about it.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 2,
    note: 'Often a little sceptical: behaupten suggests you are not sure it is true. The noun is die Behauptung.',
    forms: {
      ich: 'behaupte',
      du: 'behauptest',
      er: 'behauptet',
      wir: 'behaupten',
      ihr: 'behauptet',
      sie: 'behaupten',
    },
    perfect: 'hat behauptet',
    praeteritum: 'behauptete',
  },
  {
    id: 'v.b1.l21.vorstellen',
    de: 'sich vorstellen',
    en: 'to imagine (sich etwas vorstellen)',
    pos: 'verb',
    example: 'Sie kann sich gut vorstellen, in Berlin zu wohnen.',
    exampleEn: 'She can easily imagine living in Berlin.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 3,
    separable: true,
    note: 'For "imagine" the reflexive is DATIVE: ich stelle mir vor, du stellst dir vor. With an accusative (ich stelle mich vor) it means "I introduce myself".',
    forms: {
      ich: 'stelle mir vor',
      du: 'stellst dir vor',
      er: 'stellt sich vor',
      wir: 'stellen uns vor',
      ihr: 'stellt euch vor',
      sie: 'stellen sich vor',
    },
    perfect: 'hat sich vorgestellt',
    praeteritum: 'stellte sich vor',
  },
  {
    id: 'v.b1.l21.vermuten',
    de: 'vermuten',
    en: 'to suppose, to suspect',
    pos: 'verb',
    example: 'Ich vermute, dass der Zug Verspätung hat.',
    exampleEn: 'I suppose the train is delayed.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 2,
    note: 'A guess, not knowledge. The noun is die Vermutung. ver- is inseparable: hat vermutet.',
    forms: {
      ich: 'vermute',
      du: 'vermutest',
      er: 'vermutet',
      wir: 'vermuten',
      ihr: 'vermutet',
      sie: 'vermuten',
    },
    perfect: 'hat vermutet',
    praeteritum: 'vermutete',
  },

  /* ── Small words that measure an opinion ──────────────────────────────── */
  {
    id: 'v.b1.l21.wahrscheinlich',
    de: 'wahrscheinlich',
    en: 'probably',
    pos: 'adv',
    example: 'Wahrscheinlich hat sie den Termin vergessen.',
    exampleEn: 'She has probably forgotten the appointment.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 1,
    note: 'Stronger than vielleicht (maybe), weaker than sicher (certainly).',
  },
  {
    id: 'v.b1.l21.eigentlich',
    de: 'eigentlich',
    en: 'actually; really, in fact',
    pos: 'adv',
    example: 'Eigentlich habe ich keine Zeit, aber ich komme trotzdem.',
    exampleEn: 'Actually I do not have time, but I will come anyway.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 2,
    note: 'Softens a statement or flags a contrast with reality. In a question it signals real interest: Wie geht es dir eigentlich?',
  },
  {
    id: 'v.b1.l21.allerdings',
    de: 'allerdings',
    en: 'however, though',
    pos: 'adv',
    example: 'Die Idee ist gut, allerdings ist sie sehr teuer.',
    exampleEn: 'The idea is good; however, it is very expensive.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 2,
    note: 'An adverb like trotzdem: in position 1 the verb comes straight after it (allerdings ist sie …). A polite "but".',
  },
  {
    id: 'v.b1.l21.ausserdem',
    de: 'außerdem',
    en: 'besides, in addition',
    pos: 'adv',
    example: 'Die Wohnung ist zu klein. Außerdem ist sie zu teuer.',
    exampleEn: 'The flat is too small. Besides, it is too expensive.',
    level: 'B1',
    topic: 'opinion',
    difficulty: 1,
    note: 'Adds another argument in the same direction. As an adverb in position 1 it is followed by the verb.',
  },
]

export default vocab
