/**
 * B1 · L22 — Technology, media and news / Technik, Medien und Nachrichten
 *
 * Two halves of modern life in one list: the media you read and watch
 * (die Zeitung, die Zeitschrift, der Artikel, die Sendung, die Werbung,
 * berichten, veröffentlichen, aktuell) and the technology you use every day
 * (der Bildschirm, das Passwort, herunterladen, speichern, löschen,
 * entwickeln, erfinden, digital).
 *
 * The verbs are chosen for the passive step — things that are done to
 * texts, files and apps: es wird berichtet, die Datei wird gespeichert, die
 * App wurde entwickelt. die Nachricht (L20) is reused, not redefined.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── Media ────────────────────────────────────────────────────────────── */
  {
    id: 'v.b1.l22.zeitung',
    de: 'Zeitung',
    en: 'newspaper',
    pos: 'noun',
    article: 'die',
    plural: 'die Zeitungen',
    example: 'Ich lese die Zeitung morgens beim Frühstück.',
    exampleEn: 'I read the newspaper in the morning over breakfast.',
    level: 'B1',
    topic: 'media',
    difficulty: 1,
    note: 'in der Zeitung stehen = to be in the paper: Das stand gestern in der Zeitung.',
  },
  {
    id: 'v.b1.l22.zeitschrift',
    de: 'Zeitschrift',
    en: 'magazine',
    pos: 'noun',
    article: 'die',
    plural: 'die Zeitschriften',
    example: 'Im Wartezimmer liegen viele Zeitschriften.',
    exampleEn: 'There are lots of magazines in the waiting room.',
    level: 'B1',
    topic: 'media',
    difficulty: 1,
    note: 'A daily paper is eine Zeitung, a weekly or monthly glossy is eine Zeitschrift (or ein Magazin).',
  },
  {
    id: 'v.b1.l22.artikel',
    de: 'Artikel',
    en: 'article (in a newspaper); article (grammar)',
    pos: 'noun',
    article: 'der',
    plural: 'die Artikel',
    example: 'Hast du den Artikel über das neue Stadion gelesen?',
    exampleEn: 'Have you read the article about the new stadium?',
    level: 'B1',
    topic: 'media',
    difficulty: 1,
    note: 'Same word for der/die/das in grammar. Like many -el nouns, the plural looks the same: die Artikel.',
  },
  {
    id: 'v.b1.l22.sendung',
    de: 'Sendung',
    en: 'programme, broadcast; parcel',
    pos: 'noun',
    article: 'die',
    plural: 'die Sendungen',
    example: 'Die Sendung läuft jeden Sonntag um acht.',
    exampleEn: 'The programme is on every Sunday at eight.',
    level: 'B1',
    topic: 'media',
    difficulty: 2,
    note: 'From senden, to broadcast or send — so die Sendung is also a parcel in the post. A programme läuft (is on).',
  },
  {
    id: 'v.b1.l22.werbung',
    de: 'Werbung',
    en: 'advertising, adverts',
    pos: 'noun',
    article: 'die',
    plural: null,
    example: 'Im Internet sieht man überall Werbung.',
    exampleEn: 'You see advertising everywhere on the internet.',
    level: 'B1',
    topic: 'media',
    difficulty: 1,
    note: 'Usually uncountable. A single TV advert is ein Werbespot. Werbung machen für = to advertise something.',
  },
  {
    id: 'v.b1.l22.berichten',
    de: 'berichten',
    en: 'to report',
    pos: 'verb',
    example: 'Alle Zeitungen berichten über den Streik.',
    exampleEn: 'All the newspapers are reporting on the strike.',
    level: 'B1',
    topic: 'media',
    difficulty: 2,
    note: 'über + accusative or von + dative. The noun is der Bericht. In the news you hear it in the passive: Es wird berichtet, dass …',
    forms: {
      ich: 'berichte',
      du: 'berichtest',
      er: 'berichtet',
      wir: 'berichten',
      ihr: 'berichtet',
      sie: 'berichten',
    },
    perfect: 'hat berichtet',
    praeteritum: 'berichtete',
  },
  {
    id: 'v.b1.l22.veroeffentlichen',
    de: 'veröffentlichen',
    en: 'to publish',
    pos: 'verb',
    example: 'Die Ergebnisse werden morgen veröffentlicht.',
    exampleEn: 'The results will be published tomorrow.',
    level: 'B1',
    topic: 'media',
    difficulty: 3,
    note: 'Literally "make public" (öffentlich). ver- is inseparable — no ge-: hat veröffentlicht.',
    forms: {
      ich: 'veröffentliche',
      du: 'veröffentlichst',
      er: 'veröffentlicht',
      wir: 'veröffentlichen',
      ihr: 'veröffentlicht',
      sie: 'veröffentlichen',
    },
    perfect: 'hat veröffentlicht',
    praeteritum: 'veröffentlichte',
  },
  {
    id: 'v.b1.l22.aktuell',
    de: 'aktuell',
    en: 'current, up to date',
    pos: 'adj',
    example: 'Auf der Internetseite finden Sie immer die aktuellen Nachrichten.',
    exampleEn: 'On the website you will always find the latest news.',
    level: 'B1',
    topic: 'media',
    difficulty: 2,
    note: 'A false friend: aktuell means "current", never "actual". "Actually" is eigentlich or tatsächlich.',
  },

  /* ── Technology ───────────────────────────────────────────────────────── */
  {
    id: 'v.b1.l22.technik',
    de: 'Technik',
    en: 'technology; technique',
    pos: 'noun',
    article: 'die',
    plural: 'die Techniken',
    example: 'Mein Vater interessiert sich sehr für Technik.',
    exampleEn: 'My father is very interested in technology.',
    level: 'B1',
    topic: 'technology',
    difficulty: 1,
    note: 'Nouns in -ik are feminine: die Technik, die Musik, die Politik. Someone who repairs machines is ein Techniker.',
  },
  {
    id: 'v.b1.l22.bildschirm',
    de: 'Bildschirm',
    en: 'screen, monitor',
    pos: 'noun',
    article: 'der',
    plural: 'die Bildschirme',
    example: 'Der Bildschirm von meinem Handy ist kaputt.',
    exampleEn: 'The screen of my phone is broken.',
    level: 'B1',
    topic: 'technology',
    difficulty: 1,
    note: 'Bild (picture) + Schirm (shield, umbrella) — and der Schirm makes the compound masculine.',
  },
  {
    id: 'v.b1.l22.passwort',
    de: 'Passwort',
    en: 'password',
    pos: 'noun',
    article: 'das',
    plural: 'die Passwörter',
    example: 'Ändern Sie Ihr Passwort regelmäßig.',
    exampleEn: 'Change your password regularly.',
    level: 'B1',
    topic: 'technology',
    difficulty: 1,
    note: 'das Wort → die Wörter, so das Passwort → die Passwörter.',
  },
  {
    id: 'v.b1.l22.herunterladen',
    de: 'herunterladen',
    en: 'to download',
    pos: 'verb',
    example: 'Sie können die App kostenlos herunterladen.',
    exampleEn: 'You can download the app for free.',
    level: 'B1',
    topic: 'technology',
    difficulty: 2,
    separable: true,
    note: 'Separable, and laden takes an Umlaut: du lädst herunter, er lädt herunter. Colloquially also downloaden.',
    forms: {
      ich: 'lade herunter',
      du: 'lädst herunter',
      er: 'lädt herunter',
      wir: 'laden herunter',
      ihr: 'ladet herunter',
      sie: 'laden herunter',
    },
    perfect: 'hat heruntergeladen',
    praeteritum: 'lud herunter',
  },
  {
    id: 'v.b1.l22.speichern',
    de: 'speichern',
    en: 'to save (a file), to store',
    pos: 'verb',
    example: 'Vergiss nicht, das Dokument zu speichern!',
    exampleEn: 'Do not forget to save the document!',
    level: 'B1',
    topic: 'technology',
    difficulty: 1,
    note: 'Verbs in -ern drop the e in the ich-form only in speech: ich speichere / ich speichre. The memory of a device is der Speicher.',
    forms: {
      ich: 'speichere',
      du: 'speicherst',
      er: 'speichert',
      wir: 'speichern',
      ihr: 'speichert',
      sie: 'speichern',
    },
    perfect: 'hat gespeichert',
    praeteritum: 'speicherte',
  },
  {
    id: 'v.b1.l22.loeschen',
    de: 'löschen',
    en: 'to delete; to put out (a fire)',
    pos: 'verb',
    example: 'Ich habe die alten Fotos gelöscht.',
    exampleEn: 'I have deleted the old photos.',
    level: 'B1',
    topic: 'technology',
    difficulty: 1,
    note: 'Firefighters löschen ein Feuer — the computer meaning came later. Regular: hat gelöscht.',
    forms: {
      ich: 'lösche',
      du: 'löschst',
      er: 'löscht',
      wir: 'löschen',
      ihr: 'löscht',
      sie: 'löschen',
    },
    perfect: 'hat gelöscht',
    praeteritum: 'löschte',
  },
  {
    id: 'v.b1.l22.entwickeln',
    de: 'entwickeln',
    en: 'to develop',
    pos: 'verb',
    example: 'Die Firma entwickelt eine neue App für Studenten.',
    exampleEn: 'The company is developing a new app for students.',
    level: 'B1',
    topic: 'technology',
    difficulty: 2,
    note: 'ent- is inseparable: hat entwickelt. The noun is die Entwicklung; a software developer is ein Entwickler.',
    forms: {
      ich: 'entwickle',
      du: 'entwickelst',
      er: 'entwickelt',
      wir: 'entwickeln',
      ihr: 'entwickelt',
      sie: 'entwickeln',
    },
    perfect: 'hat entwickelt',
    praeteritum: 'entwickelte',
  },
  {
    id: 'v.b1.l22.erfinden',
    de: 'erfinden',
    en: 'to invent',
    pos: 'verb',
    example: 'Mein Sohn möchte eine Maschine erfinden, die die Wäsche faltet.',
    exampleEn: 'My son wants to invent a machine that folds the laundry.',
    level: 'B1',
    topic: 'technology',
    difficulty: 2,
    note: 'Built on finden, so it is irregular: erfand, hat erfunden. The noun is die Erfindung.',
    forms: {
      ich: 'erfinde',
      du: 'erfindest',
      er: 'erfindet',
      wir: 'erfinden',
      ihr: 'erfindet',
      sie: 'erfinden',
    },
    perfect: 'hat erfunden',
    praeteritum: 'erfand',
  },
  {
    id: 'v.b1.l22.entwicklung',
    de: 'Entwicklung',
    en: 'development',
    pos: 'noun',
    article: 'die',
    plural: 'die Entwicklungen',
    example: 'Die Entwicklung der App hat zwei Jahre gedauert.',
    exampleEn: 'Developing the app took two years.',
    level: 'B1',
    topic: 'technology',
    difficulty: 2,
    note: 'Another -ung noun, so feminine. Also "progress" in general: eine positive Entwicklung.',
  },
  {
    id: 'v.b1.l22.digital',
    de: 'digital',
    en: 'digital',
    pos: 'adj',
    example: 'Viele Ämter arbeiten heute schon digital.',
    exampleEn: 'Many public offices already work digitally today.',
    level: 'B1',
    topic: 'technology',
    difficulty: 1,
    note: 'Stress on the last syllable: digiTAL. The buzzword noun is die Digitalisierung.',
  },
]

export default vocab
