/**
 * B1 · L24 — Education, career and interviews / Ausbildung, Beruf und Bewerbung
 *
 * The vocabulary of a working life told as a story: training and studies
 * (die Ausbildung, das Studium, das Praktikum, der Abschluss), applying for
 * a job (die Bewerbung, sich bewerben, der Lebenslauf, das
 * Vorstellungsgespräch, die Stelle, der Arbeitgeber) and selling yourself in
 * the interview (die Erfahrung, die Stärke, die Schwäche, zuverlässig,
 * selbstständig, erfolgreich).
 *
 * der Beruf, der Vertrag, das Gehalt and kündigen are earlier words and are
 * reused here, not redefined.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── Training and studies ─────────────────────────────────────────────── */
  {
    id: 'v.b1.l24.ausbildung',
    de: 'Ausbildung',
    en: 'vocational training, apprenticeship',
    pos: 'noun',
    article: 'die',
    plural: 'die Ausbildungen',
    example: 'Sie macht eine Ausbildung zur Krankenpflegerin.',
    exampleEn: 'She is training to be a nurse.',
    level: 'B1',
    topic: 'education',
    difficulty: 1,
    note: 'Germany’s dual system: three years split between a company and a vocational school. eine Ausbildung zum / zur … machen.',
  },
  {
    id: 'v.b1.l24.studium',
    de: 'Studium',
    en: 'university studies, degree course',
    pos: 'noun',
    article: 'das',
    plural: 'die Studien',
    example: 'Nach dem Studium möchte ich ein Jahr im Ausland arbeiten.',
    exampleEn: 'After my degree I would like to work abroad for a year.',
    level: 'B1',
    topic: 'education',
    difficulty: 2,
    note: 'Nouns in -um are neuter. The plural changes the ending: das Studium → die Studien. The verb is studieren.',
  },
  {
    id: 'v.b1.l24.praktikum',
    de: 'Praktikum',
    en: 'internship, work placement',
    pos: 'noun',
    article: 'das',
    plural: 'die Praktika',
    example: 'Im Sommer mache ich ein Praktikum bei einer Zeitung.',
    exampleEn: 'In the summer I am doing an internship at a newspaper.',
    level: 'B1',
    topic: 'career',
    difficulty: 2,
    note: 'Another -um noun with a Latin plural: die Praktika. The intern is der Praktikant / die Praktikantin.',
  },
  {
    id: 'v.b1.l24.abschluss',
    de: 'Abschluss',
    en: 'qualification, degree; conclusion',
    pos: 'noun',
    article: 'der',
    plural: 'die Abschlüsse',
    example: 'Welchen Abschluss haben Sie?',
    exampleEn: 'What qualification do you have?',
    level: 'B1',
    topic: 'education',
    difficulty: 2,
    note: 'From abschließen, to finish. einen Abschluss machen = to graduate, to qualify. Also der Schulabschluss, der Uniabschluss.',
  },

  /* ── Applying ─────────────────────────────────────────────────────────── */
  {
    id: 'v.b1.l24.stelle',
    de: 'Stelle',
    en: 'job, position; place',
    pos: 'noun',
    article: 'die',
    plural: 'die Stellen',
    example: 'Die Stelle als Teamleiterin ist noch frei.',
    exampleEn: 'The position of team leader is still vacant.',
    level: 'B1',
    topic: 'career',
    difficulty: 1,
    note: 'eine Stelle suchen / finden / bekommen. A job advert is eine Stellenanzeige. Also the An deiner Stelle of L21.',
  },
  {
    id: 'v.b1.l24.arbeitgeber',
    de: 'Arbeitgeber',
    en: 'employer',
    pos: 'noun',
    article: 'der',
    plural: 'die Arbeitgeber',
    example: 'Mein Arbeitgeber bezahlt mir einen Deutschkurs.',
    exampleEn: 'My employer is paying for a German course for me.',
    level: 'B1',
    topic: 'career',
    difficulty: 2,
    note: 'Literally the "work-giver"; the employee is der Arbeitnehmer, the "work-taker".',
  },
  {
    id: 'v.b1.l24.bewerbung',
    de: 'Bewerbung',
    en: 'job application',
    pos: 'noun',
    article: 'die',
    plural: 'die Bewerbungen',
    example: 'Ich habe schon zehn Bewerbungen geschrieben.',
    exampleEn: 'I have already written ten applications.',
    level: 'B1',
    topic: 'career',
    difficulty: 1,
    note: 'A full German application is a folder: Anschreiben (cover letter), Lebenslauf, Zeugnisse (certificates).',
  },
  {
    id: 'v.b1.l24.bewerben',
    de: 'sich bewerben',
    en: 'to apply (for a job)',
    pos: 'verb',
    example: 'Er möchte sich bei einer großen Firma bewerben.',
    exampleEn: 'He wants to apply to a big company.',
    level: 'B1',
    topic: 'career',
    difficulty: 2,
    note: 'Irregular (e → i): du bewirbst dich, er bewirbt sich; bewarb, hat sich beworben. The company takes bei, the job um or für: sich bei Siemens um eine Stelle bewerben.',
    forms: {
      ich: 'bewerbe mich',
      du: 'bewirbst dich',
      er: 'bewirbt sich',
      wir: 'bewerben uns',
      ihr: 'bewerbt euch',
      sie: 'bewerben sich',
    },
    perfect: 'hat sich beworben',
    praeteritum: 'bewarb sich',
  },
  {
    id: 'v.b1.l24.lebenslauf',
    de: 'Lebenslauf',
    en: 'CV, résumé',
    pos: 'noun',
    article: 'der',
    plural: 'die Lebensläufe',
    example: 'Im Lebenslauf steht, dass Sie drei Sprachen sprechen.',
    exampleEn: 'Your CV says that you speak three languages.',
    level: 'B1',
    topic: 'career',
    difficulty: 1,
    note: 'das Leben + der Lauf (the course) — masculine from Lauf. A German CV is in reverse order, newest first, and often has a photo.',
  },
  {
    id: 'v.b1.l24.vorstellungsgespraech',
    de: 'Vorstellungsgespräch',
    en: 'job interview',
    pos: 'noun',
    article: 'das',
    plural: 'die Vorstellungsgespräche',
    example: 'Morgen habe ich ein Vorstellungsgespräch bei einer Bank.',
    exampleEn: 'Tomorrow I have a job interview at a bank.',
    level: 'B1',
    topic: 'career',
    difficulty: 2,
    note: 'From sich vorstellen, to introduce yourself — the meeting where you present yourself. The last part, das Gespräch, makes it neuter.',
  },
  {
    id: 'v.b1.l24.einstellen',
    de: 'einstellen',
    en: 'to hire, to take on; to adjust',
    pos: 'verb',
    example: 'Die Firma möchte drei neue Mitarbeiter einstellen.',
    exampleEn: 'The company wants to hire three new employees.',
    level: 'B1',
    topic: 'career',
    difficulty: 2,
    separable: true,
    note: 'Separable: Wir stellen Sie ein. A thermostat or a camera also wird eingestellt — adjusted.',
    forms: {
      ich: 'stelle ein',
      du: 'stellst ein',
      er: 'stellt ein',
      wir: 'stellen ein',
      ihr: 'stellt ein',
      sie: 'stellen ein',
    },
    perfect: 'hat eingestellt',
    praeteritum: 'stellte ein',
  },
  {
    id: 'v.b1.l24.verdienen',
    de: 'verdienen',
    en: 'to earn; to deserve',
    pos: 'verb',
    example: 'In dem neuen Job verdient sie mehr Geld.',
    exampleEn: 'She earns more money in the new job.',
    level: 'B1',
    topic: 'career',
    difficulty: 1,
    note: 'Also "deserve": Das hast du verdient! ver- is inseparable: hat verdient.',
    forms: {
      ich: 'verdiene',
      du: 'verdienst',
      er: 'verdient',
      wir: 'verdienen',
      ihr: 'verdient',
      sie: 'verdienen',
    },
    perfect: 'hat verdient',
    praeteritum: 'verdiente',
  },

  /* ── In the interview ─────────────────────────────────────────────────── */
  {
    id: 'v.b1.l24.erfahrung',
    de: 'Erfahrung',
    en: 'experience',
    pos: 'noun',
    article: 'die',
    plural: 'die Erfahrungen',
    example: 'Ich habe drei Jahre Erfahrung im Verkauf.',
    exampleEn: 'I have three years of experience in sales.',
    level: 'B1',
    topic: 'career',
    difficulty: 1,
    note: 'Work experience is usually singular: Berufserfahrung. Experiences you had are plural: gute Erfahrungen machen.',
  },
  {
    id: 'v.b1.l24.staerke',
    de: 'Stärke',
    en: 'strength',
    pos: 'noun',
    article: 'die',
    plural: 'die Stärken',
    example: 'Meine größte Stärke ist meine Geduld.',
    exampleEn: 'My greatest strength is my patience.',
    level: 'B1',
    topic: 'career',
    difficulty: 1,
    note: 'From stark (strong). The interview classic: Was sind Ihre Stärken und Schwächen?',
  },
  {
    id: 'v.b1.l24.schwaeche',
    de: 'Schwäche',
    en: 'weakness',
    pos: 'noun',
    article: 'die',
    plural: 'die Schwächen',
    example: 'Eine Schwäche von mir ist, dass ich manchmal zu ungeduldig bin.',
    exampleEn: 'One weakness of mine is that I am sometimes too impatient.',
    level: 'B1',
    topic: 'career',
    difficulty: 1,
    note: 'From schwach (weak). In an interview name a real but harmless one — and what you do about it.',
  },
  {
    id: 'v.b1.l24.zuverlaessig',
    de: 'zuverlässig',
    en: 'reliable',
    pos: 'adj',
    example: 'Unsere neue Kollegin ist sehr zuverlässig.',
    exampleEn: 'Our new colleague is very reliable.',
    level: 'B1',
    topic: 'career',
    difficulty: 2,
    note: 'The top word in German job adverts, together with teamfähig and flexibel. The noun is die Zuverlässigkeit.',
  },
  {
    id: 'v.b1.l24.selbststaendig',
    de: 'selbstständig',
    en: 'independent(ly); self-employed',
    pos: 'adj',
    example: 'In meinem letzten Job habe ich sehr selbstständig gearbeitet.',
    exampleEn: 'In my last job I worked very independently.',
    level: 'B1',
    topic: 'career',
    difficulty: 3,
    note: 'Two meanings: working without supervision, and being your own boss — Sie ist selbstständig. The spelling selbständig is also correct.',
  },
  {
    id: 'v.b1.l24.erfolgreich',
    de: 'erfolgreich',
    en: 'successful',
    pos: 'adj',
    example: 'Das Projekt war sehr erfolgreich.',
    exampleEn: 'The project was very successful.',
    level: 'B1',
    topic: 'career',
    difficulty: 2,
    note: 'der Erfolg (success) + -reich (rich in). Viel Erfolg! = Good luck!',
  },
]

export default vocab
