/**
 * B1 · L20 — Emails, formal and informal / E-Mails, formell und informell
 *
 * The vocabulary of written German at work: the parts of an e-mail (der
 * Betreff, die Anrede, der Anhang, Mit freundlichen Grüßen), the kinds of
 * message (die Nachricht, die Anfrage, die Absage, die Bestätigung, die
 * Rückmeldung) and the verbs that do the business (beantworten, bestätigen,
 * mitteilen, weiterleiten, erreichen, sich bedanken, sich wenden an).
 *
 * absagen, einladen, zusagen, sich melden and Bescheid sagen are A2 words
 * and are reused here, not redefined.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── The parts of an e-mail ───────────────────────────────────────────── */
  {
    id: 'v.b1.l20.nachricht',
    de: 'Nachricht',
    en: 'message; (news) item',
    pos: 'noun',
    article: 'die',
    plural: 'die Nachrichten',
    example: 'Vielen Dank für Ihre Nachricht.',
    exampleEn: 'Thank you for your message.',
    level: 'B1',
    topic: 'media',
    difficulty: 1,
    note: 'In the plural, die Nachrichten is also the TV news. A text message is often just eine Nachricht or eine SMS.',
  },
  {
    id: 'v.b1.l20.betreff',
    de: 'Betreff',
    en: 'subject line',
    pos: 'noun',
    article: 'der',
    plural: 'die Betreffe',
    example: 'Im Betreff steht nur „Frage“ — das ist zu kurz.',
    exampleEn: 'The subject line just says "question" — that is too short.',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'In old letters it was abbreviated Betr.: … A good Betreff names the topic and, if there is one, the date or number: Ihre Anfrage vom 3. Mai.',
  },
  {
    id: 'v.b1.l20.anrede',
    de: 'Anrede',
    en: 'form of address, salutation',
    pos: 'noun',
    article: 'die',
    plural: 'die Anreden',
    example: 'Die richtige Anrede ist „Sehr geehrte Frau Weber“.',
    exampleEn: 'The correct salutation is "Dear Ms Weber".',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'From anreden, to address someone. Formal: Sehr geehrte Frau … / Sehr geehrter Herr … Informal: Liebe … / Lieber … / Hallo …',
  },
  {
    id: 'v.b1.l20.anhang',
    de: 'Anhang',
    en: 'attachment; appendix',
    pos: 'noun',
    article: 'der',
    plural: 'die Anhänge',
    example: 'Im Anhang finden Sie den Vertrag.',
    exampleEn: 'Please find the contract attached.',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'Im Anhang finden Sie … is THE standard line for attachments. The verb is anhängen: Ich hänge die Datei an.',
  },
  {
    id: 'v.b1.l20.freundliche-gruesse',
    de: 'Mit freundlichen Grüßen',
    en: 'Kind regards (formal sign-off)',
    pos: 'phrase',
    example: 'Mit freundlichen Grüßen, Claudia Wenzel',
    exampleEn: 'Kind regards, Claudia Wenzel',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'The default for anyone you call Sie. No comma after it in German — the name follows on the next line. Colleagues often shorten it to Viele Grüße or Beste Grüße.',
  },

  /* ── Kinds of message ─────────────────────────────────────────────────── */
  {
    id: 'v.b1.l20.anfrage',
    de: 'Anfrage',
    en: 'enquiry, request (for information)',
    pos: 'noun',
    article: 'die',
    plural: 'die Anfragen',
    example: 'Vielen Dank für Ihre Anfrage zu unseren Kursen.',
    exampleEn: 'Thank you for your enquiry about our courses.',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    note: 'Formal for "a question by letter or e-mail". eine Anfrage stellen / schicken. Not the same as der Antrag, an official application form.',
  },
  {
    id: 'v.b1.l20.absage',
    de: 'Absage',
    en: 'cancellation; rejection',
    pos: 'noun',
    article: 'die',
    plural: 'die Absagen',
    example: 'Leider habe ich auf meine Bewerbung eine Absage bekommen.',
    exampleEn: 'Unfortunately I received a rejection for my application.',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    note: 'The noun of absagen. Its opposite is die Zusage — a yes to an invitation or a job offer.',
  },
  {
    id: 'v.b1.l20.bestaetigung',
    de: 'Bestätigung',
    en: 'confirmation',
    pos: 'noun',
    article: 'die',
    plural: 'die Bestätigungen',
    example: 'Sie bekommen eine Bestätigung per E-Mail.',
    exampleEn: 'You will receive a confirmation by e-mail.',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'die Buchungsbestätigung, die Terminbestätigung — the -ung noun of bestätigen.',
  },
  {
    id: 'v.b1.l20.rueckmeldung',
    de: 'Rückmeldung',
    en: 'reply, feedback',
    pos: 'noun',
    article: 'die',
    plural: 'die Rückmeldungen',
    example: 'Ich freue mich auf Ihre Rückmeldung.',
    exampleEn: 'I look forward to hearing from you.',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    note: 'Literally "reporting back". Ich freue mich auf Ihre Rückmeldung is the classic last line of a business e-mail.',
  },

  /* ── The verbs that do the business ───────────────────────────────────── */
  {
    id: 'v.b1.l20.beantworten',
    de: 'beantworten',
    en: 'to answer (something)',
    pos: 'verb',
    example: 'Ich beantworte Ihre E-Mail bis morgen.',
    exampleEn: 'I will answer your e-mail by tomorrow.',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    note: 'beantworten takes a direct object: eine Frage beantworten. Plain antworten needs auf: auf eine Frage antworten. be- is inseparable: hat beantwortet.',
    forms: {
      ich: 'beantworte',
      du: 'beantwortest',
      er: 'beantwortet',
      wir: 'beantworten',
      ihr: 'beantwortet',
      sie: 'beantworten',
    },
    perfect: 'hat beantwortet',
    praeteritum: 'beantwortete',
  },
  {
    id: 'v.b1.l20.bestaetigen',
    de: 'bestätigen',
    en: 'to confirm',
    pos: 'verb',
    example: 'Können Sie mir den Termin bitte schriftlich bestätigen?',
    exampleEn: 'Can you please confirm the appointment in writing?',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    note: 'be- is inseparable, so no ge-: hat bestätigt. You confirm something to someone: jemandem etwas bestätigen.',
    forms: {
      ich: 'bestätige',
      du: 'bestätigst',
      er: 'bestätigt',
      wir: 'bestätigen',
      ihr: 'bestätigt',
      sie: 'bestätigen',
    },
    perfect: 'hat bestätigt',
    praeteritum: 'bestätigte',
  },
  {
    id: 'v.b1.l20.bedanken',
    de: 'sich bedanken',
    en: 'to say thank you',
    pos: 'verb',
    example: 'Er möchte sich herzlich für Ihre Hilfe bedanken.',
    exampleEn: 'He would like to thank you warmly for your help.',
    level: 'B1',
    topic: 'social',
    difficulty: 2,
    note: 'The more formal cousin of danke sagen. The reason takes für + accusative; the person takes bei: sich bei Frau Weber für das Gespräch bedanken.',
    forms: {
      ich: 'bedanke mich',
      du: 'bedankst dich',
      er: 'bedankt sich',
      wir: 'bedanken uns',
      ihr: 'bedankt euch',
      sie: 'bedanken sich',
    },
    perfect: 'hat sich bedankt',
    praeteritum: 'bedankte sich',
  },
  {
    id: 'v.b1.l20.mitteilen',
    de: 'mitteilen',
    en: 'to inform, to let someone know',
    pos: 'verb',
    example: 'Können Sie uns bitte mitteilen, ob Sie am Kurs teilnehmen?',
    exampleEn: 'Can you please let us know whether you will take part in the course?',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    separable: true,
    note: 'The written version of Bescheid sagen. The person you inform is in the dative: Ich teile Ihnen mit, dass … The noun is die Mitteilung.',
    forms: {
      ich: 'teile mit',
      du: 'teilst mit',
      er: 'teilt mit',
      wir: 'teilen mit',
      ihr: 'teilt mit',
      sie: 'teilen mit',
    },
    perfect: 'hat mitgeteilt',
    praeteritum: 'teilte mit',
  },
  {
    id: 'v.b1.l20.weiterleiten',
    de: 'weiterleiten',
    en: 'to forward',
    pos: 'verb',
    example: 'Ich leite Ihre E-Mail an die Kollegin weiter.',
    exampleEn: 'I will forward your e-mail to my colleague.',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    separable: true,
    note: 'weiter- is stressed and splits off: Ich leite … weiter. The person it goes to takes an + accusative.',
    forms: {
      ich: 'leite weiter',
      du: 'leitest weiter',
      er: 'leitet weiter',
      wir: 'leiten weiter',
      ihr: 'leitet weiter',
      sie: 'leiten weiter',
    },
    perfect: 'hat weitergeleitet',
    praeteritum: 'leitete weiter',
  },
  {
    id: 'v.b1.l20.erreichen',
    de: 'erreichen',
    en: 'to reach (a person, a place, a goal)',
    pos: 'verb',
    example: 'Sie erreichen mich am besten am Vormittag.',
    exampleEn: 'The best time to reach me is in the morning.',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    note: 'Sie erreichen mich unter 0172 … is how you give a phone number in writing. er- is inseparable: hat erreicht.',
    forms: {
      ich: 'erreiche',
      du: 'erreichst',
      er: 'erreicht',
      wir: 'erreichen',
      ihr: 'erreicht',
      sie: 'erreichen',
    },
    perfect: 'hat erreicht',
    praeteritum: 'erreichte',
  },
  {
    id: 'v.b1.l20.wenden-an',
    de: 'sich wenden an',
    en: 'to contact, to turn to (someone)',
    pos: 'verb',
    example: 'Bei Fragen können Sie sich jederzeit an mich wenden.',
    exampleEn: 'If you have any questions, you can contact me at any time.',
    level: 'B1',
    topic: 'work',
    difficulty: 3,
    note: 'Always an + accusative: sich an die Personalabteilung wenden. The polite closing line: Bei Fragen wenden Sie sich bitte an …',
    forms: {
      ich: 'wende mich an',
      du: 'wendest dich an',
      er: 'wendet sich an',
      wir: 'wenden uns an',
      ihr: 'wendet euch an',
      sie: 'wenden sich an',
    },
    perfect: 'hat sich gewandt',
    praeteritum: 'wandte sich',
  },

  /* ── Tone ─────────────────────────────────────────────────────────────── */
  {
    id: 'v.b1.l20.hoeflich',
    de: 'höflich',
    en: 'polite',
    pos: 'adj',
    example: 'Die E-Mail ist kurz, aber sehr höflich.',
    exampleEn: 'The e-mail is short but very polite.',
    level: 'B1',
    topic: 'social',
    difficulty: 1,
    note: 'Opposite: unhöflich. The noun is die Höflichkeit. In German e-mails politeness comes from könnten / würden, not from long compliments.',
  },
  {
    id: 'v.b1.l20.persoenlich',
    de: 'persönlich',
    en: 'personal; in person',
    pos: 'adj',
    example: 'Ich möchte Sie gern persönlich kennenlernen.',
    exampleEn: 'I would like to meet you in person.',
    level: 'B1',
    topic: 'social',
    difficulty: 1,
    note: 'Works as an adjective (ein persönliches Gespräch) and as an adverb (persönlich vorbeikommen). On a letter, Persönlich means "private — for the addressee only".',
  },
]

export default vocab
