/**
 * B1 · L25 — Health and relationships / Gesundheit und Beziehungen
 *
 * Two parts of life that come up whenever people tell each other how they
 * are really doing. Health beyond a cold (die Gesundheit, die Krankheit,
 * der Unfall, die Verletzung, sich verletzen, sich erholen, sich
 * entspannen, die Ernährung) and the people in your life (die Beziehung,
 * die Freundschaft, die Hochzeit, sich verlieben, heiraten, sich streiten,
 * sich versöhnen, vertrauen).
 *
 * Most of the verbs are reflexive, and most stories about them are told in
 * the past — the raw material for the Plusquamperfekt step.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── Health ───────────────────────────────────────────────────────────── */
  {
    id: 'v.b1.l25.gesundheit',
    de: 'Gesundheit',
    en: 'health',
    pos: 'noun',
    article: 'die',
    plural: null,
    example: 'Sport ist gut für die Gesundheit.',
    exampleEn: 'Sport is good for your health.',
    level: 'B1',
    topic: 'health',
    difficulty: 1,
    note: 'Every noun in -heit is feminine. Gesundheit! is also what you say when someone sneezes.',
  },
  {
    id: 'v.b1.l25.gesund',
    de: 'gesund',
    en: 'healthy',
    pos: 'adj',
    example: 'Sie ernährt sich sehr gesund.',
    exampleEn: 'She eats very healthily.',
    level: 'B1',
    topic: 'health',
    difficulty: 1,
    note: 'Comparative with an Umlaut: gesünder, am gesündesten. Opposite: ungesund — or krank, if you mean ill.',
  },
  {
    id: 'v.b1.l25.krankheit',
    de: 'Krankheit',
    en: 'illness, disease',
    pos: 'noun',
    article: 'die',
    plural: 'die Krankheiten',
    example: 'Wegen einer Krankheit konnte er nicht arbeiten.',
    exampleEn: 'Because of an illness he could not work.',
    level: 'B1',
    topic: 'health',
    difficulty: 1,
    note: 'krank + -heit. Health insurance is die Krankenversicherung, a sick note die Krankmeldung (A2).',
  },
  {
    id: 'v.b1.l25.krankenhaus',
    de: 'Krankenhaus',
    en: 'hospital',
    pos: 'noun',
    article: 'das',
    plural: 'die Krankenhäuser',
    example: 'Nach dem Unfall musste sie ins Krankenhaus.',
    exampleEn: 'After the accident she had to go to hospital.',
    level: 'B1',
    topic: 'health',
    difficulty: 1,
    note: 'das Haus decides: neuter, plural die Krankenhäuser. Going there takes ins (accusative), being there im (dative).',
  },
  {
    id: 'v.b1.l25.unfall',
    de: 'Unfall',
    en: 'accident',
    pos: 'noun',
    article: 'der',
    plural: 'die Unfälle',
    example: 'Auf dem Weg zur Arbeit hatte er einen Unfall.',
    exampleEn: 'On the way to work he had an accident.',
    level: 'B1',
    topic: 'health',
    difficulty: 1,
    note: 'einen Unfall haben (not "machen"). der Fall makes it masculine; the plural takes an Umlaut.',
  },
  {
    id: 'v.b1.l25.verletzung',
    de: 'Verletzung',
    en: 'injury',
    pos: 'noun',
    article: 'die',
    plural: 'die Verletzungen',
    example: 'Die Verletzung am Knie war zum Glück nicht schlimm.',
    exampleEn: 'Luckily the knee injury was not serious.',
    level: 'B1',
    topic: 'health',
    difficulty: 2,
    note: 'The -ung noun of verletzen. Where you are injured takes an + dative: eine Verletzung am Arm.',
  },
  {
    id: 'v.b1.l25.verletzen',
    de: 'sich verletzen',
    en: 'to injure yourself, to get hurt',
    pos: 'verb',
    example: 'Beim Fußball kann man sich leicht verletzen.',
    exampleEn: 'You can easily get hurt playing football.',
    level: 'B1',
    topic: 'health',
    difficulty: 2,
    note: 'The body part follows an + dative: sich am Fuß verletzen. Or with a dative reflexive: Ich habe mir den Fuß verletzt.',
    forms: {
      ich: 'verletze mich',
      du: 'verletzt dich',
      er: 'verletzt sich',
      wir: 'verletzen uns',
      ihr: 'verletzt euch',
      sie: 'verletzen sich',
    },
    perfect: 'hat sich verletzt',
    praeteritum: 'verletzte sich',
  },
  {
    id: 'v.b1.l25.erholen',
    de: 'sich erholen',
    en: 'to recover; to rest, to recharge',
    pos: 'verb',
    example: 'Im Urlaub konnte sie sich endlich erholen.',
    exampleEn: 'On holiday she was finally able to recharge.',
    level: 'B1',
    topic: 'health',
    difficulty: 2,
    note: 'After an illness: sich von einer Krankheit erholen. The noun is die Erholung. Gute Erholung! = Get well / rest well!',
    forms: {
      ich: 'erhole mich',
      du: 'erholst dich',
      er: 'erholt sich',
      wir: 'erholen uns',
      ihr: 'erholt euch',
      sie: 'erholen sich',
    },
    perfect: 'hat sich erholt',
    praeteritum: 'erholte sich',
  },
  {
    id: 'v.b1.l25.entspannen',
    de: 'sich entspannen',
    en: 'to relax',
    pos: 'verb',
    example: 'Am Abend möchte er sich einfach entspannen.',
    exampleEn: 'In the evening he just wants to relax.',
    level: 'B1',
    topic: 'health',
    difficulty: 2,
    note: 'ent- is inseparable: hat sich entspannt. The adjective entspannt means relaxed; the opposite is gestresst.',
    forms: {
      ich: 'entspanne mich',
      du: 'entspannst dich',
      er: 'entspannt sich',
      wir: 'entspannen uns',
      ihr: 'entspannt euch',
      sie: 'entspannen sich',
    },
    perfect: 'hat sich entspannt',
    praeteritum: 'entspannte sich',
  },
  {
    id: 'v.b1.l25.ernaehrung',
    de: 'Ernährung',
    en: 'diet, nutrition',
    pos: 'noun',
    article: 'die',
    plural: null,
    example: 'Eine gesunde Ernährung ist sehr wichtig.',
    exampleEn: 'A healthy diet is very important.',
    level: 'B1',
    topic: 'health',
    difficulty: 2,
    note: 'Diet in the sense of what you eat in general. Being on a diet to lose weight is eine Diät machen.',
  },

  /* ── Relationships ────────────────────────────────────────────────────── */
  {
    id: 'v.b1.l25.beziehung',
    de: 'Beziehung',
    en: 'relationship',
    pos: 'noun',
    article: 'die',
    plural: 'die Beziehungen',
    example: 'Die beiden sind seit drei Jahren in einer Beziehung.',
    exampleEn: 'The two of them have been in a relationship for three years.',
    level: 'B1',
    topic: 'relationships',
    difficulty: 1,
    note: 'Romantic and professional: gute Beziehungen zu Kunden. A long-distance relationship is eine Fernbeziehung (L21).',
  },
  {
    id: 'v.b1.l25.freundschaft',
    de: 'Freundschaft',
    en: 'friendship',
    pos: 'noun',
    article: 'die',
    plural: 'die Freundschaften',
    example: 'Unsere Freundschaft ist mir sehr wichtig.',
    exampleEn: 'Our friendship is very important to me.',
    level: 'B1',
    topic: 'relationships',
    difficulty: 1,
    note: '-schaft nouns are feminine: die Freundschaft, die Mannschaft, die Gesellschaft.',
  },
  {
    id: 'v.b1.l25.hochzeit',
    de: 'Hochzeit',
    en: 'wedding',
    pos: 'noun',
    article: 'die',
    plural: 'die Hochzeiten',
    example: 'Zur Hochzeit kamen über hundert Gäste.',
    exampleEn: 'Over a hundred guests came to the wedding.',
    level: 'B1',
    topic: 'relationships',
    difficulty: 1,
    note: 'Pronounced HOCH-zeit, with a short o. die Zeit makes it feminine. The honeymoon is die Hochzeitsreise.',
  },
  {
    id: 'v.b1.l25.verlieben',
    de: 'sich verlieben',
    en: 'to fall in love',
    pos: 'verb',
    example: 'Er hat sich in seine Nachbarin verliebt.',
    exampleEn: 'He has fallen in love with his neighbour.',
    level: 'B1',
    topic: 'relationships',
    difficulty: 2,
    note: 'Always in + accusative: sich in jemanden verlieben. Being in love is a state: verliebt sein.',
    forms: {
      ich: 'verliebe mich',
      du: 'verliebst dich',
      er: 'verliebt sich',
      wir: 'verlieben uns',
      ihr: 'verliebt euch',
      sie: 'verlieben sich',
    },
    perfect: 'hat sich verliebt',
    praeteritum: 'verliebte sich',
  },
  {
    id: 'v.b1.l25.heiraten',
    de: 'heiraten',
    en: 'to marry, to get married',
    pos: 'verb',
    example: 'Meine Schwester möchte nächstes Jahr heiraten.',
    exampleEn: 'My sister wants to get married next year.',
    level: 'B1',
    topic: 'relationships',
    difficulty: 1,
    note: 'Not reflexive and no preposition: Sie heiratet ihn. The state is verheiratet sein (A1).',
    forms: {
      ich: 'heirate',
      du: 'heiratest',
      er: 'heiratet',
      wir: 'heiraten',
      ihr: 'heiratet',
      sie: 'heiraten',
    },
    perfect: 'hat geheiratet',
    praeteritum: 'heiratete',
  },
  {
    id: 'v.b1.l25.streiten',
    de: 'sich streiten',
    en: 'to argue, to quarrel',
    pos: 'verb',
    example: 'Die Kinder streiten sich ständig um das Tablet.',
    exampleEn: 'The children are constantly fighting over the tablet.',
    level: 'B1',
    topic: 'relationships',
    difficulty: 2,
    note: 'Irregular: stritt, hat sich gestritten. With a person: mit + dative; about something: über or um + accusative. The noun is der Streit.',
    forms: {
      ich: 'streite mich',
      du: 'streitest dich',
      er: 'streitet sich',
      wir: 'streiten uns',
      ihr: 'streitet euch',
      sie: 'streiten sich',
    },
    perfect: 'hat sich gestritten',
    praeteritum: 'stritt sich',
  },
  {
    id: 'v.b1.l25.versoehnen',
    de: 'sich versöhnen',
    en: 'to make up, to be reconciled',
    pos: 'verb',
    example: 'Nach dem Streit haben sich die beiden schnell wieder versöhnt.',
    exampleEn: 'After the argument the two of them quickly made up again.',
    level: 'B1',
    topic: 'relationships',
    difficulty: 3,
    note: 'The natural follow-up to sich streiten. With a person: sich mit jemandem versöhnen.',
    forms: {
      ich: 'versöhne mich',
      du: 'versöhnst dich',
      er: 'versöhnt sich',
      wir: 'versöhnen uns',
      ihr: 'versöhnt euch',
      sie: 'versöhnen sich',
    },
    perfect: 'hat sich versöhnt',
    praeteritum: 'versöhnte sich',
  },
  {
    id: 'v.b1.l25.vertrauen',
    de: 'vertrauen',
    en: 'to trust',
    pos: 'verb',
    example: 'Ich kann meiner besten Freundin alles erzählen, ich vertraue ihr.',
    exampleEn: 'I can tell my best friend everything, I trust her.',
    level: 'B1',
    topic: 'relationships',
    difficulty: 2,
    note: 'Takes the dative: Ich vertraue dir / ihm / ihr. The noun is das Vertrauen.',
    forms: {
      ich: 'vertraue',
      du: 'vertraust',
      er: 'vertraut',
      wir: 'vertrauen',
      ihr: 'vertraut',
      sie: 'vertrauen',
    },
    perfect: 'hat vertraut',
    praeteritum: 'vertraute',
  },
]

export default vocab
