/**
 * B1 · L23 — Environment and society / Umwelt und Gesellschaft
 *
 * The words for talking about how we live together and with the planet:
 * the big nouns (die Umwelt, der Klimawandel, die Gesellschaft, die
 * Zukunft, die Verantwortung), everyday action (Müll trennen, Energie
 * sparen, weniger verbrauchen, öffentliche Verkehrsmittel), and the
 * feelings and commitment that come with it (sich Sorgen machen um, sich
 * ärgern über, sich engagieren für).
 *
 * The three reflexive verbs come with fixed prepositions on purpose: they
 * are the material for g.b1.praepositionen. nachhaltig, umweltfreundlich and
 * öffentlich are the adjectives the adjective-ending step practises with.
 *
 * sich kümmern um and sich freuen auf are A2 words and are reused.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── The big picture ──────────────────────────────────────────────────── */
  {
    id: 'v.b1.l23.umwelt',
    de: 'Umwelt',
    en: 'environment',
    pos: 'noun',
    article: 'die',
    plural: null,
    example: 'Wir müssen die Umwelt besser schützen.',
    exampleEn: 'We have to protect the environment better.',
    level: 'B1',
    topic: 'environment',
    difficulty: 1,
    note: 'Um + Welt, and die Welt is feminine. No plural. Very productive: der Umweltschutz, umweltfreundlich.',
  },
  {
    id: 'v.b1.l23.klimawandel',
    de: 'Klimawandel',
    en: 'climate change',
    pos: 'noun',
    article: 'der',
    plural: null,
    example: 'Der Klimawandel ist eines der größten Probleme unserer Zeit.',
    exampleEn: 'Climate change is one of the biggest problems of our time.',
    level: 'B1',
    topic: 'environment',
    difficulty: 2,
    note: 'das Klima + der Wandel (change) — the last part makes it masculine. No plural.',
  },
  {
    id: 'v.b1.l23.muell',
    de: 'Müll',
    en: 'rubbish, waste',
    pos: 'noun',
    article: 'der',
    plural: null,
    example: 'Im Park liegt leider viel Müll.',
    exampleEn: 'Unfortunately there is a lot of rubbish lying in the park.',
    level: 'B1',
    topic: 'environment',
    difficulty: 1,
    note: 'Uncountable. den Müll trennen = to sort the rubbish; den Müll rausbringen = to take the rubbish out.',
  },
  {
    id: 'v.b1.l23.energie',
    de: 'Energie',
    en: 'energy',
    pos: 'noun',
    article: 'die',
    plural: 'die Energien',
    example: 'Mit LED-Lampen kann man viel Energie sparen.',
    exampleEn: 'You can save a lot of energy with LED lamps.',
    level: 'B1',
    topic: 'environment',
    difficulty: 1,
    note: 'Stress on the last syllable: EnerGIE. Nouns in -ie are feminine: die Energie, die Familie, die Industrie.',
  },
  {
    id: 'v.b1.l23.gesellschaft',
    de: 'Gesellschaft',
    en: 'society; company',
    pos: 'noun',
    article: 'die',
    plural: 'die Gesellschaften',
    example: 'Das Problem betrifft die ganze Gesellschaft.',
    exampleEn: 'The problem affects the whole of society.',
    level: 'B1',
    topic: 'society',
    difficulty: 2,
    note: 'Every noun in -schaft is feminine. In company names it means a firm: GmbH = Gesellschaft mit beschränkter Haftung.',
  },
  {
    id: 'v.b1.l23.zukunft',
    de: 'Zukunft',
    en: 'future',
    pos: 'noun',
    article: 'die',
    plural: null,
    example: 'In Zukunft möchte ich weniger Auto fahren.',
    exampleEn: 'In future I would like to drive less.',
    level: 'B1',
    topic: 'society',
    difficulty: 1,
    note: 'in Zukunft = from now on; in der Zukunft = at some point in the future. Plural practically never used.',
  },
  {
    id: 'v.b1.l23.verantwortung',
    de: 'Verantwortung',
    en: 'responsibility',
    pos: 'noun',
    article: 'die',
    plural: 'die Verantwortungen',
    example: 'Jeder trägt Verantwortung für die Umwelt.',
    exampleEn: 'Everyone bears responsibility for the environment.',
    level: 'B1',
    topic: 'society',
    difficulty: 3,
    note: 'Verantwortung tragen / übernehmen für + accusative. The adjective is verantwortlich (L19 reading).',
  },
  {
    id: 'v.b1.l23.verkehrsmittel',
    de: 'Verkehrsmittel',
    en: 'means of transport',
    pos: 'noun',
    article: 'das',
    plural: 'die Verkehrsmittel',
    example: 'Ich fahre am liebsten mit öffentlichen Verkehrsmitteln.',
    exampleEn: 'I prefer to travel by public transport.',
    level: 'B1',
    topic: 'transport',
    difficulty: 2,
    note: 'der Verkehr + das Mittel — neuter from Mittel. öffentliche Verkehrsmittel = public transport (bus, tram, train).',
  },

  /* ── Doing something ──────────────────────────────────────────────────── */
  {
    id: 'v.b1.l23.schuetzen',
    de: 'schützen',
    en: 'to protect',
    pos: 'verb',
    example: 'Bäume schützen die Stadt vor Hitze.',
    exampleEn: 'Trees protect the city from heat.',
    level: 'B1',
    topic: 'environment',
    difficulty: 2,
    note: 'Against something = vor + dative: vor dem Regen schützen. The noun is der Schutz.',
    forms: {
      ich: 'schütze',
      du: 'schützt',
      er: 'schützt',
      wir: 'schützen',
      ihr: 'schützt',
      sie: 'schützen',
    },
    perfect: 'hat geschützt',
    praeteritum: 'schützte',
  },
  {
    id: 'v.b1.l23.sparen',
    de: 'sparen',
    en: 'to save (money, energy, time)',
    pos: 'verb',
    example: 'Wir sparen für eine neue Küche.',
    exampleEn: 'We are saving for a new kitchen.',
    level: 'B1',
    topic: 'money',
    difficulty: 1,
    note: 'Saving FOR something takes für. Saving a file is speichern — never sparen.',
    forms: {
      ich: 'spare',
      du: 'sparst',
      er: 'spart',
      wir: 'sparen',
      ihr: 'spart',
      sie: 'sparen',
    },
    perfect: 'hat gespart',
    praeteritum: 'sparte',
  },
  {
    id: 'v.b1.l23.trennen',
    de: 'trennen',
    en: 'to separate, to sort',
    pos: 'verb',
    example: 'In Deutschland trennen fast alle ihren Müll.',
    exampleEn: 'In Germany almost everyone sorts their rubbish.',
    level: 'B1',
    topic: 'environment',
    difficulty: 1,
    note: 'Also for couples: sich trennen = to break up. die Mülltrennung = waste separation.',
    forms: {
      ich: 'trenne',
      du: 'trennst',
      er: 'trennt',
      wir: 'trennen',
      ihr: 'trennt',
      sie: 'trennen',
    },
    perfect: 'hat getrennt',
    praeteritum: 'trennte',
  },
  {
    id: 'v.b1.l23.verbrauchen',
    de: 'verbrauchen',
    en: 'to use up, to consume',
    pos: 'verb',
    example: 'Ein altes Auto verbraucht viel Benzin.',
    exampleEn: 'An old car uses a lot of petrol.',
    level: 'B1',
    topic: 'environment',
    difficulty: 2,
    note: 'brauchen = to need; verbrauchen = to use up. The consumer is der Verbraucher.',
    forms: {
      ich: 'verbrauche',
      du: 'verbrauchst',
      er: 'verbraucht',
      wir: 'verbrauchen',
      ihr: 'verbraucht',
      sie: 'verbrauchen',
    },
    perfect: 'hat verbraucht',
    praeteritum: 'verbrauchte',
  },
  {
    id: 'v.b1.l23.engagieren',
    de: 'sich engagieren',
    en: 'to get involved, to be committed (to)',
    pos: 'verb',
    example: 'Meine Schwester möchte sich für den Tierschutz engagieren.',
    exampleEn: 'My sister wants to get involved in animal protection.',
    level: 'B1',
    topic: 'society',
    difficulty: 3,
    note: 'Pronounced the French way: [ɑ̃ɡaˈʒiːʁən]. Always für + accusative. -ieren verbs take no ge-: hat sich engagiert.',
    forms: {
      ich: 'engagiere mich',
      du: 'engagierst dich',
      er: 'engagiert sich',
      wir: 'engagieren uns',
      ihr: 'engagiert euch',
      sie: 'engagieren sich',
    },
    perfect: 'hat sich engagiert',
    praeteritum: 'engagierte sich',
  },
  {
    id: 'v.b1.l23.sorgen-machen',
    de: 'sich Sorgen machen',
    en: 'to worry',
    pos: 'phrase',
    example: 'Viele junge Leute machen sich Sorgen um die Zukunft.',
    exampleEn: 'Many young people worry about the future.',
    level: 'B1',
    topic: 'emotions',
    difficulty: 2,
    note: 'The reflexive is dative (ich mache mir Sorgen), and the worry is about um + accusative. Reassuring someone: Mach dir keine Sorgen!',
  },
  {
    id: 'v.b1.l23.aergern',
    de: 'sich ärgern',
    en: 'to be annoyed, to get angry',
    pos: 'verb',
    example: 'Wir ärgern uns über den Lärm — und die Nachbarn ärgern sich über uns.',
    exampleEn: 'We are annoyed about the noise — and the neighbours are annoyed with us.',
    level: 'B1',
    topic: 'emotions',
    difficulty: 2,
    note: 'Always über + accusative. Without sich it means to annoy someone else: Das ärgert mich.',
    forms: {
      ich: 'ärgere mich',
      du: 'ärgerst dich',
      er: 'ärgert sich',
      wir: 'ärgern uns',
      ihr: 'ärgert euch',
      sie: 'ärgern sich',
    },
    perfect: 'hat sich geärgert',
    praeteritum: 'ärgerte sich',
  },

  /* ── Describing it ────────────────────────────────────────────────────── */
  {
    id: 'v.b1.l23.nachhaltig',
    de: 'nachhaltig',
    en: 'sustainable',
    pos: 'adj',
    example: 'Das Hotel ist sehr nachhaltig gebaut.',
    exampleEn: 'The hotel is built very sustainably.',
    level: 'B1',
    topic: 'environment',
    difficulty: 3,
    note: 'From forestry: cut only as many trees as grow back. The noun is die Nachhaltigkeit.',
  },
  {
    id: 'v.b1.l23.umweltfreundlich',
    de: 'umweltfreundlich',
    en: 'environmentally friendly',
    pos: 'adj',
    example: 'Mit dem Fahrrad zu fahren ist umweltfreundlich und gesund.',
    exampleEn: 'Cycling is environmentally friendly and healthy.',
    level: 'B1',
    topic: 'environment',
    difficulty: 2,
    note: 'Literally "environment-friendly". Comparative: umweltfreundlicher. The opposite is umweltschädlich.',
  },
  {
    id: 'v.b1.l23.oeffentlich',
    de: 'öffentlich',
    en: 'public',
    pos: 'adj',
    example: 'In öffentlichen Gebäuden darf man nicht rauchen.',
    exampleEn: 'You are not allowed to smoke in public buildings.',
    level: 'B1',
    topic: 'society',
    difficulty: 2,
    note: 'Related to offen (open). Almost always with an ending in front of a noun: die öffentlichen Verkehrsmittel.',
  },
]

export default vocab
