/**
 * B1 · L19 — Meetings and workplace talk / Besprechungen und Arbeitsalltag
 *
 * The words that run a meeting from the agenda to the minutes: what is on
 * the table (die Tagesordnung, der Zeitplan, das Budget, das Ziel), what
 * people do in the room (teilnehmen, leiten, unterbrechen, zusammenfassen,
 * sich einigen, entscheiden, vereinbaren) and what comes out of it (das
 * Ergebnis, die Entscheidung, das Protokoll).
 *
 * obwohl and trotzdem are here as words because they carry the lesson's
 * grammar step: the same idea, two completely different word orders.
 *
 * die Besprechung, der Kollege, die Aufgabe, die Frist, der Vorschlag and
 * vorschlagen are taught at A2 and reused here, not redefined.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── On the table ─────────────────────────────────────────────────────── */
  {
    id: 'v.b1.l19.tagesordnung',
    de: 'Tagesordnung',
    en: 'agenda',
    pos: 'noun',
    article: 'die',
    plural: 'die Tagesordnungen',
    example: 'Was steht heute auf der Tagesordnung?',
    exampleEn: 'What is on the agenda today?',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'Points on it are Tagesordnungspunkte, often shortened to TOP 1, TOP 2. Something is auf der Tagesordnung.',
  },
  {
    id: 'v.b1.l19.zeitplan',
    de: 'Zeitplan',
    en: 'schedule, timeline',
    pos: 'noun',
    article: 'der',
    plural: 'die Zeitpläne',
    example: 'Der Zeitplan ist sehr knapp, aber wir schaffen es.',
    exampleEn: 'The schedule is very tight, but we will manage it.',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'Like der Plan, the plural takes an Umlaut: die Zeitpläne. Im Zeitplan sein = to be on schedule.',
  },
  {
    id: 'v.b1.l19.budget',
    de: 'Budget',
    en: 'budget',
    pos: 'noun',
    article: 'das',
    plural: 'die Budgets',
    example: 'Das Budget für das Projekt ist leider zu klein.',
    exampleEn: 'Unfortunately the budget for the project is too small.',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'Pronounced the French way, with a silent t: [bʏˈdʒeː]. An English loanword plural: -s.',
  },
  {
    id: 'v.b1.l19.ziel',
    de: 'Ziel',
    en: 'goal, target',
    pos: 'noun',
    article: 'das',
    plural: 'die Ziele',
    example: 'Unser Ziel ist es, das Projekt bis Juni abzuschließen.',
    exampleEn: 'Our goal is to complete the project by June.',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'Also the finish line of a race. Ein Ziel erreichen = to reach a goal.',
  },

  /* ── In the room ──────────────────────────────────────────────────────── */
  {
    id: 'v.b1.l19.teilnehmer',
    de: 'Teilnehmer',
    en: 'participant',
    pos: 'noun',
    article: 'der',
    plural: 'die Teilnehmer',
    example: 'Alle Teilnehmer bekommen die Unterlagen per E-Mail.',
    exampleEn: 'All participants get the documents by e-mail.',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'A woman is die Teilnehmerin, several women die Teilnehmerinnen. Written for everyone: Teilnehmende.',
  },
  {
    id: 'v.b1.l19.teilnehmen',
    de: 'teilnehmen',
    en: 'to take part (in), to attend',
    pos: 'verb',
    example: 'Ich kann morgen leider nicht an der Besprechung teilnehmen.',
    exampleEn: 'Unfortunately I cannot attend the meeting tomorrow.',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    separable: true,
    note: 'Always an + dative: an einem Kurs teilnehmen. Built on nehmen, so the stem changes: du nimmst teil.',
    forms: {
      ich: 'nehme teil',
      du: 'nimmst teil',
      er: 'nimmt teil',
      wir: 'nehmen teil',
      ihr: 'nehmt teil',
      sie: 'nehmen teil',
    },
    perfect: 'hat teilgenommen',
    praeteritum: 'nahm teil',
  },
  {
    id: 'v.b1.l19.leiten',
    de: 'leiten',
    en: 'to lead, to chair, to manage',
    pos: 'verb',
    example: 'Frau Keller leitet heute die Besprechung.',
    exampleEn: 'Ms Keller is chairing the meeting today.',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    note: 'The person who leads is der Leiter / die Leiterin; the team lead is die Teamleiterin. The stem ends in -t, so du leitest, er leitet.',
    forms: {
      ich: 'leite',
      du: 'leitest',
      er: 'leitet',
      wir: 'leiten',
      ihr: 'leitet',
      sie: 'leiten',
    },
    perfect: 'hat geleitet',
    praeteritum: 'leitete',
  },
  {
    id: 'v.b1.l19.unterbrechen',
    de: 'unterbrechen',
    en: 'to interrupt',
    pos: 'verb',
    example: 'Darf ich Sie kurz unterbrechen?',
    exampleEn: 'May I interrupt you for a moment?',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    note: 'The stress is on -bre-, so unter- does not split off and there is no ge-: Er unterbricht mich. Er hat mich unterbrochen.',
    forms: {
      ich: 'unterbreche',
      du: 'unterbrichst',
      er: 'unterbricht',
      wir: 'unterbrechen',
      ihr: 'unterbrecht',
      sie: 'unterbrechen',
    },
    perfect: 'hat unterbrochen',
    praeteritum: 'unterbrach',
  },
  {
    id: 'v.b1.l19.zusammenfassen',
    de: 'zusammenfassen',
    en: 'to summarise',
    pos: 'verb',
    example: 'Können Sie die wichtigsten Punkte noch einmal zusammenfassen?',
    exampleEn: 'Can you summarise the most important points once more?',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    separable: true,
    note: 'The classic opener: Ich fasse kurz zusammen … The noun is die Zusammenfassung.',
    forms: {
      ich: 'fasse zusammen',
      du: 'fasst zusammen',
      er: 'fasst zusammen',
      wir: 'fassen zusammen',
      ihr: 'fasst zusammen',
      sie: 'fassen zusammen',
    },
    perfect: 'hat zusammengefasst',
    praeteritum: 'fasste zusammen',
  },
  {
    id: 'v.b1.l19.einigen',
    de: 'sich einigen',
    en: 'to agree (on), to come to an agreement',
    pos: 'verb',
    example: 'Nach einer langen Diskussion konnten sich die beiden Abteilungen einigen.',
    exampleEn: 'After a long discussion the two departments were able to agree.',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    note: 'What you agree on takes auf + accusative: sich auf einen Kompromiss einigen. Regular: hat sich geeinigt.',
    forms: {
      ich: 'einige mich',
      du: 'einigst dich',
      er: 'einigt sich',
      wir: 'einigen uns',
      ihr: 'einigt euch',
      sie: 'einigen sich',
    },
    perfect: 'hat sich geeinigt',
    praeteritum: 'einigte sich',
  },
  {
    id: 'v.b1.l19.einverstanden',
    de: 'einverstanden',
    en: 'in agreement, okay with something',
    pos: 'adj',
    example: 'Sind alle mit dem neuen Termin einverstanden?',
    exampleEn: 'Is everyone okay with the new date?',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'Always with sein and mit + dative: Ich bin mit dem Vorschlag einverstanden. On its own, Einverstanden! means "Agreed!".',
  },

  /* ── What comes out of it ─────────────────────────────────────────────── */
  {
    id: 'v.b1.l19.entscheiden',
    de: 'entscheiden',
    en: 'to decide',
    pos: 'verb',
    example: 'Wir müssen heute entscheiden, wer das Projekt leitet.',
    exampleEn: 'We have to decide today who will lead the project.',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    note: 'Irregular in the past: entschied, hat entschieden. Choosing between options is reflexive: sich für etwas entscheiden.',
    forms: {
      ich: 'entscheide',
      du: 'entscheidest',
      er: 'entscheidet',
      wir: 'entscheiden',
      ihr: 'entscheidet',
      sie: 'entscheiden',
    },
    perfect: 'hat entschieden',
    praeteritum: 'entschied',
  },
  {
    id: 'v.b1.l19.entscheidung',
    de: 'Entscheidung',
    en: 'decision',
    pos: 'noun',
    article: 'die',
    plural: 'die Entscheidungen',
    example: 'Die Entscheidung fällt erst nächste Woche.',
    exampleEn: 'The decision will only be made next week.',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'Germans say eine Entscheidung treffen (literally "meet a decision"), not "machen". The decision falls: die Entscheidung fällt.',
  },
  {
    id: 'v.b1.l19.vereinbaren',
    de: 'vereinbaren',
    en: 'to agree on, to arrange',
    pos: 'verb',
    example: 'Wir haben einen neuen Termin vereinbart.',
    exampleEn: 'We have arranged a new appointment.',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    note: 'ver- is inseparable, so no ge-: vereinbart. The formal way to make an appointment: einen Termin vereinbaren.',
    forms: {
      ich: 'vereinbare',
      du: 'vereinbarst',
      er: 'vereinbart',
      wir: 'vereinbaren',
      ihr: 'vereinbart',
      sie: 'vereinbaren',
    },
    perfect: 'hat vereinbart',
    praeteritum: 'vereinbarte',
  },
  {
    id: 'v.b1.l19.ergebnis',
    de: 'Ergebnis',
    en: 'result, outcome',
    pos: 'noun',
    article: 'das',
    plural: 'die Ergebnisse',
    example: 'Das Ergebnis der Umfrage war sehr positiv.',
    exampleEn: 'The result of the survey was very positive.',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'Words in -nis double the s in the plural: das Ergebnis → die Ergebnisse, das Erlebnis → die Erlebnisse.',
  },
  {
    id: 'v.b1.l19.protokoll',
    de: 'Protokoll',
    en: 'minutes (of a meeting), record',
    pos: 'noun',
    article: 'das',
    plural: 'die Protokolle',
    example: 'Wer schreibt heute das Protokoll?',
    exampleEn: 'Who is taking the minutes today?',
    level: 'B1',
    topic: 'work',
    difficulty: 1,
    note: 'Not "protocol" in the diplomatic sense — in an office das Protokoll is simply the written record of a meeting.',
  },

  /* ── The two connectors of the grammar step ───────────────────────────── */
  {
    id: 'v.b1.l19.obwohl',
    de: 'obwohl',
    en: 'although, even though',
    pos: 'conj',
    example: 'Wir fangen an, obwohl noch nicht alle da sind.',
    exampleEn: 'We are starting, although not everyone is here yet.',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    note: 'A subordinating conjunction like weil: the conjugated verb goes to the very end of the obwohl-clause.',
  },
  {
    id: 'v.b1.l19.trotzdem',
    de: 'trotzdem',
    en: 'nevertheless, anyway, still',
    pos: 'adv',
    example: 'Es regnet. Trotzdem fahre ich mit dem Fahrrad ins Büro.',
    exampleEn: 'It is raining. I am still cycling to the office.',
    level: 'B1',
    topic: 'work',
    difficulty: 2,
    note: 'An adverb, not a conjunction: it takes position 1 (Trotzdem fahre ich …) or sits after the verb (Ich fahre trotzdem …). Never verb-final.',
  },
]

export default vocab
