/**
 * B1 · L26 — Travel experiences and the future / Reiseerfahrungen und Zukunftspläne
 *
 * The B1 revision lesson. Its words are for telling travel stories and
 * dreaming about the next trip: places and experiences (das Ausland, die
 * Landschaft, die Sehenswürdigkeit, die Kultur, das Abenteuer, die
 * Rundreise, der Rucksack), what happens to you abroad (entdecken, sich
 * verständigen, sich gewöhnen an, vermissen) and how it felt (fremd,
 * beeindruckend, unvergesslich, spontan) — plus der Traum and träumen von
 * for the future.
 *
 * die Reise, der Urlaub, die Unterkunft, erleben and das Erlebnis are A2
 * words and are reused, not redefined.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const vocab = [
  /* ── Places and experiences ───────────────────────────────────────────── */
  {
    id: 'v.b1.l26.ausland',
    de: 'Ausland',
    en: 'abroad, foreign countries',
    pos: 'noun',
    article: 'das',
    plural: null,
    example: 'Nach dem Studium möchte ich ein Jahr im Ausland arbeiten.',
    exampleEn: 'After my studies I would like to work abroad for a year.',
    level: 'B1',
    topic: 'travel',
    difficulty: 1,
    note: 'im Ausland (being abroad, dative), ins Ausland (going abroad, accusative). Its opposite is das Inland.',
  },
  {
    id: 'v.b1.l26.abenteuer',
    de: 'Abenteuer',
    en: 'adventure',
    pos: 'noun',
    article: 'das',
    plural: 'die Abenteuer',
    example: 'Die Reise durch die Wüste war ein echtes Abenteuer.',
    exampleEn: 'The trip through the desert was a real adventure.',
    level: 'B1',
    topic: 'travel',
    difficulty: 2,
    note: 'Neuter despite ending in -er, and the plural looks the same: die Abenteuer.',
  },
  {
    id: 'v.b1.l26.sehenswuerdigkeit',
    de: 'Sehenswürdigkeit',
    en: 'sight, tourist attraction',
    pos: 'noun',
    article: 'die',
    plural: 'die Sehenswürdigkeiten',
    example: 'Der Kölner Dom ist die bekannteste Sehenswürdigkeit der Stadt.',
    exampleEn: 'Cologne Cathedral is the best-known sight in the city.',
    level: 'B1',
    topic: 'travel',
    difficulty: 2,
    note: 'Literally "something worth seeing" (sehenswert). Every noun in -keit is feminine.',
  },
  {
    id: 'v.b1.l26.landschaft',
    de: 'Landschaft',
    en: 'landscape, scenery',
    pos: 'noun',
    article: 'die',
    plural: 'die Landschaften',
    example: 'Die Landschaft in Norwegen ist wunderschön.',
    exampleEn: 'The scenery in Norway is beautiful.',
    level: 'B1',
    topic: 'nature',
    difficulty: 1,
    note: 'das Land + -schaft, and -schaft is always feminine: die Landschaft.',
  },
  {
    id: 'v.b1.l26.kultur',
    de: 'Kultur',
    en: 'culture',
    pos: 'noun',
    article: 'die',
    plural: 'die Kulturen',
    example: 'Ich interessiere mich sehr für die japanische Kultur.',
    exampleEn: 'I am very interested in Japanese culture.',
    level: 'B1',
    topic: 'travel',
    difficulty: 1,
    note: 'Nouns in -ur are feminine: die Kultur, die Natur, die Reparatur.',
  },
  {
    id: 'v.b1.l26.rundreise',
    de: 'Rundreise',
    en: 'round trip, tour',
    pos: 'noun',
    article: 'die',
    plural: 'die Rundreisen',
    example: 'Wir machen eine Rundreise durch Irland.',
    exampleEn: 'We are doing a tour of Ireland.',
    level: 'B1',
    topic: 'travel',
    difficulty: 2,
    note: 'A trip that visits several places and ends where it began. die Reise decides the gender.',
  },
  {
    id: 'v.b1.l26.rucksack',
    de: 'Rucksack',
    en: 'backpack, rucksack',
    pos: 'noun',
    article: 'der',
    plural: 'die Rucksäcke',
    example: 'Mit einem kleinen Rucksack reist man viel leichter.',
    exampleEn: 'You travel much more easily with a small backpack.',
    level: 'B1',
    topic: 'travel',
    difficulty: 1,
    note: 'English borrowed it from German. der Sack is masculine, plural with an Umlaut: die Rucksäcke.',
  },
  {
    id: 'v.b1.l26.traum',
    de: 'Traum',
    en: 'dream',
    pos: 'noun',
    article: 'der',
    plural: 'die Träume',
    example: 'Mein großer Traum ist eine Reise nach Island.',
    exampleEn: 'My big dream is a trip to Iceland.',
    level: 'B1',
    topic: 'emotions',
    difficulty: 1,
    note: 'Both the night dream and the wish. A dream holiday is der Traumurlaub.',
  },

  /* ── What happens to you ──────────────────────────────────────────────── */
  {
    id: 'v.b1.l26.traeumen',
    de: 'träumen',
    en: 'to dream',
    pos: 'verb',
    example: 'Ich träume schon lange von einer Weltreise.',
    exampleEn: 'I have been dreaming of a trip round the world for a long time.',
    level: 'B1',
    topic: 'emotions',
    difficulty: 2,
    note: 'Always von + dative: von einer Reise träumen. Regular: hat geträumt.',
    forms: {
      ich: 'träume',
      du: 'träumst',
      er: 'träumt',
      wir: 'träumen',
      ihr: 'träumt',
      sie: 'träumen',
    },
    perfect: 'hat geträumt',
    praeteritum: 'träumte',
  },
  {
    id: 'v.b1.l26.entdecken',
    de: 'entdecken',
    en: 'to discover',
    pos: 'verb',
    example: 'Am liebsten entdecke ich eine Stadt zu Fuß.',
    exampleEn: 'I like discovering a city on foot best.',
    level: 'B1',
    topic: 'travel',
    difficulty: 2,
    note: 'ent- + decken (to cover): to uncover. Inseparable: hat entdeckt. The noun is die Entdeckung.',
    forms: {
      ich: 'entdecke',
      du: 'entdeckst',
      er: 'entdeckt',
      wir: 'entdecken',
      ihr: 'entdeckt',
      sie: 'entdecken',
    },
    perfect: 'hat entdeckt',
    praeteritum: 'entdeckte',
  },
  {
    id: 'v.b1.l26.verstaendigen',
    de: 'sich verständigen',
    en: 'to make yourself understood, to communicate',
    pos: 'verb',
    example: 'In Japan konnten sie sich nur mit Händen und Füßen verständigen.',
    exampleEn: 'In Japan they could only communicate with gestures.',
    level: 'B1',
    topic: 'travel',
    difficulty: 3,
    note: 'mit Händen und Füßen = with hands and feet, i.e. with gestures. In a language: sich auf Englisch verständigen.',
    forms: {
      ich: 'verständige mich',
      du: 'verständigst dich',
      er: 'verständigt sich',
      wir: 'verständigen uns',
      ihr: 'verständigt euch',
      sie: 'verständigen sich',
    },
    perfect: 'hat sich verständigt',
    praeteritum: 'verständigte sich',
  },
  {
    id: 'v.b1.l26.gewoehnen',
    de: 'sich gewöhnen',
    en: 'to get used (to)',
    pos: 'verb',
    example: 'Nach ein paar Wochen hatte sie sich an das kalte Wetter gewöhnt.',
    exampleEn: 'After a few weeks she had got used to the cold weather.',
    level: 'B1',
    topic: 'travel',
    difficulty: 2,
    note: 'Always an + accusative: sich an etwas gewöhnen. With a whole clause: Ich habe mich daran gewöhnt, früh aufzustehen.',
    forms: {
      ich: 'gewöhne mich',
      du: 'gewöhnst dich',
      er: 'gewöhnt sich',
      wir: 'gewöhnen uns',
      ihr: 'gewöhnt euch',
      sie: 'gewöhnen sich',
    },
    perfect: 'hat sich gewöhnt',
    praeteritum: 'gewöhnte sich',
  },
  {
    id: 'v.b1.l26.vermissen',
    de: 'vermissen',
    en: 'to miss (someone or something)',
    pos: 'verb',
    example: 'Im Ausland vermisse ich am meisten das deutsche Brot.',
    exampleEn: 'Abroad, what I miss most is German bread.',
    level: 'B1',
    topic: 'emotions',
    difficulty: 2,
    note: 'Direct object, unlike English "miss": Ich vermisse dich. Missing a train is verpassen, not vermissen.',
    forms: {
      ich: 'vermisse',
      du: 'vermisst',
      er: 'vermisst',
      wir: 'vermissen',
      ihr: 'vermisst',
      sie: 'vermissen',
    },
    perfect: 'hat vermisst',
    praeteritum: 'vermisste',
  },

  /* ── How it felt ──────────────────────────────────────────────────────── */
  {
    id: 'v.b1.l26.fremd',
    de: 'fremd',
    en: 'foreign, strange, unfamiliar',
    pos: 'adj',
    example: 'Am Anfang war mir alles fremd.',
    exampleEn: 'At first everything was unfamiliar to me.',
    level: 'B1',
    topic: 'travel',
    difficulty: 2,
    note: 'Ich bin hier fremd = I am a stranger here. A foreign language is eine Fremdsprache.',
  },
  {
    id: 'v.b1.l26.beeindruckend',
    de: 'beeindruckend',
    en: 'impressive',
    pos: 'adj',
    example: 'Die Aussicht vom Berg war wirklich beeindruckend.',
    exampleEn: 'The view from the mountain was really impressive.',
    level: 'B1',
    topic: 'travel',
    difficulty: 2,
    note: 'From beeindrucken, to impress — the present participle (-end) used as an adjective, like spannend.',
  },
  {
    id: 'v.b1.l26.unvergesslich',
    de: 'unvergesslich',
    en: 'unforgettable',
    pos: 'adj',
    example: 'Der Abend am Strand war unvergesslich.',
    exampleEn: 'The evening on the beach was unforgettable.',
    level: 'B1',
    topic: 'travel',
    difficulty: 2,
    note: 'un- + vergessen + -lich: "not forgettable". In front of a noun it needs an ending: ein unvergessliches Erlebnis.',
  },
  {
    id: 'v.b1.l26.spontan',
    de: 'spontan',
    en: 'spontaneous(ly)',
    pos: 'adj',
    example: 'Wir sind ganz spontan ans Meer gefahren.',
    exampleEn: 'We went to the seaside completely on the spur of the moment.',
    level: 'B1',
    topic: 'travel',
    difficulty: 1,
    note: 'Works as an adverb too, with no ending: spontan entscheiden. Opposite: geplant.',
  },
]

export default vocab
