/**
 * A1 — pronouns and the first two cases.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const grammar = [
  /* ─────────────────────────────────────────────────────────────────────────
   * g.a1.pronomen — Personal pronouns
   * ───────────────────────────────────────────────────────────────────────── */
  {
    id: 'g.a1.pronomen',
    level: 'A1',
    title: 'Personal pronouns',
    titleDe: 'Personalpronomen',
    short: 'ich, du, er, sie — and the three different words German has for "you".',
    tags: ['pronomen', 'nominativ'],
    skill: 'grammar',
    difficulty: 1,
    explain: [
      {
        kind: 'text',
        text: 'One word for I, three for you: **du** to a friend, **ihr** to a group of friends, **Sie** to anyone you call by their surname. In an office, start with **Sie**.',
      },
      {
        kind: 'table',
        head: ['German', 'English'],
        rows: [
          ['ich', 'I'],
          ['du', 'you (one friend)'],
          ['er / sie / es', 'he / she / it'],
          ['wir', 'we'],
          ['ihr', 'you (a group)'],
          ['sie', 'they'],
          ['Sie', 'you (polite)'],
        ],
      },
      {
        kind: 'tip',
        text: 'Things take the gender of their article: **der** Tisch → *er*, **die** Lampe → *sie*, **das** Auto → *es*. Small `sie` is she or they; capital **Sie** is the polite you.',
      },
    ],
    examples: [
      { de: 'Er arbeitet bei Siemens.', en: 'He works at Siemens.' },
      {
        de: 'Wie heißen Sie, bitte?',
        en: 'What is your name, please?',
        note: 'Polite Sie — at the doctor, the bank or the town hall.',
      },
      {
        de: 'Wo ist die Milch? — Sie ist im Kühlschrank.',
        en: 'Where is the milk? — It is in the fridge.',
        note: 'die Milch → sie. German says "she", not "it".',
      },
      { de: 'Wir kommen um acht.', en: 'We are coming at eight.' },
    ],
    pitfalls: [
      {
        wrong: 'Wo ist der Bus? Es kommt gleich.',
        right: 'Wo ist der Bus? Er kommt gleich.',
        why: 'der Bus is masculine, so it comes back as er. German does not use es just because something is an object.',
      },
      {
        wrong: 'Wie heißt du, Frau Weber?',
        right: 'Wie heißen Sie, Frau Weber?',
        why: 'Herr or Frau + surname means you are in the Sie world. du to a stranger sounds rude.',
      },
      {
        wrong: 'Kinder, wo bist du?',
        right: 'Kinder, wo seid ihr?',
        why: 'More than one person you would say du to = ihr. du is only ever one person.',
      },
    ],
    exerciseIds: [
      'x.g.a1.pronomen.1',
      'x.g.a1.pronomen.2',
      'x.g.a1.pronomen.3',
      'x.g.a1.pronomen.4',
      'x.g.a1.pronomen.5',
      'x.g.a1.pronomen.6',
      'x.g.a1.pronomen.7',
      'x.g.a1.pronomen.8',
      'x.g.a1.pronomen.9',
    ],
    exercises: [
      {
        id: 'x.g.a1.pronomen.1',
        kind: 'blank',
        sentence: 'Das ist Herr Meier. ___ arbeitet im Büro.',
        options: ['Er', 'Sie', 'Es', 'Wir'],
        answer: 'Er',
        skill: 'grammar',
        difficulty: 1,
        tags: ['pronomen'],
        explain: 'Herr Meier is one man, so he comes back as er. The verb ending -t confirms a single third person.',
      },
      {
        id: 'x.g.a1.pronomen.2',
        kind: 'blank',
        sentence: 'Wo ist die Milch? ___ ist im Kühlschrank.',
        options: ['Sie', 'Er', 'Es', 'Ihr'],
        answer: 'Sie',
        skill: 'grammar',
        difficulty: 1,
        tags: ['pronomen'],
        hint: 'Look at the article of the noun, not at the English word.',
        explain: 'die Milch is feminine, so it becomes sie. A German thing is he, she or it depending on its article.',
      },
      {
        id: 'x.g.a1.pronomen.3',
        kind: 'conjugate',
        verb: 'wohnen',
        person: 'wir',
        answer: 'wohnen',
        skill: 'verbs',
        difficulty: 1,
        tags: ['pronomen'],
        explain: 'wir always takes the plain -en form, which looks exactly like the infinitive. So does sie (they) and Sie (polite you).',
      },
      {
        id: 'x.g.a1.pronomen.4',
        kind: 'mcq',
        prompt: 'You are talking to your new manager, Frau Bergmann. How do you ask where she is from?',
        options: ['Woher kommen Sie?', 'Woher kommst du?', 'Woher kommt ihr?'],
        answer: 0,
        skill: 'grammar',
        difficulty: 2,
        tags: ['pronomen', 'hoeflichkeit'],
        explain: 'A surname and a work relationship mean Sie, and the Sie-form of a verb always looks like the infinitive: kommen.',
      },
      {
        id: 'x.g.a1.pronomen.5',
        kind: 'order',
        tokens: ['wir', 'arbeiten', 'heute', 'zu', 'Hause'],
        answer: 'Wir arbeiten heute zu Hause.',
        accept: ['Heute arbeiten wir zu Hause.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['pronomen'],
        explain: 'The verb stays in position 2. If a time word takes first place, the pronoun wir simply moves behind the verb.',
      },
      {
        id: 'x.g.a1.pronomen.6',
        kind: 'correct',
        wrong: 'Frau Weber, wo wohnst du?',
        answer: 'Frau Weber, wo wohnen Sie?',
        skill: 'grammar',
        difficulty: 2,
        tags: ['pronomen', 'hoeflichkeit'],
        explain: 'Frau + surname signals the polite Sie, and Sie takes the -en form of the verb, never the du-form -st.',
      },
      {
        id: 'x.g.a1.pronomen.7',
        kind: 'dialogue',
        lines: [
          { who: 'Tom', text: 'Hallo, ich bin Tom. Und ihr?' },
          { who: 'Lisa', text: '___' },
        ],
        options: ['Wir heißen Lisa und Ben.', 'Ich heiße Lisa und Ben.', 'Sie heißen Lisa und Ben.'],
        answer: 0,
        skill: 'conversation',
        difficulty: 2,
        tags: ['pronomen'],
        explain: 'ihr asks two or more people, so the answer comes back as wir — wir is simply the plural of ich.',
      },
      {
        id: 'x.g.a1.pronomen.8',
        kind: 'mcq',
        prompt: 'Choose the correct sentence.',
        options: [
          'Meine Eltern? Sie wohnen in Bremen.',
          'Meine Eltern? Er wohnt in Bremen.',
          'Meine Eltern? Es wohnt in Bremen.',
        ],
        answer: 0,
        skill: 'grammar',
        difficulty: 3,
        tags: ['pronomen'],
        explain: 'Every plural noun becomes sie with the -en verb form, whatever gender the singular happens to have.',
      },
      {
        id: 'x.g.a1.pronomen.9',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'They work in Berlin and she works in Hamburg.',
        answer: 'Sie arbeiten in Berlin und sie arbeitet in Hamburg.',
        accept: ['Sie arbeiten in Berlin, und sie arbeitet in Hamburg.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['pronomen'],
        hint: 'The same word twice — the verb ending does the work.',
        explain: 'sie is both they and she. The verb ending tells you which: arbeiten = they, arbeitet = she.',
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────────────────────
   * g.a1.nominativ — The nominative case
   * ───────────────────────────────────────────────────────────────────────── */
  {
    id: 'g.a1.nominativ',
    level: 'A1',
    title: 'The nominative case',
    titleDe: 'Der Nominativ',
    short: 'The subject of the sentence — who or what is doing something.',
    tags: ['nominativ'],
    skill: 'cases',
    difficulty: 1,
    explain: [
      {
        kind: 'text',
        text: 'The nominative answers **wer?** (who) or **was?** (what) — the person or thing doing something. It is the form every dictionary gives you.',
      },
      {
        kind: 'table',
        head: ['Article', 'masculine', 'feminine', 'neuter', 'plural'],
        rows: [
          ['definite', 'der Chef', 'die Chefin', 'das Büro', 'die Kollegen'],
          ['indefinite', 'ein Chef', 'eine Chefin', 'ein Büro', 'Kollegen'],
        ],
      },
      {
        kind: 'tip',
        text: '**sein** and **heißen** are an equals sign, not an action — the words on both sides stay nominative: *Das ist **mein** Chef.*',
      },
    ],
    examples: [
      {
        de: 'Der Zug kommt um zehn.',
        en: 'The train arrives at ten.',
        note: 'Wer oder was kommt? → der Zug. That is your nominative.',
      },
      { de: 'Die Ärztin heißt Frau Kunz.', en: 'The doctor is called Frau Kunz.' },
      {
        de: 'Das ist mein Kollege.',
        en: 'This is my colleague.',
        note: 'Both das and mein Kollege stand around ist, so both are nominative.',
      },
      { de: 'Meine Eltern wohnen in Köln.', en: 'My parents live in Cologne.' },
    ],
    pitfalls: [
      {
        wrong: 'Das ist meinen Chef.',
        right: 'Das ist mein Chef.',
        why: 'Nothing is being done to the boss here. ist links two nominatives, so there is no accusative -en.',
      },
      {
        wrong: 'Die Kaffee ist kalt.',
        right: 'Der Kaffee ist kalt.',
        why: 'Kaffee is masculine. A noun ending almost never tells you the gender, so always store the article with the word.',
      },
    ],
    exerciseIds: [
      'x.g.a1.nominativ.1',
      'x.g.a1.nominativ.2',
      'x.g.a1.nominativ.3',
      'x.g.a1.nominativ.4',
      'x.g.a1.nominativ.5',
      'x.g.a1.nominativ.6',
      'x.g.a1.nominativ.7',
      'x.g.a1.nominativ.8',
      'x.g.a1.nominativ.9',
    ],
    exercises: [
      {
        id: 'x.g.a1.nominativ.1',
        kind: 'blank',
        sentence: '___ Bahnhof ist nicht weit.',
        options: ['Der', 'Die', 'Das', 'Den'],
        answer: 'Der',
        skill: 'cases',
        difficulty: 1,
        tags: ['nominativ'],
        explain: 'Bahnhof is masculine and it is the subject — wer oder was ist nicht weit? — so it takes der, never den.',
      },
      {
        id: 'x.g.a1.nominativ.2',
        kind: 'article',
        noun: 'Rechnung',
        answer: 'die',
        plural: 'die Rechnungen',
        meaning: 'bill, invoice',
        skill: 'articles',
        difficulty: 1,
        tags: ['nominativ', 'artikel'],
        explain: 'Nouns ending in -ung are always feminine, so it is die Rechnung — one of the few endings you can fully trust.',
      },
      {
        id: 'x.g.a1.nominativ.3',
        kind: 'dialogue',
        lines: [
          { who: 'Kollegin', text: 'Wer ist der Mann da vorne?' },
          { who: 'Sie', text: '___' },
        ],
        options: ['Das ist mein Chef.', 'Das ist meinen Chef.', 'Das ist meinem Chef.'],
        answer: 0,
        skill: 'cases',
        difficulty: 1,
        tags: ['nominativ'],
        explain: 'ist works like an equals sign, so the word after it keeps its plain nominative form: mein Chef.',
      },
      {
        id: 'x.g.a1.nominativ.4',
        kind: 'mcq',
        prompt: 'Which part is the subject (nominative) in: "Heute kauft meine Mutter das Brot."?',
        options: ['meine Mutter', 'das Brot', 'heute'],
        answer: 0,
        skill: 'cases',
        difficulty: 2,
        tags: ['nominativ'],
        explain: 'Ask wer kauft? — meine Mutter does the buying, so she is the nominative. das Brot is what gets bought.',
      },
      {
        id: 'x.g.a1.nominativ.5',
        kind: 'blank',
        sentence: '___ Kinder spielen im Garten.',
        options: ['Die', 'Der', 'Das', 'Den'],
        answer: 'Die',
        skill: 'cases',
        difficulty: 2,
        tags: ['nominativ'],
        explain: 'All plurals take die in the nominative, whatever gender the singular has: der Sohn, die Tochter → die Kinder.',
      },
      {
        id: 'x.g.a1.nominativ.6',
        kind: 'correct',
        wrong: 'Herr Klein ist meinen Nachbarn.',
        answer: 'Herr Klein ist mein Nachbar.',
        skill: 'cases',
        difficulty: 2,
        tags: ['nominativ'],
        explain: 'ist joins two nominatives, so no ending is added: mein Nachbar, not meinen Nachbarn.',
      },
      {
        id: 'x.g.a1.nominativ.7',
        kind: 'order',
        tokens: ['der', 'Chef', 'kommt', 'heute', 'später'],
        answer: 'Der Chef kommt heute später.',
        accept: ['Heute kommt der Chef später.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['nominativ'],
        explain: 'der Chef is the subject in the nominative. Whether it stands first or behind the verb, the article stays der.',
      },
      {
        id: 'x.g.a1.nominativ.8',
        kind: 'mcq',
        prompt: 'Choose the correct sentence.',
        options: [
          'Der Termin und die Adresse stehen im Brief.',
          'Den Termin und die Adresse stehen im Brief.',
          'Der Termin und der Adresse stehen im Brief.',
        ],
        answer: 0,
        skill: 'cases',
        difficulty: 3,
        tags: ['nominativ'],
        explain: 'Both nouns are subjects of stehen, so both stay nominative — and two subjects together take the plural verb.',
      },
      {
        id: 'x.g.a1.nominativ.9',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'This is my sister. She is a doctor.',
        answer: 'Das ist meine Schwester. Sie ist Ärztin.',
        accept: ['Das ist meine Schwester. Sie ist Ärztin!'],
        skill: 'writing',
        difficulty: 3,
        tags: ['nominativ'],
        hint: 'German uses no article in front of a job.',
        explain: 'Both sides of ist are nominative, and with jobs German drops the article: Sie ist Ärztin, not eine Ärztin.',
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────────────────────
   * g.a1.akkusativ — The accusative case
   * ───────────────────────────────────────────────────────────────────────── */
  {
    id: 'g.a1.akkusativ',
    level: 'A1',
    title: 'The accusative case',
    titleDe: 'Der Akkusativ',
    short: 'Only one word really changes: der becomes den.',
    tags: ['akkusativ'],
    skill: 'cases',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'The accusative marks the thing the verb does something to: *Ich kaufe **den** Kaffee.* The good news — only the masculine changes. Feminine, neuter and plural look exactly like the nominative.',
      },
      {
        kind: 'table',
        head: ['Gender', 'nominative', 'accusative'],
        rows: [
          ['masculine', 'der / ein Apfel', '**den / einen** Apfel'],
          ['feminine', 'die / eine Rechnung', 'die / eine Rechnung'],
          ['neuter', 'das / ein Brot', 'das / ein Brot'],
          ['plural', 'die Äpfel', 'die Äpfel'],
        ],
      },
      {
        kind: 'tip',
        text: 'Ask **wen oder was?** after the verb: *Ich brauche — was? — **einen** Termin.* Everyday accusative verbs: haben, brauchen, kaufen, nehmen, essen, trinken, suchen, möchten.',
      },
    ],
    examples: [
      {
        de: 'Ich nehme den Salat und einen Apfelsaft.',
        en: 'I will take the salad and an apple juice.',
        note: 'der Salat → den Salat, ein Apfelsaft → einen Apfelsaft.',
      },
      { de: 'Ich brauche einen Termin.', en: 'I need an appointment.' },
      {
        de: 'Hast du das Rezept?',
        en: 'Do you have the prescription?',
        note: 'das stays das — neuter never changes.',
      },
      { de: 'Sie sucht die Bushaltestelle.', en: 'She is looking for the bus stop.' },
    ],
    pitfalls: [
      {
        wrong: 'Ich trinke der Kaffee.',
        right: 'Ich trinke den Kaffee.',
        why: 'The coffee is what gets drunk, so it is accusative — and masculine der is the one article that becomes den.',
      },
      {
        wrong: 'Ich habe einen Frage.',
        right: 'Ich habe eine Frage.',
        why: 'Frage is feminine. Feminine never changes in the accusative, so eine stays eine — do not spread -en around.',
      },
      {
        wrong: 'Hier gibt es ein Supermarkt.',
        right: 'Hier gibt es einen Supermarkt.',
        why: 'es gibt always takes an accusative object, so a masculine ein has to become einen.',
      },
    ],
    exerciseIds: [
      'x.g.a1.akkusativ.1',
      'x.g.a1.akkusativ.2',
      'x.g.a1.akkusativ.3',
      'x.g.a1.akkusativ.4',
      'x.g.a1.akkusativ.5',
      'x.g.a1.akkusativ.6',
      'x.g.a1.akkusativ.7',
      'x.g.a1.akkusativ.8',
      'x.g.a1.akkusativ.9',
    ],
    exercises: [
      {
        id: 'x.g.a1.akkusativ.1',
        kind: 'blank',
        sentence: 'Ich möchte ___ Kaffee, bitte.',
        options: ['einen', 'ein', 'eine', 'einem'],
        answer: 'einen',
        skill: 'cases',
        difficulty: 1,
        tags: ['akkusativ'],
        explain: 'der Kaffee is masculine and it is what you want, so ein becomes einen — the one ending the accusative really adds.',
      },
      {
        id: 'x.g.a1.akkusativ.2',
        kind: 'blank',
        sentence: 'Wir kaufen ___ Brot beim Bäcker.',
        options: ['das', 'den', 'dem', 'der'],
        answer: 'das',
        skill: 'cases',
        difficulty: 1,
        tags: ['akkusativ'],
        explain: 'das Brot is neuter, and neuter looks identical in the accusative. Only the masculine ever changes shape.',
      },
      {
        id: 'x.g.a1.akkusativ.3',
        kind: 'article',
        noun: 'Termin',
        answer: 'der',
        plural: 'die Termine',
        meaning: 'appointment',
        skill: 'articles',
        difficulty: 1,
        tags: ['akkusativ', 'artikel'],
        explain: 'Termin is masculine — which is exactly why it turns into den Termin / einen Termin when you need one.',
      },
      {
        id: 'x.g.a1.akkusativ.4',
        kind: 'mcq',
        prompt: 'Choose the correct sentence.',
        options: ['Ich suche den Ausgang.', 'Ich suche der Ausgang.', 'Ich suche dem Ausgang.'],
        answer: 0,
        skill: 'cases',
        difficulty: 2,
        tags: ['akkusativ'],
        explain: 'suchen takes an accusative object, and masculine der Ausgang becomes den Ausgang.',
      },
      {
        id: 'x.g.a1.akkusativ.5',
        kind: 'correct',
        wrong: 'Ich brauche ein Kugelschreiber.',
        answer: 'Ich brauche einen Kugelschreiber.',
        skill: 'cases',
        difficulty: 2,
        tags: ['akkusativ'],
        explain: 'brauchen takes the accusative and Kugelschreiber is masculine, so ein gains -en.',
      },
      {
        id: 'x.g.a1.akkusativ.6',
        kind: 'order',
        tokens: ['ich', 'nehme', 'den', 'Bus', 'um', 'acht'],
        answer: 'Ich nehme den Bus um acht.',
        accept: ['Um acht nehme ich den Bus.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['akkusativ'],
        explain: 'den Bus is the accusative object. Its form never depends on its position — only on the verb in front of it.',
      },
      {
        id: 'x.g.a1.akkusativ.7',
        kind: 'dialogue',
        lines: [
          { who: 'Kellner', text: 'Was möchten Sie trinken?' },
          { who: 'Gast', text: '___' },
        ],
        options: ['Einen Apfelsaft, bitte.', 'Ein Apfelsaft, bitte.', 'Einem Apfelsaft, bitte.'],
        answer: 0,
        skill: 'conversation',
        difficulty: 2,
        tags: ['akkusativ'],
        explain: 'The full sentence is "Ich möchte einen Apfelsaft" — the object keeps its accusative form even when you shorten the answer.',
      },
      {
        id: 'x.g.a1.akkusativ.8',
        kind: 'blank',
        sentence: 'Ich rufe ___ heute Abend an.',
        options: ['dich', 'du', 'dir', 'dein'],
        answer: 'dich',
        skill: 'cases',
        difficulty: 3,
        tags: ['akkusativ', 'pronomen'],
        hint: 'Who is being called? That person is the object.',
        explain: 'anrufen takes an accusative object, and pronouns change too: du becomes dich, ich becomes mich.',
      },
      {
        id: 'x.g.a1.akkusativ.9',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'We are taking the train and I need a ticket.',
        answer: 'Wir nehmen den Zug und ich brauche eine Fahrkarte.',
        accept: ['Wir nehmen den Zug, und ich brauche eine Fahrkarte.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['akkusativ'],
        explain: 'Both nouns are objects, but only the masculine reacts: der Zug → den Zug, while feminine eine Fahrkarte stays as it is.',
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────────────────────
   * g.a1.possessiv — mein, dein, sein
   * ───────────────────────────────────────────────────────────────────────── */
  {
    id: 'g.a1.possessiv',
    level: 'A1',
    title: 'mein, dein, sein — possessive articles',
    titleDe: 'Possessivartikel',
    short: 'They behave exactly like ein — the ending follows the thing owned, not the owner.',
    tags: ['possessiv'],
    skill: 'grammar',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'Possessive articles copy **ein** exactly: *ein Bruder → **mein** Bruder*, *eine Schwester → **meine** Schwester*. The ending follows the thing owned, never the owner.',
      },
      {
        kind: 'table',
        head: ['Owner', 'Possessive', 'Example'],
        rows: [
          ['ich', 'mein', 'mein Auto'],
          ['du', 'dein', 'dein Auto'],
          ['er / es', 'sein', 'sein Auto'],
          ['sie (she)', 'ihr', 'ihr Auto'],
          ['wir', 'unser', 'unser Auto'],
          ['ihr', 'euer', 'euer Auto'],
          ['sie / Sie', 'ihr / Ihr', 'ihr Auto / Ihr Auto'],
        ],
      },
      {
        kind: 'warn',
        text: 'Feminine and plural add **-e**: *meine Frau*, *meine Kinder* (and *euer* → *eure*). In the accusative only the masculine changes: *Ich suche **meinen** Schlüssel.*',
      },
    ],
    examples: [
      { de: 'Das ist mein Chef, Herr Adler.', en: 'This is my boss, Mr Adler.' },
      {
        de: 'Wo ist deine Fahrkarte?',
        en: 'Where is your ticket?',
        note: 'die Fahrkarte is feminine → deine.',
      },
      {
        de: 'Ihr Mann heißt Paul.',
        en: 'Her husband is called Paul.',
        note: 'ihr = her (the owner), no ending because der Mann is masculine.',
      },
      {
        de: 'Ich suche meinen Schlüssel.',
        en: 'I am looking for my key.',
        note: 'der Schlüssel is the object here → meinen.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Das ist meine Bruder.',
        right: 'Das ist mein Bruder.',
        why: 'The ending copies the noun, not the speaker. der Bruder is masculine nominative, so mein has no ending — even if a woman is speaking.',
      },
      {
        wrong: 'Anna sucht sein Handy.',
        right: 'Anna sucht ihr Handy.',
        why: 'sein = his, ihr = her. The word itself is chosen by the owner, and Anna is female.',
      },
      {
        wrong: 'Ich brauche mein Kugelschreiber.',
        right: 'Ich brauche meinen Kugelschreiber.',
        why: 'brauchen takes the accusative, and masculine is the only gender that changes there: mein → meinen.',
      },
    ],
    exerciseIds: [
      'x.g.a1.possessiv.1',
      'x.g.a1.possessiv.2',
      'x.g.a1.possessiv.3',
      'x.g.a1.possessiv.4',
      'x.g.a1.possessiv.5',
      'x.g.a1.possessiv.6',
      'x.g.a1.possessiv.7',
      'x.g.a1.possessiv.8',
      'x.g.a1.possessiv.9',
    ],
    exercises: [
      {
        id: 'x.g.a1.possessiv.1',
        kind: 'blank',
        sentence: 'Das ist ___ Schwester. Sie heißt Nina.',
        options: ['meine', 'mein', 'meinen', 'meiner'],
        answer: 'meine',
        skill: 'grammar',
        difficulty: 1,
        tags: ['possessiv'],
        explain: 'die Schwester is feminine, so mein takes -e — exactly like eine Schwester.',
      },
      {
        id: 'x.g.a1.possessiv.2',
        kind: 'blank',
        sentence: 'Ist das ___ Handy?',
        options: ['dein', 'deine', 'deinen', 'deinem'],
        answer: 'dein',
        skill: 'grammar',
        difficulty: 1,
        tags: ['possessiv'],
        explain: 'das Handy is neuter, so dein takes no ending at all — it copies ein Handy.',
      },
      {
        id: 'x.g.a1.possessiv.3',
        kind: 'mcq',
        prompt: 'Frau Berger has a son. Which sentence is correct?',
        options: [
          'Ihr Sohn studiert in Leipzig.',
          'Sein Sohn studiert in Leipzig.',
          'Ihre Sohn studiert in Leipzig.',
        ],
        answer: 0,
        skill: 'grammar',
        difficulty: 2,
        tags: ['possessiv'],
        explain: 'The owner is female → ihr. der Sohn is masculine nominative → no ending. Two separate decisions, both needed.',
      },
      {
        id: 'x.g.a1.possessiv.4',
        kind: 'blank',
        sentence: 'Herr Ott ist krank. ___ Frau ruft im Büro an.',
        options: ['Seine', 'Sein', 'Ihre', 'Ihr'],
        answer: 'Seine',
        skill: 'grammar',
        difficulty: 2,
        tags: ['possessiv'],
        hint: 'First choose the word, then the ending.',
        explain: 'Pick sein because the owner is Herr Ott, then add -e because die Frau is feminine.',
      },
      {
        id: 'x.g.a1.possessiv.5',
        kind: 'correct',
        wrong: 'Ich suche mein Schlüssel.',
        answer: 'Ich suche meinen Schlüssel.',
        skill: 'grammar',
        difficulty: 2,
        tags: ['possessiv', 'akkusativ'],
        explain: 'suchen takes the accusative and der Schlüssel is masculine — the one place a possessive really changes shape.',
      },
      {
        id: 'x.g.a1.possessiv.6',
        kind: 'order',
        tokens: ['ich', 'suche', 'schon', 'wieder', 'meine', 'Brille'],
        answer: 'Ich suche schon wieder meine Brille.',
        accept: ['Ich suche meine Brille schon wieder.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['possessiv'],
        explain: 'die Brille is feminine, so meine looks the same in the accusative as in the nominative — nothing to change.',
      },
      {
        id: 'x.g.a1.possessiv.7',
        kind: 'dialogue',
        lines: [
          { who: 'Rezeptionistin', text: 'Entschuldigung, ist das Ihre Tasche?' },
          { who: 'Sie', text: '___' },
        ],
        options: [
          'Nein, das ist nicht meine Tasche.',
          'Nein, das ist nicht mein Tasche.',
          'Nein, das ist nicht meiner Tasche.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 2,
        tags: ['possessiv'],
        explain: 'die Tasche is feminine, so meine keeps its -e. Ihre with a capital I is the polite your, matching Sie.',
      },
      {
        id: 'x.g.a1.possessiv.8',
        kind: 'mcq',
        prompt: 'Choose the correct sentence.',
        options: ['Wo sind eure Kinder?', 'Wo sind euer Kinder?', 'Wo sind euren Kinder?'],
        answer: 0,
        skill: 'grammar',
        difficulty: 3,
        tags: ['possessiv'],
        explain: 'Plural always adds -e, and euer drops its second e as soon as an ending arrives: euer → eure.',
      },
      {
        id: 'x.g.a1.possessiv.9',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'Her husband works in Munich and his sister lives in Bonn.',
        answer: 'Ihr Mann arbeitet in München und seine Schwester wohnt in Bonn.',
        accept: ['Ihr Mann arbeitet in München, und seine Schwester wohnt in Bonn.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['possessiv'],
        hint: 'Owner picks the word, noun picks the ending.',
        explain: 'The owner chooses ihr or sein, the noun chooses the ending: der Mann → ihr, die Schwester → seine.',
      },
    ],
  },
]

export default grammar
