/**
 * A1 grammar — modal verbs, separable verbs, everyday prepositions and polite requests.
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const grammar = [
  /* ──────────────────────────────────────────────────────────────────────
   * g.a1.modalverben
   * ────────────────────────────────────────────────────────────────────── */
  {
    id: 'g.a1.modalverben',
    level: 'A1',
    title: 'Modal verbs: können, möchten, müssen',
    titleDe: 'Modalverben: können, möchten, müssen',
    short: 'Say what you can, would like and have to do — the modal is conjugated, the real verb waits at the end.',
    tags: ['modalverben'],
    skill: 'verbs',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'A modal verb says *how* you relate to an action: **können** = can, **möchten** = would like, **müssen** = have to. The modal takes position 2 and the real verb goes to the **end** as an infinitive.',
      },
      {
        kind: 'table',
        head: ['', 'können', 'möchten', 'müssen'],
        rows: [
          ['ich', 'kann', 'möchte', 'muss'],
          ['du', 'kannst', 'möchtest', 'musst'],
          ['er / sie / es', 'kann', 'möchte', 'muss'],
          ['wir', 'können', 'möchten', 'müssen'],
          ['ihr', 'könnt', 'möchtet', 'müsst'],
          ['sie / Sie', 'können', 'möchten', 'müssen'],
        ],
      },
      {
        kind: 'tip',
        text: 'The **ich** and **er** forms are identical and take no ending: ich kann, er kann. That surprises everyone once, then never again.',
      },
    ],
    examples: [
      {
        de: 'Ich kann am Montag leider nicht kommen.',
        en: 'Unfortunately I cannot come on Monday.',
        note: 'kommen is the last word — nicht stands in front of it.',
      },
      {
        de: 'Möchtest du einen Kaffee?',
        en: 'Would you like a coffee?',
        note: 'möchten can also take just a noun, with no second verb.',
      },
      {
        de: 'Wir müssen um acht Uhr im Büro sein.',
        en: 'We have to be in the office at eight.',
      },
      {
        de: 'Können Sie das bitte wiederholen?',
        en: 'Can you repeat that, please?',
        note: 'In a question the modal verb moves to the front.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Ich kann kommen nicht.',
        right: 'Ich kann nicht kommen.',
        why: 'The infinitive is always the very last word, so nicht has to stand in front of it.',
      },
      {
        wrong: 'Ich muss zu arbeiten.',
        right: 'Ich muss arbeiten.',
        why: 'After a modal verb the second verb is a bare infinitive — German never puts zu there.',
      },
      {
        wrong: 'Er kannt gut Deutsch sprechen.',
        right: 'Er kann gut Deutsch sprechen.',
        why: 'Modal verbs take no ending for ich and er/sie/es: ich kann, er kann, sie muss.',
      },
    ],
    exerciseIds: [
      'x.g.a1.modalverben.1',
      'x.g.a1.modalverben.2',
      'x.g.a1.modalverben.3',
      'x.g.a1.modalverben.4',
      'x.g.a1.modalverben.5',
      'x.g.a1.modalverben.6',
      'x.g.a1.modalverben.7',
      'x.g.a1.modalverben.8',
      'x.g.a1.modalverben.9',
    ],
    exercises: [
      {
        id: 'x.g.a1.modalverben.1',
        kind: 'conjugate',
        verb: 'können',
        person: 'du',
        answer: 'kannst',
        skill: 'verbs',
        difficulty: 1,
        tags: ['modalverben'],
        explain: 'In the singular können loses its umlaut (kann-), and du adds the normal -st ending: du kannst.',
      },
      {
        id: 'x.g.a1.modalverben.2',
        kind: 'blank',
        sentence: 'Ich ___ heute leider nicht kommen.',
        options: ['kann', 'kannst', 'können', 'könnt'],
        answer: 'kann',
        skill: 'verbs',
        difficulty: 1,
        tags: ['modalverben'],
        explain: 'ich takes the bare stem with no ending at all: ich kann, ich muss, ich möchte.',
      },
      {
        id: 'x.g.a1.modalverben.3',
        kind: 'order',
        tokens: ['wir', 'müssen', 'heute', 'lange', 'arbeiten'],
        answer: 'Wir müssen heute lange arbeiten.',
        accept: ['Heute müssen wir lange arbeiten.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['modalverben'],
        explain: 'The modal verb holds position 2 and the infinitive closes the sentence — everything else sits in between.',
      },
      {
        id: 'x.g.a1.modalverben.4',
        kind: 'mcq',
        prompt: 'You are booking an appointment. Which sentence is correct?',
        options: [
          'Ich möchte einen Termin machen.',
          'Ich möchte machen einen Termin.',
          'Ich möchte einen Termin zu machen.',
        ],
        answer: 0,
        skill: 'grammar',
        difficulty: 2,
        tags: ['modalverben'],
        explain: 'The infinitive machen has to be the last word, and after a modal verb it never takes zu.',
      },
      {
        id: 'x.g.a1.modalverben.5',
        kind: 'correct',
        wrong: 'Sie muss gehen zum Arzt.',
        answer: 'Sie muss zum Arzt gehen.',
        skill: 'wordorder',
        difficulty: 2,
        tags: ['modalverben'],
        explain: 'Nothing may follow the infinitive. The place zum Arzt moves in front of gehen.',
      },
      {
        id: 'x.g.a1.modalverben.6',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'Can you repeat that, please?',
        answer: 'Können Sie das bitte wiederholen?',
        accept: ['Kannst du das bitte wiederholen?'],
        skill: 'writing',
        difficulty: 2,
        tags: ['modalverben'],
        explain: 'In a yes/no question the modal verb comes first, and the infinitive still closes the sentence.',
      },
      {
        id: 'x.g.a1.modalverben.7',
        kind: 'dialogue',
        lines: [
          { who: 'Kellner', text: 'Was möchten Sie trinken?' },
          { who: 'Sie', text: '___' },
        ],
        options: ['Einen Apfelsaft, bitte.', 'Ich möchte trinken.', 'Ja, ich kann.'],
        answer: 0,
        skill: 'conversation',
        difficulty: 2,
        tags: ['modalverben'],
        explain: 'You answer a möchten question with the thing itself: der Apfelsaft becomes einen Apfelsaft as the object.',
      },
      {
        id: 'x.g.a1.modalverben.8',
        kind: 'blank',
        sentence: 'Wir ___ am Samstag nicht arbeiten.',
        options: ['müssen', 'muss', 'müsst', 'musst'],
        answer: 'müssen',
        skill: 'verbs',
        difficulty: 2,
        tags: ['modalverben'],
        explain: 'wir always takes the -en form, which looks exactly like the infinitive: wir müssen, wir können.',
      },
      {
        id: 'x.g.a1.modalverben.9',
        kind: 'order',
        tokens: ['am', 'Wochenende', 'möchte', 'ich', 'lange', 'schlafen'],
        answer: 'Am Wochenende möchte ich lange schlafen.',
        accept: ['Ich möchte am Wochenende lange schlafen.'],
        skill: 'wordorder',
        difficulty: 3,
        hint: 'Start with the time phrase.',
        tags: ['modalverben'],
        explain: 'If a time phrase opens the sentence, the modal verb still stays in position 2 and the subject slides in behind it.',
      },
    ],
  },

  /* ──────────────────────────────────────────────────────────────────────
   * g.a1.trennbar
   * ────────────────────────────────────────────────────────────────────── */
  {
    id: 'g.a1.trennbar',
    level: 'A1',
    title: 'Separable verbs',
    titleDe: 'Trennbare Verben',
    short: 'Verbs like aufstehen break in two: the verb is conjugated, the little prefix jumps to the end.',
    tags: ['trennbar'],
    skill: 'verbs',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'Many everyday verbs start with a small prefix: **auf**stehen, **an**rufen, **ein**kaufen, **mit**kommen. In a sentence the prefix breaks off and jumps to the **end**. The stress tells you which verbs do it: **AUF**stehen splits, be**SU**chen does not.',
      },
      {
        kind: 'table',
        head: ['Verb', 'Meaning', 'In a sentence'],
        rows: [
          ['aufstehen', 'to get up', 'Ich stehe um sechs Uhr auf.'],
          ['anrufen', 'to call (phone)', 'Ich rufe dich später an.'],
          ['einkaufen', 'to do the shopping', 'Wir kaufen am Samstag ein.'],
          ['mitkommen', 'to come along', 'Kommst du mit?'],
          ['anfangen', 'to start', 'Der Kurs fängt um neun an.'],
        ],
      },
      {
        kind: 'warn',
        text: 'Next to a modal verb the verb stays in one piece: *Ich muss um sechs Uhr aufstehen.*',
      },
    ],
    examples: [
      {
        de: 'Der Supermarkt macht um acht Uhr auf.',
        en: 'The supermarket opens at eight.',
        note: 'aufmachen = to open. The prefix is the final word.',
      },
      {
        de: 'Ich rufe dich heute Abend an.',
        en: 'I will call you this evening.',
        note: 'German uses the present tense for the near future.',
      },
      {
        de: 'Kommst du am Freitag mit?',
        en: 'Are you coming along on Friday?',
      },
      {
        de: 'Am Sonntag räume ich die Wohnung auf.',
        en: 'On Sunday I tidy up the flat.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Ich aufstehe um sechs Uhr.',
        right: 'Ich stehe um sechs Uhr auf.',
        why: 'The prefix never stays glued to the conjugated verb — it travels to the end of the sentence.',
      },
      {
        wrong: 'Ich stehe auf um sechs Uhr.',
        right: 'Ich stehe um sechs Uhr auf.',
        why: 'The prefix is the last word, so time and place have to squeeze in before it.',
      },
      {
        wrong: 'Ich muss früh aufstehe.',
        right: 'Ich muss früh aufstehen.',
        why: 'With a modal verb the separable verb is not split at all — it sits at the end as a whole infinitive.',
      },
    ],
    exerciseIds: [
      'x.g.a1.trennbar.1',
      'x.g.a1.trennbar.2',
      'x.g.a1.trennbar.3',
      'x.g.a1.trennbar.4',
      'x.g.a1.trennbar.5',
      'x.g.a1.trennbar.6',
      'x.g.a1.trennbar.7',
      'x.g.a1.trennbar.8',
      'x.g.a1.trennbar.9',
    ],
    exercises: [
      {
        id: 'x.g.a1.trennbar.1',
        kind: 'blank',
        sentence: 'Ich stehe um sieben Uhr ___.',
        options: ['auf', 'an', 'ein', 'mit'],
        answer: 'auf',
        skill: 'verbs',
        difficulty: 1,
        tags: ['trennbar'],
        explain: 'The verb is aufstehen, so the prefix auf splits off and becomes the last word.',
      },
      {
        id: 'x.g.a1.trennbar.2',
        kind: 'conjugate',
        verb: 'anrufen',
        person: 'du',
        answer: 'rufst an',
        skill: 'verbs',
        difficulty: 1,
        hint: 'Two pieces: the conjugated verb and the prefix.',
        explain: 'anrufen splits into rufst … an. You conjugate the rufen part and park an at the end.',
      },
      {
        id: 'x.g.a1.trennbar.3',
        kind: 'order',
        tokens: ['der', 'Film', 'fängt', 'um', 'acht', 'Uhr', 'an'],
        answer: 'Der Film fängt um acht Uhr an.',
        skill: 'wordorder',
        difficulty: 2,
        tags: ['trennbar'],
        explain: 'The conjugated verb stays in position 2 and the prefix an closes the sentence — the time goes in between.',
      },
      {
        id: 'x.g.a1.trennbar.4',
        kind: 'correct',
        wrong: 'Wir einkaufen am Samstag.',
        answer: 'Wir kaufen am Samstag ein.',
        skill: 'verbs',
        difficulty: 2,
        tags: ['trennbar'],
        explain: 'You cannot conjugate the whole word. kaufen takes position 2 and the prefix ein goes to the end.',
      },
      {
        id: 'x.g.a1.trennbar.5',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: [
          'Ich muss heute meinen Chef anrufen.',
          'Ich muss heute meinen Chef an rufen.',
          'Ich muss heute meinen Chef anrufe.',
        ],
        answer: 0,
        skill: 'grammar',
        difficulty: 2,
        tags: ['trennbar', 'modalverben'],
        explain: 'Next to a modal verb the separable verb stays whole and in the infinitive: anrufen, written as one word.',
      },
      {
        id: 'x.g.a1.trennbar.6',
        kind: 'dialogue',
        lines: [
          { who: 'Anna', text: 'Wir gehen heute ins Kino. ___ du mit?' },
          { who: 'Sie', text: 'Ja, gern!' },
        ],
        options: ['Kommst', 'Kommen', 'Mitkommst'],
        answer: 0,
        skill: 'conversation',
        difficulty: 2,
        tags: ['trennbar'],
        explain: 'In a yes/no question the conjugated verb comes first — but the prefix mit still waits at the end.',
      },
      {
        id: 'x.g.a1.trennbar.7',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'When does the shop open?',
        answer: 'Wann macht der Laden auf?',
        accept: ['Wann macht das Geschäft auf?'],
        skill: 'writing',
        difficulty: 2,
        tags: ['trennbar'],
        explain: 'aufmachen splits even in questions: the question word is first, the verb second, the prefix auf last.',
      },
      {
        id: 'x.g.a1.trennbar.8',
        kind: 'order',
        tokens: ['am', 'Sonntag', 'räume', 'ich', 'die', 'Wohnung', 'auf'],
        answer: 'Am Sonntag räume ich die Wohnung auf.',
        accept: ['Ich räume am Sonntag die Wohnung auf.'],
        skill: 'wordorder',
        difficulty: 3,
        tags: ['trennbar'],
        explain: 'Verb and prefix form a frame: the conjugated verb keeps position 2, the prefix auf shuts the frame at the very end.',
      },
      {
        id: 'x.g.a1.trennbar.9',
        kind: 'correct',
        wrong: 'Fängt der Deutschkurs wann an?',
        answer: 'Wann fängt der Deutschkurs an?',
        skill: 'wordorder',
        difficulty: 3,
        tags: ['trennbar'],
        explain: 'A question word always opens the sentence; the verb follows in position 2 and the prefix an still ends it.',
      },
    ],
  },

  /* ──────────────────────────────────────────────────────────────────────
   * g.a1.praepositionen
   * ────────────────────────────────────────────────────────────────────── */
  {
    id: 'g.a1.praepositionen',
    level: 'A1',
    title: 'Everyday prepositions (in, nach, zu, mit, aus)',
    titleDe: 'Präpositionen im Alltag',
    short: 'Which little word takes you where: nach Berlin, zum Arzt, in die Stadt, mit dem Bus, aus Indien.',
    tags: ['praeposition'],
    skill: 'prepositions',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'German chooses the preposition by the *kind* of place. Learn each one as a fixed chunk — the little word after it belongs to the chunk.',
      },
      {
        kind: 'table',
        head: ['Word', 'Use it for', 'Example'],
        rows: [
          ['nach', 'cities and most countries', 'Ich fahre nach Hamburg.'],
          ['in', 'going into a place', 'Ich gehe in die Stadt.'],
          ['zu', 'people, shops, institutions', 'Ich gehe zum Arzt.'],
          ['mit', 'transport and company', 'Ich fahre mit dem Bus.'],
          ['aus', 'where you come from', 'Ich komme aus Indien.'],
        ],
      },
      {
        kind: 'tip',
        text: 'Two chunks carry you through the whole day: **zum** = zu dem (der/das words) and **zur** = zu der (die words). zum Bahnhof, zum Büro, zur Arbeit, zur Apotheke.',
      },
    ],
    examples: [
      {
        de: 'Im August fahren wir nach Österreich.',
        en: 'In August we are going to Austria.',
        note: 'nach for countries that have no article.',
      },
      {
        de: 'Ich muss um zehn zum Zahnarzt.',
        en: 'I have to go to the dentist at ten.',
        note: 'With zu you can even leave gehen out — everyone understands.',
      },
      {
        de: 'Kommst du mit dem Auto oder mit der Bahn?',
        en: 'Are you coming by car or by train?',
      },
      {
        de: 'Meine Kollegin kommt aus der Türkei.',
        en: 'My colleague is from Turkey.',
        note: 'Countries that keep an article: aus der Türkei, aus der Schweiz, aus den USA.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Ich gehe nach dem Arzt.',
        right: 'Ich gehe zum Arzt.',
        why: 'nach is for places on a map. People and institutions always take zu.',
      },
      {
        wrong: 'Ich fahre mit das Auto.',
        right: 'Ich fahre mit dem Auto.',
        why: 'mit is followed by dem or der, never by das or die: mit dem Bus, mit der Bahn, mit dem Fahrrad.',
      },
      {
        wrong: 'Ich komme von Indien.',
        right: 'Ich komme aus Indien.',
        why: 'Your home country takes aus. von is only a starting point you have just left, like von der Arbeit.',
      },
    ],
    exerciseIds: [
      'x.g.a1.praepositionen.1',
      'x.g.a1.praepositionen.2',
      'x.g.a1.praepositionen.3',
      'x.g.a1.praepositionen.4',
      'x.g.a1.praepositionen.5',
      'x.g.a1.praepositionen.6',
      'x.g.a1.praepositionen.7',
      'x.g.a1.praepositionen.8',
      'x.g.a1.praepositionen.9',
    ],
    exercises: [
      {
        id: 'x.g.a1.praepositionen.1',
        kind: 'blank',
        sentence: 'Ich komme ___ Indien.',
        options: ['aus', 'nach', 'zu', 'mit'],
        answer: 'aus',
        skill: 'prepositions',
        difficulty: 1,
        tags: ['praeposition'],
        explain: 'The country you come from always takes aus: aus Indien, aus Polen, aus Deutschland.',
      },
      {
        id: 'x.g.a1.praepositionen.2',
        kind: 'blank',
        sentence: 'Am Freitag fahre ich ___ Berlin.',
        options: ['nach', 'zu', 'in', 'aus'],
        answer: 'nach',
        skill: 'prepositions',
        difficulty: 1,
        tags: ['praeposition'],
        explain: 'Cities and countries without an article take nach: nach Berlin, nach Italien, nach Hause.',
      },
      {
        id: 'x.g.a1.praepositionen.3',
        kind: 'mcq',
        prompt: 'You have an appointment with your doctor. What do you say?',
        options: ['Ich gehe zum Arzt.', 'Ich gehe nach Arzt.', 'Ich gehe in Arzt.'],
        answer: 0,
        skill: 'prepositions',
        difficulty: 2,
        tags: ['praeposition'],
        explain: 'People and institutions take zu, and zu dem is always shortened to zum: zum Arzt, zum Chef.',
      },
      {
        id: 'x.g.a1.praepositionen.4',
        kind: 'blank',
        sentence: 'Wir fahren ___ dem Bus zur Arbeit.',
        options: ['mit', 'aus', 'nach', 'in'],
        answer: 'mit',
        skill: 'prepositions',
        difficulty: 2,
        tags: ['praeposition'],
        explain: 'Means of transport take mit: mit dem Bus, mit der Bahn, mit dem Fahrrad. Only zu Fuß has no mit.',
      },
      {
        id: 'x.g.a1.praepositionen.5',
        kind: 'order',
        tokens: ['ich', 'gehe', 'heute', 'in', 'die', 'Stadt'],
        answer: 'Ich gehe heute in die Stadt.',
        accept: ['Heute gehe ich in die Stadt.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['praeposition'],
        explain: 'in die Stadt is one fixed chunk and stays together at the end; the verb keeps position 2.',
      },
      {
        id: 'x.g.a1.praepositionen.6',
        kind: 'correct',
        wrong: 'Er fährt mit das Fahrrad ins Büro.',
        answer: 'Er fährt mit dem Fahrrad ins Büro.',
        skill: 'prepositions',
        difficulty: 2,
        tags: ['praeposition'],
        explain: 'After mit, der- and das-words both become dem: das Fahrrad becomes mit dem Fahrrad.',
      },
      {
        id: 'x.g.a1.praepositionen.7',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'I have to go to the pharmacy.',
        answer: 'Ich muss zur Apotheke.',
        accept: ['Ich muss zur Apotheke gehen.'],
        skill: 'writing',
        difficulty: 2,
        tags: ['praeposition'],
        explain: 'die Apotheke is a die-word, so zu der shortens to zur. With zu the verb gehen may simply be left out.',
      },
      {
        id: 'x.g.a1.praepositionen.8',
        kind: 'dialogue',
        lines: [
          { who: 'Kollege', text: 'Wohin fährst du im Urlaub?' },
          { who: 'Sie', text: '___' },
        ],
        options: ['Nach Spanien.', 'In Spanien.', 'Zu Spanien.'],
        answer: 0,
        skill: 'prepositions',
        difficulty: 3,
        tags: ['praeposition'],
        explain: 'Wohin? asks for a destination, and countries take nach. In Spanien answers Wo? — where you already are.',
      },
      {
        id: 'x.g.a1.praepositionen.9',
        kind: 'order',
        tokens: ['am', 'Montag', 'fahre', 'ich', 'mit', 'dem', 'Zug', 'nach', 'München'],
        answer: 'Am Montag fahre ich mit dem Zug nach München.',
        accept: ['Ich fahre am Montag mit dem Zug nach München.'],
        skill: 'wordorder',
        difficulty: 3,
        hint: 'Time, then how, then where.',
        tags: ['praeposition'],
        explain: 'German orders the extras as time – manner – place: am Montag, then mit dem Zug, then nach München.',
      },
    ],
  },

  /* ──────────────────────────────────────────────────────────────────────
   * g.a1.imperativ-basis
   * ────────────────────────────────────────────────────────────────────── */
  {
    id: 'g.a1.imperativ-basis',
    level: 'A1',
    title: 'Simple commands and polite requests',
    titleDe: 'Höfliche Bitten',
    short: 'Nehmen Sie bitte Platz — put the verb first, keep Sie, add bitte. That is the whole trick.',
    tags: ['hoeflichkeit'],
    skill: 'grammar',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'To ask politely with **Sie**, take the normal sentence and move the verb to the front: *Sie nehmen Platz* becomes **Nehmen Sie Platz.** Add **bitte** and you have perfect German for shops, offices and the doctor.',
      },
      {
        kind: 'table',
        head: ['Statement', 'Polite request'],
        rows: [
          ['Sie gehen geradeaus.', 'Gehen Sie bitte geradeaus.'],
          ['Sie warten hier.', 'Warten Sie bitte hier.'],
          ['Sie kommen herein.', 'Kommen Sie herein!'],
          ['Sie sprechen langsam.', 'Sprechen Sie bitte langsam.'],
        ],
      },
      {
        kind: 'tip',
        text: 'Softest of all is a question: **Können Sie das bitte wiederholen?** Asking always sounds friendlier than telling.',
      },
    ],
    examples: [
      {
        de: 'Nehmen Sie bitte Platz.',
        en: 'Please take a seat.',
        note: 'What you hear in every waiting room in Germany.',
      },
      {
        de: 'Gehen Sie geradeaus und dann links.',
        en: 'Go straight on and then left.',
      },
      {
        de: 'Warten Sie bitte einen Moment.',
        en: 'Please wait a moment.',
      },
      {
        de: 'Können Sie das bitte buchstabieren?',
        en: 'Can you spell that, please?',
        note: 'Gold on the phone and at any counter.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Nehmen bitte Platz.',
        right: 'Nehmen Sie bitte Platz.',
        why: 'The polite form always keeps Sie directly after the verb. Without Sie the sentence is simply not German.',
      },
      {
        wrong: 'Sie gehen geradeaus, bitte.',
        right: 'Gehen Sie bitte geradeaus.',
        why: 'Verb in position 2 is a statement; verb in position 1 is a request. Moving the verb is what makes it a request.',
      },
      {
        wrong: 'Bitte Sie warten hier.',
        right: 'Warten Sie bitte hier.',
        why: 'Nothing may come between the verb and Sie. Bitte warten Sie hier is fine too — bitte just cannot stand in the middle.',
      },
    ],
    exerciseIds: [
      'x.g.a1.imperativ-basis.1',
      'x.g.a1.imperativ-basis.2',
      'x.g.a1.imperativ-basis.3',
      'x.g.a1.imperativ-basis.4',
      'x.g.a1.imperativ-basis.5',
      'x.g.a1.imperativ-basis.6',
      'x.g.a1.imperativ-basis.7',
      'x.g.a1.imperativ-basis.8',
      'x.g.a1.imperativ-basis.9',
    ],
    exercises: [
      {
        id: 'x.g.a1.imperativ-basis.1',
        kind: 'mcq',
        prompt: 'The receptionist wants you to sit down. What does she say?',
        options: ['Nehmen Sie bitte Platz.', 'Sie nehmen bitte Platz.', 'Bitte Platz Sie nehmen.'],
        answer: 0,
        skill: 'grammar',
        difficulty: 1,
        tags: ['hoeflichkeit'],
        explain: 'A polite request starts with the verb and keeps Sie right behind it; bitte comes after those two.',
      },
      {
        id: 'x.g.a1.imperativ-basis.2',
        kind: 'blank',
        sentence: '___ Sie bitte langsam!',
        options: ['Sprechen', 'Sprichst', 'Sprecht', 'Spricht'],
        answer: 'Sprechen',
        skill: 'grammar',
        difficulty: 1,
        tags: ['hoeflichkeit'],
        explain: 'The Sie-request uses the plain -en form, exactly like the infinitive: sprechen, gehen, warten.',
      },
      {
        id: 'x.g.a1.imperativ-basis.3',
        kind: 'order',
        tokens: ['gehen', 'Sie', 'bitte', 'geradeaus'],
        answer: 'Gehen Sie bitte geradeaus.',
        accept: ['Bitte gehen Sie geradeaus.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['hoeflichkeit'],
        explain: 'Verb first, then Sie. bitte may also open the sentence, but it must never split Sie from its verb.',
      },
      {
        id: 'x.g.a1.imperativ-basis.4',
        kind: 'correct',
        wrong: 'Warten bitte Sie hier.',
        answer: 'Warten Sie bitte hier.',
        skill: 'wordorder',
        difficulty: 2,
        tags: ['hoeflichkeit'],
        explain: 'Sie belongs immediately after the verb — the pair is fixed, and bitte follows behind it.',
      },
      {
        id: 'x.g.a1.imperativ-basis.5',
        kind: 'dialogue',
        lines: [
          { who: 'Arzthelferin', text: 'Guten Tag! ___' },
          { who: 'Patient', text: 'Danke schön.' },
        ],
        options: ['Nehmen Sie bitte Platz.', 'Bitte Sie nehmen Platz.', 'Platz nehmen Sie bitte.'],
        answer: 0,
        skill: 'conversation',
        difficulty: 2,
        tags: ['hoeflichkeit'],
        explain: 'Strangers address you with Sie, and the request keeps its fixed shape: verb, Sie, bitte, rest.',
      },
      {
        id: 'x.g.a1.imperativ-basis.6',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'Please come in.',
        answer: 'Kommen Sie bitte herein.',
        accept: ['Bitte kommen Sie herein.'],
        skill: 'writing',
        difficulty: 2,
        tags: ['hoeflichkeit'],
        explain: 'hereinkommen is separable, so the prefix herein waits at the end while kommen takes first position.',
      },
      {
        id: 'x.g.a1.imperativ-basis.7',
        kind: 'speak',
        prompt: 'Ask politely: "Can you spell that, please?"',
        answer: 'Können Sie das bitte buchstabieren?',
        skill: 'conversation',
        difficulty: 2,
        tags: ['hoeflichkeit'],
        explain: 'A Können Sie …? question is the friendliest request of all, and the second verb still closes the sentence.',
      },
      {
        id: 'x.g.a1.imperativ-basis.8',
        kind: 'order',
        tokens: ['fahren', 'Sie', 'bitte', 'mit', 'dem', 'Bus'],
        answer: 'Fahren Sie bitte mit dem Bus.',
        accept: ['Bitte fahren Sie mit dem Bus.'],
        skill: 'wordorder',
        difficulty: 3,
        tags: ['hoeflichkeit'],
        explain: 'mit dem Bus is one chunk and stays together at the end; the verb keeps position 1 with Sie behind it.',
      },
      {
        id: 'x.g.a1.imperativ-basis.9',
        kind: 'correct',
        wrong: 'Können Sie bitte wiederholen das?',
        answer: 'Können Sie das bitte wiederholen?',
        skill: 'wordorder',
        difficulty: 3,
        tags: ['hoeflichkeit'],
        explain: 'With können the second verb must be the last word, so das and bitte both move in front of wiederholen.',
      },
    ],
  },
]

export default grammar
