/**
 * A1 — the four verb topics every beginner needs first.
 *
 *   g.a1.sein            sein — to be
 *   g.a1.haben           haben — to have
 *   g.a1.praesens        regular verbs in the present tense
 *   g.a1.unregelmaessig  stem-changing verbs
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const grammar = [
  /* ── 1. sein ──────────────────────────────────────────────────────────── */
  {
    id: 'g.a1.sein',
    level: 'A1',
    title: 'sein — to be',
    titleDe: 'Das Verb sein',
    short: 'The most important verb in German. It is irregular — learn the six forms by heart.',
    tags: ['verbs', 'praesens'],
    skill: 'verbs',
    difficulty: 1,
    explain: [
      {
        kind: 'text',
        text: '**sein** means *to be*. It is completely irregular, so learn the six forms by heart — you will use them in every single conversation.',
      },
      {
        kind: 'table',
        head: ['Person', 'sein', 'Beispiel'],
        rows: [
          ['ich', 'bin', 'Ich bin neu hier.'],
          ['du', 'bist', 'Du bist sehr nett.'],
          ['er / sie / es', 'ist', 'Sie ist Ärztin.'],
          ['wir', 'sind', 'Wir sind im Büro.'],
          ['ihr', 'seid', 'Ihr seid zu spät.'],
          ['sie / Sie', 'sind', 'Sind Sie Frau Klein?'],
        ],
      },
      {
        kind: 'tip',
        text: '**ihr seid** is the form everyone forgets. It ends in **-d**; the word *seit* with a **-t** means *since*.',
      },
      {
        kind: 'warn',
        text: 'Age and jobs use **sein**, not *haben*, and jobs take no article: *Ich bin 30* and *Ich bin Ingenieurin*.',
      },
    ],
    examples: [
      { de: 'Ich bin neu hier im Büro.', en: 'I am new here in the office.' },
      {
        de: 'Wo bist du? Ich bin schon im Supermarkt.',
        en: 'Where are you? I am already at the supermarket.',
      },
      { de: 'Herr Weber ist heute krank.', en: 'Mr Weber is ill today.' },
      {
        de: 'Guten Tag, sind Sie Frau Klein?',
        en: 'Hello, are you Ms Klein?',
        note: 'Formal Sie always takes sind — the same form as wir and sie (they).',
      },
    ],
    pitfalls: [
      {
        wrong: 'Ich habe 30 Jahre.',
        right: 'Ich bin 30 Jahre alt.',
        why: 'German states age with sein, never with haben: Ich bin 30 (Jahre alt).',
      },
      {
        wrong: 'Ihr seit im Deutschkurs.',
        right: 'Ihr seid im Deutschkurs.',
        why: 'The verb form is seid with -d. seit with -t is the little word for "since".',
      },
      {
        wrong: 'Sie ist eine Lehrerin.',
        right: 'Sie ist Lehrerin.',
        why: 'After sein, jobs and nationalities stand alone with no article: Er ist Inder, Sie ist Lehrerin.',
      },
    ],
    exerciseIds: [
      'x.g.a1.sein.1',
      'x.g.a1.sein.2',
      'x.g.a1.sein.3',
      'x.g.a1.sein.4',
      'x.g.a1.sein.5',
      'x.g.a1.sein.6',
      'x.g.a1.sein.7',
      'x.g.a1.sein.8',
    ],
    exercises: [
      {
        id: 'x.g.a1.sein.1',
        kind: 'conjugate',
        verb: 'sein',
        person: 'du',
        answer: 'bist',
        skill: 'verbs',
        difficulty: 1,
        tags: ['praesens'],
        explain: 'sein has its own forms — you cannot build them from the infinitive. The du form is bist.',
      },
      {
        id: 'x.g.a1.sein.2',
        kind: 'blank',
        sentence: 'Wir ___ heute im Büro.',
        options: ['sind', 'seid', 'ist', 'bin'],
        answer: 'sind',
        skill: 'verbs',
        difficulty: 1,
        tags: ['praesens'],
        explain: 'wir, sie (they) and formal Sie all share one form: sind. Learn those three together.',
      },
      {
        id: 'x.g.a1.sein.3',
        kind: 'blank',
        sentence: 'Ihr ___ sehr freundlich.',
        options: ['seid', 'seit', 'sind', 'bist'],
        answer: 'seid',
        skill: 'verbs',
        difficulty: 2,
        tags: ['praesens'],
        hint: 'Verb or preposition? Listen to the last letter.',
        explain: 'The ihr form is seid, written with -d. seit with -t is not a verb at all — it means "since".',
      },
      {
        id: 'x.g.a1.sein.4',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: ['Ich bin 32 Jahre alt.', 'Ich habe 32 Jahre.', 'Ich habe 32 Jahre alt.'],
        answer: 0,
        skill: 'verbs',
        difficulty: 2,
        tags: ['praesens'],
        explain: 'Age is expressed with sein in German: Ich bin 32. haben is for things you own, not for years.',
      },
      {
        id: 'x.g.a1.sein.5',
        kind: 'order',
        tokens: ['Frau', 'Meier', 'ist', 'heute', 'nicht', 'im', 'Büro'],
        answer: 'Frau Meier ist heute nicht im Büro.',
        accept: ['Heute ist Frau Meier nicht im Büro.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['wortstellung'],
        explain: 'Whatever you put first, the conjugated verb ist is the second element of the sentence.',
      },
      {
        id: 'x.g.a1.sein.6',
        kind: 'correct',
        wrong: 'Sie ist eine Ärztin.',
        answer: 'Sie ist Ärztin.',
        skill: 'grammar',
        difficulty: 2,
        tags: ['praesens'],
        explain: 'Professions after sein take no article, so you drop ein/eine: Sie ist Ärztin, Er ist Student.',
      },
      {
        id: 'x.g.a1.sein.7',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'We are new here and the colleagues are very nice.',
        answer: 'Wir sind neu hier und die Kollegen sind sehr nett.',
        accept: ['Wir sind hier neu und die Kollegen sind sehr nett.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['praesens'],
        hint: 'Two subjects, so two verbs.',
        explain: 'und simply joins two full sentences — each half keeps its own subject and its own form of sein.',
      },
      {
        id: 'x.g.a1.sein.8',
        kind: 'dialogue',
        lines: [
          { who: 'Empfang', text: 'Guten Tag! Sind Sie Frau Klein?' },
          { who: 'Sie', text: '___' },
        ],
        options: ['Ja, das bin ich.', 'Ja, das ist ich.', 'Ja, ich habe Frau Klein.'],
        answer: 0,
        skill: 'conversation',
        difficulty: 3,
        tags: ['praesens'],
        explain: 'To confirm who you are, Germans say "Ja, das bin ich." The verb agrees with ich, so it is bin.',
      },
    ],
  },

  /* ── 2. haben ─────────────────────────────────────────────────────────── */
  {
    id: 'g.a1.haben',
    level: 'A1',
    title: 'haben — to have',
    titleDe: 'Das Verb haben',
    short: 'Your second essential verb — and the du and er forms quietly lose the b.',
    tags: ['verbs', 'praesens'],
    skill: 'verbs',
    difficulty: 1,
    explain: [
      {
        kind: 'text',
        text: '**haben** is regular except for two forms: *du* and *er/sie/es* drop the **b** — *du hast*, *er hat*.',
      },
      {
        kind: 'table',
        head: ['Person', 'haben', 'Beispiel'],
        rows: [
          ['ich', 'habe', 'Ich habe Zeit.'],
          ['du', 'hast', 'Hast du Hunger?'],
          ['er / sie / es', 'hat', 'Er hat einen Termin.'],
          ['wir', 'haben', 'Wir haben Urlaub.'],
          ['ihr', 'habt', 'Habt ihr Kinder?'],
          ['sie / Sie', 'haben', 'Haben Sie Kleingeld?'],
        ],
      },
      {
        kind: 'tip',
        text: 'Many everyday states are *had* in German: **Hunger haben**, **Durst haben**, **Zeit haben**, **Angst haben**.',
      },
      {
        kind: 'warn',
        text: 'Negate the noun after *haben* with **kein-**, not *nicht*: *Ich habe keine Zeit*, *Ich habe kein Geld*.',
      },
    ],
    examples: [
      {
        de: 'Ich habe morgen einen Termin beim Arzt.',
        en: 'I have an appointment at the doctor tomorrow.',
        note: 'What you have goes in the accusative: einen Termin.',
      },
      { de: 'Hast du heute Abend Zeit?', en: 'Do you have time this evening?' },
      { de: 'Wir haben eine Wohnung in Köln.', en: 'We have a flat in Cologne.' },
      { de: 'Entschuldigung, haben Sie Kleingeld?', en: 'Excuse me, do you have any change?' },
    ],
    pitfalls: [
      {
        wrong: 'Du habst einen Termin.',
        right: 'Du hast einen Termin.',
        why: 'du and er/sie/es lose the -b- of the stem: du hast, er hat. There is no form "habst".',
      },
      {
        wrong: 'Ich habe nicht Zeit.',
        right: 'Ich habe keine Zeit.',
        why: 'A noun is negated with kein-, not with nicht: keine Zeit, kein Geld, keinen Termin.',
      },
      {
        wrong: 'Habt Sie einen Moment?',
        right: 'Haben Sie einen Moment?',
        why: 'Formal Sie takes the same form as wir and sie (they): haben. habt belongs to ihr.',
      },
    ],
    exerciseIds: [
      'x.g.a1.haben.1',
      'x.g.a1.haben.2',
      'x.g.a1.haben.3',
      'x.g.a1.haben.4',
      'x.g.a1.haben.5',
      'x.g.a1.haben.6',
      'x.g.a1.haben.7',
      'x.g.a1.haben.8',
      'x.g.a1.haben.9',
    ],
    exercises: [
      {
        id: 'x.g.a1.haben.1',
        kind: 'conjugate',
        verb: 'haben',
        person: 'du',
        answer: 'hast',
        skill: 'verbs',
        difficulty: 1,
        tags: ['praesens'],
        explain: 'du and er/sie/es drop the -b- of haben: du hast, er hat. All the other forms keep it.',
      },
      {
        id: 'x.g.a1.haben.2',
        kind: 'blank',
        sentence: 'Ich ___ heute leider keine Zeit.',
        options: ['habe', 'hast', 'hat', 'haben'],
        answer: 'habe',
        skill: 'verbs',
        difficulty: 1,
        tags: ['praesens'],
        explain: 'ich always takes -e: ich habe. Note also keine Zeit — nouns are negated with kein-.',
      },
      {
        id: 'x.g.a1.haben.3',
        kind: 'blank',
        sentence: '___ ihr am Samstag Zeit?',
        options: ['Habt', 'Habst', 'Haben', 'Hat'],
        answer: 'Habt',
        skill: 'verbs',
        difficulty: 2,
        tags: ['praesens'],
        explain: 'The ihr form is habt. In a yes/no question the verb moves to the front, but the ending still matches ihr.',
      },
      {
        id: 'x.g.a1.haben.4',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: ['Er hat einen Bruder.', 'Er habt einen Bruder.', 'Er haben ein Bruder.'],
        answer: 0,
        skill: 'verbs',
        difficulty: 2,
        tags: ['praesens'],
        explain: 'er/sie/es takes hat, and what you have stands in the accusative — der Bruder becomes einen Bruder.',
      },
      {
        id: 'x.g.a1.haben.5',
        kind: 'match',
        pairs: [
          ['Ich habe Hunger.', 'I am hungry.'],
          ['Ich habe Durst.', 'I am thirsty.'],
          ['Ich habe Angst.', 'I am afraid.'],
          ['Ich habe Zeit.', 'I have time.'],
        ],
        skill: 'vocabulary',
        difficulty: 2,
        tags: ['praesens'],
        explain: 'Where English says "I am ...", German often says "ich habe ..." — these are fixed noun phrases, so no article.',
      },
      {
        id: 'x.g.a1.haben.6',
        kind: 'order',
        tokens: ['wir', 'haben', 'am Montag', 'einen', 'Termin'],
        answer: 'Wir haben am Montag einen Termin.',
        accept: ['Am Montag haben wir einen Termin.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['wortstellung'],
        explain: 'A time expression may open the sentence, but haben still has to sit in position 2.',
      },
      {
        id: 'x.g.a1.haben.7',
        kind: 'correct',
        wrong: 'Haben du einen Kugelschreiber?',
        answer: 'Hast du einen Kugelschreiber?',
        skill: 'verbs',
        difficulty: 2,
        tags: ['praesens'],
        explain: 'Even when the verb comes first in a question, it matches the subject: du → hast.',
      },
      {
        id: 'x.g.a1.haben.8',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'We have a question. Do you (du) have five minutes?',
        answer: 'Wir haben eine Frage. Hast du fünf Minuten?',
        accept: ['Wir haben eine Frage. Hast du 5 Minuten?'],
        skill: 'writing',
        difficulty: 3,
        tags: ['praesens'],
        hint: 'wir keeps the -en ending; du does not.',
        explain: 'wir haben looks like the infinitive, while du swaps to hast — the two most common forms in one sentence.',
      },
      {
        id: 'x.g.a1.haben.9',
        kind: 'dialogue',
        lines: [
          { who: 'Praxis', text: 'Guten Tag, haben Sie einen Termin?' },
          { who: 'Patient', text: '___' },
        ],
        options: [
          'Nein, leider nicht. Ich habe Rückenschmerzen.',
          'Nein, leider nicht. Ich bin Rückenschmerzen.',
          'Nein, leider nicht. Ich habt Rückenschmerzen.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 3,
        tags: ['praesens'],
        explain: 'Pain is something you have, not something you are: ich habe Rückenschmerzen. habt belongs to ihr.',
      },
    ],
  },

  /* ── 3. Präsens — regular verbs ───────────────────────────────────────── */
  {
    id: 'g.a1.praesens',
    level: 'A1',
    title: 'Regular verbs in the present tense',
    titleDe: 'Das Präsens: regelmäßige Verben',
    short: 'One stem, six endings. Learn the pattern once and hundreds of verbs are yours.',
    tags: ['verbs', 'praesens', 'konjugation'],
    skill: 'verbs',
    difficulty: 1,
    explain: [
      {
        kind: 'text',
        text: 'Cut **-en** off the infinitive and add the ending: *wohnen* → *wohn-* → *ich wohne, du wohnst, er wohnt*. Almost every German verb works like this.',
      },
      {
        kind: 'table',
        head: ['Person', 'Ending', 'machen', 'arbeiten'],
        rows: [
          ['ich', '-e', 'mache', 'arbeite'],
          ['du', '-st', 'machst', 'arbeitest'],
          ['er / sie / es', '-t', 'macht', 'arbeitet'],
          ['wir', '-en', 'machen', 'arbeiten'],
          ['ihr', '-t', 'macht', 'arbeitet'],
          ['sie / Sie', '-en', 'machen', 'arbeiten'],
        ],
      },
      {
        kind: 'tip',
        text: 'If the stem ends in **-t** or **-d**, add an extra **-e-** so you can pronounce it: *du arbeitest*, *er findet*, *ihr arbeitet*.',
      },
      {
        kind: 'warn',
        text: 'German has only one present tense. *Ich arbeite* means both *I work* and *I am working*.',
      },
    ],
    examples: [
      { de: 'Ich wohne in Hamburg und arbeite in Berlin.', en: 'I live in Hamburg and work in Berlin.' },
      {
        de: 'Wo arbeitest du?',
        en: 'Where do you work?',
        note: 'The stem arbeit- ends in -t, so du gets an extra -e-: arbeitest.',
      },
      { de: 'Wir kaufen im Supermarkt Brot und Milch.', en: 'We buy bread and milk at the supermarket.' },
      { de: 'Der Bus kommt um acht Uhr.', en: 'The bus comes at eight.' },
    ],
    pitfalls: [
      {
        wrong: 'Du arbeitst im Büro.',
        right: 'Du arbeitest im Büro.',
        why: 'Stems ending in -t or -d insert an -e- before the ending, or the word cannot be pronounced.',
      },
      {
        wrong: 'Ich bin wohne in Berlin.',
        right: 'Ich wohne in Berlin.',
        why: 'German has no "am/is + -ing" form. One conjugated verb is the whole present tense.',
      },
      {
        wrong: 'Er wohnt in Wien und arbeite in Graz.',
        right: 'Er wohnt in Wien und arbeitet in Graz.',
        why: 'After und the subject is still er, so the second verb needs the er ending too.',
      },
    ],
    exerciseIds: [
      'x.g.a1.praesens.1',
      'x.g.a1.praesens.2',
      'x.g.a1.praesens.3',
      'x.g.a1.praesens.4',
      'x.g.a1.praesens.5',
      'x.g.a1.praesens.6',
      'x.g.a1.praesens.7',
      'x.g.a1.praesens.8',
      'x.g.a1.praesens.9',
    ],
    exercises: [
      {
        id: 'x.g.a1.praesens.1',
        kind: 'conjugate',
        verb: 'wohnen',
        person: 'ihr',
        answer: 'wohnt',
        skill: 'verbs',
        difficulty: 1,
        tags: ['konjugation'],
        explain: 'ihr takes -t, exactly like er/sie/es. The pronoun in front tells you which one is meant.',
      },
      {
        id: 'x.g.a1.praesens.2',
        kind: 'blank',
        sentence: 'Wir ___ jeden Morgen Kaffee.',
        options: ['trinken', 'trinkt', 'trinkst', 'trinke'],
        answer: 'trinken',
        skill: 'verbs',
        difficulty: 1,
        tags: ['konjugation'],
        explain: 'wir takes -en, so the form is identical to the infinitive: wir trinken.',
      },
      {
        id: 'x.g.a1.praesens.3',
        kind: 'conjugate',
        verb: 'arbeiten',
        person: 'du',
        answer: 'arbeitest',
        skill: 'verbs',
        difficulty: 2,
        tags: ['konjugation'],
        hint: 'What sound does the stem end in?',
        explain: 'The stem arbeit- ends in -t, so an -e- is slipped in before the -st ending: du arbeitest.',
      },
      {
        id: 'x.g.a1.praesens.4',
        kind: 'blank',
        sentence: 'Anna ___ aus Polen und wohnt jetzt in Bonn.',
        answer: 'kommt',
        skill: 'verbs',
        difficulty: 2,
        tags: ['konjugation'],
        hint: 'kommen',
        explain: 'Anna is er/sie/es, so the ending is -t: sie kommt. Names always behave like er, sie or es.',
      },
      {
        id: 'x.g.a1.praesens.5',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: [
          'Ihr macht am Freitag eine Pause.',
          'Ihr machen am Freitag eine Pause.',
          'Ihr machst am Freitag eine Pause.',
        ],
        answer: 0,
        skill: 'verbs',
        difficulty: 2,
        tags: ['konjugation'],
        explain: 'ihr takes -t. The ending -st belongs to du and -en to wir and sie/Sie.',
      },
      {
        id: 'x.g.a1.praesens.6',
        kind: 'order',
        tokens: ['ich', 'lerne', 'jeden', 'Abend', 'eine', 'Stunde', 'Deutsch'],
        answer: 'Ich lerne jeden Abend eine Stunde Deutsch.',
        accept: ['Jeden Abend lerne ich eine Stunde Deutsch.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['wortstellung'],
        explain: 'Move the time phrase to the front if you like — the conjugated verb lerne stays in position 2.',
      },
      {
        id: 'x.g.a1.praesens.7',
        kind: 'dialogue',
        lines: [
          { who: 'Lena', text: 'Was machst du beruflich?' },
          { who: 'Du', text: '___' },
        ],
        options: [
          'Ich arbeite als Krankenpfleger.',
          'Ich arbeitest als Krankenpfleger.',
          'Ich arbeiten als Krankenpfleger.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 2,
        tags: ['konjugation'],
        explain: 'ich takes plain -e: ich arbeite. The extra -e- rule only affects the du, er and ihr endings.',
      },
      {
        id: 'x.g.a1.praesens.8',
        kind: 'correct',
        wrong: 'Was machst ihr am Samstag?',
        answer: 'Was macht ihr am Samstag?',
        skill: 'verbs',
        difficulty: 3,
        tags: ['konjugation'],
        explain: '-st is the du ending. With ihr the verb takes -t, even though the question word comes first.',
      },
      {
        id: 'x.g.a1.praesens.9',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'My brother lives in Munich and works there too.',
        answer: 'Mein Bruder wohnt in München und arbeitet dort auch.',
        accept: ['Mein Bruder wohnt in München und arbeitet auch dort.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['konjugation'],
        hint: 'One subject, two verbs — both need the er ending.',
        explain: 'Both verbs belong to mein Bruder, so both take -t; arbeitet adds -e- because its stem ends in -t.',
      },
    ],
  },

  /* ── 4. Stem-changing verbs ───────────────────────────────────────────── */
  {
    id: 'g.a1.unregelmaessig',
    level: 'A1',
    title: 'Stem-changing verbs (fahren, essen, sehen, sprechen)',
    titleDe: 'Verben mit Vokalwechsel',
    short: 'A handful of everyday verbs change their vowel — but only for du and er/sie/es.',
    tags: ['verbs', 'konjugation'],
    skill: 'verbs',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'A small group of very common verbs changes its stem vowel — but **only in the du and er/sie/es forms**. All the other forms are completely regular.',
      },
      {
        kind: 'table',
        head: ['Verb', 'du', 'er / sie / es', 'Change'],
        rows: [
          ['fahren', 'fährst', 'fährt', 'a → ä'],
          ['schlafen', 'schläfst', 'schläft', 'a → ä'],
          ['essen', 'isst', 'isst', 'e → i'],
          ['sprechen', 'sprichst', 'spricht', 'e → i'],
          ['nehmen', 'nimmst', 'nimmt', 'e → i'],
          ['sehen', 'siehst', 'sieht', 'e → ie'],
        ],
      },
      {
        kind: 'tip',
        text: 'Learn every new verb with its *er* form. If you know *er fährt*, the *du* form comes free: *du fährst*.',
      },
      {
        kind: 'warn',
        text: '*wir*, *ihr* and *sie/Sie* never change the vowel: *wir fahren*, *ihr fahrt*, *sie fahren*.',
      },
    ],
    examples: [
      {
        de: 'Ich fahre mit dem Bus, aber Max fährt mit dem Rad.',
        en: 'I go by bus, but Max goes by bike.',
        note: 'ich fahre stays regular — only du and er change.',
      },
      { de: 'Was isst du zum Frühstück?', en: 'What do you eat for breakfast?' },
      {
        de: 'Sprichst du Englisch? Meine Kollegin spricht nur Deutsch.',
        en: 'Do you speak English? My colleague only speaks German.',
      },
      { de: 'Siehst du den Bus? Er kommt gleich.', en: 'Do you see the bus? It is coming in a moment.' },
    ],
    pitfalls: [
      {
        wrong: 'Du fahrst nach Berlin.',
        right: 'Du fährst nach Berlin.',
        why: 'fahren changes a → ä in the du and er forms: du fährst, er fährt.',
      },
      {
        wrong: 'Wir fahren nach Wien und ihr fährt nach Graz.',
        right: 'Wir fahren nach Wien und ihr fahrt nach Graz.',
        why: 'The vowel change never reaches wir, ihr or sie — ihr fahrt keeps the plain a.',
      },
      {
        wrong: 'Er esst einen Apfel.',
        right: 'Er isst einen Apfel.',
        why: 'essen changes e → i, and because the stem ends in -ss, du and er look identical: isst.',
      },
    ],
    exerciseIds: [
      'x.g.a1.unregelmaessig.1',
      'x.g.a1.unregelmaessig.2',
      'x.g.a1.unregelmaessig.3',
      'x.g.a1.unregelmaessig.4',
      'x.g.a1.unregelmaessig.5',
      'x.g.a1.unregelmaessig.6',
      'x.g.a1.unregelmaessig.7',
      'x.g.a1.unregelmaessig.8',
      'x.g.a1.unregelmaessig.9',
    ],
    exercises: [
      {
        id: 'x.g.a1.unregelmaessig.1',
        kind: 'conjugate',
        verb: 'fahren',
        person: 'er',
        answer: 'fährt',
        skill: 'verbs',
        difficulty: 1,
        tags: ['konjugation'],
        explain: 'fahren changes a → ä in exactly two forms, du and er/sie/es: er fährt.',
      },
      {
        id: 'x.g.a1.unregelmaessig.2',
        kind: 'blank',
        sentence: 'Wir ___ am Freitag nach München.',
        options: ['fahren', 'fährt', 'fährst', 'fahrt'],
        answer: 'fahren',
        skill: 'verbs',
        difficulty: 1,
        tags: ['konjugation'],
        explain: 'wir never takes the vowel change, and its ending is -en — so the form equals the infinitive.',
      },
      {
        id: 'x.g.a1.unregelmaessig.3',
        kind: 'conjugate',
        verb: 'sprechen',
        person: 'du',
        answer: 'sprichst',
        skill: 'verbs',
        difficulty: 2,
        tags: ['konjugation'],
        explain: 'sprechen changes e → i for du and er: du sprichst, er spricht. The endings themselves are normal.',
      },
      {
        id: 'x.g.a1.unregelmaessig.4',
        kind: 'blank',
        sentence: 'Was ___ du zum Frühstück?',
        options: ['isst', 'esst', 'essen', 'esse'],
        answer: 'isst',
        skill: 'verbs',
        difficulty: 2,
        tags: ['konjugation'],
        explain: 'essen changes e → i; since the stem already ends in -ss, du isst and er isst are the same word.',
      },
      {
        id: 'x.g.a1.unregelmaessig.5',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: [
          'Meine Chefin spricht sehr schnell.',
          'Meine Chefin sprecht sehr schnell.',
          'Meine Chefin sprichst sehr schnell.',
        ],
        answer: 0,
        skill: 'verbs',
        difficulty: 2,
        tags: ['konjugation'],
        explain: 'Meine Chefin is sie, so you need the changed stem sprich- plus -t. The -st ending is only for du.',
      },
      {
        id: 'x.g.a1.unregelmaessig.6',
        kind: 'dialogue',
        lines: [
          { who: 'Kellner', text: 'Was nehmen Sie, Kaffee oder Tee?' },
          { who: 'Gast', text: '___' },
        ],
        options: [
          'Ich nehme einen Kaffee, bitte.',
          'Ich nimmst einen Kaffee, bitte.',
          'Ich nimmt einen Kaffee, bitte.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 2,
        tags: ['konjugation'],
        explain: 'ich keeps the original stem: ich nehme. nehm- only becomes nimm- for du and er/sie/es.',
      },
      {
        id: 'x.g.a1.unregelmaessig.7',
        kind: 'order',
        tokens: ['am Samstag', 'fährt', 'mein', 'Bruder', 'nach Hamburg'],
        answer: 'Am Samstag fährt mein Bruder nach Hamburg.',
        accept: ['Mein Bruder fährt am Samstag nach Hamburg.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['wortstellung'],
        explain: 'The vowel change belongs to the verb, not to its position — fährt stays the second element either way.',
      },
      {
        id: 'x.g.a1.unregelmaessig.8',
        kind: 'correct',
        wrong: 'Nimmst ihr den Bus oder das Taxi?',
        answer: 'Nehmt ihr den Bus oder das Taxi?',
        skill: 'verbs',
        difficulty: 3,
        tags: ['konjugation'],
        explain: 'ihr keeps the plain stem and takes -t: ihr nehmt. Only du and er/sie/es turn nehm- into nimm-.',
      },
      {
        id: 'x.g.a1.unregelmaessig.9',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'Do you (du) see the bus? It goes to the station.',
        answer: 'Siehst du den Bus? Er fährt zum Bahnhof.',
        accept: ['Siehst du den Bus? Er fährt zum Bahnhof hin.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['konjugation'],
        hint: 'Two different vowel changes in one answer.',
        explain: 'sehen changes e → ie for du (siehst) and fahren changes a → ä for er (fährt) — the pattern differs per verb.',
      },
    ],
  },
]

export default grammar
