/**
 * A2 — putting sentences together.
 *
 *   g.a2.nebensatz        subordinate clauses (verb to the end)
 *   g.a2.weil-dass-wenn   the three everyday conjunctions
 *   g.a2.konjunktionen    und / aber / oder / denn / sondern, deshalb, trotzdem
 *   g.a2.satzbau          Time – Manner – Place
 *   g.a2.imperativ        the imperative (du / ihr / Sie)
 *   g.a2.komparativ       comparative and superlative
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const grammar = [
  /* ── 1. Nebensatz ─────────────────────────────────────────────────────── */
  {
    id: 'g.a2.nebensatz',
    level: 'A2',
    title: 'Subordinate clauses',
    titleDe: 'Der Nebensatz',
    short: 'A second half-sentence after a comma — and its conjugated verb drops to the very end.',
    tags: ['nebensatz'],
    skill: 'wordorder',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'A **Nebensatz** is a second half-sentence introduced by a conjunction such as *weil*, *dass*, *wenn* or *ob*. Its conjugated verb moves to the **very end**, after a comma.',
      },
      {
        kind: 'table',
        head: ['Hauptsatz', 'Nebensatz'],
        rows: [
          ['Ich bleibe zu Hause,', 'weil ich krank bin.'],
          ['Der Kollege sagt,', 'dass er später kommt.'],
          ['Ich frage,', 'ob der Termin noch steht.'],
        ],
      },
      {
        kind: 'tip',
        text: 'Two verbs? The conjugated one goes last: *…, weil ich heute arbeiten muss.*',
      },
      {
        kind: 'warn',
        text: 'If the Nebensatz stands first, it counts as position 1, so the main clause begins with its verb: *Weil ich krank bin, bleibe ich zu Hause.*',
      },
    ],
    examples: [
      {
        de: 'Ich komme heute später, weil der Zug Verspätung hat.',
        en: 'I am coming later today because the train is delayed.',
      },
      {
        de: 'Der Kollege sagt, dass die Besprechung um zehn beginnt.',
        en: 'My colleague says that the meeting starts at ten.',
      },
      {
        de: 'Ich weiß nicht, ob der Chef heute im Büro ist.',
        en: 'I do not know whether the boss is in the office today.',
        note: 'ob means whether — and ist still lands at the end of the clause.',
      },
      {
        de: 'Wenn ich Feierabend habe, gehe ich einkaufen.',
        en: 'When I finish work, I go shopping.',
        note: 'The clause comes first, so the main clause opens with gehe.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Ich bleibe zu Hause, weil ich bin krank.',
        right: 'Ich bleibe zu Hause, weil ich krank bin.',
        why: 'After weil the conjugated verb has to stand at the very end of the clause.',
      },
      {
        wrong: 'Der Kollege sagt dass er später kommt.',
        right: 'Der Kollege sagt, dass er später kommt.',
        why: 'German always puts a comma in front of the conjunction that opens a Nebensatz.',
      },
      {
        wrong: 'Wenn ich Zeit habe, ich komme mit.',
        right: 'Wenn ich Zeit habe, komme ich mit.',
        why: 'The whole Nebensatz fills position 1, so the main clause verb comes straight after the comma.',
      },
    ],
    exerciseIds: [
      'x.g.a2.nebensatz.1',
      'x.g.a2.nebensatz.2',
      'x.g.a2.nebensatz.3',
      'x.g.a2.nebensatz.4',
      'x.g.a2.nebensatz.5',
      'x.g.a2.nebensatz.6',
      'x.g.a2.nebensatz.7',
      'x.g.a2.nebensatz.8',
    ],
    exercises: [
      {
        id: 'x.g.a2.nebensatz.1',
        kind: 'blank',
        sentence: 'Ich gehe früher nach Hause, weil ich müde ___.',
        options: ['bin', 'ist', 'sein', 'bist'],
        answer: 'bin',
        skill: 'wordorder',
        difficulty: 1,
        tags: ['nebensatz'],
        explain: 'In a Nebensatz the conjugated verb closes the clause, and it still has to match the subject ich → bin.',
      },
      {
        id: 'x.g.a2.nebensatz.2',
        kind: 'blank',
        sentence: 'Er sagt, ___ er heute im Homeoffice arbeitet.',
        options: ['dass', 'das', 'denn', 'aber'],
        answer: 'dass',
        skill: 'wordorder',
        difficulty: 1,
        tags: ['nebensatz'],
        explain: 'dass reports what someone says and sends the verb (arbeitet) to the end. das with one s is an article or pronoun, never a conjunction.',
      },
      {
        id: 'x.g.a2.nebensatz.3',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: [
          'Ich rufe später an, weil ich jetzt keine Zeit habe.',
          'Ich rufe später an, weil ich habe jetzt keine Zeit.',
          'Ich rufe später an, weil habe ich jetzt keine Zeit.',
        ],
        answer: 0,
        skill: 'wordorder',
        difficulty: 2,
        tags: ['nebensatz'],
        explain: 'weil is subordinating: subject first, then everything else, and the conjugated verb habe right at the end.',
      },
      {
        id: 'x.g.a2.nebensatz.4',
        kind: 'order',
        tokens: ['ich', 'kann', 'heute', 'nicht', 'kommen', 'weil', 'ich', 'einen', 'Termin', 'habe'],
        answer: 'Ich kann heute nicht kommen, weil ich einen Termin habe.',
        accept: ['Weil ich einen Termin habe, kann ich heute nicht kommen.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['nebensatz'],
        explain: 'Both halves can swap places: the weil-clause always keeps habe at the end, and the main clause always keeps kann in position 2.',
      },
      {
        id: 'x.g.a2.nebensatz.5',
        kind: 'correct',
        wrong: 'Ich weiß nicht, ob kommt der Bus pünktlich.',
        answer: 'Ich weiß nicht, ob der Bus pünktlich kommt.',
        skill: 'wordorder',
        difficulty: 2,
        tags: ['nebensatz'],
        explain: 'Nothing may stand between ob and the subject — and kommt has to close the clause, like every verb in a Nebensatz.',
      },
      {
        id: 'x.g.a2.nebensatz.6',
        kind: 'dialogue',
        lines: [
          { who: 'Chefin', text: 'Warum bist du heute später gekommen?' },
          { who: 'Du', text: '___' },
        ],
        options: [
          'Weil mein Zug ausgefallen ist.',
          'Weil mein Zug ist ausgefallen.',
          'Weil ist mein Zug ausgefallen.',
        ],
        answer: 0,
        skill: 'wordorder',
        difficulty: 2,
        tags: ['nebensatz', 'perfekt'],
        explain: 'In the Perfekt the helper verb is the conjugated one, so inside a Nebensatz it slides behind the participle: … ausgefallen ist.',
      },
      {
        id: 'x.g.a2.nebensatz.7',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'I hope that the flat is still free.',
        answer: 'Ich hoffe, dass die Wohnung noch frei ist.',
        skill: 'writing',
        difficulty: 3,
        tags: ['nebensatz'],
        hint: 'Comma, then dass — and where does ist go?',
        explain: 'After hoffen, glauben and sagen the content clause starts with dass, and its verb ist is pushed to the very end.',
      },
      {
        id: 'x.g.a2.nebensatz.8',
        kind: 'order',
        tokens: ['weil', 'ich', 'morgen', 'früh', 'aufstehen', 'muss', 'gehe', 'ich', 'jetzt', 'ins Bett'],
        answer: 'Weil ich morgen früh aufstehen muss, gehe ich jetzt ins Bett.',
        accept: ['Ich gehe jetzt ins Bett, weil ich morgen früh aufstehen muss.'],
        skill: 'wordorder',
        difficulty: 3,
        tags: ['nebensatz', 'modalverben'],
        hint: 'The modal verb is the conjugated one.',
        explain: 'With a modal, the modal itself closes the Nebensatz, behind the infinitive: … aufstehen muss.',
      },
    ],
  },

  /* ── 2. weil, dass, wenn ──────────────────────────────────────────────── */
  {
    id: 'g.a2.weil-dass-wenn',
    level: 'A2',
    title: 'weil, dass, wenn',
    titleDe: 'weil, dass, wenn',
    short: 'The three conjunctions you need every day — a reason, a statement, a condition.',
    tags: ['nebensatz'],
    skill: 'wordorder',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'Three conjunctions cover most of everyday speech: **weil** = *because*, **dass** = *that*, **wenn** = *if / whenever*. All three send the conjugated verb to the end.',
      },
      {
        kind: 'table',
        head: ['Konjunktion', 'Use it for', 'Beispiel'],
        rows: [
          ['weil', 'a reason', 'Ich nehme das Rad, weil das Wetter schön ist.'],
          ['dass', 'what someone says or thinks', 'Ich glaube, dass er recht hat.'],
          ['wenn', 'a condition or a repeated time', 'Wenn es regnet, nehme ich den Bus.'],
        ],
      },
      {
        kind: 'tip',
        text: '**denn** also means *because*, but it is a main-clause word: *Ich nehme das Rad, denn das Wetter ist schön.*',
      },
      {
        kind: 'warn',
        text: '*wenn* is not the question word *wann*: *Wann kommst du?* asks a question, *wenn du kommst* sets a condition.',
      },
    ],
    examples: [
      {
        de: 'Ich kaufe heute nichts, weil ich kein Bargeld habe.',
        en: 'I am not buying anything today because I have no cash.',
      },
      {
        de: 'Der Arzt sagt, dass ich mehr trinken soll.',
        en: 'The doctor says that I should drink more.',
      },
      {
        de: 'Wenn ich Zeit habe, koche ich am Abend.',
        en: 'When I have time, I cook in the evening.',
        note: 'The wenn-clause is position 1, so koche comes straight after the comma.',
      },
      {
        de: 'Ich bleibe heute im Büro, denn morgen habe ich frei.',
        en: 'I am staying in the office today, because tomorrow I am off.',
        note: 'After denn the order is completely normal — verb in position 2.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Ich komme nicht, weil ich muss arbeiten.',
        right: 'Ich komme nicht, weil ich arbeiten muss.',
        why: 'weil sends the conjugated verb — here the modal muss — right to the end, behind the infinitive.',
      },
      {
        wrong: 'Ich glaube, dass er hat recht.',
        right: 'Ich glaube, dass er recht hat.',
        why: 'dass is subordinating, so hat must close the clause instead of standing in second position.',
      },
      {
        wrong: 'Wann du Zeit hast, ruf mich an.',
        right: 'Wenn du Zeit hast, ruf mich an.',
        why: 'wann only asks questions; a condition or a repeated moment needs wenn.',
      },
    ],
    exerciseIds: [
      'x.g.a2.weil-dass-wenn.1',
      'x.g.a2.weil-dass-wenn.2',
      'x.g.a2.weil-dass-wenn.3',
      'x.g.a2.weil-dass-wenn.4',
      'x.g.a2.weil-dass-wenn.5',
      'x.g.a2.weil-dass-wenn.6',
      'x.g.a2.weil-dass-wenn.7',
      'x.g.a2.weil-dass-wenn.8',
    ],
    exercises: [
      {
        id: 'x.g.a2.weil-dass-wenn.1',
        kind: 'blank',
        sentence: 'Ich gehe zum Arzt, ___ ich seit drei Tagen Kopfschmerzen habe.',
        options: ['weil', 'dass', 'wenn', 'denn'],
        answer: 'weil',
        skill: 'wordorder',
        difficulty: 1,
        tags: ['nebensatz'],
        explain: 'The clause gives a reason and its verb habe already stands last — that is weil. With denn it would have to be "denn ich habe …".',
      },
      {
        id: 'x.g.a2.weil-dass-wenn.2',
        kind: 'blank',
        sentence: 'Meine Kollegin hofft, ___ der Termin nicht ausfällt.',
        options: ['dass', 'das', 'weil', 'wenn'],
        answer: 'dass',
        skill: 'wordorder',
        difficulty: 1,
        tags: ['nebensatz'],
        explain: 'Verbs like hoffen, sagen and glauben are followed by a dass-clause. dass has two s; das with one s is an article.',
      },
      {
        id: 'x.g.a2.weil-dass-wenn.3',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: [
          'Wenn das Wetter schön ist, fahren wir an den See.',
          'Wenn das Wetter schön ist, wir fahren an den See.',
          'Wenn ist das Wetter schön, fahren wir an den See.',
        ],
        answer: 0,
        skill: 'wordorder',
        difficulty: 2,
        tags: ['nebensatz'],
        explain: 'The wenn-clause takes the whole first position, so the main clause has to open with its verb: fahren wir.',
      },
      {
        id: 'x.g.a2.weil-dass-wenn.4',
        kind: 'correct',
        wrong: 'Ich kann nicht kommen, weil ich muss meine Tochter abholen.',
        answer: 'Ich kann nicht kommen, weil ich meine Tochter abholen muss.',
        skill: 'wordorder',
        difficulty: 2,
        tags: ['nebensatz', 'modalverben'],
        explain: 'In a weil-clause the modal is the conjugated verb, so it goes last of all — after the infinitive abholen.',
      },
      {
        id: 'x.g.a2.weil-dass-wenn.5',
        kind: 'order',
        tokens: ['ich', 'glaube', 'dass', 'die', 'Apotheke', 'um', 'acht', 'öffnet'],
        answer: 'Ich glaube, dass die Apotheke um acht öffnet.',
        skill: 'wordorder',
        difficulty: 2,
        tags: ['nebensatz'],
        explain: 'dass needs a comma in front of it and the verb öffnet at the end of its own clause.',
      },
      {
        id: 'x.g.a2.weil-dass-wenn.6',
        kind: 'dialogue',
        lines: [
          { who: 'Kollege', text: 'Kommst du heute Abend mit ins Kino?' },
          { who: 'Du', text: '___' },
        ],
        options: [
          'Nur wenn ich pünktlich Feierabend habe.',
          'Nur wann ich pünktlich Feierabend habe.',
          'Nur wenn habe ich pünktlich Feierabend.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 2,
        tags: ['nebensatz'],
        explain: 'A condition takes wenn, never wann — and the verb habe closes the clause.',
      },
      {
        id: 'x.g.a2.weil-dass-wenn.7',
        kind: 'blank',
        sentence: 'Ich nehme ein Taxi, ___ die Bahn fährt heute nicht.',
        options: ['denn', 'weil', 'dass', 'wenn'],
        answer: 'denn',
        skill: 'wordorder',
        difficulty: 3,
        tags: ['nebensatz'],
        hint: 'Look where the verb fährt is standing.',
        explain: 'The second half keeps normal order with fährt in position 2, and only denn allows that. weil would need "… weil die Bahn heute nicht fährt".',
      },
      {
        id: 'x.g.a2.weil-dass-wenn.8',
        kind: 'correct',
        wrong: 'Wenn ich nach Hause komme, ich koche zuerst Kaffee.',
        answer: 'Wenn ich nach Hause komme, koche ich zuerst Kaffee.',
        skill: 'wordorder',
        difficulty: 3,
        tags: ['nebensatz'],
        explain: 'The whole wenn-clause counts as position 1, so the main clause must start with its conjugated verb: koche ich.',
      },
    ],
  },

  /* ── 3. Konjunktionen und Konnektoren ─────────────────────────────────── */
  {
    id: 'g.a2.konjunktionen',
    level: 'A2',
    title: 'Connecting sentences (und/aber/oder/denn/sondern, deshalb, trotzdem)',
    titleDe: 'Sätze verbinden',
    short: 'Some connectors change nothing in the sentence — others grab position 1 and push the subject behind the verb.',
    tags: ['konnektoren'],
    skill: 'grammar',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: '**und, aber, oder, denn, sondern** simply glue two main clauses together — they change **nothing**. Each half keeps its verb in position 2.',
      },
      {
        kind: 'text',
        text: '**deshalb** (*therefore*) and **trotzdem** (*nevertheless*) are different: they take position 1, so the verb follows immediately.',
      },
      {
        kind: 'table',
        head: ['Konnektor', 'Bedeutung', 'Beispiel'],
        rows: [
          ['und', 'and', 'Ich koche und du deckst den Tisch.'],
          ['aber', 'but', 'Die Wohnung ist klein, aber sie ist hell.'],
          ['sondern', 'but rather (after a no)', 'Ich trinke keinen Kaffee, sondern Tee.'],
          ['denn', 'because', 'Ich bleibe hier, denn ich habe noch Arbeit.'],
          ['deshalb', 'so, therefore', 'Es regnet, deshalb nehme ich den Bus.'],
          ['trotzdem', 'nevertheless', 'Es regnet, trotzdem gehe ich zu Fuß.'],
        ],
      },
      {
        kind: 'tip',
        text: '**sondern** only after a negation: *nicht heute, sondern morgen*. Otherwise use **aber**.',
      },
    ],
    examples: [
      {
        de: 'Die Wohnung ist klein, aber sie ist sehr hell.',
        en: 'The flat is small, but it is very bright.',
      },
      {
        de: 'Ich nehme keinen Zucker, sondern Milch.',
        en: 'I do not take sugar, but milk.',
        note: 'sondern corrects a no: first kein/nicht, then sondern.',
      },
      {
        de: 'Der Drucker ist kaputt, deshalb arbeite ich heute zu Hause.',
        en: 'The printer is broken, so I am working at home today.',
        note: 'deshalb sits in position 1, so arbeite comes straight after it.',
      },
      {
        de: 'Ich habe wenig Zeit, trotzdem koche ich jeden Abend.',
        en: 'I have little time; nevertheless I cook every evening.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Es regnet, deshalb ich nehme den Bus.',
        right: 'Es regnet, deshalb nehme ich den Bus.',
        why: 'deshalb occupies position 1 of the second sentence, so the verb has to come next and the subject moves behind it.',
      },
      {
        wrong: 'Ich möchte keinen Tee, aber Kaffee.',
        right: 'Ich möchte keinen Tee, sondern Kaffee.',
        why: 'After a negation the correction takes sondern. aber only contrasts two things that are both true.',
      },
      {
        wrong: 'Ich bleibe zu Hause, denn ich krank bin.',
        right: 'Ich bleibe zu Hause, denn ich bin krank.',
        why: 'denn is not subordinating — after it the sentence keeps normal order with the verb in position 2.',
      },
    ],
    exerciseIds: [
      'x.g.a2.konjunktionen.1',
      'x.g.a2.konjunktionen.2',
      'x.g.a2.konjunktionen.3',
      'x.g.a2.konjunktionen.4',
      'x.g.a2.konjunktionen.5',
      'x.g.a2.konjunktionen.6',
      'x.g.a2.konjunktionen.7',
      'x.g.a2.konjunktionen.8',
    ],
    exercises: [
      {
        id: 'x.g.a2.konjunktionen.1',
        kind: 'blank',
        sentence: 'Möchten Sie einen Kaffee ___ einen Tee?',
        options: ['oder', 'aber', 'sondern', 'denn'],
        answer: 'oder',
        skill: 'grammar',
        difficulty: 1,
        tags: ['konnektoren'],
        explain: 'oder offers an alternative between two possibilities and changes nothing else in the sentence.',
      },
      {
        id: 'x.g.a2.konjunktionen.2',
        kind: 'blank',
        sentence: 'Die Wohnung ist teuer, ___ sie liegt sehr zentral.',
        options: ['aber', 'sondern', 'deshalb', 'weil'],
        answer: 'aber',
        skill: 'grammar',
        difficulty: 1,
        tags: ['konnektoren'],
        explain: 'aber contrasts two facts that are both true and leaves the word order untouched: sie liegt stays as it is.',
      },
      {
        id: 'x.g.a2.konjunktionen.3',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: [
          'Ich habe keinen Termin, deshalb muss ich warten.',
          'Ich habe keinen Termin, deshalb ich muss warten.',
          'Ich habe keinen Termin, deshalb warten ich muss.',
        ],
        answer: 0,
        skill: 'grammar',
        difficulty: 2,
        tags: ['konnektoren'],
        explain: 'deshalb fills position 1, so the conjugated verb muss comes second and the subject ich follows it.',
      },
      {
        id: 'x.g.a2.konjunktionen.4',
        kind: 'blank',
        sentence: 'Ich esse kein Fleisch, ___ nur Gemüse.',
        options: ['sondern', 'aber', 'oder', 'denn'],
        answer: 'sondern',
        skill: 'grammar',
        difficulty: 2,
        tags: ['konnektoren'],
        explain: 'A correction after kein or nicht always takes sondern: not X, but rather Y.',
      },
      {
        id: 'x.g.a2.konjunktionen.5',
        kind: 'correct',
        wrong: 'Ich bin sehr müde, trotzdem ich gehe noch einkaufen.',
        answer: 'Ich bin sehr müde, trotzdem gehe ich noch einkaufen.',
        skill: 'grammar',
        difficulty: 2,
        tags: ['konnektoren'],
        explain: 'trotzdem behaves like deshalb: it is position 1, so the verb gehe must follow it directly.',
      },
      {
        id: 'x.g.a2.konjunktionen.6',
        kind: 'order',
        tokens: ['ich', 'habe', 'heute', 'frei', 'deshalb', 'gehe', 'ich', 'zum', 'Zahnarzt'],
        answer: 'Ich habe heute frei, deshalb gehe ich zum Zahnarzt.',
        skill: 'wordorder',
        difficulty: 2,
        tags: ['konnektoren'],
        explain: 'The first half keeps normal order; after deshalb the verb comes immediately, so the subject lands behind it: gehe ich.',
      },
      {
        id: 'x.g.a2.konjunktionen.7',
        kind: 'dialogue',
        lines: [
          { who: 'Kollegin', text: 'Kommst du mit in die Kantine?' },
          { who: 'Du', text: '___' },
        ],
        options: [
          'Gern, aber ich habe nur zwanzig Minuten Zeit.',
          'Gern, sondern ich habe nur zwanzig Minuten Zeit.',
          'Gern, aber habe ich nur zwanzig Minuten Zeit.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 3,
        tags: ['konnektoren'],
        explain: 'aber joins two main clauses and changes nothing, so ich habe keeps normal order. sondern would need a negation in front of it.',
      },
      {
        id: 'x.g.a2.konjunktionen.8',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'The train is delayed, therefore I am taking a taxi.',
        answer: 'Der Zug hat Verspätung, deshalb nehme ich ein Taxi.',
        accept: ['Der Zug ist verspätet, deshalb nehme ich ein Taxi.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['konnektoren'],
        hint: 'What comes right after deshalb?',
        explain: 'deshalb opens the second sentence, so the verb follows it at once and the subject moves behind: deshalb nehme ich.',
      },
    ],
  },

  /* ── 4. Time – Manner – Place ─────────────────────────────────────────── */
  {
    id: 'g.a2.satzbau',
    level: 'A2',
    title: 'Time – Manner – Place',
    titleDe: 'Wortstellung: temporal – modal – lokal',
    short: 'When? How? Where? — German always lines the extra details up in that order.',
    tags: ['wortstellung'],
    skill: 'wordorder',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'When several extra details follow the verb, German lines them up as **Time – Manner – Place**: *wann? – wie? – wohin?*',
      },
      {
        kind: 'table',
        head: ['Satz', 'Zeit (wann?)', 'Art (wie?)', 'Ort (wohin?)'],
        rows: [
          ['Ich fahre', 'morgen', 'mit dem Bus', 'nach Köln.'],
          ['Wir gehen', 'am Samstag', 'zu zweit', 'ins Kino.'],
          ['Sie kommt', 'um acht', 'mit dem Rad', 'ins Büro.'],
        ],
      },
      {
        kind: 'tip',
        text: 'Only one element may stand in front of the verb. Putting the time there is very common: *Morgen fahre ich mit dem Bus nach Köln.*',
      },
      {
        kind: 'warn',
        text: 'English says *place* before *time*. German is the other way round — never *Ich fahre nach Köln morgen*.',
      },
    ],
    examples: [
      {
        de: 'Ich fahre morgen mit dem Zug nach Hamburg.',
        en: 'I am going to Hamburg by train tomorrow.',
        note: 'Time (morgen) – Manner (mit dem Zug) – Place (nach Hamburg).',
      },
      {
        de: 'Wir treffen uns um sieben vor dem Kino.',
        en: 'We are meeting at seven in front of the cinema.',
      },
      {
        de: 'Am Montag gehe ich zu Fuß ins Büro.',
        en: 'On Monday I walk to the office.',
        note: 'The time phrase moved to position 1, so gehe still stands second.',
      },
      {
        de: 'Sie bringt die Kinder jeden Morgen mit dem Auto in die Schule.',
        en: 'She takes the children to school by car every morning.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Ich gehe ins Kino heute Abend.',
        right: 'Ich gehe heute Abend ins Kino.',
        why: 'German puts the time before the place — exactly the opposite of English.',
      },
      {
        wrong: 'Morgen ich fahre nach Berlin.',
        right: 'Morgen fahre ich nach Berlin.',
        why: 'Only one element may stand before the verb. If the time takes that slot, the subject moves behind the verb.',
      },
      {
        wrong: 'Wir fahren nach Italien mit dem Auto im Sommer.',
        right: 'Wir fahren im Sommer mit dem Auto nach Italien.',
        why: 'Time – Manner – Place: first im Sommer, then mit dem Auto, then nach Italien.',
      },
    ],
    exerciseIds: [
      'x.g.a2.satzbau.1',
      'x.g.a2.satzbau.2',
      'x.g.a2.satzbau.3',
      'x.g.a2.satzbau.4',
      'x.g.a2.satzbau.5',
      'x.g.a2.satzbau.6',
      'x.g.a2.satzbau.7',
      'x.g.a2.satzbau.8',
    ],
    exercises: [
      {
        id: 'x.g.a2.satzbau.1',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: [
          'Ich fahre am Freitag nach München.',
          'Ich fahre nach München am Freitag.',
          'Ich am Freitag fahre nach München.',
        ],
        answer: 0,
        skill: 'wordorder',
        difficulty: 1,
        tags: ['wortstellung'],
        explain: 'Time comes before place in German, and the conjugated verb fahre keeps position 2.',
      },
      {
        id: 'x.g.a2.satzbau.2',
        kind: 'order',
        tokens: ['wir', 'gehen', 'heute', 'ins Kino'],
        answer: 'Wir gehen heute ins Kino.',
        accept: ['Heute gehen wir ins Kino.'],
        skill: 'wordorder',
        difficulty: 1,
        tags: ['wortstellung'],
        explain: 'The time (heute) stands before the place (ins Kino); if you front the time, the verb still stays second.',
      },
      {
        id: 'x.g.a2.satzbau.3',
        kind: 'order',
        tokens: ['ich', 'fahre', 'morgen', 'mit dem Zug', 'nach Frankfurt'],
        answer: 'Ich fahre morgen mit dem Zug nach Frankfurt.',
        accept: ['Morgen fahre ich mit dem Zug nach Frankfurt.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['wortstellung'],
        explain: 'Time – Manner – Place: morgen, then mit dem Zug, then nach Frankfurt.',
      },
      {
        id: 'x.g.a2.satzbau.4',
        kind: 'correct',
        wrong: 'Wir treffen uns im Restaurant um acht.',
        answer: 'Wir treffen uns um acht im Restaurant.',
        skill: 'wordorder',
        difficulty: 2,
        tags: ['wortstellung'],
        explain: 'The time phrase (um acht) always comes before the place phrase (im Restaurant).',
      },
      {
        id: 'x.g.a2.satzbau.5',
        kind: 'order',
        tokens: ['am Samstag', 'fahren', 'wir', 'mit dem Auto', 'zum Baumarkt'],
        answer: 'Am Samstag fahren wir mit dem Auto zum Baumarkt.',
        accept: ['Wir fahren am Samstag mit dem Auto zum Baumarkt.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['wortstellung'],
        explain: 'Whichever part you put first, the rest keeps the order Time – Manner – Place.',
      },
      {
        id: 'x.g.a2.satzbau.6',
        kind: 'mcq',
        prompt: 'Which sentence sounds natural in German?',
        options: [
          'Sie kommt jeden Tag mit dem Rad ins Büro.',
          'Sie kommt mit dem Rad jeden Tag ins Büro.',
          'Sie kommt ins Büro jeden Tag mit dem Rad.',
        ],
        answer: 0,
        skill: 'wordorder',
        difficulty: 2,
        tags: ['wortstellung'],
        explain: 'wann (jeden Tag) – wie (mit dem Rad) – wohin (ins Büro) is the neutral German order.',
      },
      {
        id: 'x.g.a2.satzbau.7',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'We are flying to Vienna by plane on Sunday.',
        answer: 'Wir fliegen am Sonntag mit dem Flugzeug nach Wien.',
        accept: ['Am Sonntag fliegen wir mit dem Flugzeug nach Wien.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['wortstellung'],
        hint: 'English gives place, manner, time — German reverses it.',
        explain: 'German rebuilds the English order into Time – Manner – Place: am Sonntag, mit dem Flugzeug, nach Wien.',
      },
      {
        id: 'x.g.a2.satzbau.8',
        kind: 'correct',
        wrong: 'Heute ich muss mit dem Bus zum Arzt fahren.',
        answer: 'Heute muss ich mit dem Bus zum Arzt fahren.',
        skill: 'wordorder',
        difficulty: 3,
        tags: ['wortstellung', 'modalverben'],
        explain: 'Only one element may stand before the verb: heute takes that slot, so muss follows at once and ich comes after it.',
      },
    ],
  },

  /* ── 5. Imperativ ─────────────────────────────────────────────────────── */
  {
    id: 'g.a2.imperativ',
    level: 'A2',
    title: 'The imperative',
    titleDe: 'Der Imperativ',
    short: 'Three forms for three ways of addressing people — and a bitte to keep it friendly.',
    tags: ['imperativ'],
    skill: 'grammar',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'German has three imperative forms — one for **du**, one for **ihr**, one for **Sie**.',
      },
      {
        kind: 'table',
        head: ['Form', 'Regel', 'Beispiel'],
        rows: [
          ['du', 'stem only, no -st, no pronoun', 'Komm bitte herein!'],
          ['ihr', 'the normal ihr-form, no pronoun', 'Kommt bitte herein!'],
          ['Sie', 'verb first, then Sie', 'Kommen Sie bitte herein!'],
          ['trennbar', 'the prefix goes to the end', 'Ruf mich bitte an!'],
        ],
      },
      {
        kind: 'tip',
        text: '**bitte** turns an order into a polite request — Germans put it into almost every imperative.',
      },
      {
        kind: 'warn',
        text: 'Verbs with **a → ä** drop the umlaut here (*fahren → Fahr langsam!*), and **sein** is irregular: *Sei ruhig! Seid ruhig! Seien Sie ruhig!*',
      },
    ],
    examples: [
      {
        de: 'Nehmen Sie bitte Platz, Herr Bauer.',
        en: 'Please take a seat, Mr Bauer.',
      },
      {
        de: 'Ruf mich heute Abend an!',
        en: 'Call me this evening!',
        note: 'Separable verb: the prefix an goes to the end.',
      },
      {
        de: 'Macht bitte die Fenster zu, es ist kalt.',
        en: 'Please close the windows, it is cold.',
      },
      {
        de: 'Sei bitte pünktlich!',
        en: 'Please be on time!',
        note: 'sein has its own imperative: Sei / Seid / Seien Sie.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Du komm bitte herein!',
        right: 'Komm bitte herein!',
        why: 'The du imperative never keeps the pronoun — the bare stem is the whole form.',
      },
      {
        wrong: 'Kommst du herein!',
        right: 'Komm herein!',
        why: 'The du imperative drops the -st ending: kommst becomes komm, gehst becomes geh.',
      },
      {
        wrong: 'Fährst bitte langsam!',
        right: 'Fahr bitte langsam!',
        why: 'Verbs with a → ä lose the umlaut in the imperative: fahren becomes fahr, schlafen becomes schlaf.',
      },
    ],
    exerciseIds: [
      'x.g.a2.imperativ.1',
      'x.g.a2.imperativ.2',
      'x.g.a2.imperativ.3',
      'x.g.a2.imperativ.4',
      'x.g.a2.imperativ.5',
      'x.g.a2.imperativ.6',
      'x.g.a2.imperativ.7',
      'x.g.a2.imperativ.8',
    ],
    exercises: [
      {
        id: 'x.g.a2.imperativ.1',
        kind: 'blank',
        sentence: 'Herr Klein, ___ Sie bitte hier einen Moment.',
        options: ['warten', 'wartet', 'warte', 'wartest'],
        answer: 'warten',
        skill: 'grammar',
        difficulty: 1,
        tags: ['imperativ'],
        explain: 'The Sie imperative looks like the infinitive and the pronoun Sie follows it: Warten Sie bitte.',
      },
      {
        id: 'x.g.a2.imperativ.2',
        kind: 'blank',
        sentence: 'Anna, ___ mich bitte heute Abend an!',
        options: ['ruf', 'rufst', 'rufen', 'ruft'],
        answer: 'ruf',
        skill: 'grammar',
        difficulty: 1,
        tags: ['imperativ', 'trennbar'],
        explain: 'To one friend you use the bare stem without -st, and the separable prefix an stays at the end.',
      },
      {
        id: 'x.g.a2.imperativ.3',
        kind: 'mcq',
        prompt: 'You are speaking to your whole team (ihr). Which is correct?',
        options: [
          'Kommt bitte pünktlich zur Besprechung!',
          'Kommen bitte pünktlich zur Besprechung!',
          'Komm bitte pünktlich zur Besprechung!',
        ],
        answer: 0,
        skill: 'grammar',
        difficulty: 2,
        tags: ['imperativ'],
        explain: 'The ihr imperative is simply the ihr present form without the pronoun: ihr kommt becomes Kommt!',
      },
      {
        id: 'x.g.a2.imperativ.4',
        kind: 'correct',
        wrong: 'Du gehst bitte zum Schalter drei!',
        answer: 'Geh bitte zum Schalter drei!',
        skill: 'grammar',
        difficulty: 2,
        tags: ['imperativ'],
        explain: 'A command to one person drops both the pronoun and the -st ending: du gehst becomes Geh!',
      },
      {
        id: 'x.g.a2.imperativ.5',
        kind: 'conjugate',
        verb: 'fahren',
        person: 'Imperativ (du)',
        answer: 'fahr',
        skill: 'grammar',
        difficulty: 2,
        tags: ['imperativ'],
        hint: 'Does the umlaut survive?',
        explain: 'Verbs with a → ä lose the umlaut in the imperative (Fahr!), while e → i verbs keep their change (nehmen → Nimm!).',
      },
      {
        id: 'x.g.a2.imperativ.6',
        kind: 'order',
        tokens: ['machen', 'Sie', 'bitte', 'das', 'Fenster', 'auf'],
        answer: 'Machen Sie bitte das Fenster auf.',
        skill: 'wordorder',
        difficulty: 2,
        tags: ['imperativ', 'trennbar'],
        explain: 'In the Sie imperative the verb comes first and Sie right after it; the separable prefix auf closes the sentence.',
      },
      {
        id: 'x.g.a2.imperativ.7',
        kind: 'dialogue',
        lines: [
          { who: 'Patient', text: 'Guten Tag, ich habe seit gestern starke Halsschmerzen.' },
          { who: 'Ärztin', text: '___' },
        ],
        options: [
          'Machen Sie bitte den Mund auf.',
          'Machen bitte Sie den Mund auf.',
          'Machst Sie bitte den Mund auf.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 3,
        tags: ['imperativ'],
        explain: 'With Sie the verb stands first and the pronoun follows it immediately — nothing may come between them.',
      },
      {
        id: 'x.g.a2.imperativ.8',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'Please be on time and bring your passport. (to a friend, du)',
        answer: 'Sei bitte pünktlich und bring deinen Pass mit.',
        accept: ['Sei bitte pünktlich und bringe deinen Pass mit.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['imperativ', 'trennbar'],
        hint: 'sein does not follow the normal pattern.',
        explain: 'sein has the irregular imperative Sei, and mitbringen splits, so mit goes to the very end.',
      },
    ],
  },

  /* ── 6. Komparativ und Superlativ ─────────────────────────────────────── */
  {
    id: 'g.a2.komparativ',
    level: 'A2',
    title: 'Comparative and superlative',
    titleDe: 'Komparativ und Superlativ',
    short: 'Add -er to compare and am …-sten for the winner — German never uses "more" plus an adjective.',
    tags: ['komparativ'],
    skill: 'grammar',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'Add **-er** to compare and **am …-sten** for the top: *billig – billiger – am billigsten*. Comparisons take **als**, equality takes **so … wie**.',
      },
      {
        kind: 'table',
        head: ['Adjektiv', 'Komparativ', 'Superlativ'],
        rows: [
          ['billig', 'billiger', 'am billigsten'],
          ['alt', 'älter', 'am ältesten'],
          ['groß', 'größer', 'am größten'],
          ['gut', 'besser', 'am besten'],
          ['viel', 'mehr', 'am meisten'],
          ['gern', 'lieber', 'am liebsten'],
        ],
      },
      {
        kind: 'tip',
        text: 'Many short adjectives with **a, o, u** take an umlaut: *alt → älter*, *groß → größer*, *jung → jünger*.',
      },
      {
        kind: 'warn',
        text: 'Never say *mehr billig* — German has no *more + adjective*. And after a comparative you need **als**, not *wie*.',
      },
    ],
    examples: [
      {
        de: 'Der Bus ist billiger als das Taxi.',
        en: 'The bus is cheaper than the taxi.',
      },
      {
        de: 'Meine neue Wohnung ist größer als die alte.',
        en: 'My new flat is bigger than the old one.',
      },
      {
        de: 'Im Supermarkt ist das Obst am günstigsten.',
        en: 'The fruit is cheapest at the supermarket.',
        note: 'am + adjective + -sten is the normal superlative after a verb.',
      },
      {
        de: 'Ich trinke gern Tee, aber Kaffee trinke ich lieber.',
        en: 'I like drinking tea, but I prefer coffee.',
        note: 'gern – lieber – am liebsten is completely irregular.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Der Zug ist schneller wie das Auto.',
        right: 'Der Zug ist schneller als das Auto.',
        why: 'After a comparative German uses als. wie only appears in so … wie, which means equally.',
      },
      {
        wrong: 'Meine Wohnung ist mehr klein.',
        right: 'Meine Wohnung ist kleiner.',
        why: 'German never builds a comparative with mehr — the ending -er does the whole job.',
      },
      {
        wrong: 'Das Hotel ist am billiger.',
        right: 'Das Hotel ist am billigsten.',
        why: 'The superlative is am + adjective + -sten; am can never combine with a comparative.',
      },
    ],
    exerciseIds: [
      'x.g.a2.komparativ.1',
      'x.g.a2.komparativ.2',
      'x.g.a2.komparativ.3',
      'x.g.a2.komparativ.4',
      'x.g.a2.komparativ.5',
      'x.g.a2.komparativ.6',
      'x.g.a2.komparativ.7',
      'x.g.a2.komparativ.8',
      'x.g.a2.komparativ.9',
    ],
    exercises: [
      {
        id: 'x.g.a2.komparativ.1',
        kind: 'blank',
        sentence: 'Der Bus ist ___ als das Taxi.',
        options: ['billiger', 'billig', 'am billigsten', 'billigste'],
        answer: 'billiger',
        skill: 'grammar',
        difficulty: 1,
        tags: ['komparativ'],
        explain: 'Comparing exactly two things needs the -er form, and als introduces what you compare it with.',
      },
      {
        id: 'x.g.a2.komparativ.2',
        kind: 'blank',
        sentence: 'Dieses Handy ist gut, aber das andere ist ___.',
        options: ['besser', 'guter', 'mehr gut', 'am besten'],
        answer: 'besser',
        skill: 'grammar',
        difficulty: 1,
        tags: ['komparativ'],
        explain: 'gut is irregular: gut – besser – am besten. German has no form "mehr gut".',
      },
      {
        id: 'x.g.a2.komparativ.3',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: [
          'Die Miete in Berlin ist höher als in Leipzig.',
          'Die Miete in Berlin ist höher wie in Leipzig.',
          'Die Miete in Berlin ist mehr hoch als in Leipzig.',
        ],
        answer: 0,
        skill: 'grammar',
        difficulty: 2,
        tags: ['komparativ'],
        explain: 'hoch becomes höher, and a comparative is always followed by als — wie belongs to so … wie.',
      },
      {
        id: 'x.g.a2.komparativ.4',
        kind: 'blank',
        sentence: 'Meine Schwester ist zwei Jahre ___ als ich.',
        options: ['älter', 'alter', 'am ältesten', 'alt'],
        answer: 'älter',
        skill: 'grammar',
        difficulty: 2,
        tags: ['komparativ'],
        explain: 'Short adjectives with a usually add an umlaut: alt becomes älter. The measure zwei Jahre stands in front of it.',
      },
      {
        id: 'x.g.a2.komparativ.5',
        kind: 'correct',
        wrong: 'Im Discounter ist das Brot am billiger.',
        answer: 'Im Discounter ist das Brot am billigsten.',
        skill: 'grammar',
        difficulty: 2,
        tags: ['komparativ'],
        explain: 'The superlative form is am + adjective + -sten, so am billigsten. am plus a comparative does not exist.',
      },
      {
        id: 'x.g.a2.komparativ.6',
        kind: 'order',
        tokens: ['im', 'Sommer', 'sind', 'die', 'Hotels', 'teurer', 'als', 'im', 'Winter'],
        answer: 'Im Sommer sind die Hotels teurer als im Winter.',
        accept: ['Die Hotels sind im Sommer teurer als im Winter.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['komparativ', 'wortstellung'],
        explain: 'The als-part closes the sentence, and fronting Im Sommer still leaves sind in position 2.',
      },
      {
        id: 'x.g.a2.komparativ.7',
        kind: 'blank',
        sentence: 'Ich fahre gern mit dem Auto, aber mit dem Zug fahre ich ___.',
        options: ['lieber', 'gerner', 'mehr gern', 'am liebsten'],
        answer: 'lieber',
        skill: 'grammar',
        difficulty: 3,
        tags: ['komparativ'],
        hint: 'Two options are compared, not three.',
        explain: 'gern is irregular: gern – lieber – am liebsten. Comparing two things takes lieber; the form "gerner" does not exist.',
      },
      {
        id: 'x.g.a2.komparativ.8',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'The new flat is smaller, but it is much cheaper.',
        answer: 'Die neue Wohnung ist kleiner, aber sie ist viel billiger.',
        accept: ['Die neue Wohnung ist kleiner, aber viel billiger.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['komparativ'],
        explain: 'Both comparatives are built with -er alone, and viel in front of a comparative is how German says "much".',
      },
      {
        id: 'x.g.a2.komparativ.9',
        kind: 'dialogue',
        lines: [
          { who: 'Verkäufer', text: 'Möchten Sie das Handy für 300 Euro oder das für 500 Euro?' },
          { who: 'Kundin', text: '___' },
        ],
        options: [
          'Ich nehme das für 300 Euro, es ist billiger.',
          'Ich nehme das für 300 Euro, es ist mehr billig.',
          'Ich nehme das für 300 Euro, es ist billiger wie das andere.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 3,
        tags: ['komparativ'],
        explain: 'A comparative is formed with -er on its own; mehr + adjective and comparative + wie are both wrong.',
      },
    ],
  },
]

export default grammar
