/**
 * A2 — the five verb topics that turn beginner German into everyday German.
 *
 *   g.a2.perfekt                the perfect tense
 *   g.a2.perfekt-unregelmaessig irregular past participles
 *   g.a2.modalverben            modal verbs in full (incl. konnte/musste/wollte)
 *   g.a2.reflexiv               reflexive verbs
 *   g.a2.trennbar               separable and inseparable verbs
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const grammar = [
  /* ── 1. Perfekt ───────────────────────────────────────────────────────── */
  {
    id: 'g.a2.perfekt',
    level: 'A2',
    title: 'The perfect tense',
    titleDe: 'Das Perfekt',
    short: 'How Germans talk about yesterday: haben or sein in position 2, participle at the end.',
    tags: ['perfekt'],
    skill: 'verbs',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'To talk about the past, German uses the **Perfekt**: a form of **haben** or **sein** in position 2, and the past participle at the very end.',
      },
      {
        kind: 'text',
        text: 'Regular participles are **ge- + stem + -t**: *machen → gemacht*, *kaufen → gekauft*, *arbeiten → gearbeitet*.',
      },
      {
        kind: 'table',
        head: ['mit haben', 'mit sein'],
        rows: [
          ['Ich habe gearbeitet.', 'Ich bin gefahren.'],
          ['Sie hat gekocht.', 'Sie ist geblieben.'],
        ],
      },
      {
        kind: 'tip',
        text: 'Verbs of movement or change take **sein**: *gehen, fahren, kommen, fliegen, bleiben*. Everything else takes **haben**.',
      },
      {
        kind: 'warn',
        text: 'Verbs ending in **-ieren** and verbs with an inseparable prefix take **no ge-**: *telefoniert*, *reserviert*, *bezahlt*.',
      },
    ],
    examples: [
      {
        de: 'Ich habe gestern acht Stunden im Büro gearbeitet.',
        en: 'I worked in the office for eight hours yesterday.',
        note: 'habe is the second element, gearbeitet closes the sentence — everything else sits in between.',
      },
      { de: 'Am Wochenende haben wir die Wohnung geputzt.', en: 'At the weekend we cleaned the flat.' },
      {
        de: 'Meine Kollegin ist heute früh nach Hamburg gefahren.',
        en: 'My colleague drove to Hamburg early today.',
        note: 'fahren is movement from A to B, so the auxiliary is sein.',
      },
      { de: 'Hast du schon mit dem Arzt telefoniert?', en: 'Have you already spoken to the doctor on the phone?' },
    ],
    pitfalls: [
      {
        wrong: 'Ich habe nach Berlin gefahren.',
        right: 'Ich bin nach Berlin gefahren.',
        why: 'Verbs that move you from one place to another (fahren, gehen, fliegen, kommen) build the Perfekt with sein.',
      },
      {
        wrong: 'Ich habe im Büro gearbeitet gestern.',
        right: 'Ich habe gestern im Büro gearbeitet.',
        why: 'Nothing may follow the participle. haben and the participle form a bracket around the rest of the sentence.',
      },
      {
        wrong: 'Ich habe mit dem Vermieter getelefoniert.',
        right: 'Ich habe mit dem Vermieter telefoniert.',
        why: 'Verbs ending in -ieren never take ge-: telefoniert, reserviert, funktioniert, studiert.',
      },
    ],
    exerciseIds: [
      'x.g.a2.perfekt.1',
      'x.g.a2.perfekt.2',
      'x.g.a2.perfekt.3',
      'x.g.a2.perfekt.4',
      'x.g.a2.perfekt.5',
      'x.g.a2.perfekt.6',
      'x.g.a2.perfekt.7',
      'x.g.a2.perfekt.8',
      'x.g.a2.perfekt.9',
    ],
    exercises: [
      {
        id: 'x.g.a2.perfekt.1',
        kind: 'blank',
        sentence: 'Ich ___ gestern acht Stunden gearbeitet.',
        options: ['habe', 'bin', 'hat', 'ist'],
        answer: 'habe',
        skill: 'verbs',
        difficulty: 1,
        tags: ['perfekt'],
        explain: 'arbeiten describes an activity, not a movement, so the auxiliary is haben — and it agrees with ich: habe.',
      },
      {
        id: 'x.g.a2.perfekt.2',
        kind: 'conjugate',
        verb: 'machen',
        person: 'Partizip II',
        answer: 'gemacht',
        skill: 'verbs',
        difficulty: 1,
        tags: ['perfekt'],
        explain: 'Regular verbs build the participle as ge- + stem + -t: mach- becomes gemacht. The same recipe gives gekauft and gelernt.',
      },
      {
        id: 'x.g.a2.perfekt.3',
        kind: 'blank',
        sentence: 'Wir ___ am Sonntag nach Dresden gefahren.',
        options: ['sind', 'haben', 'seid', 'ist'],
        answer: 'sind',
        skill: 'verbs',
        difficulty: 2,
        tags: ['perfekt'],
        hint: 'Does anybody change place here?',
        explain: 'fahren is a movement verb, so it takes sein — and the auxiliary still has to match the subject wir: sind.',
      },
      {
        id: 'x.g.a2.perfekt.4',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: [
          'Wir haben gestern Abend zusammen gekocht.',
          'Wir haben gestern Abend zusammen kochen.',
          'Wir sind gestern Abend zusammen gekocht.',
        ],
        answer: 0,
        skill: 'verbs',
        difficulty: 2,
        tags: ['perfekt'],
        explain: 'The Perfekt needs a participle, not an infinitive, and kochen is an activity — so haben plus gekocht.',
      },
      {
        id: 'x.g.a2.perfekt.5',
        kind: 'order',
        tokens: ['ich', 'habe', 'am Montag', 'einen Termin', 'beim Arzt', 'gemacht'],
        answer: 'Ich habe am Montag einen Termin beim Arzt gemacht.',
        accept: ['Am Montag habe ich einen Termin beim Arzt gemacht.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['perfekt', 'wortstellung'],
        explain: 'habe stays in position 2 and gemacht at the very end; the time, object and place phrases all live inside that bracket.',
      },
      {
        id: 'x.g.a2.perfekt.6',
        kind: 'correct',
        wrong: 'Ich habe gestern mit der Chefin getelefoniert.',
        answer: 'Ich habe gestern mit der Chefin telefoniert.',
        skill: 'verbs',
        difficulty: 2,
        tags: ['perfekt'],
        explain: 'Verbs in -ieren form the participle without ge-: telefoniert, reserviert, studiert. The stress is on -iert, and ge- never sits on an unstressed syllable.',
      },
      {
        id: 'x.g.a2.perfekt.7',
        kind: 'blank',
        sentence: 'Ich habe die E-Mail schon an den Kunden ___.',
        answer: 'geschickt',
        skill: 'verbs',
        difficulty: 2,
        tags: ['perfekt'],
        hint: 'schicken',
        explain: 'schicken is regular, so the participle is ge- + schick- + -t = geschickt, and it goes to the end of the sentence.',
      },
      {
        id: 'x.g.a2.perfekt.8',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'Yesterday I bought bread and milk at the supermarket.',
        answer: 'Gestern habe ich im Supermarkt Brot und Milch gekauft.',
        accept: ['Ich habe gestern im Supermarkt Brot und Milch gekauft.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['perfekt', 'wortstellung'],
        hint: 'If you start with gestern, the subject moves behind the verb.',
        explain: 'Whatever opens the sentence, habe is the second element and gekauft the last word — that bracket is the heart of the Perfekt.',
      },
      {
        id: 'x.g.a2.perfekt.9',
        kind: 'dialogue',
        lines: [
          { who: 'Kollege', text: 'Was hast du am Wochenende gemacht?' },
          { who: 'Du', text: '___' },
        ],
        options: [
          'Ich bin mit dem Rad an den See gefahren.',
          'Ich habe mit dem Rad an den See gefahren.',
          'Ich bin mit dem Rad an den See gefahrt.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 3,
        tags: ['perfekt'],
        explain: 'fahren takes sein and its participle is irregular: gefahren, not "gefahrt". Answer a Perfekt question in the Perfekt.',
      },
    ],
  },

  /* ── 2. Irregular participles ─────────────────────────────────────────── */
  {
    id: 'g.a2.perfekt-unregelmaessig',
    level: 'A2',
    title: 'Irregular past participles',
    titleDe: 'Unregelmäßige Partizipien',
    short: 'The most common verbs end in -en and often change their vowel. Learn them as a list.',
    tags: ['perfekt'],
    skill: 'verbs',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'Strong verbs build the participle with **ge- … -en** and often change the stem vowel: *trinken → getrunken*. There is no rule — learn each verb together with its auxiliary.',
      },
      {
        kind: 'table',
        head: ['Infinitiv', 'Perfekt', 'English'],
        rows: [
          ['essen', 'hat gegessen', 'to eat'],
          ['trinken', 'hat getrunken', 'to drink'],
          ['nehmen', 'hat genommen', 'to take'],
          ['schreiben', 'hat geschrieben', 'to write'],
          ['sprechen', 'hat gesprochen', 'to speak'],
          ['gehen', 'ist gegangen', 'to go'],
          ['bleiben', 'ist geblieben', 'to stay'],
          ['sein', 'ist gewesen', 'to be'],
        ],
      },
      {
        kind: 'tip',
        text: 'A few verbs mix both patterns: *bringen → gebracht*, *denken → gedacht*, *kennen → gekannt* — new vowel, but the regular **-t**.',
      },
      {
        kind: 'warn',
        text: '**bleiben**, **sein** and **passieren** take **sein** although nobody moves: *Ich bin zu Hause geblieben.*',
      },
    ],
    examples: [
      {
        de: 'Ich habe den Termin leider vergessen.',
        en: 'Unfortunately I forgot the appointment.',
        note: 'vergessen has the inseparable prefix ver-, so there is no ge-: vergessen.',
      },
      { de: 'Wir sind gestern lange im Büro geblieben.', en: 'We stayed at the office for a long time yesterday.' },
      { de: 'Was hast du zum Mittagessen gegessen?', en: 'What did you eat for lunch?' },
      { de: 'Der Chef hat mir heute eine E-Mail geschrieben.', en: 'The boss wrote me an email today.' },
    ],
    pitfalls: [
      {
        wrong: 'Ich habe einen Kaffee getrinkt.',
        right: 'Ich habe einen Kaffee getrunken.',
        why: 'Strong verbs end in -en, not -t, and trinken also swaps i for u: getrunken.',
      },
      {
        wrong: 'Wir haben zwei Stunden im Café geblieben.',
        right: 'Wir sind zwei Stunden im Café geblieben.',
        why: 'bleiben takes sein even though nobody goes anywhere — it is one of the fixed exceptions.',
      },
      {
        wrong: 'Ich habe den Schlüssel nicht gefindet.',
        right: 'Ich habe den Schlüssel nicht gefunden.',
        why: 'finden is strong: the vowel changes to u and the ending is -en, giving gefunden.',
      },
    ],
    exerciseIds: [
      'x.g.a2.perfekt-unregelmaessig.1',
      'x.g.a2.perfekt-unregelmaessig.2',
      'x.g.a2.perfekt-unregelmaessig.3',
      'x.g.a2.perfekt-unregelmaessig.4',
      'x.g.a2.perfekt-unregelmaessig.5',
      'x.g.a2.perfekt-unregelmaessig.6',
      'x.g.a2.perfekt-unregelmaessig.7',
      'x.g.a2.perfekt-unregelmaessig.8',
      'x.g.a2.perfekt-unregelmaessig.9',
    ],
    exercises: [
      {
        id: 'x.g.a2.perfekt-unregelmaessig.1',
        kind: 'blank',
        sentence: 'Ich habe heute schon drei Tassen Kaffee ___.',
        options: ['getrunken', 'getrinkt', 'getrunkt', 'trinken'],
        answer: 'getrunken',
        skill: 'verbs',
        difficulty: 1,
        tags: ['perfekt'],
        explain: 'trinken is strong: the vowel becomes u and the ending stays -en. Strong participles never end in -t.',
      },
      {
        id: 'x.g.a2.perfekt-unregelmaessig.2',
        kind: 'conjugate',
        verb: 'gehen',
        person: 'Partizip II',
        answer: 'gegangen',
        skill: 'verbs',
        difficulty: 1,
        tags: ['perfekt'],
        explain: 'gehen doubles its irregularity — new stem gang- plus the strong ending -en: gegangen (with sein).',
      },
      {
        id: 'x.g.a2.perfekt-unregelmaessig.3',
        kind: 'blank',
        sentence: 'Wir ___ bis acht Uhr im Büro geblieben.',
        options: ['sind', 'haben', 'seid', 'ist'],
        answer: 'sind',
        skill: 'verbs',
        difficulty: 2,
        tags: ['perfekt'],
        explain: 'bleiben belongs to the small sein group even though it means the opposite of moving. Learn it next to gehen and kommen.',
      },
      {
        id: 'x.g.a2.perfekt-unregelmaessig.4',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: [
          'Hast du meine E-Mail schon gelesen?',
          'Hast du meine E-Mail schon gelest?',
          'Bist du meine E-Mail schon gelesen?',
        ],
        answer: 0,
        skill: 'verbs',
        difficulty: 2,
        tags: ['perfekt'],
        explain: 'lesen is strong, so the participle keeps -en: gelesen. Reading is an activity, so the auxiliary is haben.',
      },
      {
        id: 'x.g.a2.perfekt-unregelmaessig.5',
        kind: 'match',
        pairs: [
          ['essen', 'hat gegessen'],
          ['nehmen', 'hat genommen'],
          ['schreiben', 'hat geschrieben'],
          ['gehen', 'ist gegangen'],
        ],
        skill: 'verbs',
        difficulty: 2,
        tags: ['perfekt'],
        explain: 'Always store a strong verb with its auxiliary, not just its participle — "ist gegangen" is one unit in your memory.',
      },
      {
        id: 'x.g.a2.perfekt-unregelmaessig.6',
        kind: 'correct',
        wrong: 'Ich habe den Bus um sieben genommt.',
        answer: 'Ich habe den Bus um sieben genommen.',
        skill: 'verbs',
        difficulty: 2,
        tags: ['perfekt'],
        explain: 'nehmen is strong: genommen with -en. Adding the regular -t to a strong stem is the classic learner mistake.',
      },
      {
        id: 'x.g.a2.perfekt-unregelmaessig.7',
        kind: 'order',
        tokens: ['gestern', 'hat', 'mir', 'meine Kollegin', 'geholfen'],
        answer: 'Gestern hat mir meine Kollegin geholfen.',
        accept: ['Meine Kollegin hat mir gestern geholfen.'],
        skill: 'wordorder',
        difficulty: 3,
        tags: ['perfekt', 'wortstellung'],
        explain: 'helfen takes a dative object (mir) and the strong participle geholfen, which stays last whatever opens the sentence.',
      },
      {
        id: 'x.g.a2.perfekt-unregelmaessig.8',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'I slept badly last night.',
        answer: 'Ich habe letzte Nacht schlecht geschlafen.',
        accept: ['Letzte Nacht habe ich schlecht geschlafen.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['perfekt'],
        hint: 'schlafen is strong — and sleeping is not a movement.',
        explain: 'schlafen keeps its vowel but takes the strong ending: geschlafen. It is an activity, so the auxiliary is haben.',
      },
      {
        id: 'x.g.a2.perfekt-unregelmaessig.9',
        kind: 'dialogue',
        lines: [
          { who: 'Ärztin', text: 'Was haben Sie heute gegessen?' },
          { who: 'Patient', text: '___' },
        ],
        options: [
          'Ich habe nur eine Suppe gegessen.',
          'Ich habe nur eine Suppe geesst.',
          'Ich bin nur eine Suppe gegessen.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 3,
        tags: ['perfekt'],
        explain: 'essen already has a double s in the stem, so the participle is gegessen — irregular, with haben.',
      },
    ],
  },

  /* ── 3. Modal verbs in full ───────────────────────────────────────────── */
  {
    id: 'g.a2.modalverben',
    level: 'A2',
    title: 'Modal verbs in full (incl. Präteritum konnte/musste/wollte)',
    titleDe: 'Die Modalverben',
    short: 'können, müssen, wollen, dürfen, sollen, möchten — and their simple past forms.',
    tags: ['modalverben'],
    skill: 'verbs',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'A modal verb stands in position 2 and pushes the main verb, as an infinitive, to the end: *Ich muss heute länger arbeiten.* **ich** and **er/sie/es** never take an ending.',
      },
      {
        kind: 'table',
        head: ['Person', 'können', 'müssen', 'wollen', 'dürfen', 'sollen'],
        rows: [
          ['ich', 'kann', 'muss', 'will', 'darf', 'soll'],
          ['du', 'kannst', 'musst', 'willst', 'darfst', 'sollst'],
          ['er / sie / es', 'kann', 'muss', 'will', 'darf', 'soll'],
          ['wir / sie / Sie', 'können', 'müssen', 'wollen', 'dürfen', 'sollen'],
          ['ihr', 'könnt', 'müsst', 'wollt', 'dürft', 'sollt'],
        ],
      },
      {
        kind: 'text',
        text: 'For the past, modals use short **-te** forms instead of the Perfekt.',
      },
      {
        kind: 'table',
        head: ['heute', 'gestern'],
        rows: [
          ['ich kann', 'ich konnte'],
          ['ich muss', 'ich musste'],
          ['ich will', 'ich wollte'],
          ['ich darf', 'ich durfte'],
          ['ich soll', 'ich sollte'],
        ],
      },
      {
        kind: 'tip',
        text: '**möchten** (*would like*) is the polite one: *Ich möchte bitte einen Kaffee.*',
      },
      {
        kind: 'warn',
        text: '**nicht müssen** means *do not have to*. For *must not* you need **nicht dürfen**: *Hier darf man nicht parken.*',
      },
    ],
    examples: [
      {
        de: 'Ich muss morgen früh zum Arzt.',
        en: 'I have to go to the doctor early tomorrow.',
        note: 'With a clear destination Germans often leave gehen or fahren out after a modal.',
      },
      { de: 'Können Sie mir bitte helfen?', en: 'Could you help me, please?' },
      {
        de: 'Letzte Woche musste ich zwei Tage im Homeoffice arbeiten.',
        en: 'Last week I had to work from home for two days.',
        note: 'musste is the past of muss — modals do not use the Perfekt here.',
      },
      { de: 'Hier darf man nicht parken.', en: 'You are not allowed to park here.' },
    ],
    pitfalls: [
      {
        wrong: 'Ich muss zum Arzt gehe.',
        right: 'Ich muss zum Arzt gehen.',
        why: 'Only the modal is conjugated. The second verb stays in the infinitive and waits at the end.',
      },
      {
        wrong: 'Ich kanne dir am Freitag helfen.',
        right: 'Ich kann dir am Freitag helfen.',
        why: 'Modals take no ending in the ich and er/sie/es forms: ich kann, er muss, sie will.',
      },
      {
        wrong: 'Du musst hier nicht rauchen, das ist verboten.',
        right: 'Du darfst hier nicht rauchen, das ist verboten.',
        why: 'nicht müssen only says something is unnecessary. A ban needs nicht dürfen.',
      },
    ],
    exerciseIds: [
      'x.g.a2.modalverben.1',
      'x.g.a2.modalverben.2',
      'x.g.a2.modalverben.3',
      'x.g.a2.modalverben.4',
      'x.g.a2.modalverben.5',
      'x.g.a2.modalverben.6',
      'x.g.a2.modalverben.7',
      'x.g.a2.modalverben.8',
      'x.g.a2.modalverben.9',
    ],
    exercises: [
      {
        id: 'x.g.a2.modalverben.1',
        kind: 'conjugate',
        verb: 'können',
        person: 'ich',
        answer: 'kann',
        skill: 'verbs',
        difficulty: 1,
        tags: ['modalverben'],
        explain: 'Modals lose the umlaut and take no ending in the ich form: ich kann, ich muss, ich darf.',
      },
      {
        id: 'x.g.a2.modalverben.2',
        kind: 'blank',
        sentence: 'Wir ___ am Freitag leider nicht kommen.',
        options: ['können', 'könnt', 'kann', 'konnten'],
        answer: 'können',
        skill: 'verbs',
        difficulty: 1,
        tags: ['modalverben'],
        explain: 'wir takes -en, so the modal looks like the infinitive — and kommen stays an infinitive at the end.',
      },
      {
        id: 'x.g.a2.modalverben.3',
        kind: 'blank',
        sentence: 'Guten Tag, ich ___ bitte einen Termin für Montag.',
        options: ['möchte', 'möchtest', 'möchten', 'mag'],
        answer: 'möchte',
        skill: 'verbs',
        difficulty: 2,
        tags: ['modalverben'],
        explain: 'möchte is the polite way to ask for something. It is the one modal whose ich form ends in -e: ich möchte, du möchtest, er möchte.',
      },
      {
        id: 'x.g.a2.modalverben.4',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: [
          'Ich muss heute länger arbeiten.',
          'Ich muss heute länger arbeite.',
          'Ich musse heute länger arbeiten.',
        ],
        answer: 0,
        skill: 'verbs',
        difficulty: 2,
        tags: ['modalverben'],
        explain: 'Two rules at once: the modal has no ending with ich (muss), and the second verb keeps its infinitive form at the end.',
      },
      {
        id: 'x.g.a2.modalverben.5',
        kind: 'blank',
        sentence: 'Letzten Montag ___ ich zwei Stunden auf den Bus warten.',
        options: ['musste', 'muss', 'musst', 'müssen'],
        answer: 'musste',
        skill: 'verbs',
        difficulty: 2,
        tags: ['modalverben'],
        hint: 'The time phrase points to the past.',
        explain: 'For past obligation German uses the short form musste, not a Perfekt — the same pattern gives konnte, wollte, durfte.',
      },
      {
        id: 'x.g.a2.modalverben.6',
        kind: 'correct',
        wrong: 'Du musst hier nicht rauchen, das ist verboten.',
        answer: 'Du darfst hier nicht rauchen, das ist verboten.',
        skill: 'verbs',
        difficulty: 2,
        tags: ['modalverben'],
        explain: 'nicht müssen = you do not need to; nicht dürfen = you are not allowed to. A prohibition always needs dürfen.',
      },
      {
        id: 'x.g.a2.modalverben.7',
        kind: 'order',
        tokens: ['am Samstag', 'wollen', 'wir', 'ins Kino', 'gehen'],
        answer: 'Am Samstag wollen wir ins Kino gehen.',
        accept: ['Wir wollen am Samstag ins Kino gehen.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['modalverben', 'wortstellung'],
        explain: 'The modal takes position 2 and the infinitive the last place — that bracket holds however you start the sentence.',
      },
      {
        id: 'x.g.a2.modalverben.8',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'Can you (formal) tell me where the station is?',
        answer: 'Können Sie mir sagen, wo der Bahnhof ist?',
        accept: ['Können Sie mir bitte sagen, wo der Bahnhof ist?'],
        skill: 'writing',
        difficulty: 3,
        tags: ['modalverben'],
        hint: 'sagen goes before the comma, not after it.',
        explain: 'The modal keeps its own infinitive (sagen) at the end of the main clause; the wo-clause that follows is a separate unit.',
      },
      {
        id: 'x.g.a2.modalverben.9',
        kind: 'dialogue',
        lines: [
          { who: 'Kollegin', text: 'Kommst du morgen zur Besprechung?' },
          { who: 'Du', text: '___' },
        ],
        options: [
          'Nein, ich muss leider zum Zahnarzt.',
          'Nein, ich muss leider zum Zahnarzt gehe.',
          'Nein, ich musse leider zum Zahnarzt.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 3,
        tags: ['modalverben'],
        explain: 'zum Zahnarzt already says "to the dentist", so gehen may be dropped — but if you add it, it must be the infinitive gehen.',
      },
    ],
  },

  /* ── 4. Reflexive verbs ───────────────────────────────────────────────── */
  {
    id: 'g.a2.reflexiv',
    level: 'A2',
    title: 'Reflexive verbs',
    titleDe: 'Reflexive Verben',
    short: 'sich freuen, sich beeilen, sich fühlen — verbs that always carry a little pronoun.',
    tags: ['reflexiv'],
    skill: 'verbs',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'Some verbs need a pronoun that points back at the subject: *Ich freue **mich**.* It normally stands directly after the conjugated verb.',
      },
      {
        kind: 'table',
        head: ['Person', 'Pronomen', 'Beispiel'],
        rows: [
          ['ich', 'mich', 'Ich beeile mich.'],
          ['du', 'dich', 'Beeil dich!'],
          ['er / sie / es', 'sich', 'Er fühlt sich nicht gut.'],
          ['wir', 'uns', 'Wir treffen uns um acht.'],
          ['ihr', 'euch', 'Setzt euch bitte.'],
          ['sie / Sie', 'sich', 'Bitte setzen Sie sich.'],
        ],
      },
      {
        kind: 'tip',
        text: 'If another object is already in the sentence, the pronoun switches to the dative: *Ich wasche **mir** die Hände.*',
      },
      {
        kind: 'warn',
        text: 'English drops the pronoun, German never does: *I am hurrying* = *Ich beeile **mich**.*',
      },
    ],
    examples: [
      { de: 'Ich muss mich beeilen, mein Bus fährt gleich.', en: 'I have to hurry, my bus is leaving in a moment.' },
      { de: 'Wir treffen uns um sieben vor dem Kino.', en: 'We are meeting at seven in front of the cinema.' },
      {
        de: 'Wie fühlen Sie sich heute?',
        en: 'How are you feeling today?',
        note: 'The polite Sie form keeps sich — the standard question at the doctor.',
      },
      {
        de: 'Ich habe mich für den Deutschkurs angemeldet.',
        en: 'I have registered for the German course.',
        note: 'In the Perfekt the pronoun comes straight after haben.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Ich freue auf das Wochenende.',
        right: 'Ich freue mich auf das Wochenende.',
        why: 'freuen cannot exist without its pronoun — the verb is listed in the dictionary as sich freuen.',
      },
      {
        wrong: 'Meine Kollegin fühlt mich nicht gut.',
        right: 'Meine Kollegin fühlt sich nicht gut.',
        why: 'The pronoun must match the subject. With er, sie, es and Sie it is always sich.',
      },
      {
        wrong: 'Ich wasche mich die Hände.',
        right: 'Ich wasche mir die Hände.',
        why: 'die Hände is already the accusative object, so the reflexive pronoun moves to the dative: mir.',
      },
    ],
    exerciseIds: [
      'x.g.a2.reflexiv.1',
      'x.g.a2.reflexiv.2',
      'x.g.a2.reflexiv.3',
      'x.g.a2.reflexiv.4',
      'x.g.a2.reflexiv.5',
      'x.g.a2.reflexiv.6',
      'x.g.a2.reflexiv.7',
      'x.g.a2.reflexiv.8',
      'x.g.a2.reflexiv.9',
    ],
    exercises: [
      {
        id: 'x.g.a2.reflexiv.1',
        kind: 'blank',
        sentence: 'Ich muss ___ beeilen, der Zug fährt in fünf Minuten.',
        options: ['mich', 'mir', 'sich', 'dich'],
        answer: 'mich',
        skill: 'verbs',
        difficulty: 1,
        tags: ['reflexiv'],
        explain: 'The pronoun always copies the subject: ich → mich. sich only belongs to er/sie/es and Sie.',
      },
      {
        id: 'x.g.a2.reflexiv.2',
        kind: 'blank',
        sentence: 'Wie fühlst du ___ heute?',
        options: ['dich', 'dir', 'sich', 'euch'],
        answer: 'dich',
        skill: 'verbs',
        difficulty: 1,
        tags: ['reflexiv'],
        explain: 'sich fühlen has no other object, so the pronoun stays accusative: du → dich.',
      },
      {
        id: 'x.g.a2.reflexiv.3',
        kind: 'blank',
        sentence: 'Wir treffen ___ am Samstag im Café.',
        options: ['uns', 'euch', 'sich', 'unser'],
        answer: 'uns',
        skill: 'verbs',
        difficulty: 2,
        tags: ['reflexiv'],
        explain: 'wir → uns. With sich treffen the pronoun also carries the meaning "each other": we meet one another.',
      },
      {
        id: 'x.g.a2.reflexiv.4',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: ['Bitte setzen Sie sich.', 'Bitte setzen Sie Ihnen.', 'Bitte sich setzen Sie.'],
        answer: 0,
        skill: 'verbs',
        difficulty: 2,
        tags: ['reflexiv'],
        explain: 'Formal Sie takes sich, not Ihnen, and the pronoun follows the subject. This is the standard phrase in every waiting room.',
      },
      {
        id: 'x.g.a2.reflexiv.5',
        kind: 'correct',
        wrong: 'Ich freue auf den Urlaub im Juli.',
        answer: 'Ich freue mich auf den Urlaub im Juli.',
        skill: 'verbs',
        difficulty: 2,
        tags: ['reflexiv'],
        explain: 'sich freuen auf is a fixed unit: the pronoun is part of the verb, and auf takes the accusative (den Urlaub).',
      },
      {
        id: 'x.g.a2.reflexiv.6',
        kind: 'blank',
        sentence: 'Ich wasche ___ vor dem Essen immer die Hände.',
        options: ['mir', 'mich', 'mein', 'sich'],
        answer: 'mir',
        skill: 'verbs',
        difficulty: 3,
        tags: ['reflexiv'],
        hint: 'Is there already an accusative object in the sentence?',
        explain: 'die Hände occupies the accusative slot, so the reflexive pronoun takes the dative instead: mir. Same with "Ich putze mir die Zähne."',
      },
      {
        id: 'x.g.a2.reflexiv.7',
        kind: 'order',
        tokens: ['ich', 'habe', 'mich', 'für den Kurs', 'angemeldet'],
        answer: 'Ich habe mich für den Kurs angemeldet.',
        skill: 'wordorder',
        difficulty: 2,
        tags: ['reflexiv', 'wortstellung'],
        explain: 'In the Perfekt the pronoun sits right after the auxiliary, and the participle still closes the sentence.',
      },
      {
        id: 'x.g.a2.reflexiv.8',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'My colleague is not feeling well today.',
        answer: 'Meine Kollegin fühlt sich heute nicht gut.',
        accept: ['Mein Kollege fühlt sich heute nicht gut.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['reflexiv'],
        hint: 'English has no pronoun here — German still needs one.',
        explain: 'sich fühlen always carries its pronoun, and with a third-person subject that pronoun is sich.',
      },
      {
        id: 'x.g.a2.reflexiv.9',
        kind: 'dialogue',
        lines: [
          { who: 'Empfang', text: 'Guten Tag, haben Sie sich schon angemeldet?' },
          { who: 'Patient', text: '___' },
        ],
        options: [
          'Ja, ich habe mich gerade angemeldet.',
          'Ja, ich habe sich gerade angemeldet.',
          'Ja, ich habe mich gerade anmelden.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 3,
        tags: ['reflexiv'],
        explain: 'Answering about yourself means switching sich to mich, and the Perfekt needs the participle angemeldet, not the infinitive.',
      },
    ],
  },

  /* ── 5. Separable and inseparable verbs ───────────────────────────────── */
  {
    id: 'g.a2.trennbar',
    level: 'A2',
    title: 'Separable and inseparable verbs',
    titleDe: 'Trennbare und untrennbare Verben',
    short: 'Some prefixes fly to the end of the sentence, others never move at all.',
    tags: ['trennbar'],
    skill: 'verbs',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'A **separable** prefix (*an-, auf-, aus-, ein-, mit-, ab-, zu-*) is stressed and jumps to the end of the clause: *Ich stehe um sechs **auf**.*',
      },
      {
        kind: 'text',
        text: 'An **inseparable** prefix (*be-, er-, ver-, ent-, ge-*) is unstressed and never moves: *Ich **be**zahle die Rechnung.*',
      },
      {
        kind: 'table',
        head: ['Verb', 'Präsens', 'Perfekt'],
        rows: [
          ['aufstehen', 'ich stehe auf', 'ich bin aufgestanden'],
          ['einkaufen', 'ich kaufe ein', 'ich habe eingekauft'],
          ['anrufen', 'ich rufe an', 'ich habe angerufen'],
          ['bezahlen', 'ich bezahle', 'ich habe bezahlt'],
          ['verstehen', 'ich verstehe', 'ich habe verstanden'],
        ],
      },
      {
        kind: 'tip',
        text: 'In the Perfekt the **ge-** slips inside a separable verb: *ein-ge-kauft*, *an-ge-rufen*. Inseparable verbs take no ge- at all.',
      },
      {
        kind: 'warn',
        text: 'After a modal the verb goes back together at the end: *Ich muss morgen früh aufstehen.*',
      },
    ],
    examples: [
      {
        de: 'Ich stehe während der Woche um halb sieben auf.',
        en: 'During the week I get up at half past six.',
        note: 'stehe is the second element, the prefix auf waits at the very end.',
      },
      { de: 'Rufst du mich heute Abend an?', en: 'Will you call me this evening?' },
      { de: 'Wir haben am Samstag im Supermarkt eingekauft.', en: 'We did the shopping at the supermarket on Saturday.' },
      {
        de: 'Ich habe die Rechnung schon bezahlt.',
        en: 'I have already paid the bill.',
        note: 'be- is inseparable, so the participle has no ge-: bezahlt.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Ich aufstehe jeden Tag um sechs Uhr.',
        right: 'Ich stehe jeden Tag um sechs Uhr auf.',
        why: 'In a main clause a separable verb splits: the conjugated part goes to position 2, the prefix to the end.',
      },
      {
        wrong: 'Ich habe die Miete schon gebezahlt.',
        right: 'Ich habe die Miete schon bezahlt.',
        why: 'An inseparable prefix blocks ge-. The same goes for verstanden, bekommen and erklärt.',
      },
      {
        wrong: 'Ich muss morgen früh stehe auf.',
        right: 'Ich muss morgen früh aufstehen.',
        why: 'After a modal the verb is not conjugated and not split — it stands at the end as one infinitive.',
      },
    ],
    exerciseIds: [
      'x.g.a2.trennbar.1',
      'x.g.a2.trennbar.2',
      'x.g.a2.trennbar.3',
      'x.g.a2.trennbar.4',
      'x.g.a2.trennbar.5',
      'x.g.a2.trennbar.6',
      'x.g.a2.trennbar.7',
      'x.g.a2.trennbar.8',
      'x.g.a2.trennbar.9',
    ],
    exercises: [
      {
        id: 'x.g.a2.trennbar.1',
        kind: 'blank',
        sentence: 'Ich ___ morgens um sechs Uhr auf.',
        options: ['stehe', 'aufstehe', 'stehen', 'steht'],
        answer: 'stehe',
        skill: 'verbs',
        difficulty: 1,
        tags: ['trennbar'],
        explain: 'Only the verb part is conjugated and put in position 2; the prefix auf is already waiting at the end.',
      },
      {
        id: 'x.g.a2.trennbar.2',
        kind: 'blank',
        sentence: 'Wann ___ der Zug in Köln an?',
        options: ['kommt', 'ankommt', 'kommen', 'kommst'],
        answer: 'kommt',
        skill: 'verbs',
        difficulty: 1,
        tags: ['trennbar'],
        explain: 'ankommen splits in questions too: kommt agrees with der Zug, and an stays at the end.',
      },
      {
        id: 'x.g.a2.trennbar.3',
        kind: 'order',
        tokens: ['ich', 'kaufe', 'am Samstag', 'im Supermarkt', 'ein'],
        answer: 'Ich kaufe am Samstag im Supermarkt ein.',
        accept: ['Am Samstag kaufe ich im Supermarkt ein.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['trennbar', 'wortstellung'],
        explain: 'The two halves of einkaufen form a bracket: kaufe in position 2, ein in last place, everything else in between.',
      },
      {
        id: 'x.g.a2.trennbar.4',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: [
          'Ich habe meinen Chef gestern angerufen.',
          'Ich habe meinen Chef gestern gerufen an.',
          'Ich habe meinen Chef gestern anrufen.',
        ],
        answer: 0,
        skill: 'verbs',
        difficulty: 2,
        tags: ['trennbar'],
        explain: 'In the Perfekt a separable verb becomes one word again with ge- in the middle: an + ge + rufen = angerufen.',
      },
      {
        id: 'x.g.a2.trennbar.5',
        kind: 'correct',
        wrong: 'Ich habe die Miete schon gebezahlt.',
        answer: 'Ich habe die Miete schon bezahlt.',
        skill: 'verbs',
        difficulty: 2,
        tags: ['trennbar'],
        explain: 'be- is unstressed and inseparable, and such verbs never add ge-: bezahlt, besucht, verstanden.',
      },
      {
        id: 'x.g.a2.trennbar.6',
        kind: 'blank',
        sentence: 'Wir haben gestern im Supermarkt ___.',
        answer: 'eingekauft',
        skill: 'verbs',
        difficulty: 2,
        tags: ['trennbar'],
        hint: 'einkaufen',
        explain: 'Put ge- between the prefix and the stem: ein + ge + kauft. The prefix never leaves the participle.',
      },
      {
        id: 'x.g.a2.trennbar.7',
        kind: 'match',
        pairs: [
          ['aufstehen', 'ist aufgestanden'],
          ['anrufen', 'hat angerufen'],
          ['bezahlen', 'hat bezahlt'],
          ['verstehen', 'hat verstanden'],
        ],
        skill: 'verbs',
        difficulty: 2,
        tags: ['trennbar'],
        explain: 'Compare the pairs: stressed prefixes keep ge- inside, unstressed ones drop it completely.',
      },
      {
        id: 'x.g.a2.trennbar.8',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'I have to get up early tomorrow because I have an appointment.',
        answer: 'Ich muss morgen früh aufstehen, weil ich einen Termin habe.',
        accept: ['Morgen muss ich früh aufstehen, weil ich einen Termin habe.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['trennbar'],
        hint: 'A modal keeps the separable verb in one piece.',
        explain: 'After muss the verb stays whole as aufstehen; in the weil-clause the conjugated habe moves to the very end.',
      },
      {
        id: 'x.g.a2.trennbar.9',
        kind: 'dialogue',
        lines: [
          { who: 'Kollegin', text: 'Wann fängt die Besprechung an?' },
          { who: 'Du', text: '___' },
        ],
        options: [
          'Sie fängt um zehn Uhr an.',
          'Sie anfängt um zehn Uhr.',
          'Sie fängt an um zehn Uhr.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 3,
        tags: ['trennbar'],
        explain: 'anfangen splits in the answer exactly as in the question: fängt in position 2, an in final place after the time.',
      },
    ],
  },
]

export default grammar
