/**
 * B1 — the four tense topics that move a learner past everyday small talk.
 *
 *   g.b1.praeteritum       Präteritum of common verbs
 *   g.b1.plusquamperfekt   Plusquamperfekt
 *   g.b1.futur             Futur I and talking about plans
 *   g.b1.passiv            The passive voice
 *
 * Plain data only. See ../SCHEMA.md.
 */

export const grammar = [
  /* ── 1. Präteritum ────────────────────────────────────────────────────── */
  {
    id: 'g.b1.praeteritum',
    level: 'B1',
    title: 'Präteritum of common verbs',
    titleDe: 'Das Präteritum der wichtigsten Verben',
    short:
      'The simple past. In speech Germans use the Perfekt — except for sein, haben, werden and the modal verbs.',
    tags: ['praeteritum'],
    skill: 'verbs',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'The **Präteritum** is the simple past. In conversation most verbs appear in the Perfekt, but **sein, haben, werden, the modal verbs** and **es gibt** almost always take the Präteritum.',
      },
      {
        kind: 'table',
        head: ['Verb', 'ich / er', 'du', 'wir / sie'],
        rows: [
          ['sein', 'war', 'warst', 'waren'],
          ['haben', 'hatte', 'hattest', 'hatten'],
          ['werden', 'wurde', 'wurdest', 'wurden'],
          ['können', 'konnte', 'konntest', 'konnten'],
          ['müssen', 'musste', 'musstest', 'mussten'],
          ['gehen', 'ging', 'gingst', 'gingen'],
        ],
      },
      {
        kind: 'tip',
        text: 'The **ich** and the **er/sie/es** form are always identical and carry no ending: *ich war – er war*, *ich musste – er musste*.',
      },
      {
        kind: 'warn',
        text: 'Modal verbs lose the umlaut: *müssen → musste*, *können → konnte*, *dürfen → durfte*. With umlaut (*müsste, könnte*) you are in Konjunktiv II.',
      },
    ],
    examples: [
      {
        de: 'Gestern war ich beim Arzt, aber ich hatte keinen Termin.',
        en: 'Yesterday I was at the doctor, but I did not have an appointment.',
        note: 'Nobody says "ich bin gewesen" or "ich habe gehabt" here — the Präteritum is the normal choice.',
      },
      {
        de: 'Wir mussten fast eine Stunde auf den Bus warten.',
        en: 'We had to wait almost an hour for the bus.',
      },
      {
        de: 'Es gab gestern kein frisches Brot mehr im Supermarkt.',
        en: 'There was no fresh bread left at the supermarket yesterday.',
        note: 'es gibt → es gab. The Perfekt "es hat gegeben" sounds odd in speech.',
      },
      {
        de: 'Als Kind wollte ich Busfahrerin werden.',
        en: 'As a child I wanted to become a bus driver.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Ich habe gestern leider keine Zeit gehabt.',
        right: 'Ich hatte gestern leider keine Zeit.',
        why: 'haben, sein and the modals keep the Präteritum even in spoken German. The Perfekt of these verbs sounds heavy and bookish.',
      },
      {
        wrong: 'Als Kind dürfte ich nicht lange fernsehen.',
        right: 'Als Kind durfte ich nicht lange fernsehen.',
        why: 'The Präteritum of a modal verb has no umlaut: durfte, konnte, musste. dürfte and könnte are Konjunktiv II and sound hypothetical.',
      },
      {
        wrong: 'Er gingte nach Hause.',
        right: 'Er ging nach Hause.',
        why: 'Strong verbs change their stem instead of adding -te, and the er form takes no ending: gehen → ging, kommen → kam, fahren → fuhr.',
      },
    ],
    exerciseIds: [
      'x.g.b1.praeteritum.1',
      'x.g.b1.praeteritum.2',
      'x.g.b1.praeteritum.3',
      'x.g.b1.praeteritum.4',
      'x.g.b1.praeteritum.5',
      'x.g.b1.praeteritum.6',
      'x.g.b1.praeteritum.7',
      'x.g.b1.praeteritum.8',
      'x.g.b1.praeteritum.9',
    ],
    exercises: [
      {
        id: 'x.g.b1.praeteritum.1',
        kind: 'conjugate',
        verb: 'sein',
        person: 'wir (Präteritum)',
        answer: 'waren',
        skill: 'verbs',
        difficulty: 1,
        tags: ['praeteritum'],
        explain: 'sein builds its Präteritum on the stem war- and adds the normal endings: wir/sie waren, ihr wart, du warst.',
      },
      {
        id: 'x.g.b1.praeteritum.2',
        kind: 'blank',
        sentence: 'Als Kind ___ ich jeden Sommer bei meinen Großeltern.',
        options: ['war', 'bin', 'wäre', 'bin gewesen'],
        answer: 'war',
        skill: 'verbs',
        difficulty: 1,
        tags: ['praeteritum'],
        explain: 'Talking about your past life takes the Präteritum of sein: ich war. wäre is Konjunktiv II and would mean "would be".',
      },
      {
        id: 'x.g.b1.praeteritum.3',
        kind: 'blank',
        sentence: 'Gestern ___ ich leider keine Zeit für den Termin.',
        options: ['hatte', 'habe', 'hätte', 'hatten'],
        answer: 'hatte',
        skill: 'verbs',
        difficulty: 2,
        tags: ['praeteritum'],
        explain: 'haben forms the Präteritum with hatt- + ending, and ich takes no ending at all: ich hatte, er hatte. hätte is Konjunktiv II.',
      },
      {
        id: 'x.g.b1.praeteritum.4',
        kind: 'conjugate',
        verb: 'müssen',
        person: 'er (Präteritum)',
        answer: 'musste',
        skill: 'verbs',
        difficulty: 2,
        tags: ['praeteritum'],
        hint: 'The umlaut disappears.',
        explain: 'Modal verbs drop the umlaut and add -te in the Präteritum: müssen → musste, können → konnte, dürfen → durfte.',
      },
      {
        id: 'x.g.b1.praeteritum.5',
        kind: 'mcq',
        prompt: 'Which sentence sounds natural in spoken German?',
        options: [
          'Ich hatte gestern starke Kopfschmerzen.',
          'Ich habe gestern starke Kopfschmerzen gehabt.',
          'Ich bin gestern starke Kopfschmerzen gehabt.',
        ],
        answer: 0,
        skill: 'verbs',
        difficulty: 2,
        tags: ['praeteritum'],
        explain: 'haben, sein and the modals stay in the Präteritum even in conversation, and haben never builds its Perfekt with sein.',
      },
      {
        id: 'x.g.b1.praeteritum.6',
        kind: 'order',
        tokens: ['letzte Woche', 'musste', 'ich', 'zweimal', 'zum', 'Zahnarzt', 'gehen'],
        answer: 'Letzte Woche musste ich zweimal zum Zahnarzt gehen.',
        accept: ['Ich musste letzte Woche zweimal zum Zahnarzt gehen.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['praeteritum', 'wortstellung'],
        explain: 'musste is the conjugated verb, so it takes position 2 wherever you start; the infinitive gehen closes the sentence bracket at the end.',
      },
      {
        id: 'x.g.b1.praeteritum.7',
        kind: 'correct',
        wrong: 'Ich könnte gestern nicht zur Besprechung kommen.',
        answer: 'Ich konnte gestern nicht zur Besprechung kommen.',
        skill: 'verbs',
        difficulty: 3,
        tags: ['praeteritum'],
        explain: 'A real past fact needs konnte without umlaut. The umlaut turns the form into Konjunktiv II, which talks about something unreal.',
      },
      {
        id: 'x.g.b1.praeteritum.8',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'There was no milk left in the fridge, so I had to go shopping.',
        answer: 'Es gab keine Milch mehr im Kühlschrank, deshalb musste ich einkaufen gehen.',
        accept: ['Im Kühlschrank gab es keine Milch mehr, deshalb musste ich einkaufen gehen.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['praeteritum'],
        hint: 'es gibt → es gab',
        explain: 'es gibt becomes es gab in the past, and deshalb is a main-clause connector: the verb musste follows it directly in position 2.',
      },
      {
        id: 'x.g.b1.praeteritum.9',
        kind: 'dialogue',
        lines: [
          { who: 'Kollegin', text: 'Warum warst du gestern nicht im Büro?' },
          { who: 'Du', text: '___' },
        ],
        options: [
          'Ich war krank und musste zum Arzt.',
          'Ich bin krank und muss zum Arzt.',
          'Ich wäre krank und müsste zum Arzt.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 2,
        tags: ['praeteritum'],
        explain: 'The question is in the Präteritum (warst), so the answer stays in the past: war und musste. wäre/müsste are Konjunktiv II and sound hypothetical.',
      },
    ],
  },

  /* ── 2. Plusquamperfekt ───────────────────────────────────────────────── */
  {
    id: 'g.b1.plusquamperfekt',
    level: 'B1',
    title: 'Plusquamperfekt',
    titleDe: 'Das Plusquamperfekt',
    short: 'The past before the past: hatte or war plus Partizip II. Its natural home is the nachdem-clause.',
    tags: ['plusquamperfekt'],
    skill: 'verbs',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'The **Plusquamperfekt** is the past before the past. Build it exactly like the Perfekt, but put *haben* or *sein* into the Präteritum: **hatte / war + Partizip II**.',
      },
      {
        kind: 'table',
        head: ['Perfekt', 'Plusquamperfekt'],
        rows: [
          ['ich habe gearbeitet', 'ich hatte gearbeitet'],
          ['er hat vergessen', 'er hatte vergessen'],
          ['wir sind gefahren', 'wir waren gefahren'],
          ['sie ist angekommen', 'sie war angekommen'],
        ],
      },
      {
        kind: 'tip',
        text: 'It lives with **nachdem**: *Nachdem ich gefrühstückt hatte, fuhr ich ins Büro.* The nachdem-clause is Plusquamperfekt, the main clause Präteritum or Perfekt.',
      },
      {
        kind: 'warn',
        text: 'The auxiliary never changes: a verb that takes *sein* in the Perfekt takes *war* here — *ich war gegangen*, not *ich hatte gegangen*.',
      },
    ],
    examples: [
      {
        de: 'Nachdem ich die Mail geschrieben hatte, ging ich in die Mittagspause.',
        en: 'After I had written the email, I went for my lunch break.',
      },
      {
        de: 'Der Zug war schon abgefahren, als wir am Bahnhof ankamen.',
        en: 'The train had already left when we arrived at the station.',
        note: 'The earlier event takes the Plusquamperfekt, the later one the Präteritum.',
      },
      {
        de: 'Ich hatte den Termin völlig vergessen und musste noch einmal anrufen.',
        en: 'I had completely forgotten the appointment and had to call again.',
      },
      {
        de: 'Sie hatte drei Jahre in Wien gewohnt, bevor sie nach Berlin zog.',
        en: 'She had lived in Vienna for three years before she moved to Berlin.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Nachdem wir das Formular abgegeben haben, bekamen wir einen Termin.',
        right: 'Nachdem wir das Formular abgegeben hatten, bekamen wir einen Termin.',
        why: 'nachdem always pushes the earlier action one step further back: Plusquamperfekt in the nachdem-clause, Präteritum in the main clause.',
      },
      {
        wrong: 'Ich hatte schon nach Hause gegangen.',
        right: 'Ich war schon nach Hause gegangen.',
        why: 'gehen takes sein in the Perfekt (ich bin gegangen), so the Plusquamperfekt uses war, never hatte.',
      },
      {
        wrong: 'Nachdem ich hatte geduscht, machte ich mir einen Kaffee.',
        right: 'Nachdem ich geduscht hatte, machte ich mir einen Kaffee.',
        why: 'In a subordinate clause the conjugated verb comes last of all, so the participle geduscht stands in front of hatte.',
      },
    ],
    exerciseIds: [
      'x.g.b1.plusquamperfekt.1',
      'x.g.b1.plusquamperfekt.2',
      'x.g.b1.plusquamperfekt.3',
      'x.g.b1.plusquamperfekt.4',
      'x.g.b1.plusquamperfekt.5',
      'x.g.b1.plusquamperfekt.6',
      'x.g.b1.plusquamperfekt.7',
      'x.g.b1.plusquamperfekt.8',
    ],
    exercises: [
      {
        id: 'x.g.b1.plusquamperfekt.1',
        kind: 'blank',
        sentence: 'Als ich ankam, ___ das Meeting schon begonnen.',
        options: ['hatte', 'war', 'ist', 'wird'],
        answer: 'hatte',
        skill: 'verbs',
        difficulty: 1,
        tags: ['plusquamperfekt'],
        explain: 'beginnen takes haben in the Perfekt (hat begonnen), so the step further back is hatte begonnen — the meeting started before you arrived.',
      },
      {
        id: 'x.g.b1.plusquamperfekt.2',
        kind: 'blank',
        sentence: 'Der Bus ___ schon abgefahren, als wir an der Haltestelle ankamen.',
        options: ['war', 'hatte', 'wurde', 'ist gewesen'],
        answer: 'war',
        skill: 'verbs',
        difficulty: 1,
        tags: ['plusquamperfekt'],
        explain: 'abfahren is a movement verb and takes sein: ist abgefahren in the Perfekt, war abgefahren in the Plusquamperfekt.',
      },
      {
        id: 'x.g.b1.plusquamperfekt.3',
        kind: 'mcq',
        prompt: 'Which sentence is correct?',
        options: [
          'Nachdem ich gegessen hatte, ging ich spazieren.',
          'Nachdem ich gegessen habe, ging ich spazieren.',
          'Nachdem ich hatte gegessen, ging ich spazieren.',
        ],
        answer: 0,
        skill: 'verbs',
        difficulty: 2,
        tags: ['plusquamperfekt', 'nebensatz'],
        explain: 'nachdem needs the Plusquamperfekt for the earlier action, and in a subordinate clause the finite verb hatte stands at the very end.',
      },
      {
        id: 'x.g.b1.plusquamperfekt.4',
        kind: 'order',
        tokens: ['nachdem', 'wir', 'den', 'Vertrag', 'unterschrieben', 'hatten', 'tranken', 'wir', 'einen', 'Kaffee'],
        answer: 'Nachdem wir den Vertrag unterschrieben hatten, tranken wir einen Kaffee.',
        skill: 'wordorder',
        difficulty: 2,
        tags: ['plusquamperfekt', 'nebensatz'],
        explain: 'In the nachdem-clause hatten goes last. That whole clause then fills position 1, so the main clause has to start with its verb tranken.',
      },
      {
        id: 'x.g.b1.plusquamperfekt.5',
        kind: 'correct',
        wrong: 'Wir waren schon gegessen, als die Gäste kamen.',
        answer: 'Wir hatten schon gegessen, als die Gäste kamen.',
        skill: 'verbs',
        difficulty: 2,
        tags: ['plusquamperfekt'],
        explain: 'essen takes haben (wir haben gegessen), so its Plusquamperfekt is hatten gegessen. Only movement and change-of-state verbs use sein.',
      },
      {
        id: 'x.g.b1.plusquamperfekt.6',
        kind: 'blank',
        sentence: 'Sie war sehr müde, weil sie die ganze Nacht ___ hatte.',
        answer: 'gearbeitet',
        skill: 'verbs',
        difficulty: 2,
        tags: ['plusquamperfekt'],
        hint: 'arbeiten',
        explain: 'hatte + Partizip II makes the Plusquamperfekt; regular verbs form the participle with ge- … -t, so arbeiten becomes gearbeitet.',
      },
      {
        id: 'x.g.b1.plusquamperfekt.7',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'After I had sent the email, the boss called.',
        answer: 'Nachdem ich die Mail geschickt hatte, rief der Chef an.',
        accept: ['Nachdem ich die E-Mail geschickt hatte, rief der Chef an.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['plusquamperfekt'],
        hint: 'nachdem + Plusquamperfekt, then Präteritum.',
        explain: 'nachdem forces the Plusquamperfekt for the earlier action, and the separable verb anrufen splits in the Präteritum: rief … an.',
      },
      {
        id: 'x.g.b1.plusquamperfekt.8',
        kind: 'dialogue',
        lines: [
          { who: 'Anna', text: 'Warum bist du gestern nicht mitgekommen?' },
          { who: 'Ben', text: '___' },
        ],
        options: [
          'Ich hatte den Termin völlig vergessen.',
          'Ich war den Termin völlig vergessen.',
          'Ich hatte den Termin völlig vergessen gehabt.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 3,
        tags: ['plusquamperfekt'],
        explain: 'vergessen takes haben, so the form is hatte vergessen. A doubled participle like "vergessen gehabt" is not standard German.',
      },
    ],
  },

  /* ── 3. Futur I ───────────────────────────────────────────────────────── */
  {
    id: 'g.b1.futur',
    level: 'B1',
    title: 'Futur I and talking about plans',
    titleDe: 'Futur I und über Pläne sprechen',
    short: 'German usually says the future with the present tense. Futur I is for promises, predictions and guesses.',
    tags: ['futur'],
    skill: 'verbs',
    difficulty: 2,
    explain: [
      {
        kind: 'text',
        text: 'For fixed plans German simply uses the **present tense plus a time word**: *Morgen fahre ich nach Köln.* **Futur I** — *werden* + Infinitiv — is for predictions, promises and firm intentions.',
      },
      {
        kind: 'table',
        head: ['Person', 'werden', 'Beispiel'],
        rows: [
          ['ich', 'werde', 'Ich werde dich anrufen.'],
          ['du', 'wirst', 'Du wirst das schaffen.'],
          ['er / sie / es', 'wird', 'Es wird morgen regnen.'],
          ['wir', 'werden', 'Wir werden pünktlich sein.'],
          ['ihr', 'werdet', 'Ihr werdet viel lernen.'],
          ['sie / Sie', 'werden', 'Die Preise werden steigen.'],
        ],
      },
      {
        kind: 'tip',
        text: 'Only *werden* is conjugated. The infinitive always closes the sentence: *Ich werde dich morgen im Büro anrufen.*',
      },
      {
        kind: 'warn',
        text: 'With **wohl**, **sicher** or **bestimmt**, Futur I is a guess about *now*: *Er wird wohl im Stau stehen.* = He is probably stuck in traffic.',
      },
    ],
    examples: [
      {
        de: 'Nächste Woche fange ich bei der neuen Firma an.',
        en: 'Next week I start at the new company.',
        note: 'Present tense plus a time word — the everyday way to talk about the future.',
      },
      {
        de: 'Ich werde Ihnen die Unterlagen bis Freitag schicken.',
        en: 'I will send you the documents by Friday.',
        note: 'Futur I sounds binding, so it is perfect for a promise at work.',
      },
      {
        de: 'Es wird morgen wahrscheinlich den ganzen Tag regnen.',
        en: 'It will probably rain all day tomorrow.',
      },
      {
        de: 'Meine Kollegin wird wohl noch im Meeting sein.',
        en: 'My colleague is probably still in the meeting.',
        note: 'werden + wohl guesses about the present, not the future.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Ich will dich morgen anrufen.',
        right: 'Ich werde dich morgen anrufen.',
        why: 'For "I will …" German needs werden. will is a false friend: it means "want to", not "will".',
      },
      {
        wrong: 'Ich werde morgen anrufen dich.',
        right: 'Ich werde dich morgen anrufen.',
        why: 'The infinitive closes the sentence bracket, so nothing may follow it — objects and time phrases stand in front of anrufen.',
      },
      {
        wrong: 'Wir werden nächstes Jahr nach Bremen gezogen.',
        right: 'Wir werden nächstes Jahr nach Bremen ziehen.',
        why: 'Futur I takes the bare infinitive. werden + Partizip II is the passive and would say something completely different.',
      },
    ],
    exerciseIds: [
      'x.g.b1.futur.1',
      'x.g.b1.futur.2',
      'x.g.b1.futur.3',
      'x.g.b1.futur.4',
      'x.g.b1.futur.5',
      'x.g.b1.futur.6',
      'x.g.b1.futur.7',
      'x.g.b1.futur.8',
      'x.g.b1.futur.9',
    ],
    exercises: [
      {
        id: 'x.g.b1.futur.1',
        kind: 'conjugate',
        verb: 'werden',
        person: 'du',
        answer: 'wirst',
        skill: 'verbs',
        difficulty: 1,
        tags: ['futur'],
        explain: 'werden is irregular in exactly two forms, du wirst and er/sie/es wird; the other four are perfectly regular.',
      },
      {
        id: 'x.g.b1.futur.2',
        kind: 'blank',
        sentence: 'Ich ___ dir morgen die neue Adresse schicken.',
        options: ['werde', 'wirst', 'wird', 'werdet'],
        answer: 'werde',
        skill: 'verbs',
        difficulty: 1,
        tags: ['futur'],
        explain: 'In Futur I only werden carries the person ending, so ich → werde. The main verb stays an infinitive at the end.',
      },
      {
        id: 'x.g.b1.futur.3',
        kind: 'mcq',
        prompt: 'Which sentence means "I will call you tomorrow"?',
        options: [
          'Ich werde dich morgen anrufen.',
          'Ich will dich morgen anrufen.',
          'Ich möchte dich morgen anrufen.',
        ],
        answer: 0,
        skill: 'verbs',
        difficulty: 2,
        tags: ['futur'],
        explain: 'German will means "want to" and möchte means "would like to". The future auxiliary is werden — a classic false friend.',
      },
      {
        id: 'x.g.b1.futur.4',
        kind: 'order',
        tokens: ['ich', 'werde', 'Ihnen', 'die', 'Unterlagen', 'bis Freitag', 'schicken'],
        answer: 'Ich werde Ihnen die Unterlagen bis Freitag schicken.',
        accept: ['Bis Freitag werde ich Ihnen die Unterlagen schicken.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['futur', 'wortstellung'],
        explain: 'werden is the conjugated verb and holds position 2; the infinitive schicken closes the bracket, and everything else sits between the two.',
      },
      {
        id: 'x.g.b1.futur.5',
        kind: 'correct',
        wrong: 'Ich werde nächste Woche mit dem Chef gesprochen.',
        answer: 'Ich werde nächste Woche mit dem Chef sprechen.',
        skill: 'verbs',
        difficulty: 2,
        tags: ['futur'],
        explain: 'Futur I needs the plain infinitive sprechen. werden plus a Partizip II builds the passive instead, which makes no sense here.',
      },
      {
        id: 'x.g.b1.futur.6',
        kind: 'blank',
        sentence: 'Morgen ___ es wahrscheinlich den ganzen Tag regnen.',
        options: ['wird', 'werden', 'werdet', 'wirst'],
        answer: 'wird',
        skill: 'verbs',
        difficulty: 2,
        tags: ['futur'],
        explain: 'The subject is es, so werden becomes wird — and it keeps position 2 even though Morgen opens the sentence.',
      },
      {
        id: 'x.g.b1.futur.7',
        kind: 'dialogue',
        lines: [
          { who: 'Chefin', text: 'Schaffen Sie den Bericht bis Freitag?' },
          { who: 'Sie', text: '___' },
        ],
        options: [
          'Ja, ich werde ihn bis Freitag fertigstellen.',
          'Ja, ich werde ihn bis Freitag fertiggestellt.',
          'Ja, ich werde ihn bis Freitag fertigstellen werden.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 2,
        tags: ['futur'],
        explain: 'A promise at work takes Futur I: one conjugated werden plus one infinitive at the end — never a participle and never a second werden.',
      },
      {
        id: 'x.g.b1.futur.8',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'She is probably still stuck in traffic.',
        answer: 'Sie wird wohl noch im Stau stehen.',
        accept: ['Sie steht wohl noch im Stau.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['futur'],
        hint: 'werden + wohl is a guess about right now.',
        explain: 'werden + wohl expresses a supposition about the present, not the future — one of the commonest uses of Futur I in real speech.',
      },
      {
        id: 'x.g.b1.futur.9',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'Next month we are moving to Hamburg.',
        answer: 'Nächsten Monat ziehen wir nach Hamburg um.',
        accept: ['Wir ziehen nächsten Monat nach Hamburg um.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['futur'],
        hint: 'A fixed plan needs no werden.',
        explain: 'A settled plan with a time expression uses the present tense in German, and the separable prefix um still goes to the end.',
      },
    ],
  },

  /* ── 4. Passiv ────────────────────────────────────────────────────────── */
  {
    id: 'g.b1.passiv',
    level: 'B1',
    title: 'The passive voice',
    titleDe: 'Das Passiv',
    short: 'werden + Partizip II. Use it when the action matters more than the person behind it.',
    tags: ['passiv'],
    skill: 'grammar',
    difficulty: 3,
    explain: [
      {
        kind: 'text',
        text: 'The passive puts the **action** first and the doer in the background: **werden + Partizip II**. *Man repariert den Aufzug* → *Der Aufzug wird repariert.*',
      },
      {
        kind: 'table',
        head: ['Zeit', 'Aktiv', 'Passiv'],
        rows: [
          ['Präsens', 'Man repariert den Aufzug.', 'Der Aufzug wird repariert.'],
          ['Präteritum', 'Man reparierte den Aufzug.', 'Der Aufzug wurde repariert.'],
          ['Perfekt', 'Man hat den Aufzug repariert.', 'Der Aufzug ist repariert worden.'],
          ['mit Modalverb', 'Man muss den Aufzug reparieren.', 'Der Aufzug muss repariert werden.'],
        ],
      },
      {
        kind: 'tip',
        text: 'The accusative object of the active sentence becomes the subject: *den Aufzug* → *der Aufzug*.',
      },
      {
        kind: 'warn',
        text: 'If you do name the doer, use **von** + Dativ: *Das Paket wurde von meinem Nachbarn angenommen.*',
      },
    ],
    examples: [
      {
        de: 'Die Miete wird jeden Monat automatisch abgebucht.',
        en: 'The rent is debited automatically every month.',
      },
      {
        de: 'Das Formular wurde gestern schon abgeschickt.',
        en: 'The form was already sent off yesterday.',
        note: 'wurde + Partizip II is the standard past passive in emails and offices.',
      },
      {
        de: 'Der Termin muss leider verschoben werden.',
        en: 'Unfortunately the appointment has to be postponed.',
        note: 'With a modal verb the end of the sentence is Partizip II + werden.',
      },
      {
        de: 'Das Paket wurde von meinem Nachbarn angenommen.',
        en: 'The parcel was accepted by my neighbour.',
      },
    ],
    pitfalls: [
      {
        wrong: 'Im Moment ist der Aufzug repariert.',
        right: 'Im Moment wird der Aufzug repariert.',
        why: 'sein + Partizip II describes a finished state; an action in progress needs werden: wird repariert.',
      },
      {
        wrong: 'Die Rechnung ist letzte Woche bezahlt geworden.',
        right: 'Die Rechnung ist letzte Woche bezahlt worden.',
        why: 'In the passive, werden has the special Partizip II worden without ge-. geworden belongs to the full verb: Er ist Arzt geworden.',
      },
      {
        wrong: 'Der Termin muss verschoben sein.',
        right: 'Der Termin muss verschoben werden.',
        why: 'A modal passive ends in Partizip II + werden. With sein you would claim the job is already done.',
      },
    ],
    exerciseIds: [
      'x.g.b1.passiv.1',
      'x.g.b1.passiv.2',
      'x.g.b1.passiv.3',
      'x.g.b1.passiv.4',
      'x.g.b1.passiv.5',
      'x.g.b1.passiv.6',
      'x.g.b1.passiv.7',
      'x.g.b1.passiv.8',
    ],
    exercises: [
      {
        id: 'x.g.b1.passiv.1',
        kind: 'blank',
        sentence: 'Im Moment ___ der Aufzug repariert.',
        options: ['wird', 'ist', 'hat', 'werden'],
        answer: 'wird',
        skill: 'grammar',
        difficulty: 1,
        tags: ['passiv'],
        explain: 'The present passive is werden + Partizip II: wird repariert. sein + Partizip II would describe a finished state instead.',
      },
      {
        id: 'x.g.b1.passiv.2',
        kind: 'blank',
        sentence: 'Das Formular ___ gestern schon abgeschickt.',
        options: ['wurde', 'wird', 'hatte', 'werdet'],
        answer: 'wurde',
        skill: 'grammar',
        difficulty: 1,
        tags: ['passiv'],
        explain: 'For a completed action use the Präteritum of werden: wurde + Partizip II. This is the everyday past passive in offices and emails.',
      },
      {
        id: 'x.g.b1.passiv.3',
        kind: 'mcq',
        prompt: 'Which sentence is the passive of "Man muss die Heizung reparieren"?',
        options: [
          'Die Heizung muss repariert werden.',
          'Die Heizung muss werden repariert.',
          'Die Heizung muss repariert sein.',
        ],
        answer: 0,
        skill: 'grammar',
        difficulty: 2,
        tags: ['passiv'],
        explain: 'In a modal passive the two verb forms line up at the end as Partizip II + werden; sein would mean the work is already finished.',
      },
      {
        id: 'x.g.b1.passiv.4',
        kind: 'order',
        tokens: ['die', 'Miete', 'wird', 'am Monatsende', 'automatisch', 'abgebucht'],
        answer: 'Die Miete wird am Monatsende automatisch abgebucht.',
        accept: ['Am Monatsende wird die Miete automatisch abgebucht.'],
        skill: 'wordorder',
        difficulty: 2,
        tags: ['passiv', 'wortstellung'],
        explain: 'wird is the only conjugated verb, so it takes position 2; the Partizip II abgebucht closes the sentence bracket at the end.',
      },
      {
        id: 'x.g.b1.passiv.5',
        kind: 'blank',
        sentence: 'Das Paket wurde ___ meiner Nachbarin angenommen.',
        options: ['von', 'durch', 'mit', 'bei'],
        answer: 'von',
        skill: 'grammar',
        difficulty: 2,
        tags: ['passiv'],
        explain: 'The person behind a passive action is introduced with von + Dativ: von meiner Nachbarin, vom Vermieter.',
      },
      {
        id: 'x.g.b1.passiv.6',
        kind: 'correct',
        wrong: 'Der Vertrag ist gestern unterschrieben geworden.',
        answer: 'Der Vertrag ist gestern unterschrieben worden.',
        skill: 'grammar',
        difficulty: 2,
        tags: ['passiv'],
        explain: 'In the Perfekt passive werden takes the short participle worden, without ge-. geworden is only the full verb: Sie ist Ärztin geworden.',
      },
      {
        id: 'x.g.b1.passiv.7',
        kind: 'translate',
        direction: 'en-de',
        prompt: 'The appointment was postponed because the doctor was ill.',
        answer: 'Der Termin wurde verschoben, weil der Arzt krank war.',
        accept: ['Weil der Arzt krank war, wurde der Termin verschoben.'],
        skill: 'writing',
        difficulty: 3,
        tags: ['passiv'],
        hint: 'wurde + Partizip II',
        explain: 'The past passive is wurde + Partizip II, and weil sends its own verb war right to the end of the subordinate clause.',
      },
      {
        id: 'x.g.b1.passiv.8',
        kind: 'dialogue',
        lines: [
          { who: 'Mieterin', text: 'Wann wird das Bad endlich renoviert?' },
          { who: 'Hausmeister', text: '___' },
        ],
        options: [
          'Die Fliesen werden nächste Woche erneuert.',
          'Die Fliesen sind nächste Woche erneuert.',
          'Die Fliesen werden nächste Woche erneuert worden.',
        ],
        answer: 0,
        skill: 'conversation',
        difficulty: 3,
        tags: ['passiv'],
        explain: 'A planned job takes the present passive werden + Partizip II. worden belongs only to the Perfekt, and sein would claim the work is done.',
      },
    ],
  },
]

export default grammar
