/**
 * Optional AI tutor.
 *
 * The whole app works without this. When the learner supplies their own
 * Anthropic API key in Settings, free conversation and richer explanations
 * become available — but the *structured* content (lessons, exercises,
 * vocabulary) is never generated by AI, so the level stays controlled.
 *
 * The key is stored only in this browser's localStorage and is sent only to
 * api.anthropic.com. Calls run directly from the browser, which means the key
 * is visible to anything running on this page — fine for a personal tool on
 * your own machine, not something to deploy publicly. The UI says so.
 */

const ENDPOINT = 'https://api.anthropic.com/v1/messages'
const API_VERSION = '2023-06-01'

export const MODELS = [
  { id: 'claude-sonnet-5', label: 'Claude Sonnet 5 — balanced' },
  { id: 'claude-opus-5', label: 'Claude Opus 5 — most capable' },
  { id: 'claude-haiku-4-5-20251001', label: 'Claude Haiku 4.5 — fastest' },
]

export function aiReady(settings) {
  return !!(settings?.aiEnabled && settings?.aiKey?.startsWith('sk-'))
}

/**
 * Everything the tutor is allowed to know about the learner. Keeping this
 * explicit is what stops the AI drifting to B2 vocabulary in an A1 lesson.
 */
export function buildLearnerContext({ state, level, lesson, knownVocab = [], weakAreas = [] }) {
  const lines = [
    `CEFR level: ${level}`,
    lesson ? `Current lesson: ${lesson.title} (${lesson.level}, lesson ${lesson.order})` : null,
    lesson?.objectives?.length ? `Lesson goals: ${lesson.objectives.join('; ')}` : null,
    knownVocab.length
      ? `Vocabulary the learner has met (stay within this plus international words): ${knownVocab.slice(0, 220).join(', ')}`
      : null,
    weakAreas.length ? `Recurring weak areas: ${weakAreas.join(', ')}` : null,
    state?.profile?.name ? `Learner's name: ${state.profile.name}` : null,
  ].filter(Boolean)
  return lines.join('\n')
}

const LEVEL_RULES = {
  A1: 'Use ONLY present tense (plus "möchte"). Short main clauses. No Perfekt, no Dativ objects, no subordinate clauses, no Konjunktiv, no passive. Everyday words only. Maximum 12 words per sentence.',
  A2: 'Present and Perfekt. Dative allowed. Simple subordinate clauses with weil/dass/wenn. Modal verbs. No Konjunktiv II beyond "ich hätte gern/ich würde", no passive, no relative clauses. Maximum 16 words per sentence.',
  B1: 'Full range of A2 plus relative clauses, Konjunktiv II, passive, Präteritum of common verbs, and connectors like obwohl/trotzdem/deshalb. Still everyday register, not academic.',
}

export function systemPrompt({ level = 'A1', scenario, learnerContext }) {
  return `You are a warm, patient German tutor inside a learning app. You role-play a
conversation partner AND quietly correct mistakes.

LEVEL DISCIPLINE — this is the most important rule.
The learner is at ${level}. ${LEVEL_RULES[level] || LEVEL_RULES.A1}
Never use vocabulary or grammar above ${level}, even if the learner does.

${scenario ? `SCENARIO\nYou play: ${scenario.roleBot}\nSetting: ${scenario.setting}\nThe learner's task: ${scenario.goal}\n` : ''}
LEARNER
${learnerContext}

HOW TO REPLY
Always answer with a single JSON object and nothing else:
{
  "de": "your reply in German",
  "en": "an English translation of your reply",
  "corrections": [
    { "wrong": "exact phrase the learner wrote", "right": "the corrected phrase",
      "why": "one short sentence explaining the rule", "tag": "one of: artikel, konjugation, wortstellung, akkusativ, dativ, negation, praeposition, nebensatz, plural, grossschreibung, vokabular" }
  ],
  "onTarget": true,
  "done": false
}

- "corrections" is [] when the learner's German was fine. Correct only real errors —
  never rewrite acceptable German just to make it fancier.
- Keep "de" to one or two sentences and always move the conversation forward with a question.
- Set "done": true once the scenario's goal has been achieved.
- Never break character, never mention JSON, never add text outside the object.`
}

/**
 * Send one turn to the API.
 * @returns {Promise<{de,en,corrections,onTarget,done}>}
 * @throws {Error} with a message suitable for showing to the user
 */
export async function chat({ settings, system, messages, maxTokens = 500, signal }) {
  if (!aiReady(settings)) throw new Error('AI is not configured.')
  let res
  try {
    res = await fetch(ENDPOINT, {
      method: 'POST',
      signal,
      headers: {
        'content-type': 'application/json',
        'x-api-key': settings.aiKey,
        'anthropic-version': API_VERSION,
        'anthropic-dangerous-direct-browser-access': 'true',
      },
      body: JSON.stringify({
        model: settings.aiModel || 'claude-sonnet-5',
        max_tokens: maxTokens,
        system,
        messages,
      }),
    })
  } catch (e) {
    if (e.name === 'AbortError') throw e
    throw new Error('Could not reach the Anthropic API. Check your connection.')
  }

  if (!res.ok) {
    const body = await res.text().catch(() => '')
    if (res.status === 401) throw new Error('That API key was rejected.')
    if (res.status === 429) throw new Error('Rate limited — wait a moment and try again.')
    throw new Error(`API error ${res.status}. ${body.slice(0, 160)}`)
  }

  const data = await res.json()
  const text = (data.content || [])
    .filter((b) => b.type === 'text')
    .map((b) => b.text)
    .join('')
  return text
}

/** Parse the tutor's JSON reply, tolerating stray prose around it. */
export function parseTutorReply(text) {
  const trimmed = String(text || '').trim()
  const start = trimmed.indexOf('{')
  const end = trimmed.lastIndexOf('}')
  if (start === -1 || end <= start) {
    return { de: trimmed, en: '', corrections: [], onTarget: true, done: false, raw: true }
  }
  try {
    const obj = JSON.parse(trimmed.slice(start, end + 1))
    return {
      de: obj.de || '',
      en: obj.en || '',
      corrections: Array.isArray(obj.corrections) ? obj.corrections.filter((c) => c?.wrong && c?.right) : [],
      onTarget: obj.onTarget !== false,
      done: !!obj.done,
    }
  } catch {
    return { de: trimmed, en: '', corrections: [], onTarget: true, done: false, raw: true }
  }
}

/** A one-off explanation request, used by the "Explain this" buttons. */
export async function explain({ settings, question, level, context, signal }) {
  const text = await chat({
    settings,
    system: `You are a German tutor. The learner is at CEFR level ${level}. Answer in English,
in at most 90 words. Give one clear rule, one example in German with its English translation,
and stop. No lists longer than three items. Never use grammar terminology without explaining it.`,
    messages: [{ role: 'user', content: context ? `${question}\n\nContext: ${context}` : question }],
    maxTokens: 320,
    signal,
  })
  return text.trim()
}

/** Verify a key works, for the Settings page. */
export async function testKey(settings) {
  const text = await chat({
    settings,
    system: 'Reply with exactly: OK',
    messages: [{ role: 'user', content: 'ping' }],
    maxTokens: 10,
  })
  return text.trim().length > 0
}
