/**
 * A1 · L03 — Numbers, time and dates.
 *
 * Grammar: g.a1.janein (yes/no questions) and g.a1.satzbau (verb in position 2).
 * Plain data only. See ../SCHEMA.md.
 */

export const lesson = {
  id: 'a1.l03',
  moduleId: 'a1.everyday',
  level: 'A1',
  order: 3,
  title: 'Numbers, time and dates',
  titleDe: 'Zahlen, Uhrzeit und Datum',
  icon: '🕐',
  summary: 'Count to a hundred, tell the time, and fix a day and a date for an appointment.',
  minutes: 16,
  objectives: [
    'Say and understand the numbers from 0 to 100',
    'Ask "Wie spät ist es?" and tell the time with halb, Viertel nach and Viertel vor',
    'Name the days and months and say when something happens: um, am, im',
    'Ask a yes/no question and keep the verb in position 2',
  ],
  vocabIds: [
    'v.a1.l03.uhr',
    'v.a1.l03.stunde',
    'v.a1.l03.minute',
    'v.a1.l03.termin',
    'v.a1.l03.woche',
    'v.a1.l03.montag',
    'v.a1.l03.januar',
    'v.a1.l03.datum',
    'v.a1.l03.viertel',
    'v.a1.l03.halb',
    'v.a1.l03.heute',
    'v.a1.l03.morgen',
    'v.a1.l03.gestern',
    'v.a1.l03.hundert',
    'v.a1.l03.tausend',
    'v.a1.l03.beginnen',
  ],
  grammarIds: ['g.a1.janein', 'g.a1.satzbau'],

  steps: [
    /* ── 1. Learn ───────────────────────────────────────────────────────── */
    {
      type: 'learn',
      title: 'Time and dates',
      blocks: [
        {
          kind: 'text',
          text: 'After this lesson you can say **how many**, **what time it is** and **which day** something happens — the three things every appointment needs.',
        },
        {
          kind: 'table',
          head: ['Uhr', 'Man sagt', 'English'],
          rows: [
            ['7:00', 'Es ist sieben Uhr.', 'It is seven o’clock.'],
            ['7:15', 'Es ist Viertel nach sieben.', 'a quarter past seven'],
            ['7:30', 'Es ist halb acht.', 'half past seven'],
            ['7:45', 'Es ist Viertel vor acht.', 'a quarter to eight'],
          ],
        },
        {
          kind: 'examples',
          items: [
            { de: 'Wie spät ist es?', en: 'What time is it?', note: 'Also: Wie viel Uhr ist es?' },
            { de: 'Wann beginnt der Kurs?', en: 'When does the course start?' },
            { de: 'Der Kurs beginnt um zehn Uhr.', en: 'The course starts at ten o’clock.' },
            { de: 'Am Montag habe ich einen Termin.', en: 'On Monday I have an appointment.' },
          ],
        },
        {
          kind: 'tip',
          text: 'Three little words carry every date: **um** + clock time, **am** + day, **im** + month — *um acht Uhr*, *am Montag*, *im Januar*.',
        },
        {
          kind: 'warn',
          text: '**halb acht** is 7:30, not 8:30. German counts towards the next full hour: *halb* is halfway there.',
        },
      ],
    },

    /* ── 2. Vocab ───────────────────────────────────────────────────────── */
    {
      type: 'vocab',
      title: 'New words',
      vocabIds: [
        'v.a1.l03.uhr',
        'v.a1.l03.stunde',
        'v.a1.l03.minute',
        'v.a1.l03.termin',
        'v.a1.l03.woche',
        'v.a1.l03.montag',
        'v.a1.l03.januar',
        'v.a1.l03.datum',
        'v.a1.l03.viertel',
        'v.a1.l03.halb',
        'v.a1.l03.heute',
        'v.a1.l03.morgen',
        'v.a1.l03.gestern',
        'v.a1.l03.hundert',
        'v.a1.l03.tausend',
        'v.a1.l03.beginnen',
      ],
    },

    /* ── 3-4. Grammar ───────────────────────────────────────────────────── */
    { type: 'grammar', title: 'Yes/no questions', grammarId: 'g.a1.janein' },
    { type: 'grammar', title: 'Verb in position 2', grammarId: 'g.a1.satzbau' },

    /* ── 5. Practice ────────────────────────────────────────────────────── */
    {
      type: 'practice',
      title: 'Practice',
      exercises: [
        {
          id: 'x.a1.l03.1',
          kind: 'match',
          pairs: [
            ['acht Uhr', '8:00'],
            ['Viertel nach acht', '8:15'],
            ['halb acht', '7:30'],
            ['Viertel vor acht', '7:45'],
          ],
          skill: 'vocabulary',
          difficulty: 1,
          tags: ['zeitangaben'],
          explain: 'nach and vor count from the hour you can hear, but halb points to the NEXT hour — that is why halb acht is 7:30 and Viertel vor acht is 7:45.',
        },
        {
          id: 'x.a1.l03.2',
          kind: 'blank',
          sentence: 'Der Kurs beginnt ___ neun Uhr.',
          options: ['um', 'am', 'im', 'in'],
          answer: 'um',
          skill: 'prepositions',
          difficulty: 1,
          tags: ['praeposition', 'zeitangaben'],
          explain: 'Clock times always take um. Keep the set together: um neun Uhr, am Montag, im Januar.',
        },
        {
          id: 'x.a1.l03.3',
          kind: 'article',
          noun: 'Stunde',
          answer: 'die',
          plural: 'die Stunden',
          meaning: 'hour',
          skill: 'articles',
          difficulty: 1,
          tags: ['artikel'],
          explain: 'German nouns ending in -e are feminine in the great majority of cases, and they add -n in the plural: die Stunde, die Minute, die Woche.',
        },
        {
          id: 'x.a1.l03.4',
          kind: 'mcq',
          prompt: 'How do you say 21 in German?',
          options: ['einundzwanzig', 'zwanzigundeins', 'zwanzig eins'],
          answer: 0,
          skill: 'vocabulary',
          difficulty: 2,
          tags: ['zahlen'],
          explain: 'German says the unit first and glues it on with und: ein-und-zwanzig. The same pattern runs up to 99 — sechsundvierzig is 46.',
        },
        {
          id: 'x.a1.l03.5',
          kind: 'blank',
          sentence: '___ du am Freitag Zeit?',
          options: ['Hast', 'Hat', 'Habt', 'Haben'],
          answer: 'Hast',
          skill: 'wordorder',
          difficulty: 2,
          tags: ['wortstellung'],
          explain: 'A yes/no question opens with the conjugated verb, but moving it to the front never changes its ending — du still needs hast.',
        },
        {
          id: 'x.a1.l03.6',
          kind: 'mcq',
          prompt: 'Which sentence is a correct yes/no question?',
          options: [
            'Beginnt der Kurs um neun Uhr?',
            'Der Kurs beginnt um neun Uhr?',
            'Tut der Kurs um neun Uhr beginnen?',
          ],
          answer: 0,
          skill: 'wordorder',
          difficulty: 2,
          tags: ['wortstellung'],
          explain: 'The verb itself jumps to position 1. German has no helper word like "does", so a verb such as tun is never added.',
        },
        {
          id: 'x.a1.l03.7',
          kind: 'correct',
          wrong: 'Am Montag ich habe einen Termin.',
          answer: 'Am Montag habe ich einen Termin.',
          skill: 'wordorder',
          difficulty: 2,
          tags: ['wortstellung'],
          explain: 'Only one element may stand in front of the verb. „Am Montag" already fills position 1, so the subject ich moves behind habe.',
        },
        {
          id: 'x.a1.l03.8',
          kind: 'listen',
          audio: 'Der Zug nach Köln fährt um Viertel vor zehn.',
          question: 'When does the train to Cologne leave?',
          options: ['9:45', '10:15', '10:45'],
          answer: 0,
          skill: 'listening',
          difficulty: 2,
          tags: ['zeitangaben'],
          explain: 'Viertel vor counts backwards from the hour you hear: fifteen minutes before ten o’clock is 9:45.',
        },
        {
          id: 'x.a1.l03.9',
          kind: 'translate',
          direction: 'en-de',
          prompt: 'The film starts at half past seven.',
          answer: 'Der Film beginnt um halb acht.',
          accept: ['Der Film beginnt um 19:30 Uhr.'],
          skill: 'writing',
          difficulty: 3,
          tags: ['zeitangaben'],
          hint: 'Which hour is German heading towards?',
          explain: 'Half past seven is halb acht, because halb names the hour it is heading towards — and the clock time still needs um in front of it.',
        },
      ],
    },

    /* ── 6. Build ───────────────────────────────────────────────────────── */
    {
      type: 'build',
      title: 'Build the sentence',
      exercises: [
        {
          id: 'x.a1.l03.10',
          kind: 'order',
          tokens: ['wie', 'spät', 'ist', 'es'],
          answer: 'Wie spät ist es?',
          skill: 'wordorder',
          difficulty: 1,
          tags: ['wortstellung'],
          explain: '„Wie spät" is one single element in position 1, so the verb ist comes straight after it and the subject es waits behind the verb.',
        },
        {
          id: 'x.a1.l03.11',
          kind: 'order',
          tokens: ['der Kurs', 'beginnt', 'um neun Uhr'],
          answer: 'Der Kurs beginnt um neun Uhr.',
          accept: ['Um neun Uhr beginnt der Kurs.'],
          skill: 'wordorder',
          difficulty: 2,
          tags: ['wortstellung'],
          explain: 'Both versions are correct German because beginnt stays the second element either way — only the element you choose for position 1 changes.',
        },
        {
          id: 'x.a1.l03.12',
          kind: 'order',
          tokens: ['am Montag', 'habe', 'ich', 'einen Termin'],
          answer: 'Am Montag habe ich einen Termin.',
          accept: ['Ich habe am Montag einen Termin.'],
          skill: 'wordorder',
          difficulty: 2,
          tags: ['wortstellung'],
          explain: 'Put the time phrase first and the subject has to hop behind the verb — habe never gives up position 2.',
        },
        {
          id: 'x.a1.l03.13',
          kind: 'order',
          tokens: ['um halb acht', 'fährt', 'mein Zug', 'nach Hamburg'],
          answer: 'Um halb acht fährt mein Zug nach Hamburg.',
          accept: ['Mein Zug fährt um halb acht nach Hamburg.'],
          skill: 'wordorder',
          difficulty: 3,
          tags: ['wortstellung'],
          explain: '„Um halb acht" is three words but one element, so the verb follows immediately; everything else then queues up behind the subject.',
        },
      ],
    },

    /* ── 7-9. Apply ─────────────────────────────────────────────────────── */
    { type: 'reading', title: 'Read', readingId: 'r.a1.l03.sprachschule' },
    { type: 'listening', title: 'Listen', listeningId: 'h.a1.l03.bahnhof' },
    { type: 'conversation', title: 'Use it', conversationId: 'c.a1.l03.kaffee-termin' },

    /* ── 10. Quiz ───────────────────────────────────────────────────────── */
    {
      type: 'quiz',
      title: 'Quiz',
      exercises: [
        {
          id: 'x.a1.l03.14',
          kind: 'article',
          noun: 'Termin',
          answer: 'der',
          plural: 'die Termine',
          meaning: 'appointment',
          skill: 'articles',
          difficulty: 1,
          tags: ['artikel'],
          explain: 'der Termin is masculine, and masculine nouns very often build the plural with -e: der Termin → die Termine, der Tag → die Tage, der Monat → die Monate.',
        },
        {
          id: 'x.a1.l03.15',
          kind: 'blank',
          sentence: 'Der neue Kurs beginnt ___ Januar.',
          options: ['im', 'am', 'um'],
          answer: 'im',
          skill: 'prepositions',
          difficulty: 2,
          tags: ['praeposition', 'zeitangaben'],
          explain: 'Months take im (a short form of in dem): im Januar, im Mai. Days take am and clock times take um.',
        },
        {
          id: 'x.a1.l03.16',
          kind: 'mcq',
          prompt: 'It is 8:30. Which German sentence says that?',
          options: ['Es ist halb acht.', 'Es ist halb neun.', 'Es ist Viertel vor neun.'],
          answer: 1,
          skill: 'vocabulary',
          difficulty: 3,
          tags: ['zeitangaben'],
          explain: 'halb names the hour the clock is heading towards, so 8:30 is halb neun — halfway to nine. halb acht would be 7:30.',
        },
        {
          id: 'x.a1.l03.17',
          kind: 'order',
          tokens: ['hast', 'du', 'am Mittwoch', 'Zeit'],
          answer: 'Hast du am Mittwoch Zeit?',
          skill: 'wordorder',
          difficulty: 2,
          tags: ['wortstellung'],
          explain: 'In a yes/no question the verb takes position 1 and the subject follows it directly; the time phrase only comes afterwards.',
        },
        {
          id: 'x.a1.l03.18',
          kind: 'dialogue',
          lines: [
            { who: 'Lena', text: 'Wann beginnt der Deutschkurs?' },
            { who: 'Du', text: '___' },
          ],
          options: [
            'Er beginnt um Viertel nach sechs.',
            'Er beginnt am Viertel nach sechs.',
            'Ja, er beginnt um sechs.',
          ],
          answer: 0,
          skill: 'conversation',
          difficulty: 2,
          tags: ['zeitangaben'],
          explain: 'Wann? asks for information, so „ja" answers nothing — and a clock time always takes um, never am.',
        },
        {
          id: 'x.a1.l03.19',
          kind: 'translate',
          direction: 'en-de',
          prompt: 'Do you (du) have time on Friday at four o’clock?',
          answer: 'Hast du am Freitag um vier Uhr Zeit?',
          accept: ['Hast du am Freitag um 16 Uhr Zeit?'],
          skill: 'writing',
          difficulty: 3,
          tags: ['wortstellung', 'zeitangaben'],
          hint: 'The verb comes first, and the bigger time unit comes before the smaller one.',
          explain: 'The verb opens the yes/no question and the subject follows it; German then orders time from the larger unit to the smaller one — am Freitag before um vier Uhr.',
        },
      ],
    },

    /* ── 11. Review ─────────────────────────────────────────────────────── */
    { type: 'review', title: 'Review', count: 3 },
  ],
}

export default lesson
